semi: true
tabWidth: 2
printWidth: 150
singleQuote: false
bracketSpacing: true
jsxSingleQuote: false
bracketSameLine: false
trailingComma: none
arrowParens: always
proseWrap: preserve
htmlWhitespaceSensitivity: css
embeddedLanguageFormatting: auto