import { EnvironmentEntry } from "../types";
const Abstract_Realism: Record<string, EnvironmentEntry> = {
  "Crystal Burst": {
    environment_title: "Crystal Burst",
    images: [
      {
        original_file_name: "Crystal Burst (1).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#1b1f27",
        primary: "#b9aaa0",
        tertiary: "#7a6c66",
        branch: "Abstract",
        folder: "Realism",
        bytes: 55644,
        type: "min",
      },
      {
        original_file_name: "Crystal Burst (2).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#26262e",
        primary: "#d0a988",
        tertiary: "#8a6555",
        branch: "Abstract",
        folder: "Realism",
        bytes: 65568,
        type: "min",
      },
      {
        original_file_name: "Crystal Burst (3).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#cfba9f",
        primary: "#2d2224",
        tertiary: "#937a6b",
        branch: "Abstract",
        folder: "Realism",
        bytes: 56134,
        type: "min",
      },
      {
        original_file_name: "Crystal Burst (4).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#d7b79a",
        primary: "#332d30",
        tertiary: "#956e5b",
        branch: "Abstract",
        folder: "Realism",
        bytes: 63745,
        type: "min",
      },
      {
        original_file_name: "Crystal Burst (1).jpg",
        megabytes: 1.4,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#1b1f27",
        primary: "#b9a99f",
        tertiary: "#796c66",
        branch: "Abstract",
        folder: "Realism",
        bytes: 1463268,
        type: "max",
      },
      {
        original_file_name: "Crystal Burst (2).jpg",
        megabytes: 1.64,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#26272f",
        primary: "#d0a987",
        tertiary: "#8a6556",
        branch: "Abstract",
        folder: "Realism",
        bytes: 1723636,
        type: "max",
      },
      {
        original_file_name: "Crystal Burst (3).jpg",
        megabytes: 1.41,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#cfba9f",
        primary: "#2d2224",
        tertiary: "#937a6b",
        branch: "Abstract",
        folder: "Realism",
        bytes: 1476433,
        type: "max",
      },
      {
        original_file_name: "Crystal Burst (4).jpg",
        megabytes: 1.53,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#d7b699",
        primary: "#332d30",
        tertiary: "#956e5c",
        branch: "Abstract",
        folder: "Realism",
        bytes: 1603337,
        type: "max",
      },
    ]
  },
  "Ink Blossom": {
    environment_title: "Ink Blossom",
    images: [
      {
        original_file_name: "Ink Blossom (1).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#722f26",
        primary: "#a1a09d",
        tertiary: "#8d503f",
        branch: "Abstract",
        folder: "Realism",
        bytes: 39945,
        type: "min",
      },
      {
        original_file_name: "Ink Blossom (2).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#533433",
        primary: "#ad9e94",
        tertiary: "#4a626b",
        branch: "Abstract",
        folder: "Realism",
        bytes: 54294,
        type: "min",
      },
      {
        original_file_name: "Ink Blossom (3).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#34444c",
        primary: "#c5a9a4",
        tertiary: "#6d7c86",
        branch: "Abstract",
        folder: "Realism",
        bytes: 45641,
        type: "min",
      },
      {
        original_file_name: "Ink Blossom (4).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#30353d",
        primary: "#929797",
        tertiary: "#d2beb3",
        branch: "Abstract",
        folder: "Realism",
        bytes: 55991,
        type: "min",
      },
      {
        original_file_name: "Ink Blossom (1).jpg",
        megabytes: 1.14,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#732f26",
        primary: "#a1a09d",
        tertiary: "#8d5040",
        branch: "Abstract",
        folder: "Realism",
        bytes: 1196731,
        type: "max",
      },
      {
        original_file_name: "Ink Blossom (2).jpg",
        megabytes: 1.37,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#3e484f",
        primary: "#aea097",
        tertiary: "#dbdbd8",
        branch: "Abstract",
        folder: "Realism",
        bytes: 1434917,
        type: "max",
      },
      {
        original_file_name: "Ink Blossom (3).jpg",
        megabytes: 1.3,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#34444d",
        primary: "#c5a9a4",
        tertiary: "#6d7c86",
        branch: "Abstract",
        folder: "Realism",
        bytes: 1364107,
        type: "max",
      },
      {
        original_file_name: "Ink Blossom (4).jpg",
        megabytes: 1.5,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#30353d",
        primary: "#929797",
        tertiary: "#d3beb3",
        branch: "Abstract",
        folder: "Realism",
        bytes: 1569543,
        type: "max",
      },
    ]
  },
  "Ink Waves": {
    environment_title: "Ink Waves",
    images: [
      {
        original_file_name: "Ink Waves (1).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c2bfb8",
        primary: "#262f34",
        tertiary: "#8f908e",
        branch: "Abstract",
        folder: "Realism",
        bytes: 52063,
        type: "min",
      },
      {
        original_file_name: "Ink Waves (2).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#bbbab5",
        primary: "#222b32",
        tertiary: "#80898b",
        branch: "Abstract",
        folder: "Realism",
        bytes: 53101,
        type: "min",
      },
      {
        original_file_name: "Ink Waves (3).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#29333b",
        primary: "#a9b6b8",
        tertiary: "#cdcdca",
        branch: "Abstract",
        folder: "Realism",
        bytes: 53176,
        type: "min",
      },
      {
        original_file_name: "Ink Waves (4).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c5c7c6",
        primary: "#1e2b35",
        tertiary: "#858f94",
        branch: "Abstract",
        folder: "Realism",
        bytes: 68553,
        type: "min",
      },
      {
        original_file_name: "Ink Waves (1).jpg",
        megabytes: 1.8,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c2bfb8",
        primary: "#272f34",
        tertiary: "#8f908e",
        branch: "Abstract",
        folder: "Realism",
        bytes: 1889314,
        type: "max",
      },
      {
        original_file_name: "Ink Waves (2).jpg",
        megabytes: 1.68,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#bbbab5",
        primary: "#222b32",
        tertiary: "#80898b",
        branch: "Abstract",
        folder: "Realism",
        bytes: 1759570,
        type: "max",
      },
      {
        original_file_name: "Ink Waves (3).jpg",
        megabytes: 1.95,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#2a333b",
        primary: "#acb9bb",
        tertiary: "#cdcdca",
        branch: "Abstract",
        folder: "Realism",
        bytes: 2040356,
        type: "max",
      },
      {
        original_file_name: "Ink Waves (4).jpg",
        megabytes: 2.4,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c5c7c6",
        primary: "#1e2b35",
        tertiary: "#858e94",
        branch: "Abstract",
        folder: "Realism",
        bytes: 2519396,
        type: "max",
      },
    ]
  },
  "Liquid Smoke": {
    environment_title: "Liquid Smoke",
    images: [
      {
        original_file_name: "Liquid Smoke (1).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#2a2421",
        primary: "#c28351",
        tertiary: "#8d7361",
        branch: "Abstract",
        folder: "Realism",
        bytes: 43844,
        type: "min",
      },
      {
        original_file_name: "Liquid Smoke (2).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#231613",
        primary: "#c09f84",
        tertiary: "#805643",
        branch: "Abstract",
        folder: "Realism",
        bytes: 45256,
        type: "min",
      },
      {
        original_file_name: "Liquid Smoke (3).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#1d2125",
        primary: "#b5ada5",
        tertiary: "#766c63",
        branch: "Abstract",
        folder: "Realism",
        bytes: 38700,
        type: "min",
      },
      {
        original_file_name: "Liquid Smoke (4).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#221c1d",
        primary: "#ba825f",
        tertiary: "#856152",
        branch: "Abstract",
        folder: "Realism",
        bytes: 55624,
        type: "min",
      },
      {
        original_file_name: "Liquid Smoke (1).jpg",
        megabytes: 1.12,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#2a2422",
        primary: "#c28351",
        tertiary: "#8d7361",
        branch: "Abstract",
        folder: "Realism",
        bytes: 1179088,
        type: "max",
      },
      {
        original_file_name: "Liquid Smoke (2).jpg",
        megabytes: 1.27,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#231614",
        primary: "#c09e83",
        tertiary: "#805543",
        branch: "Abstract",
        folder: "Realism",
        bytes: 1335667,
        type: "max",
      },
      {
        original_file_name: "Liquid Smoke (3).jpg",
        megabytes: 1.11,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#1d2125",
        primary: "#b5ada5",
        tertiary: "#766c63",
        branch: "Abstract",
        folder: "Realism",
        bytes: 1160238,
        type: "max",
      },
      {
        original_file_name: "Liquid Smoke (4).jpg",
        megabytes: 1.39,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#ba825f",
        primary: "#231d1d",
        tertiary: "#856153",
        branch: "Abstract",
        folder: "Realism",
        bytes: 1454362,
        type: "max",
      },
    ]
  },
  "Marble Veins": {
    environment_title: "Marble Veins",
    images: [
      {
        original_file_name: "Marble Veins (1).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#372b21",
        primary: "#a69b8b",
        tertiary: "#81592e",
        branch: "Abstract",
        folder: "Realism",
        bytes: 70597,
        type: "min",
      },
      {
        original_file_name: "Marble Veins (2).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c7c4bd",
        primary: "#a78c67",
        tertiary: "#231e1c",
        branch: "Abstract",
        folder: "Realism",
        bytes: 69052,
        type: "min",
      },
      {
        original_file_name: "Marble Veins (3).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#302f2d",
        primary: "#b1a898",
        tertiary: "#8d6227",
        branch: "Abstract",
        folder: "Realism",
        bytes: 72086,
        type: "min",
      },
      {
        original_file_name: "Marble Veins (4).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#2a2622",
        primary: "#866842",
        tertiary: "#d1ccc5",
        branch: "Abstract",
        folder: "Realism",
        bytes: 78542,
        type: "min",
      },
      {
        original_file_name: "Marble Veins (1).jpg",
        megabytes: 2.23,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#322a25",
        primary: "#927f66",
        tertiary: "#c5c5c5",
        branch: "Abstract",
        folder: "Realism",
        bytes: 2336398,
        type: "max",
      },
      {
        original_file_name: "Marble Veins (2).jpg",
        megabytes: 2.24,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#231e1d",
        primary: "#ae9674",
        tertiary: "#cac8c2",
        branch: "Abstract",
        folder: "Realism",
        bytes: 2346222,
        type: "max",
      },
      {
        original_file_name: "Marble Veins (3).jpg",
        megabytes: 2.0,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#302f2d",
        primary: "#b1a898",
        tertiary: "#8d6226",
        branch: "Abstract",
        folder: "Realism",
        bytes: 2095018,
        type: "max",
      },
      {
        original_file_name: "Marble Veins (4).jpg",
        megabytes: 2.17,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#2a2622",
        primary: "#957145",
        tertiary: "#d0ccc5",
        branch: "Abstract",
        folder: "Realism",
        bytes: 2271133,
        type: "max",
      },
    ]
  },
  "Melted Glass": {
    environment_title: "Melted Glass",
    images: [
      {
        original_file_name: "Melted Glass (1).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#2d2220",
        primary: "#ce7522",
        tertiary: "#974d22",
        branch: "Abstract",
        folder: "Realism",
        bytes: 64750,
        type: "min",
      },
      {
        original_file_name: "Melted Glass (2).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#d57829",
        primary: "#823111",
        tertiary: "#110c0f",
        branch: "Abstract",
        folder: "Realism",
        bytes: 72938,
        type: "min",
      },
      {
        original_file_name: "Melted Glass (3).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#392723",
        primary: "#d1762d",
        tertiary: "#a14e22",
        branch: "Abstract",
        folder: "Realism",
        bytes: 69090,
        type: "min",
      },
      {
        original_file_name: "Melted Glass (4).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#321f1d",
        primary: "#d57935",
        tertiary: "#9e4a26",
        branch: "Abstract",
        folder: "Realism",
        bytes: 71652,
        type: "min",
      },
      {
        original_file_name: "Melted Glass (1).jpg",
        megabytes: 1.61,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#2d2220",
        primary: "#ce7522",
        tertiary: "#974d22",
        branch: "Abstract",
        folder: "Realism",
        bytes: 1689819,
        type: "max",
      },
      {
        original_file_name: "Melted Glass (2).jpg",
        megabytes: 1.95,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#d57828",
        primary: "#833111",
        tertiary: "#110d0f",
        branch: "Abstract",
        folder: "Realism",
        bytes: 2041118,
        type: "max",
      },
      {
        original_file_name: "Melted Glass (3).jpg",
        megabytes: 1.86,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#392823",
        primary: "#d1762d",
        tertiary: "#a14e22",
        branch: "Abstract",
        folder: "Realism",
        bytes: 1952144,
        type: "max",
      },
      {
        original_file_name: "Melted Glass (4).jpg",
        megabytes: 1.81,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#321f1d",
        primary: "#d67834",
        tertiary: "#9e4a25",
        branch: "Abstract",
        folder: "Realism",
        bytes: 1895951,
        type: "max",
      },
    ]
  },
  "Metallic Drips": {
    environment_title: "Metallic Drips",
    images: [
      {
        original_file_name: "Metallic Drips (1).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c5bdb0",
        primary: "#342d28",
        tertiary: "#8b7a65",
        branch: "Abstract",
        folder: "Realism",
        bytes: 66870,
        type: "min",
      },
      {
        original_file_name: "Metallic Drips (2).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#2b1509",
        primary: "#8f8d8a",
        tertiary: "#522e10",
        branch: "Abstract",
        folder: "Realism",
        bytes: 58452,
        type: "min",
      },
      {
        original_file_name: "Metallic Drips (3).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#191513",
        primary: "#c2b9ae",
        tertiary: "#7a726c",
        branch: "Abstract",
        folder: "Realism",
        bytes: 79245,
        type: "min",
      },
      {
        original_file_name: "Metallic Drips (4).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#d4d3d0",
        primary: "#32302e",
        tertiary: "#8f8e88",
        branch: "Abstract",
        folder: "Realism",
        bytes: 54971,
        type: "min",
      },
      {
        original_file_name: "Metallic Drips (1).jpg",
        megabytes: 1.67,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c5bcb1",
        primary: "#352f2a",
        tertiary: "#8c7c69",
        branch: "Abstract",
        folder: "Realism",
        bytes: 1751531,
        type: "max",
      },
      {
        original_file_name: "Metallic Drips (2).jpg",
        megabytes: 1.45,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#2b1509",
        primary: "#8f8d8b",
        tertiary: "#532d0f",
        branch: "Abstract",
        folder: "Realism",
        bytes: 1523846,
        type: "max",
      },
      {
        original_file_name: "Metallic Drips (3).jpg",
        megabytes: 2.06,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#191513",
        primary: "#c2b9ae",
        tertiary: "#79726b",
        branch: "Abstract",
        folder: "Realism",
        bytes: 2161223,
        type: "max",
      },
      {
        original_file_name: "Metallic Drips (4).jpg",
        megabytes: 1.35,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#d4d3cf",
        primary: "#32302e",
        tertiary: "#8f8d86",
        branch: "Abstract",
        folder: "Realism",
        bytes: 1413430,
        type: "max",
      },
    ]
  },
  "Oil Rainbow": {
    environment_title: "Oil Rainbow",
    images: [
      {
        original_file_name: "Oil Rainbow (1).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#cf9432",
        primary: "#553d3f",
        tertiary: "#9f6034",
        branch: "Abstract",
        folder: "Realism",
        bytes: 59723,
        type: "min",
      },
      {
        original_file_name: "Oil Rainbow (2).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c79149",
        primary: "#4e3d3d",
        tertiary: "#966c4d",
        branch: "Abstract",
        folder: "Realism",
        bytes: 61701,
        type: "min",
      },
      {
        original_file_name: "Oil Rainbow (3).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#bd8639",
        primary: "#5c362d",
        tertiary: "#728266",
        branch: "Abstract",
        folder: "Realism",
        bytes: 46574,
        type: "min",
      },
      {
        original_file_name: "Oil Rainbow (4).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#363237",
        primary: "#c98c32",
        tertiary: "#99602d",
        branch: "Abstract",
        folder: "Realism",
        bytes: 54848,
        type: "min",
      },
      {
        original_file_name: "Oil Rainbow (1).jpg",
        megabytes: 1.92,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#cf9432",
        primary: "#563d40",
        tertiary: "#9f6034",
        branch: "Abstract",
        folder: "Realism",
        bytes: 2012740,
        type: "max",
      },
      {
        original_file_name: "Oil Rainbow (2).jpg",
        megabytes: 1.78,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c79149",
        primary: "#4e3d3d",
        tertiary: "#966c4d",
        branch: "Abstract",
        folder: "Realism",
        bytes: 1869563,
        type: "max",
      },
      {
        original_file_name: "Oil Rainbow (3).jpg",
        megabytes: 1.63,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#be8639",
        primary: "#5c362d",
        tertiary: "#738265",
        branch: "Abstract",
        folder: "Realism",
        bytes: 1707448,
        type: "max",
      },
      {
        original_file_name: "Oil Rainbow (4).jpg",
        megabytes: 1.79,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#363237",
        primary: "#c98c32",
        tertiary: "#99612e",
        branch: "Abstract",
        folder: "Realism",
        bytes: 1875239,
        type: "max",
      },
    ]
  },
  "Paint Pour": {
    environment_title: "Paint Pour",
    images: [
      {
        original_file_name: "Paint Pour (1).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#533430",
        primary: "#d09e60",
        tertiary: "#a07146",
        branch: "Abstract",
        folder: "Realism",
        bytes: 80094,
        type: "min",
      },
      {
        original_file_name: "Paint Pour (2).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#974d34",
        primary: "#c26d2a",
        tertiary: "#322536",
        branch: "Abstract",
        folder: "Realism",
        bytes: 74381,
        type: "min",
      },
      {
        original_file_name: "Paint Pour (3).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#4c3742",
        primary: "#d29037",
        tertiary: "#97603c",
        branch: "Abstract",
        folder: "Realism",
        bytes: 69054,
        type: "min",
      },
      {
        original_file_name: "Paint Pour (4).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#2a2c37",
        primary: "#cf9f52",
        tertiary: "#914e35",
        branch: "Abstract",
        folder: "Realism",
        bytes: 71785,
        type: "min",
      },
      {
        original_file_name: "Paint Pour (1).jpg",
        megabytes: 2.52,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#533430",
        primary: "#d09e5f",
        tertiary: "#a07146",
        branch: "Abstract",
        folder: "Realism",
        bytes: 2639444,
        type: "max",
      },
      {
        original_file_name: "Paint Pour (2).jpg",
        megabytes: 2.75,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#974c34",
        primary: "#c26d2a",
        tertiary: "#322537",
        branch: "Abstract",
        folder: "Realism",
        bytes: 2887446,
        type: "max",
      },
      {
        original_file_name: "Paint Pour (3).jpg",
        megabytes: 2.17,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#4c3743",
        primary: "#d28f37",
        tertiary: "#97603c",
        branch: "Abstract",
        folder: "Realism",
        bytes: 2270884,
        type: "max",
      },
      {
        original_file_name: "Paint Pour (4).jpg",
        megabytes: 2.11,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#2a2c37",
        primary: "#d09f52",
        tertiary: "#914f37",
        branch: "Abstract",
        folder: "Realism",
        bytes: 2215380,
        type: "max",
      },
    ]
  },
  "Smoke Pillar": {
    environment_title: "Smoke Pillar",
    images: [
      {
        original_file_name: "Smoke Pillar (1).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#bfa791",
        primary: "#2a303b",
        tertiary: "#897672",
        branch: "Abstract",
        folder: "Realism",
        bytes: 37017,
        type: "min",
      },
      {
        original_file_name: "Smoke Pillar (2).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#8c9491",
        primary: "#c5c5bd",
        tertiary: "#a2adaf",
        branch: "Abstract",
        folder: "Realism",
        bytes: 37933,
        type: "min",
      },
      {
        original_file_name: "Smoke Pillar (3).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#1e2127",
        primary: "#bb9a84",
        tertiary: "#715753",
        branch: "Abstract",
        folder: "Realism",
        bytes: 36504,
        type: "min",
      },
      {
        original_file_name: "Smoke Pillar (4).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#cdc0ac",
        primary: "#342f31",
        tertiary: "#bfa792",
        branch: "Abstract",
        folder: "Realism",
        bytes: 31031,
        type: "min",
      },
      {
        original_file_name: "Smoke Pillar (1).jpg",
        megabytes: 1.08,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#bfa791",
        primary: "#2b303b",
        tertiary: "#8a7672",
        branch: "Abstract",
        folder: "Realism",
        bytes: 1137219,
        type: "max",
      },
      {
        original_file_name: "Smoke Pillar (2).jpg",
        megabytes: 1.09,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#312c2b",
        primary: "#859291",
        tertiary: "#b8b0a3",
        branch: "Abstract",
        folder: "Realism",
        bytes: 1138327,
        type: "max",
      },
      {
        original_file_name: "Smoke Pillar (3).jpg",
        megabytes: 0.98,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#1e2127",
        primary: "#bb9a84",
        tertiary: "#715753",
        branch: "Abstract",
        folder: "Realism",
        bytes: 1024945,
        type: "max",
      },
      {
        original_file_name: "Smoke Pillar (4).jpg",
        megabytes: 0.94,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#cdc0ad",
        primary: "#332f31",
        tertiary: "#bea792",
        branch: "Abstract",
        folder: "Realism",
        bytes: 984268,
        type: "max",
      },
    ]
  },
};
export default Abstract_Realism;
