import { EnvironmentEntry } from "../types";
const Abstract_Anime: Record<string, EnvironmentEntry> = {
  "Bubble Hearts": {
    environment_title: "Bubble Hearts",
    images: [
      {
        original_file_name: "Bubble Hearts (1).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#9a7d9f",
        primary: "#e8afd8",
        tertiary: "#b19bda",
        branch: "Abstract",
        folder: "Anime",
        bytes: 37076,
        type: "min"
      },
      {
        original_file_name: "Bubble Hearts (2).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#424c87",
        primary: "#f1afdb",
        tertiary: "#72659f",
        branch: "Abstract",
        folder: "Anime",
        bytes: 47285,
        type: "min"
      },
      {
        original_file_name: "Bubble Hearts (3).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#eeaad9",
        primary: "#a89dce",
        tertiary: "#7c8aba",
        branch: "Abstract",
        folder: "Anime",
        bytes: 33427,
        type: "min"
      },
      {
        original_file_name: "Bubble Hearts (4).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#b5aede",
        primary: "#eabed9",
        tertiary: "#a1abd8",
        branch: "Abstract",
        folder: "Anime",
        bytes: 40002,
        type: "min"
      },
      {
        original_file_name: "Bubble Hearts (1).jpg",
        megabytes: 1.1,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#9a7d9f",
        primary: "#e8afd8",
        tertiary: "#b19bda",
        branch: "Abstract",
        folder: "Anime",
        bytes: 1157108,
        type: "max"
      },
      {
        original_file_name: "Bubble Hearts (2).jpg",
        megabytes: 1.27,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#414c87",
        primary: "#72659f",
        tertiary: "#f9cded",
        branch: "Abstract",
        folder: "Anime",
        bytes: 1327469,
        type: "max"
      },
      {
        original_file_name: "Bubble Hearts (3).jpg",
        megabytes: 0.98,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#eeaad9",
        primary: "#a99dcf",
        tertiary: "#7c8abb",
        branch: "Abstract",
        folder: "Anime",
        bytes: 1028817,
        type: "max"
      },
      {
        original_file_name: "Bubble Hearts (4).jpg",
        megabytes: 1.0,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#b5aede",
        primary: "#ebbeda",
        tertiary: "#a1acd9",
        branch: "Abstract",
        folder: "Anime",
        bytes: 1044039,
        type: "max"
      }
    ]
  },
  "Bubble Ocean": {
    environment_title: "Bubble Ocean",
    images: [
      {
        original_file_name: "Bubble Ocean (1).jpg",
        megabytes: 0.09,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#59c6be",
        primary: "#173d53",
        tertiary: "#bbebef",
        branch: "Abstract",
        folder: "Anime",
        bytes: 91552,
        type: "min"
      },
      {
        original_file_name: "Bubble Ocean (2).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#133353",
        primary: "#b7eeea",
        tertiary: "#5fd1ca",
        branch: "Abstract",
        folder: "Anime",
        bytes: 87866,
        type: "min"
      },
      {
        original_file_name: "Bubble Ocean (3).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#74d2e1",
        primary: "#194d5c",
        tertiary: "#5d9bd6",
        branch: "Abstract",
        folder: "Anime",
        bytes: 87616,
        type: "min"
      },
      {
        original_file_name: "Bubble Ocean (4).jpg",
        megabytes: 0.09,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#275c79",
        primary: "#bae6e9",
        tertiary: "#6ed0c7",
        branch: "Abstract",
        folder: "Anime",
        bytes: 89188,
        type: "min"
      },
      {
        original_file_name: "Bubble Ocean (1).jpg",
        megabytes: 1.84,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#163851",
        primary: "#58c7be",
        tertiary: "#bbedf0",
        branch: "Abstract",
        folder: "Anime",
        bytes: 1932661,
        type: "max"
      },
      {
        original_file_name: "Bubble Ocean (2).jpg",
        megabytes: 1.73,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#153b58",
        primary: "#b8eee9",
        tertiary: "#5fd1cb",
        branch: "Abstract",
        folder: "Anime",
        bytes: 1812872,
        type: "max"
      },
      {
        original_file_name: "Bubble Ocean (3).jpg",
        megabytes: 1.73,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#1b4f61",
        primary: "#c1edf7",
        tertiary: "#74d3e2",
        branch: "Abstract",
        folder: "Anime",
        bytes: 1816209,
        type: "max"
      },
      {
        original_file_name: "Bubble Ocean (4).jpg",
        megabytes: 1.76,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#275c79",
        primary: "#bae6e9",
        tertiary: "#6dd0c7",
        branch: "Abstract",
        folder: "Anime",
        bytes: 1841454,
        type: "max"
      }
    ]
  },
  "Candy Smoke": {
    environment_title: "Candy Smoke",
    images: [
      {
        original_file_name: "Candy Smoke (1).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#323355",
        primary: "#dc9eb1",
        tertiary: "#7385d0",
        branch: "Abstract",
        folder: "Anime",
        bytes: 84620,
        type: "min"
      },
      {
        original_file_name: "Candy Smoke (2).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#957ba8",
        primary: "#2b3251",
        tertiary: "#ee9bab",
        branch: "Abstract",
        folder: "Anime",
        bytes: 68416,
        type: "min"
      },
      {
        original_file_name: "Candy Smoke (3).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#2c3456",
        primary: "#de92bc",
        tertiary: "#86668e",
        branch: "Abstract",
        folder: "Anime",
        bytes: 74503,
        type: "min"
      },
      {
        original_file_name: "Candy Smoke (4).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#283150",
        primary: "#db9dc0",
        tertiary: "#957295",
        branch: "Abstract",
        folder: "Anime",
        bytes: 69651,
        type: "min"
      },
      {
        original_file_name: "Candy Smoke (1).jpg",
        megabytes: 1.92,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#323355",
        primary: "#dd9db1",
        tertiary: "#7285d0",
        branch: "Abstract",
        folder: "Anime",
        bytes: 2018109,
        type: "max"
      },
      {
        original_file_name: "Candy Smoke (2).jpg",
        megabytes: 1.65,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#947ba8",
        primary: "#2b3251",
        tertiary: "#ee9baa",
        branch: "Abstract",
        folder: "Anime",
        bytes: 1726640,
        type: "max"
      },
      {
        original_file_name: "Candy Smoke (3).jpg",
        megabytes: 1.71,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#2c3457",
        primary: "#df92bc",
        tertiary: "#86668d",
        branch: "Abstract",
        folder: "Anime",
        bytes: 1797189,
        type: "max"
      },
      {
        original_file_name: "Candy Smoke (4).jpg",
        megabytes: 1.69,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#283150",
        primary: "#db9dc0",
        tertiary: "#957295",
        branch: "Abstract",
        folder: "Anime",
        bytes: 1775556,
        type: "max"
      }
    ]
  },
  "Cotton Tones": {
    environment_title: "Cotton Tones",
    images: [
      {
        original_file_name: "Cotton Tones (1).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#ebdadd",
        primary: "#85b8df",
        tertiary: "#b6bad6",
        branch: "Abstract",
        folder: "Anime",
        bytes: 71555,
        type: "min"
      },
      {
        original_file_name: "Cotton Tones (2).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#7babdd",
        primary: "#e2e5ed",
        tertiary: "#3d7fc5",
        branch: "Abstract",
        folder: "Anime",
        bytes: 78157,
        type: "min"
      },
      {
        original_file_name: "Cotton Tones (3).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#e2edf2",
        primary: "#78a9d5",
        tertiary: "#32629a",
        branch: "Abstract",
        folder: "Anime",
        bytes: 78801,
        type: "min"
      },
      {
        original_file_name: "Cotton Tones (4).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#e1eef5",
        primary: "#5e93c5",
        tertiary: "#a0bede",
        branch: "Abstract",
        folder: "Anime",
        bytes: 83705,
        type: "min"
      },
      {
        original_file_name: "Cotton Tones (1).jpg",
        megabytes: 1.6,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#ecdadd",
        primary: "#85b8df",
        tertiary: "#b7bad6",
        branch: "Abstract",
        folder: "Anime",
        bytes: 1682644,
        type: "max"
      },
      {
        original_file_name: "Cotton Tones (2).jpg",
        megabytes: 1.7,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#7eacdd",
        primary: "#e2e6ed",
        tertiary: "#397cc5",
        branch: "Abstract",
        folder: "Anime",
        bytes: 1781010,
        type: "max"
      },
      {
        original_file_name: "Cotton Tones (3).jpg",
        megabytes: 1.8,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#e3edf2",
        primary: "#78a9d6",
        tertiary: "#3578b8",
        branch: "Abstract",
        folder: "Anime",
        bytes: 1883104,
        type: "max"
      },
      {
        original_file_name: "Cotton Tones (4).jpg",
        megabytes: 1.81,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#a6c6e5",
        primary: "#5d92c5",
        tertiary: "#e1eef6",
        branch: "Abstract",
        folder: "Anime",
        bytes: 1897114,
        type: "max"
      }
    ]
  },
  "Crystal Hearts": {
    environment_title: "Crystal Hearts",
    images: [
      {
        original_file_name: "Crystal Hearts (1).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#526c9d",
        primary: "#e0bfdb",
        tertiary: "#9d9ec2",
        branch: "Abstract",
        folder: "Anime",
        bytes: 68429,
        type: "min"
      },
      {
        original_file_name: "Crystal Hearts (2).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#5384bd",
        primary: "#f1c8dc",
        tertiary: "#abb3d9",
        branch: "Abstract",
        folder: "Anime",
        bytes: 41135,
        type: "min"
      },
      {
        original_file_name: "Crystal Hearts (3).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#ddb7d1",
        primary: "#273757",
        tertiary: "#6895c2",
        branch: "Abstract",
        folder: "Anime",
        bytes: 65674,
        type: "min"
      },
      {
        original_file_name: "Crystal Hearts (4).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#ead6ec",
        primary: "#92add9",
        tertiary: "#3c6da7",
        branch: "Abstract",
        folder: "Anime",
        bytes: 69543,
        type: "min"
      },
      {
        original_file_name: "Crystal Hearts (1).jpg",
        megabytes: 1.47,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#526c9d",
        primary: "#e0bfdb",
        tertiary: "#9d9ec3",
        branch: "Abstract",
        folder: "Anime",
        bytes: 1544172,
        type: "max"
      },
      {
        original_file_name: "Crystal Hearts (2).jpg",
        megabytes: 0.95,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#5283bc",
        primary: "#f2c8dc",
        tertiary: "#abb3d9",
        branch: "Abstract",
        folder: "Anime",
        bytes: 995489,
        type: "max"
      },
      {
        original_file_name: "Crystal Hearts (3).jpg",
        megabytes: 1.42,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#ddb7d1",
        primary: "#273757",
        tertiary: "#544967",
        branch: "Abstract",
        folder: "Anime",
        bytes: 1490744,
        type: "max"
      },
      {
        original_file_name: "Crystal Hearts (4).jpg",
        megabytes: 1.5,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#ead5ec",
        primary: "#91adda",
        tertiary: "#3c6ea8",
        branch: "Abstract",
        folder: "Anime",
        bytes: 1572288,
        type: "max"
      }
    ]
  },
  "Feather Drifts": {
    environment_title: "Feather Drifts",
    images: [
      {
        original_file_name: "Feather Drifts (1).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#5584b9",
        primary: "#e4d6db",
        tertiary: "#9ca8c9",
        branch: "Abstract",
        folder: "Anime",
        bytes: 85577,
        type: "min"
      },
      {
        original_file_name: "Feather Drifts (2).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#e3d8de",
        primary: "#517bb2",
        tertiary: "#9da5cd",
        branch: "Abstract",
        folder: "Anime",
        bytes: 86935,
        type: "min"
      },
      {
        original_file_name: "Feather Drifts (3).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#ded3db",
        primary: "#4c77ae",
        tertiary: "#93cdf5",
        branch: "Abstract",
        folder: "Anime",
        bytes: 88229,
        type: "min"
      },
      {
        original_file_name: "Feather Drifts (4).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#e1cfde",
        primary: "#5a8abf",
        tertiary: "#9b92b7",
        branch: "Abstract",
        folder: "Anime",
        bytes: 87280,
        type: "min"
      },
      {
        original_file_name: "Feather Drifts (1).jpg",
        megabytes: 1.85,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#5484b9",
        primary: "#e4d6db",
        tertiary: "#9da8ca",
        branch: "Abstract",
        folder: "Anime",
        bytes: 1943879,
        type: "max"
      },
      {
        original_file_name: "Feather Drifts (2).jpg",
        megabytes: 1.85,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#e3d8de",
        primary: "#517bb2",
        tertiary: "#9da5cd",
        branch: "Abstract",
        folder: "Anime",
        bytes: 1938967,
        type: "max"
      },
      {
        original_file_name: "Feather Drifts (3).jpg",
        megabytes: 1.84,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#dfd3db",
        primary: "#4c77ae",
        tertiary: "#92cdf6",
        branch: "Abstract",
        folder: "Anime",
        bytes: 1924368,
        type: "max"
      },
      {
        original_file_name: "Feather Drifts (4).jpg",
        megabytes: 1.88,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#e2cfde",
        primary: "#598abf",
        tertiary: "#9b91b7",
        branch: "Abstract",
        folder: "Anime",
        bytes: 1974073,
        type: "max"
      }
    ]
  },
  "Frilly Bloom": {
    environment_title: "Frilly Bloom",
    images: [
      {
        original_file_name: "Frilly Bloom (1).jpg",
        megabytes: 0.09,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#28463a",
        primary: "#abbbd5",
        tertiary: "#9b9c41",
        branch: "Abstract",
        folder: "Anime",
        bytes: 92430,
        type: "min"
      },
      {
        original_file_name: "Frilly Bloom (2).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#98bd46",
        primary: "#325028",
        tertiary: "#e9dedd",
        branch: "Abstract",
        folder: "Anime",
        bytes: 78280,
        type: "min"
      },
      {
        original_file_name: "Frilly Bloom (3).jpg",
        megabytes: 0.09,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#96944b",
        primary: "#315847",
        tertiary: "#efe7df",
        branch: "Abstract",
        folder: "Anime",
        bytes: 97813,
        type: "min"
      },
      {
        original_file_name: "Frilly Bloom (4).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#e9ddd6",
        primary: "#28534a",
        tertiary: "#8da258",
        branch: "Abstract",
        folder: "Anime",
        bytes: 83932,
        type: "min"
      },
      {
        original_file_name: "Frilly Bloom (1).jpg",
        megabytes: 1.99,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#28473a",
        primary: "#abbbd5",
        tertiary: "#9c9d3f",
        branch: "Abstract",
        folder: "Anime",
        bytes: 2089086,
        type: "max"
      },
      {
        original_file_name: "Frilly Bloom (2).jpg",
        megabytes: 1.63,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#98bd46",
        primary: "#325028",
        tertiary: "#e9dedd",
        branch: "Abstract",
        folder: "Anime",
        bytes: 1711070,
        type: "max"
      },
      {
        original_file_name: "Frilly Bloom (3).jpg",
        megabytes: 2.07,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#97934a",
        primary: "#325948",
        tertiary: "#f0e7df",
        branch: "Abstract",
        folder: "Anime",
        bytes: 2167434,
        type: "max"
      },
      {
        original_file_name: "Frilly Bloom (4).jpg",
        megabytes: 1.89,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#e9ddd6",
        primary: "#28534a",
        tertiary: "#8ea257",
        branch: "Abstract",
        folder: "Anime",
        bytes: 1980206,
        type: "max"
      }
    ]
  },
  "Petal Glow": {
    environment_title: "Petal Glow",
    images: [
      {
        original_file_name: "Petal Glow (1).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#1e151d",
        primary: "#eaae9f",
        tertiary: "#8475b2",
        branch: "Abstract",
        folder: "Anime",
        bytes: 81557,
        type: "min"
      },
      {
        original_file_name: "Petal Glow (2).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#262e44",
        primary: "#ebac9d",
        tertiary: "#815a66",
        branch: "Abstract",
        folder: "Anime",
        bytes: 76419,
        type: "min"
      },
      {
        original_file_name: "Petal Glow (3).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#141c2f",
        primary: "#ecb4c2",
        tertiary: "#515877",
        branch: "Abstract",
        folder: "Anime",
        bytes: 66780,
        type: "min"
      },
      {
        original_file_name: "Petal Glow (4).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#1d1b28",
        primary: "#d7afc4",
        tertiary: "#764d4b",
        branch: "Abstract",
        folder: "Anime",
        bytes: 66100,
        type: "min"
      },
      {
        original_file_name: "Petal Glow (1).jpg",
        megabytes: 1.59,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#1f151d",
        primary: "#ebae9f",
        tertiary: "#8375b2",
        branch: "Abstract",
        folder: "Anime",
        bytes: 1663624,
        type: "max"
      },
      {
        original_file_name: "Petal Glow (2).jpg",
        megabytes: 1.59,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#262e44",
        primary: "#ebac9d",
        tertiary: "#815a66",
        branch: "Abstract",
        folder: "Anime",
        bytes: 1665756,
        type: "max"
      },
      {
        original_file_name: "Petal Glow (3).jpg",
        megabytes: 1.35,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#141c2f",
        primary: "#edb4c2",
        tertiary: "#4f5876",
        branch: "Abstract",
        folder: "Anime",
        bytes: 1418741,
        type: "max"
      },
      {
        original_file_name: "Petal Glow (4).jpg",
        megabytes: 1.44,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#1d1b29",
        primary: "#d8afc3",
        tertiary: "#764d4b",
        branch: "Abstract",
        folder: "Anime",
        bytes: 1509319,
        type: "max"
      }
    ]
  },
  "Pixel Rain": {
    environment_title: "Pixel Rain",
    images: [
      {
        original_file_name: "Pixel Rain (1).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c26f9b",
        primary: "#1c1827",
        tertiary: "#6f425f",
        branch: "Abstract",
        folder: "Anime",
        bytes: 48367,
        type: "min"
      },
      {
        original_file_name: "Pixel Rain (2).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#bf7ba4",
        primary: "#1d172e",
        tertiary: "#692f54",
        branch: "Abstract",
        folder: "Anime",
        bytes: 68995,
        type: "min"
      },
      {
        original_file_name: "Pixel Rain (3).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c16276",
        primary: "#1b1d2f",
        tertiary: "#6d405b",
        branch: "Abstract",
        folder: "Anime",
        bytes: 66336,
        type: "min"
      },
      {
        original_file_name: "Pixel Rain (4).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#121426",
        primary: "#ce7cb6",
        tertiary: "#574a74",
        branch: "Abstract",
        folder: "Anime",
        bytes: 61753,
        type: "min"
      },
      {
        original_file_name: "Pixel Rain (1).jpg",
        megabytes: 1.09,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c86d9b",
        primary: "#1c1827",
        tertiary: "#6f3f5d",
        branch: "Abstract",
        folder: "Anime",
        bytes: 1140458,
        type: "max"
      },
      {
        original_file_name: "Pixel Rain (2).jpg",
        megabytes: 1.41,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c077a2",
        primary: "#1d172f",
        tertiary: "#6b2e54",
        branch: "Abstract",
        folder: "Anime",
        bytes: 1481079,
        type: "max"
      },
      {
        original_file_name: "Pixel Rain (3).jpg",
        megabytes: 1.58,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c16175",
        primary: "#1b1d2f",
        tertiary: "#6d405b",
        branch: "Abstract",
        folder: "Anime",
        bytes: 1654634,
        type: "max"
      },
      {
        original_file_name: "Pixel Rain (4).jpg",
        megabytes: 1.4,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#121426",
        primary: "#cf7cb6",
        tertiary: "#574a75",
        branch: "Abstract",
        folder: "Anime",
        bytes: 1469078,
        type: "max"
      }
    ]
  },
  "Rainbow Wisp": {
    environment_title: "Rainbow Wisp",
    images: [
      {
        original_file_name: "Rainbow Wisp (1).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#4d85c7",
        primary: "#b8bed8",
        tertiary: "#172e55",
        branch: "Abstract",
        folder: "Anime",
        bytes: 75740,
        type: "min"
      },
      {
        original_file_name: "Rainbow Wisp (2).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#1b2a4b",
        primary: "#d1a1ab",
        tertiary: "#57578e",
        branch: "Abstract",
        folder: "Anime",
        bytes: 77066,
        type: "min"
      },
      {
        original_file_name: "Rainbow Wisp (3).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#162d59",
        primary: "#cba9bb",
        tertiary: "#4f7dc8",
        branch: "Abstract",
        folder: "Anime",
        bytes: 72975,
        type: "min"
      },
      {
        original_file_name: "Rainbow Wisp (4).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#caaaa7",
        primary: "#1b2d4e",
        tertiary: "#496694",
        branch: "Abstract",
        folder: "Anime",
        bytes: 75268,
        type: "min"
      },
      {
        original_file_name: "Rainbow Wisp (1).jpg",
        megabytes: 1.78,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#4c85c7",
        primary: "#b8bed8",
        tertiary: "#172e55",
        branch: "Abstract",
        folder: "Anime",
        bytes: 1864611,
        type: "max"
      },
      {
        original_file_name: "Rainbow Wisp (2).jpg",
        megabytes: 1.8,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#1b2a4b",
        primary: "#d2a1ab",
        tertiary: "#56578e",
        branch: "Abstract",
        folder: "Anime",
        bytes: 1885918,
        type: "max"
      },
      {
        original_file_name: "Rainbow Wisp (3).jpg",
        megabytes: 1.76,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#162d59",
        primary: "#cba9bb",
        tertiary: "#4e7dc8",
        branch: "Abstract",
        folder: "Anime",
        bytes: 1841256,
        type: "max"
      },
      {
        original_file_name: "Rainbow Wisp (4).jpg",
        megabytes: 1.77,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#1b2e4f",
        primary: "#caaaa7",
        tertiary: "#496594",
        branch: "Abstract",
        folder: "Anime",
        bytes: 1853058,
        type: "max"
      }
    ]
  },
  "Ribbon Burst": {
    environment_title: "Ribbon Burst",
    images: [
      {
        original_file_name: "Ribbon Burst (1).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#648ecc",
        primary: "#e4beba",
        tertiary: "#665db0",
        branch: "Abstract",
        folder: "Anime",
        bytes: 56053,
        type: "min"
      },
      {
        original_file_name: "Ribbon Burst (2).jpg",
        megabytes: 0.0,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#b4b4b4",
        primary: "#040404",
        tertiary: "#5c5c5c",
        branch: "Abstract",
        folder: "Anime",
        bytes: 2772,
        type: "min"
      },
      {
        original_file_name: "Ribbon Burst (3).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#364e73",
        primary: "#e2b3a5",
        tertiary: "#8bcbd9",
        branch: "Abstract",
        folder: "Anime",
        bytes: 64030,
        type: "min"
      },
      {
        original_file_name: "Ribbon Burst (4).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#355f98",
        primary: "#ddc5c7",
        tertiary: "#8fd2e0",
        branch: "Abstract",
        folder: "Anime",
        bytes: 63577,
        type: "min"
      },
      {
        original_file_name: "Ribbon Burst (1).jpg",
        megabytes: 1.49,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#648ecd",
        primary: "#e4beba",
        tertiary: "#95d5cc",
        branch: "Abstract",
        folder: "Anime",
        bytes: 1567298,
        type: "max"
      },
      {
        original_file_name: "Ribbon Burst (2).jpg",
        megabytes: 0.11,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#b7b7b7",
        primary: "#040404",
        tertiary: "#5b5b5b",
        branch: "Abstract",
        folder: "Anime",
        bytes: 112709,
        type: "max"
      },
      {
        original_file_name: "Ribbon Burst (3).jpg",
        megabytes: 1.53,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#364f74",
        primary: "#e3b1a4",
        tertiary: "#8bcbd9",
        branch: "Abstract",
        folder: "Anime",
        bytes: 1608473,
        type: "max"
      },
      {
        original_file_name: "Ribbon Burst (4).jpg",
        megabytes: 1.65,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#365f98",
        primary: "#dec5c7",
        tertiary: "#8fd2e0",
        branch: "Abstract",
        folder: "Anime",
        bytes: 1724934,
        type: "max"
      }
    ]
  },
  "Smiling Shapes": {
    environment_title: "Smiling Shapes",
    images: [
      {
        original_file_name: "Smiling Shapes (1).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#6b4b3d",
        primary: "#f3d6c4",
        tertiary: "#2b2220",
        branch: "Abstract",
        folder: "Anime",
        bytes: 77854,
        type: "min"
      },
      {
        original_file_name: "Smiling Shapes (2).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#efc8b4",
        primary: "#5d463b",
        tertiary: "#342d28",
        branch: "Abstract",
        folder: "Anime",
        bytes: 78719,
        type: "min"
      },
      {
        original_file_name: "Smiling Shapes (3).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#2b2823",
        primary: "#e8cab1",
        tertiary: "#749e7e",
        branch: "Abstract",
        folder: "Anime",
        bytes: 84309,
        type: "min"
      },
      {
        original_file_name: "Smiling Shapes (4).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#42342f",
        primary: "#f0cbb7",
        tertiary: "#59403b",
        branch: "Abstract",
        folder: "Anime",
        bytes: 83049,
        type: "min"
      },
      {
        original_file_name: "Smiling Shapes (1).jpg",
        megabytes: 1.67,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#6b4b3d",
        primary: "#f3d6c4",
        tertiary: "#2b2320",
        branch: "Abstract",
        folder: "Anime",
        bytes: 1753927,
        type: "max"
      },
      {
        original_file_name: "Smiling Shapes (2).jpg",
        megabytes: 1.66,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#f0c8b4",
        primary: "#5d463b",
        tertiary: "#342e29",
        branch: "Abstract",
        folder: "Anime",
        bytes: 1735691,
        type: "max"
      },
      {
        original_file_name: "Smiling Shapes (3).jpg",
        megabytes: 1.77,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#2b2823",
        primary: "#e9cab1",
        tertiary: "#73a07e",
        branch: "Abstract",
        folder: "Anime",
        bytes: 1853142,
        type: "max"
      },
      {
        original_file_name: "Smiling Shapes (4).jpg",
        megabytes: 1.78,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#846354",
        primary: "#f3cbb6",
        tertiary: "#574a4a",
        branch: "Abstract",
        folder: "Anime",
        bytes: 1867572,
        type: "max"
      }
    ]
  },
  "Soft Galaxy": {
    environment_title: "Soft Galaxy",
    images: [
      {
        original_file_name: "Soft Galaxy (1).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#4e4980",
        primary: "#d7b7e4",
        tertiary: "#9690d1",
        branch: "Abstract",
        folder: "Anime",
        bytes: 85923,
        type: "min"
      },
      {
        original_file_name: "Soft Galaxy (2).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#252345",
        primary: "#cda7de",
        tertiary: "#665a9f",
        branch: "Abstract",
        folder: "Anime",
        bytes: 81144,
        type: "min"
      },
      {
        original_file_name: "Soft Galaxy (3).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#dca7d3",
        primary: "#4a467c",
        tertiary: "#9470a5",
        branch: "Abstract",
        folder: "Anime",
        bytes: 86354,
        type: "min"
      },
      {
        original_file_name: "Soft Galaxy (4).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#3f4177",
        primary: "#7e73b2",
        tertiary: "#daabd8",
        branch: "Abstract",
        folder: "Anime",
        bytes: 85332,
        type: "min"
      },
      {
        original_file_name: "Soft Galaxy (1).jpg",
        megabytes: 1.91,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#4e4980",
        primary: "#d7b7e4",
        tertiary: "#9690d1",
        branch: "Abstract",
        folder: "Anime",
        bytes: 1999505,
        type: "max"
      },
      {
        original_file_name: "Soft Galaxy (2).jpg",
        megabytes: 1.92,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#252345",
        primary: "#cda6de",
        tertiary: "#66599f",
        branch: "Abstract",
        folder: "Anime",
        bytes: 2017343,
        type: "max"
      },
      {
        original_file_name: "Soft Galaxy (3).jpg",
        megabytes: 2.04,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#dda6d3",
        primary: "#4a467c",
        tertiary: "#9470a5",
        branch: "Abstract",
        folder: "Anime",
        bytes: 2144263,
        type: "max"
      },
      {
        original_file_name: "Soft Galaxy (4).jpg",
        megabytes: 2.08,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#3f4177",
        primary: "#7e73b2",
        tertiary: "#daabd8",
        branch: "Abstract",
        folder: "Anime",
        bytes: 2184848,
        type: "max"
      }
    ]
  },
  "Soft Pastels": {
    environment_title: "Soft Pastels",
    images: [
      {
        original_file_name: "Soft Pastels (1).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#5789ba",
        primary: "#dfd6de",
        tertiary: "#99acd1",
        branch: "Abstract",
        folder: "Anime",
        bytes: 69563,
        type: "min"
      },
      {
        original_file_name: "Soft Pastels (2).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#587cad",
        primary: "#e9cbc9",
        tertiary: "#a49dbf",
        branch: "Abstract",
        folder: "Anime",
        bytes: 69557,
        type: "min"
      },
      {
        original_file_name: "Soft Pastels (3).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#dfc8c9",
        primary: "#4d87ba",
        tertiary: "#95a6c9",
        branch: "Abstract",
        folder: "Anime",
        bytes: 74285,
        type: "min"
      },
      {
        original_file_name: "Soft Pastels (4).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#2b6397",
        primary: "#e1b9bb",
        tertiary: "#9e93b7",
        branch: "Abstract",
        folder: "Anime",
        bytes: 81325,
        type: "min"
      },
      {
        original_file_name: "Soft Pastels (1).jpg",
        megabytes: 1.48,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#5789bb",
        primary: "#dfd6de",
        tertiary: "#99acd2",
        branch: "Abstract",
        folder: "Anime",
        bytes: 1555447,
        type: "max"
      },
      {
        original_file_name: "Soft Pastels (2).jpg",
        megabytes: 1.54,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#e9cbc9",
        primary: "#5e82b2",
        tertiary: "#a49ebf",
        branch: "Abstract",
        folder: "Anime",
        bytes: 1619780,
        type: "max"
      },
      {
        original_file_name: "Soft Pastels (3).jpg",
        megabytes: 1.6,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#dfc8c8",
        primary: "#538cbd",
        tertiary: "#95a6ca",
        branch: "Abstract",
        folder: "Anime",
        bytes: 1674846,
        type: "max"
      },
      {
        original_file_name: "Soft Pastels (4).jpg",
        megabytes: 1.74,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#2b6398",
        primary: "#e2b9ba",
        tertiary: "#9d93b7",
        branch: "Abstract",
        folder: "Anime",
        bytes: 1820016,
        type: "max"
      }
    ]
  },
  "Spiral Sparks": {
    environment_title: "Spiral Sparks",
    images: [
      {
        original_file_name: "Spiral Sparks (1).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#cfa7ca",
        primary: "#40476c",
        tertiary: "#1f2637",
        branch: "Abstract",
        folder: "Anime",
        bytes: 73945,
        type: "min"
      },
      {
        original_file_name: "Spiral Sparks (2).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#221a28",
        primary: "#daa2a6",
        tertiary: "#805367",
        branch: "Abstract",
        folder: "Anime",
        bytes: 84655,
        type: "min"
      },
      {
        original_file_name: "Spiral Sparks (3).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#211f2b",
        primary: "#d6bcb1",
        tertiary: "#745961",
        branch: "Abstract",
        folder: "Anime",
        bytes: 73829,
        type: "min"
      },
      {
        original_file_name: "Spiral Sparks (4).jpg",
        megabytes: 0.09,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#2a273c",
        primary: "#dfacb6",
        tertiary: "#7f5863",
        branch: "Abstract",
        folder: "Anime",
        bytes: 92184,
        type: "min"
      },
      {
        original_file_name: "Spiral Sparks (1).jpg",
        megabytes: 1.73,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#cfa6c9",
        primary: "#40476c",
        tertiary: "#1f2637",
        branch: "Abstract",
        folder: "Anime",
        bytes: 1809996,
        type: "max"
      },
      {
        original_file_name: "Spiral Sparks (2).jpg",
        megabytes: 1.78,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#221a29",
        primary: "#daa1a5",
        tertiary: "#805266",
        branch: "Abstract",
        folder: "Anime",
        bytes: 1870618,
        type: "max"
      },
      {
        original_file_name: "Spiral Sparks (3).jpg",
        megabytes: 1.67,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#211f2c",
        primary: "#d7bbaf",
        tertiary: "#745860",
        branch: "Abstract",
        folder: "Anime",
        bytes: 1755946,
        type: "max"
      },
      {
        original_file_name: "Spiral Sparks (4).jpg",
        megabytes: 1.96,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#2a273c",
        primary: "#dfacb5",
        tertiary: "#7f5762",
        branch: "Abstract",
        folder: "Anime",
        bytes: 2051156,
        type: "max"
      }
    ]
  }
};
export default Abstract_Anime;
