import { EnvironmentEntry } from "../types";
const Abstract_Cinematic: Record<string, EnvironmentEntry> = {
  "Chromatic Storm": {
    environment_title: "Chromatic Storm",
    images: [
      {
        original_file_name: "Chromatic Storm (1).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#262b31",
        primary: "#c48987",
        tertiary: "#77adba",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 39299,
        type: "min",
      },
      {
        original_file_name: "Chromatic Storm (2).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#b5958e",
        primary: "#1d242e",
        tertiary: "#527182",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 36700,
        type: "min",
      },
      {
        original_file_name: "Chromatic Storm (3).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#b2abb6",
        primary: "#24323f",
        tertiary: "#5f7482",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 36776,
        type: "min",
      },
      {
        original_file_name: "Chromatic Storm (4).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c98e92",
        primary: "#1d2934",
        tertiary: "#704453",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 33361,
        type: "min",
      },
      {
        original_file_name: "Chromatic Storm (1).jpg",
        megabytes: 1.23,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#262b31",
        primary: "#c48986",
        tertiary: "#77adba",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 1287312,
        type: "max",
      },
      {
        original_file_name: "Chromatic Storm (2).jpg",
        megabytes: 0.98,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#b5958e",
        primary: "#1d242e",
        tertiary: "#527282",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 1027031,
        type: "max",
      },
      {
        original_file_name: "Chromatic Storm (3).jpg",
        megabytes: 1.07,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#b2abb6",
        primary: "#24323f",
        tertiary: "#5f7482",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 1118705,
        type: "max",
      },
      {
        original_file_name: "Chromatic Storm (4).jpg",
        megabytes: 0.95,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c98e91",
        primary: "#1d2934",
        tertiary: "#704453",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 996794,
        type: "max",
      },
    ]
  },
  "Cosmic Swirl": {
    environment_title: "Cosmic Swirl",
    images: [
      {
        original_file_name: "Cosmic Swirl (1).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c19489",
        primary: "#1a1b25",
        tertiary: "#3b5976",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 45767,
        type: "min",
      },
      {
        original_file_name: "Cosmic Swirl (2).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#ac99b1",
        primary: "#12131a",
        tertiary: "#3e536d",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 43418,
        type: "min",
      },
      {
        original_file_name: "Cosmic Swirl (3).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#b9a593",
        primary: "#111722",
        tertiary: "#5c686f",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 49065,
        type: "min",
      },
      {
        original_file_name: "Cosmic Swirl (4).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#15151d",
        primary: "#a48076",
        tertiary: "#71646e",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 38422,
        type: "min",
      },
      {
        original_file_name: "Cosmic Swirl (1).jpg",
        megabytes: 1.23,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c09488",
        primary: "#1a1b25",
        tertiary: "#3c5876",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 1285896,
        type: "max",
      },
      {
        original_file_name: "Cosmic Swirl (2).jpg",
        megabytes: 1.16,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#ac98b1",
        primary: "#12131a",
        tertiary: "#3e536d",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 1217765,
        type: "max",
      },
      {
        original_file_name: "Cosmic Swirl (3).jpg",
        megabytes: 1.17,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#b9a492",
        primary: "#111722",
        tertiary: "#5c686f",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 1228966,
        type: "max",
      },
      {
        original_file_name: "Cosmic Swirl (4).jpg",
        megabytes: 1.1,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#15151d",
        primary: "#a48076",
        tertiary: "#70646e",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 1151498,
        type: "max",
      },
    ]
  },
  "Ethereal Smoke": {
    environment_title: "Ethereal Smoke",
    images: [
      {
        original_file_name: "Ethereal Smoke (1).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c0c0c6",
        primary: "#6b8797",
        tertiary: "#282235",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 33294,
        type: "min",
      },
      {
        original_file_name: "Ethereal Smoke (2).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#2c2e47",
        primary: "#b1b9bf",
        tertiary: "#3b5d72",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 44876,
        type: "min",
      },
      {
        original_file_name: "Ethereal Smoke (3).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#262636",
        primary: "#798894",
        tertiary: "#b1b8be",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 42436,
        type: "min",
      },
      {
        original_file_name: "Ethereal Smoke (4).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#bab2b8",
        primary: "#5c7084",
        tertiary: "#231f32",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 32980,
        type: "min",
      },
      {
        original_file_name: "Ethereal Smoke (1).jpg",
        megabytes: 1.06,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c0c0c6",
        primary: "#6b8797",
        tertiary: "#272235",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 1109779,
        type: "max",
      },
      {
        original_file_name: "Ethereal Smoke (2).jpg",
        megabytes: 1.22,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#293149",
        primary: "#b1b9bf",
        tertiary: "#504769",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 1283544,
        type: "max",
      },
      {
        original_file_name: "Ethereal Smoke (3).jpg",
        megabytes: 1.23,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#222331",
        primary: "#7a8794",
        tertiary: "#b7bec3",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 1286250,
        type: "max",
      },
      {
        original_file_name: "Ethereal Smoke (4).jpg",
        megabytes: 1.06,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#bab2b8",
        primary: "#5c7084",
        tertiary: "#231f33",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 1113901,
        type: "max",
      },
    ]
  },
  "Galactic Drip": {
    environment_title: "Galactic Drip",
    images: [
      {
        original_file_name: "Galactic Drip (1).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#b74d79",
        primary: "#221722",
        tertiary: "#783453",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 49773,
        type: "min",
      },
      {
        original_file_name: "Galactic Drip (2).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#281b2d",
        primary: "#c3bac0",
        tertiary: "#93446f",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 54996,
        type: "min",
      },
      {
        original_file_name: "Galactic Drip (3).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#2a1d2b",
        primary: "#b36e85",
        tertiary: "#885a6f",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 51136,
        type: "min",
      },
      {
        original_file_name: "Galactic Drip (4).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#2b1b29",
        primary: "#bf96ad",
        tertiary: "#805870",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 54932,
        type: "min",
      },
      {
        original_file_name: "Galactic Drip (1).jpg",
        megabytes: 1.48,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#b74c78",
        primary: "#221822",
        tertiary: "#783553",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 1547694,
        type: "max",
      },
      {
        original_file_name: "Galactic Drip (2).jpg",
        megabytes: 1.51,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#281b2e",
        primary: "#c3bac0",
        tertiary: "#93446f",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 1580483,
        type: "max",
      },
      {
        original_file_name: "Galactic Drip (3).jpg",
        megabytes: 1.57,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#2a1d2b",
        primary: "#b36e85",
        tertiary: "#88596f",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 1648066,
        type: "max",
      },
      {
        original_file_name: "Galactic Drip (4).jpg",
        megabytes: 1.75,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#2b1b2a",
        primary: "#be95ad",
        tertiary: "#7f5871",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 1839352,
        type: "max",
      },
    ]
  },
  "Gilded Cascade": {
    environment_title: "Gilded Cascade",
    images: [
      {
        original_file_name: "Gilded Cascade (1).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#131317",
        primary: "#c8a46e",
        tertiary: "#63421d",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 68786,
        type: "min",
      },
      {
        original_file_name: "Gilded Cascade (2).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#7d5421",
        primary: "#cba160",
        tertiary: "#0e101a",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 84128,
        type: "min",
      },
      {
        original_file_name: "Gilded Cascade (3).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#714d1d",
        primary: "#b99456",
        tertiary: "#0d131c",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 68080,
        type: "min",
      },
      {
        original_file_name: "Gilded Cascade (4).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#0b101a",
        primary: "#b58f4e",
        tertiary: "#67471d",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 60970,
        type: "min",
      },
      {
        original_file_name: "Gilded Cascade (1).jpg",
        megabytes: 1.78,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#131317",
        primary: "#c9a46c",
        tertiary: "#624119",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 1864922,
        type: "max",
      },
      {
        original_file_name: "Gilded Cascade (2).jpg",
        megabytes: 2.14,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#7e551f",
        primary: "#cba05e",
        tertiary: "#0e111b",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 2244821,
        type: "max",
      },
      {
        original_file_name: "Gilded Cascade (3).jpg",
        megabytes: 1.81,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#6e4a19",
        primary: "#a47c3c",
        tertiary: "#0d131c",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 1892716,
        type: "max",
      },
      {
        original_file_name: "Gilded Cascade (4).jpg",
        megabytes: 1.51,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#0b101a",
        primary: "#b68e4b",
        tertiary: "#67471b",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 1580629,
        type: "max",
      },
    ]
  },
  "Neon Whirl": {
    environment_title: "Neon Whirl",
    images: [
      {
        original_file_name: "Neon Whirl (1).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#673531",
        primary: "#ae5e4d",
        tertiary: "#0a0e0e",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 63893,
        type: "min",
      },
      {
        original_file_name: "Neon Whirl (2).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#0b0b10",
        primary: "#b16f44",
        tertiary: "#68412c",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 45601,
        type: "min",
      },
      {
        original_file_name: "Neon Whirl (3).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#0d0c0e",
        primary: "#66aca4",
        tertiary: "#a3474d",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 56785,
        type: "min",
      },
      {
        original_file_name: "Neon Whirl (4).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#0a0c12",
        primary: "#ab5068",
        tertiary: "#3cabc0",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 73249,
        type: "min",
      },
      {
        original_file_name: "Neon Whirl (1).jpg",
        megabytes: 1.62,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#673631",
        primary: "#ae5d4c",
        tertiary: "#0a0e0e",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 1697907,
        type: "max",
      },
      {
        original_file_name: "Neon Whirl (2).jpg",
        megabytes: 1.13,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#0c0b0f",
        primary: "#b26f42",
        tertiary: "#67402b",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 1189801,
        type: "max",
      },
      {
        original_file_name: "Neon Whirl (3).jpg",
        megabytes: 1.58,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#45aca8",
        primary: "#ab4e59",
        tertiary: "#0a0f11",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 1653155,
        type: "max",
      },
      {
        original_file_name: "Neon Whirl (4).jpg",
        megabytes: 2.15,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#0a0c12",
        primary: "#ad4d65",
        tertiary: "#39acc0",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 2253091,
        type: "max",
      },
    ]
  },
  "Obsidian Flow": {
    environment_title: "Obsidian Flow",
    images: [
      {
        original_file_name: "Obsidian Flow (1).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#393e42",
        primary: "#15171a",
        tertiary: "#5b6064",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 53425,
        type: "min",
      },
      {
        original_file_name: "Obsidian Flow (2).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#546169",
        primary: "#0e1217",
        tertiary: "#939fa5",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 55901,
        type: "min",
      },
      {
        original_file_name: "Obsidian Flow (3).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#57666f",
        primary: "#111417",
        tertiary: "#abb4b9",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 56400,
        type: "min",
      },
      {
        original_file_name: "Obsidian Flow (4).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#41464b",
        primary: "#16191d",
        tertiary: "#62696c",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 60969,
        type: "min",
      },
      {
        original_file_name: "Obsidian Flow (1).jpg",
        megabytes: 1.48,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#3e4346",
        primary: "#17191c",
        tertiary: "#4f5558",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 1549595,
        type: "max",
      },
      {
        original_file_name: "Obsidian Flow (2).jpg",
        megabytes: 1.42,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#536169",
        primary: "#0e1217",
        tertiary: "#9fa7ad",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 1486535,
        type: "max",
      },
      {
        original_file_name: "Obsidian Flow (3).jpg",
        megabytes: 1.5,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#57666f",
        primary: "#111417",
        tertiary: "#acb6ba",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 1572010,
        type: "max",
      },
      {
        original_file_name: "Obsidian Flow (4).jpg",
        megabytes: 1.65,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#41464a",
        primary: "#16191d",
        tertiary: "#62686c",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 1733143,
        type: "max",
      },
    ]
  },
  "Prismatic Blur": {
    environment_title: "Prismatic Blur",
    images: [
      {
        original_file_name: "Prismatic Blur (1).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#b5583c",
        primary: "#131215",
        tertiary: "#353c6e",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 41589,
        type: "min",
      },
      {
        original_file_name: "Prismatic Blur (2).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#161216",
        primary: "#b66640",
        tertiary: "#6f3a26",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 54580,
        type: "min",
      },
      {
        original_file_name: "Prismatic Blur (3).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#101213",
        primary: "#af6935",
        tertiary: "#69372d",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 48927,
        type: "min",
      },
      {
        original_file_name: "Prismatic Blur (4).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#76443b",
        primary: "#bc7b47",
        tertiary: "#0a0b0d",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 43240,
        type: "min",
      },
      {
        original_file_name: "Prismatic Blur (1).jpg",
        megabytes: 1.06,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#b6583c",
        primary: "#131215",
        tertiary: "#363c6e",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 1108072,
        type: "max",
      },
      {
        original_file_name: "Prismatic Blur (2).jpg",
        megabytes: 1.48,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#161216",
        primary: "#b5633d",
        tertiary: "#6e3a26",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 1549381,
        type: "max",
      },
      {
        original_file_name: "Prismatic Blur (3).jpg",
        megabytes: 1.36,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#101314",
        primary: "#af6835",
        tertiary: "#69372c",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 1425200,
        type: "max",
      },
      {
        original_file_name: "Prismatic Blur (4).jpg",
        megabytes: 1.5,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#76443b",
        primary: "#bc7c48",
        tertiary: "#0a0b0d",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 1576315,
        type: "max",
      },
    ]
  },
  "Retro Static": {
    environment_title: "Retro Static",
    images: [
      {
        original_file_name: "Retro Static (1).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#5a444d",
        primary: "#0d0e11",
        tertiary: "#a38a8f",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 63253,
        type: "min",
      },
      {
        original_file_name: "Retro Static (2).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#9f6037",
        primary: "#13141a",
        tertiary: "#663d30",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 55824,
        type: "min",
      },
      {
        original_file_name: "Retro Static (3).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#ae6e6c",
        primary: "#131117",
        tertiary: "#683a42",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 72739,
        type: "min",
      },
      {
        original_file_name: "Retro Static (4).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#121216",
        primary: "#bd8a50",
        tertiary: "#69483a",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 63521,
        type: "min",
      },
      {
        original_file_name: "Retro Static (1).jpg",
        megabytes: 1.89,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#5a404a",
        primary: "#0d0e12",
        tertiary: "#a37e85",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 1980142,
        type: "max",
      },
      {
        original_file_name: "Retro Static (2).jpg",
        megabytes: 1.83,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#9f6037",
        primary: "#13151a",
        tertiary: "#673d2f",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 1920407,
        type: "max",
      },
      {
        original_file_name: "Retro Static (3).jpg",
        megabytes: 2.29,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#ae6c6a",
        primary: "#131117",
        tertiary: "#683942",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 2397460,
        type: "max",
      },
      {
        original_file_name: "Retro Static (4).jpg",
        megabytes: 1.98,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#121216",
        primary: "#bd8950",
        tertiary: "#694839",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 2080584,
        type: "max",
      },
    ]
  },
  "Vortex Glint": {
    environment_title: "Vortex Glint",
    images: [
      {
        original_file_name: "Vortex Glint (1).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#1d1109",
        primary: "#c19b67",
        tertiary: "#78532b",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 84462,
        type: "min",
      },
      {
        original_file_name: "Vortex Glint (2).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#150c07",
        primary: "#c2965c",
        tertiary: "#784d26",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 79537,
        type: "min",
      },
      {
        original_file_name: "Vortex Glint (3).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#160d09",
        primary: "#c59958",
        tertiary: "#724c24",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 79196,
        type: "min",
      },
      {
        original_file_name: "Vortex Glint (4).jpg",
        megabytes: 0.09,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#1f0f08",
        primary: "#cfa564",
        tertiary: "#805628",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 90205,
        type: "min",
      },
      {
        original_file_name: "Vortex Glint (1).jpg",
        megabytes: 1.97,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#1d1209",
        primary: "#c19964",
        tertiary: "#78522a",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 2066695,
        type: "max",
      },
      {
        original_file_name: "Vortex Glint (2).jpg",
        megabytes: 1.83,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#150c07",
        primary: "#c29659",
        tertiary: "#784d25",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 1916354,
        type: "max",
      },
      {
        original_file_name: "Vortex Glint (3).jpg",
        megabytes: 1.68,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#160d09",
        primary: "#c69857",
        tertiary: "#724c23",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 1760700,
        type: "max",
      },
      {
        original_file_name: "Vortex Glint (4).jpg",
        megabytes: 2.08,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#1f0f08",
        primary: "#cfa462",
        tertiary: "#805526",
        branch: "Abstract",
        folder: "Cinematic",
        bytes: 2183930,
        type: "max",
      },
    ]
  },
};
export default Abstract_Cinematic;
