import { EnvironmentEntry } from "../types";
const Abstract_Geometry: Record<string, EnvironmentEntry> = {
  "Circuit Maze": {
    environment_title: "Circuit Maze",
    images: [
      {
        original_file_name: "Circuit Maze (1).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#cfcfd0",
        primary: "#2c2c2e",
        tertiary: "#7c7c7d",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 84040,
        type: "min",
      },
      {
        original_file_name: "Circuit Maze (2).jpg",
        megabytes: 0.1,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c4c4c8",
        primary: "#27272b",
        tertiary: "#77777b",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 102966,
        type: "min",
      },
      {
        original_file_name: "Circuit Maze (3).jpg",
        megabytes: 0.1,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#cacacd",
        primary: "#29292c",
        tertiary: "#7c7c7e",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 103896,
        type: "min",
      },
      {
        original_file_name: "Circuit Maze (4).jpg",
        megabytes: 0.09,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#cbcbcd",
        primary: "#252528",
        tertiary: "#7c7b7e",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 90424,
        type: "min",
      },
      {
        original_file_name: "Circuit Maze (1).jpg",
        megabytes: 1.85,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#ceced0",
        primary: "#2d2d2f",
        tertiary: "#7c7b7d",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 1937153,
        type: "max",
      },
      {
        original_file_name: "Circuit Maze (2).jpg",
        megabytes: 2.14,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c3c3c7",
        primary: "#27272b",
        tertiary: "#76767b",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 2248926,
        type: "max",
      },
      {
        original_file_name: "Circuit Maze (3).jpg",
        megabytes: 2.31,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#cbcacd",
        primary: "#2c2c2f",
        tertiary: "#7c7c7e",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 2425062,
        type: "max",
      },
      {
        original_file_name: "Circuit Maze (4).jpg",
        megabytes: 2.02,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#cbcacd",
        primary: "#252528",
        tertiary: "#7c7b7e",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 2118924,
        type: "max",
      },
    ]
  },
  "Cubist Storm": {
    environment_title: "Cubist Storm",
    images: [
      {
        original_file_name: "Cubist Storm (1).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#3d4e5d",
        primary: "#d1dae1",
        tertiary: "#7a909e",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 44076,
        type: "min",
      },
      {
        original_file_name: "Cubist Storm (2).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c5d0da",
        primary: "#32414f",
        tertiary: "#6c8395",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 46833,
        type: "min",
      },
      {
        original_file_name: "Cubist Storm (3).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c9dce7",
        primary: "#3d5363",
        tertiary: "#92b5c7",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 44630,
        type: "min",
      },
      {
        original_file_name: "Cubist Storm (4).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#405262",
        primary: "#bfcad5",
        tertiary: "#131920",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 38691,
        type: "min",
      },
      {
        original_file_name: "Cubist Storm (1).jpg",
        megabytes: 0.96,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#3d4e5d",
        primary: "#d1dae2",
        tertiary: "#79909e",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 1010382,
        type: "max",
      },
      {
        original_file_name: "Cubist Storm (2).jpg",
        megabytes: 1.02,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c5cfda",
        primary: "#32414f",
        tertiary: "#6b8395",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 1074671,
        type: "max",
      },
      {
        original_file_name: "Cubist Storm (3).jpg",
        megabytes: 0.96,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c9dce7",
        primary: "#3b4f5f",
        tertiary: "#91b5c7",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 1002528,
        type: "max",
      },
      {
        original_file_name: "Cubist Storm (4).jpg",
        megabytes: 0.92,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#bccad5",
        primary: "#405262",
        tertiary: "#92a7b8",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 961671,
        type: "max",
      },
    ]
  },
  "Facet Glare": {
    environment_title: "Facet Glare",
    images: [
      {
        original_file_name: "Facet Glare (1).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#8c8e95",
        primary: "#efede8",
        tertiary: "#5a5f69",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 28585,
        type: "min",
      },
      {
        original_file_name: "Facet Glare (2).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#e4e4e5",
        primary: "#929295",
        tertiary: "#5b5b5f",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 33551,
        type: "min",
      },
      {
        original_file_name: "Facet Glare (3).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#46474d",
        primary: "#a7a8ac",
        tertiary: "#eaeaed",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 34939,
        type: "min",
      },
      {
        original_file_name: "Facet Glare (4).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#62636b",
        primary: "#aeafb3",
        tertiary: "#e6e6e6",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 37157,
        type: "min",
      },
      {
        original_file_name: "Facet Glare (1).jpg",
        megabytes: 0.66,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#8c8e95",
        primary: "#f0ede8",
        tertiary: "#5a5f69",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 688337,
        type: "max",
      },
      {
        original_file_name: "Facet Glare (2).jpg",
        megabytes: 0.77,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#e4e4e5",
        primary: "#929295",
        tertiary: "#5b5b5f",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 802316,
        type: "max",
      },
      {
        original_file_name: "Facet Glare (3).jpg",
        megabytes: 0.78,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#46474d",
        primary: "#a7a8ac",
        tertiary: "#eaebed",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 813032,
        type: "max",
      },
      {
        original_file_name: "Facet Glare (4).jpg",
        megabytes: 0.81,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#62636c",
        primary: "#aeafb3",
        tertiary: "#e6e6e6",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 848498,
        type: "max",
      },
    ]
  },
  "Hexa Fade": {
    environment_title: "Hexa Fade",
    images: [
      {
        original_file_name: "Hexa Fade (1).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#e5bebf",
        primary: "#6d6d77",
        tertiary: "#333f4c",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 48485,
        type: "min",
      },
      {
        original_file_name: "Hexa Fade (2).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#794a59",
        primary: "#a68893",
        tertiary: "#e4dcdf",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 39917,
        type: "min",
      },
      {
        original_file_name: "Hexa Fade (3).jpg",
        megabytes: 0.02,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#5e6c83",
        primary: "#c8b2ba",
        tertiary: "#895870",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 24806,
        type: "min",
      },
      {
        original_file_name: "Hexa Fade (4).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#8d8597",
        primary: "#4d5c6a",
        tertiary: "#edbcc5",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 29011,
        type: "min",
      },
      {
        original_file_name: "Hexa Fade (1).jpg",
        megabytes: 1.15,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#e5bfbf",
        primary: "#6d6d77",
        tertiary: "#333f4c",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 1207992,
        type: "max",
      },
      {
        original_file_name: "Hexa Fade (2).jpg",
        megabytes: 1.02,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#794a59",
        primary: "#a68893",
        tertiary: "#e4dce0",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 1066561,
        type: "max",
      },
      {
        original_file_name: "Hexa Fade (3).jpg",
        megabytes: 0.71,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#6f536f",
        primary: "#ceb8bf",
        tertiary: "#62798a",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 742509,
        type: "max",
      },
      {
        original_file_name: "Hexa Fade (4).jpg",
        megabytes: 0.8,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#475a67",
        primary: "#a596a6",
        tertiary: "#ecbcc5",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 836538,
        type: "max",
      },
    ]
  },
  "Isometric Web": {
    environment_title: "Isometric Web",
    images: [
      {
        original_file_name: "Isometric Web (1).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#b567ab",
        primary: "#202133",
        tertiary: "#763971",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 61623,
        type: "min",
      },
      {
        original_file_name: "Isometric Web (2).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#1c1d2b",
        primary: "#c37ba9",
        tertiary: "#4ec8ce",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 69110,
        type: "min",
      },
      {
        original_file_name: "Isometric Web (3).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#1a2432",
        primary: "#d26ead",
        tertiary: "#6e3966",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 45494,
        type: "min",
      },
      {
        original_file_name: "Isometric Web (4).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#1f1f30",
        primary: "#c46eb7",
        tertiary: "#6e396a",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 65638,
        type: "min",
      },
      {
        original_file_name: "Isometric Web (1).jpg",
        megabytes: 1.67,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#b565aa",
        primary: "#212336",
        tertiary: "#744a80",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 1751065,
        type: "max",
      },
      {
        original_file_name: "Isometric Web (2).jpg",
        megabytes: 1.68,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#1c1d2b",
        primary: "#c378a7",
        tertiary: "#4cc9ce",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 1765916,
        type: "max",
      },
      {
        original_file_name: "Isometric Web (3).jpg",
        megabytes: 1.05,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#d36dad",
        primary: "#1d2433",
        tertiary: "#6e3966",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 1101968,
        type: "max",
      },
      {
        original_file_name: "Isometric Web (4).jpg",
        megabytes: 1.6,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#1f1f30",
        primary: "#c46db6",
        tertiary: "#57527a",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 1673377,
        type: "max",
      },
    ]
  },
  "Op Art": {
    environment_title: "Op Art",
    images: [
      {
        original_file_name: "Op Art (1).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#2b2b2b",
        primary: "#ababaa",
        tertiary: "#d5d5d5",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 76676,
        type: "min",
      },
      {
        original_file_name: "Op Art (2).jpg",
        megabytes: 0.09,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#d1d1d1",
        primary: "#272727",
        tertiary: "#8f8f8f",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 90788,
        type: "min",
      },
      {
        original_file_name: "Op Art (3).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#939393",
        primary: "#4e4e4e",
        tertiary: "#cccccc",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 82238,
        type: "min",
      },
      {
        original_file_name: "Op Art (4).jpg",
        megabytes: 0.09,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#a3a3a3",
        primary: "#d5d5d5",
        tertiary: "#212121",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 89897,
        type: "min",
      },
      {
        original_file_name: "Op Art (1).jpg",
        megabytes: 1.54,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#8d8d8d",
        primary: "#2b2b2b",
        tertiary: "#afafaf",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 1609890,
        type: "max",
      },
      {
        original_file_name: "Op Art (2).jpg",
        megabytes: 1.8,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#d1d1d1",
        primary: "#272727",
        tertiary: "#929292",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 1890080,
        type: "max",
      },
      {
        original_file_name: "Op Art (3).jpg",
        megabytes: 1.85,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#5b5b5c",
        primary: "#c7c7c7",
        tertiary: "#141414",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 1942007,
        type: "max",
      },
      {
        original_file_name: "Op Art (4).jpg",
        megabytes: 1.71,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#a3a3a3",
        primary: "#d5d5d5",
        tertiary: "#222222",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 1792011,
        type: "max",
      },
    ]
  },
  "Polygon Fog": {
    environment_title: "Polygon Fog",
    images: [
      {
        original_file_name: "Polygon Fog (1).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#cccccb",
        primary: "#646465",
        tertiary: "#232324",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 31944,
        type: "min",
      },
      {
        original_file_name: "Polygon Fog (2).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#d0d0d0",
        primary: "#464646",
        tertiary: "#8f8f8e",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 30704,
        type: "min",
      },
      {
        original_file_name: "Polygon Fog (3).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#8e8e8e",
        primary: "#393939",
        tertiary: "#c9c9c8",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 28105,
        type: "min",
      },
      {
        original_file_name: "Polygon Fog (4).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c9c9c8",
        primary: "#5a5a5b",
        tertiary: "#acacab",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 28343,
        type: "min",
      },
      {
        original_file_name: "Polygon Fog (1).jpg",
        megabytes: 0.78,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#cccccc",
        primary: "#646465",
        tertiary: "#b4b4b4",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 822399,
        type: "max",
      },
      {
        original_file_name: "Polygon Fog (2).jpg",
        megabytes: 0.74,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#d0d0d0",
        primary: "#464646",
        tertiary: "#8f8f8f",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 773752,
        type: "max",
      },
      {
        original_file_name: "Polygon Fog (3).jpg",
        megabytes: 0.71,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#8e8e8e",
        primary: "#393939",
        tertiary: "#c9c9c9",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 744916,
        type: "max",
      },
      {
        original_file_name: "Polygon Fog (4).jpg",
        megabytes: 0.76,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c9c9c9",
        primary: "#5a5a5b",
        tertiary: "#acacac",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 794311,
        type: "max",
      },
    ]
  },
  "Prism Grid": {
    environment_title: "Prism Grid",
    images: [
      {
        original_file_name: "Prism Grid (1).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#be827e",
        primary: "#28202c",
        tertiary: "#74495a",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 79077,
        type: "min",
      },
      {
        original_file_name: "Prism Grid (2).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#242027",
        primary: "#cb9772",
        tertiary: "#75564d",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 71412,
        type: "min",
      },
      {
        original_file_name: "Prism Grid (3).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c8a294",
        primary: "#28252a",
        tertiary: "#766161",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 58290,
        type: "min",
      },
      {
        original_file_name: "Prism Grid (4).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#1b1722",
        primary: "#c36966",
        tertiary: "#713f4b",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 56110,
        type: "min",
      },
      {
        original_file_name: "Prism Grid (1).jpg",
        megabytes: 2.07,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#bf817d",
        primary: "#28202c",
        tertiary: "#74485a",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 2168674,
        type: "max",
      },
      {
        original_file_name: "Prism Grid (2).jpg",
        megabytes: 1.69,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#242028",
        primary: "#cc956f",
        tertiary: "#76564c",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 1769389,
        type: "max",
      },
      {
        original_file_name: "Prism Grid (3).jpg",
        megabytes: 1.42,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c9a194",
        primary: "#28252a",
        tertiary: "#756161",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 1484867,
        type: "max",
      },
      {
        original_file_name: "Prism Grid (4).jpg",
        megabytes: 1.46,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#1c1722",
        primary: "#c36866",
        tertiary: "#713f4a",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 1531029,
        type: "max",
      },
    ]
  },
  "Triangle Bloom": {
    environment_title: "Triangle Bloom",
    images: [
      {
        original_file_name: "Triangle Bloom (1).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#3c3141",
        primary: "#da8561",
        tertiary: "#87b9bf",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 55175,
        type: "min",
      },
      {
        original_file_name: "Triangle Bloom (2).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#4e2330",
        primary: "#cdaa90",
        tertiary: "#cd6b5f",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 47059,
        type: "min",
      },
      {
        original_file_name: "Triangle Bloom (3).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#cb6d5f",
        primary: "#4b4158",
        tertiary: "#b1b19e",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 40181,
        type: "min",
      },
      {
        original_file_name: "Triangle Bloom (4).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#7b2f38",
        primary: "#2e2c3f",
        tertiary: "#ed7368",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 49875,
        type: "min",
      },
      {
        original_file_name: "Triangle Bloom (1).jpg",
        megabytes: 1.32,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#3c3141",
        primary: "#dc8668",
        tertiary: "#8bbbbd",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 1385036,
        type: "max",
      },
      {
        original_file_name: "Triangle Bloom (2).jpg",
        megabytes: 1.22,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#d4755e",
        primary: "#4f2837",
        tertiary: "#9798c3",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 1283081,
        type: "max",
      },
      {
        original_file_name: "Triangle Bloom (3).jpg",
        megabytes: 1.13,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#4a4158",
        primary: "#d47a67",
        tertiary: "#8e4550",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 1184871,
        type: "max",
      },
      {
        original_file_name: "Triangle Bloom (4).jpg",
        megabytes: 1.22,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#2e2c3f",
        primary: "#ad4751",
        tertiary: "#5f2633",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 1283701,
        type: "max",
      },
    ]
  },
  "Warp Matrix": {
    environment_title: "Warp Matrix",
    images: [
      {
        original_file_name: "Warp Matrix (1).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#b9a8c5",
        primary: "#191a27",
        tertiary: "#575575",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 40018,
        type: "min",
      },
      {
        original_file_name: "Warp Matrix (2).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#bdbda3",
        primary: "#1a1e22",
        tertiary: "#6a6d62",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 46952,
        type: "min",
      },
      {
        original_file_name: "Warp Matrix (3).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#55afb4",
        primary: "#132127",
        tertiary: "#386e76",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 51708,
        type: "min",
      },
      {
        original_file_name: "Warp Matrix (4).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#6da8ba",
        primary: "#121b27",
        tertiary: "#9dd4e3",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 56958,
        type: "min",
      },
      {
        original_file_name: "Warp Matrix (1).jpg",
        megabytes: 1.57,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#b9a8c4",
        primary: "#191a28",
        tertiary: "#575575",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 1646916,
        type: "max",
      },
      {
        original_file_name: "Warp Matrix (2).jpg",
        megabytes: 1.29,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#bdbca0",
        primary: "#1a1e22",
        tertiary: "#6a6c61",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 1357014,
        type: "max",
      },
      {
        original_file_name: "Warp Matrix (3).jpg",
        megabytes: 1.49,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#53afb4",
        primary: "#132128",
        tertiary: "#386e76",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 1559548,
        type: "max",
      },
      {
        original_file_name: "Warp Matrix (4).jpg",
        megabytes: 1.77,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#6da8bb",
        primary: "#111925",
        tertiary: "#9cd5e4",
        branch: "Abstract",
        folder: "Geometry",
        bytes: 1857278,
        type: "max",
      },
    ]
  },
};
export default Abstract_Geometry;
