import { EnvironmentEntry } from "../types";
const Minimalist_Cinematic: Record<string, EnvironmentEntry> = {
  "Falling Shapes": {
    environment_title: "Falling Shapes",
    images: [
      {
        original_file_name: "Falling Shapes (1).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#cabbaa",
        primary: "#3a4041",
        tertiary: "#96897a",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 36566,
        type: "min",
      },
      {
        original_file_name: "Falling Shapes (2).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#464747",
        primary: "#c3c1bd",
        tertiary: "#908e89",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 48238,
        type: "min",
      },
      {
        original_file_name: "Falling Shapes (3).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#d7cfc2",
        primary: "#3c3936",
        tertiary: "#968e82",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 40835,
        type: "min",
      },
      {
        original_file_name: "Falling Shapes (4).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#2b2d2e",
        primary: "#c0b6ab",
        tertiary: "#8c8983",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 38381,
        type: "min",
      },
      {
        original_file_name: "Falling Shapes (1).jpg",
        megabytes: 1.19,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#424a4b",
        primary: "#cec1b1",
        tertiary: "#9a8b7c",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 1245855,
        type: "max",
      },
      {
        original_file_name: "Falling Shapes (2).jpg",
        megabytes: 1.26,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#464747",
        primary: "#c3c2bd",
        tertiary: "#8f8e89",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 1325290,
        type: "max",
      },
      {
        original_file_name: "Falling Shapes (3).jpg",
        megabytes: 1.17,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#d7cfc2",
        primary: "#4f4c47",
        tertiary: "#948e84",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 1223845,
        type: "max",
      },
      {
        original_file_name: "Falling Shapes (4).jpg",
        megabytes: 1.16,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c2bcb3",
        primary: "#2c2e2f",
        tertiary: "#8a8b87",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 1221530,
        type: "max",
      },
    ]
  },
  "Glass Arch": {
    environment_title: "Glass Arch",
    images: [
      {
        original_file_name: "Glass Arch (1).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#12181b",
        primary: "#b8b3a9",
        tertiary: "#636c6b",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 37128,
        type: "min",
      },
      {
        original_file_name: "Glass Arch (2).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#acadaa",
        primary: "#121417",
        tertiary: "#676d6f",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 44679,
        type: "min",
      },
      {
        original_file_name: "Glass Arch (3).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#151718",
        primary: "#b0a08a",
        tertiary: "#7ba0a9",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 56783,
        type: "min",
      },
      {
        original_file_name: "Glass Arch (4).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#191c1e",
        primary: "#bbbebb",
        tertiary: "#6f726f",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 45904,
        type: "min",
      },
      {
        original_file_name: "Glass Arch (1).jpg",
        megabytes: 1.19,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#12181b",
        primary: "#b8b3a9",
        tertiary: "#636c6a",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 1245731,
        type: "max",
      },
      {
        original_file_name: "Glass Arch (2).jpg",
        megabytes: 1.36,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#adaeab",
        primary: "#121417",
        tertiary: "#676d6f",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 1425069,
        type: "max",
      },
      {
        original_file_name: "Glass Arch (3).jpg",
        megabytes: 1.56,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#151718",
        primary: "#b09f89",
        tertiary: "#7ba1aa",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 1635680,
        type: "max",
      },
      {
        original_file_name: "Glass Arch (4).jpg",
        megabytes: 1.49,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#191c1e",
        primary: "#bbbeba",
        tertiary: "#6e726f",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 1558933,
        type: "max",
      },
    ]
  },
  "Gold Triangle": {
    environment_title: "Gold Triangle",
    images: [
      {
        original_file_name: "Gold Triangle (1).jpg",
        megabytes: 0.02,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#111010",
        primary: "#ba9352",
        tertiary: "#6e4f22",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 22531,
        type: "min",
      },
      {
        original_file_name: "Gold Triangle (2).jpg",
        megabytes: 0.02,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#171412",
        primary: "#ca9e5e",
        tertiary: "#714d27",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 22850,
        type: "min",
      },
      {
        original_file_name: "Gold Triangle (3).jpg",
        megabytes: 0.02,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#d9b47d",
        primary: "#131213",
        tertiary: "#674823",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 23051,
        type: "min",
      },
      {
        original_file_name: "Gold Triangle (4).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#110d0a",
        primary: "#ccab70",
        tertiary: "#684f31",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 27697,
        type: "min",
      },
      {
        original_file_name: "Gold Triangle (1).jpg",
        megabytes: 0.59,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#111010",
        primary: "#ba9250",
        tertiary: "#6d4e21",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 617878,
        type: "max",
      },
      {
        original_file_name: "Gold Triangle (2).jpg",
        megabytes: 0.61,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#181513",
        primary: "#cb9f5d",
        tertiary: "#724d27",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 639881,
        type: "max",
      },
      {
        original_file_name: "Gold Triangle (3).jpg",
        megabytes: 0.53,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#d9b37c",
        primary: "#131213",
        tertiary: "#684822",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 550940,
        type: "max",
      },
      {
        original_file_name: "Gold Triangle (4).jpg",
        megabytes: 0.75,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#110d0a",
        primary: "#cca96e",
        tertiary: "#684f31",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 788295,
        type: "max",
      },
    ]
  },
  "Neon Curve": {
    environment_title: "Neon Curve",
    images: [
      {
        original_file_name: "Neon Curve (1).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#0e0f17",
        primary: "#bd5369",
        tertiary: "#58a8b9",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 44101,
        type: "min",
      },
      {
        original_file_name: "Neon Curve (2).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#14121a",
        primary: "#bd8eb0",
        tertiary: "#643b57",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 38500,
        type: "min",
      },
      {
        original_file_name: "Neon Curve (3).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#9a79ba",
        primary: "#0a0f1a",
        tertiary: "#55afcc",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 31092,
        type: "min",
      },
      {
        original_file_name: "Neon Curve (4).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#140e19",
        primary: "#a5597d",
        tertiary: "#672842",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 42349,
        type: "min",
      },
      {
        original_file_name: "Neon Curve (1).jpg",
        megabytes: 1.28,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#0e0f17",
        primary: "#be5269",
        tertiary: "#53a7b8",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 1338396,
        type: "max",
      },
      {
        original_file_name: "Neon Curve (2).jpg",
        megabytes: 1.11,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#15121a",
        primary: "#be8daf",
        tertiary: "#653a56",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 1165369,
        type: "max",
      },
      {
        original_file_name: "Neon Curve (3).jpg",
        megabytes: 0.85,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#9a74b9",
        primary: "#0a0f1a",
        tertiary: "#54b0cd",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 895748,
        type: "max",
      },
      {
        original_file_name: "Neon Curve (4).jpg",
        megabytes: 1.41,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#140e19",
        primary: "#a5597d",
        tertiary: "#672842",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 1474282,
        type: "max",
      },
    ]
  },
  "Oscillate Wave": {
    environment_title: "Oscillate Wave",
    images: [
      {
        original_file_name: "Oscillate Wave (1).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#828382",
        primary: "#292d31",
        tertiary: "#c8c8c6",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 74111,
        type: "min",
      },
      {
        original_file_name: "Oscillate Wave (2).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#cecfcf",
        primary: "#2b2c2e",
        tertiary: "#848584",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 83606,
        type: "min",
      },
      {
        original_file_name: "Oscillate Wave (3).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#adb7ba",
        primary: "#181d22",
        tertiary: "#6c7478",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 66880,
        type: "min",
      },
      {
        original_file_name: "Oscillate Wave (4).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#1d2126",
        primary: "#cacbc9",
        tertiary: "#757b7f",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 81667,
        type: "min",
      },
      {
        original_file_name: "Oscillate Wave (1).jpg",
        megabytes: 2.02,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#828382",
        primary: "#292d32",
        tertiary: "#c8c8c6",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 2119613,
        type: "max",
      },
      {
        original_file_name: "Oscillate Wave (2).jpg",
        megabytes: 1.91,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#cecfce",
        primary: "#2b2c2e",
        tertiary: "#848484",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 2004505,
        type: "max",
      },
      {
        original_file_name: "Oscillate Wave (3).jpg",
        megabytes: 1.6,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#adb6ba",
        primary: "#181d22",
        tertiary: "#6b7478",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 1675000,
        type: "max",
      },
      {
        original_file_name: "Oscillate Wave (4).jpg",
        megabytes: 2.2,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#1e2126",
        primary: "#cacbc8",
        tertiary: "#747a7f",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 2307667,
        type: "max",
      },
    ]
  },
  "Shadow Lines": {
    environment_title: "Shadow Lines",
    images: [
      {
        original_file_name: "Shadow Lines (1).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#111111",
        primary: "#b4b4b3",
        tertiary: "#949493",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 41252,
        type: "min",
      },
      {
        original_file_name: "Shadow Lines (2).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#8c8882",
        primary: "#131617",
        tertiary: "#d9d6d2",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 32093,
        type: "min",
      },
      {
        original_file_name: "Shadow Lines (3).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#1f2021",
        primary: "#b8b5ae",
        tertiary: "#757777",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 61185,
        type: "min",
      },
      {
        original_file_name: "Shadow Lines (4).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#131a1f",
        primary: "#947256",
        tertiary: "#564538",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 53629,
        type: "min",
      },
      {
        original_file_name: "Shadow Lines (1).jpg",
        megabytes: 1.34,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#121212",
        primary: "#b0b0af",
        tertiary: "#8b8c8b",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 1401062,
        type: "max",
      },
      {
        original_file_name: "Shadow Lines (2).jpg",
        megabytes: 1.25,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#8c8882",
        primary: "#131617",
        tertiary: "#dbd9d6",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 1307456,
        type: "max",
      },
      {
        original_file_name: "Shadow Lines (3).jpg",
        megabytes: 1.91,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#1f2021",
        primary: "#b8b5ae",
        tertiary: "#757877",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 2002641,
        type: "max",
      },
      {
        original_file_name: "Shadow Lines (4).jpg",
        megabytes: 1.91,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#131a20",
        primary: "#947256",
        tertiary: "#574538",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 2003904,
        type: "max",
      },
    ]
  },
  "Shimmer Rings": {
    environment_title: "Shimmer Rings",
    images: [
      {
        original_file_name: "Shimmer Rings (1).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#140c07",
        primary: "#d4ba93",
        tertiary: "#765834",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 69206,
        type: "min",
      },
      {
        original_file_name: "Shimmer Rings (2).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c9b99b",
        primary: "#191818",
        tertiary: "#433f3c",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 36352,
        type: "min",
      },
      {
        original_file_name: "Shimmer Rings (3).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#ab906b",
        primary: "#110f12",
        tertiary: "#644d37",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 31239,
        type: "min",
      },
      {
        original_file_name: "Shimmer Rings (4).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#151413",
        primary: "#b39877",
        tertiary: "#684d33",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 40256,
        type: "min",
      },
      {
        original_file_name: "Shimmer Rings (1).jpg",
        megabytes: 1.61,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#765833",
        primary: "#d4b993",
        tertiary: "#140c07",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 1691006,
        type: "max",
      },
      {
        original_file_name: "Shimmer Rings (2).jpg",
        megabytes: 0.96,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#cab89a",
        primary: "#191818",
        tertiary: "#433f3c",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 1010984,
        type: "max",
      },
      {
        original_file_name: "Shimmer Rings (3).jpg",
        megabytes: 0.81,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#ab8f6a",
        primary: "#110f12",
        tertiary: "#644e36",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 851070,
        type: "max",
      },
      {
        original_file_name: "Shimmer Rings (4).jpg",
        megabytes: 0.99,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#151413",
        primary: "#b29675",
        tertiary: "#684d32",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 1037029,
        type: "max",
      },
    ]
  },
  "Slit Light": {
    environment_title: "Slit Light",
    images: [
      {
        original_file_name: "Slit Light (1).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#232220",
        primary: "#d0ccc5",
        tertiary: "#756b5f",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 39535,
        type: "min",
      },
      {
        original_file_name: "Slit Light (2).jpg",
        megabytes: 0.02,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#cfc7bb",
        primary: "#221f1b",
        tertiary: "#6d6254",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 22041,
        type: "min",
      },
      {
        original_file_name: "Slit Light (3).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#1a1a1a",
        primary: "#c4bcb3",
        tertiary: "#6e6966",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 29307,
        type: "min",
      },
      {
        original_file_name: "Slit Light (4).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#d1c2b0",
        primary: "#1f1d1b",
        tertiary: "#705b4b",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 26946,
        type: "min",
      },
      {
        original_file_name: "Slit Light (1).jpg",
        megabytes: 1.31,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#232220",
        primary: "#d1cdc6",
        tertiary: "#746a5e",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 1372653,
        type: "max",
      },
      {
        original_file_name: "Slit Light (2).jpg",
        megabytes: 1.16,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#d0c8bc",
        primary: "#221f1b",
        tertiary: "#6c6254",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 1214463,
        type: "max",
      },
      {
        original_file_name: "Slit Light (3).jpg",
        megabytes: 1.11,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#1a1a1a",
        primary: "#c5bcb3",
        tertiary: "#6e6966",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 1161413,
        type: "max",
      },
      {
        original_file_name: "Slit Light (4).jpg",
        megabytes: 1.12,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#d0c1af",
        primary: "#1f1d1b",
        tertiary: "#705b4a",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 1172371,
        type: "max",
      },
    ]
  },
  "Spotlight Cube": {
    environment_title: "Spotlight Cube",
    images: [
      {
        original_file_name: "Spotlight Cube (1).jpg",
        megabytes: 0.01,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#b69e8b",
        primary: "#191715",
        tertiary: "#6d5d4f",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 14809,
        type: "min",
      },
      {
        original_file_name: "Spotlight Cube (2).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#111216",
        primary: "#c4c1c0",
        tertiary: "#636e74",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 28781,
        type: "min",
      },
      {
        original_file_name: "Spotlight Cube (3).jpg",
        megabytes: 0.02,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c6cad1",
        primary: "#19191d",
        tertiary: "#6b6f75",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 25876,
        type: "min",
      },
      {
        original_file_name: "Spotlight Cube (4).jpg",
        megabytes: 0.02,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c4c5c8",
        primary: "#1b1b1e",
        tertiary: "#696c70",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 15919,
        type: "min",
      },
      {
        original_file_name: "Spotlight Cube (1).jpg",
        megabytes: 0.5,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#b69e8b",
        primary: "#191715",
        tertiary: "#6e5d4f",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 519652,
        type: "max",
      },
      {
        original_file_name: "Spotlight Cube (2).jpg",
        megabytes: 0.68,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#111216",
        primary: "#c4c1c0",
        tertiary: "#636e74",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 718025,
        type: "max",
      },
      {
        original_file_name: "Spotlight Cube (3).jpg",
        megabytes: 0.69,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c6cad0",
        primary: "#19191d",
        tertiary: "#6b6f75",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 721564,
        type: "max",
      },
      {
        original_file_name: "Spotlight Cube (4).jpg",
        megabytes: 0.55,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c0c1c5",
        primary: "#1b1b1d",
        tertiary: "#696c70",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 573967,
        type: "max",
      },
    ]
  },
  "Vertigo Spiral": {
    environment_title: "Vertigo Spiral",
    images: [
      {
        original_file_name: "Vertigo Spiral (1).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#141413",
        primary: "#b6b6b4",
        tertiary: "#71716f",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 66879,
        type: "min",
      },
      {
        original_file_name: "Vertigo Spiral (2).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#6e6e6d",
        primary: "#c0c0be",
        tertiary: "#0e0e0e",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 65252,
        type: "min",
      },
      {
        original_file_name: "Vertigo Spiral (3).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#757574",
        primary: "#202020",
        tertiary: "#bbbbba",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 55917,
        type: "min",
      },
      {
        original_file_name: "Vertigo Spiral (4).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#191918",
        primary: "#b2b2b1",
        tertiary: "#949492",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 54522,
        type: "min",
      },
      {
        original_file_name: "Vertigo Spiral (1).jpg",
        megabytes: 1.8,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#141413",
        primary: "#b6b6b4",
        tertiary: "#71716f",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 1891148,
        type: "max",
      },
      {
        original_file_name: "Vertigo Spiral (2).jpg",
        megabytes: 1.8,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#6e6e6c",
        primary: "#c0c0be",
        tertiary: "#0e0e0e",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 1883752,
        type: "max",
      },
      {
        original_file_name: "Vertigo Spiral (3).jpg",
        megabytes: 1.84,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#757574",
        primary: "#212120",
        tertiary: "#babbba",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 1928978,
        type: "max",
      },
      {
        original_file_name: "Vertigo Spiral (4).jpg",
        megabytes: 1.61,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#191919",
        primary: "#b2b2b1",
        tertiary: "#949492",
        branch: "Minimalist",
        folder: "Cinematic",
        bytes: 1691338,
        type: "max",
      },
    ]
  },
};
export default Minimalist_Cinematic;
