import { EnvironmentEntry } from "../types";
const Minimalist_Geometry: Record<string, EnvironmentEntry> = {
  "Contour Wave": {
    environment_title: "Contour Wave",
    images: [
      {
        original_file_name: "Contour Wave (1).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#643741",
        primary: "#ca6849",
        tertiary: "#232a3b",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 48636,
        type: "min",
      },
      {
        original_file_name: "Contour Wave (2).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#171627",
        primary: "#ba6a4d",
        tertiary: "#6a3640",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 28636,
        type: "min",
      },
      {
        original_file_name: "Contour Wave (3).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#323a53",
        primary: "#c88168",
        tertiary: "#8fb1af",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 42358,
        type: "min",
      },
      {
        original_file_name: "Contour Wave (4).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#252a41",
        primary: "#c16158",
        tertiary: "#7b4d62",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 30786,
        type: "min",
      },
      {
        original_file_name: "Contour Wave (1).jpg",
        megabytes: 1.61,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#643741",
        primary: "#ca6849",
        tertiary: "#232a3b",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 1686517,
        type: "max",
      },
      {
        original_file_name: "Contour Wave (2).jpg",
        megabytes: 0.9,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#171627",
        primary: "#ba694d",
        tertiary: "#6a3640",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 943195,
        type: "max",
      },
      {
        original_file_name: "Contour Wave (3).jpg",
        megabytes: 1.34,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#323a53",
        primary: "#c98167",
        tertiary: "#8eb0af",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 1406167,
        type: "max",
      },
      {
        original_file_name: "Contour Wave (4).jpg",
        megabytes: 1.33,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#282a42",
        primary: "#c16158",
        tertiary: "#7b4d62",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 1389721,
        type: "max",
      },
    ]
  },
  "Flat Circle": {
    environment_title: "Flat Circle",
    images: [
      {
        original_file_name: "Flat Circle (1).jpg",
        megabytes: 0.02,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#795055",
        primary: "#e4c2bb",
        tertiary: "#a07680",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 16231,
        type: "min",
      },
      {
        original_file_name: "Flat Circle (2).jpg",
        megabytes: 0.01,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#4c7e7e",
        primary: "#e8bab1",
        tertiary: "#a8bab9",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 15003,
        type: "min",
      },
      {
        original_file_name: "Flat Circle (3).jpg",
        megabytes: 0.01,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#9cb5b6",
        primary: "#f0bdb3",
        tertiary: "#c3bebc",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 11746,
        type: "min",
      },
      {
        original_file_name: "Flat Circle (4).jpg",
        megabytes: 0.01,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#95acab",
        primary: "#e2beba",
        tertiary: "#678084",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 13100,
        type: "min",
      },
      {
        original_file_name: "Flat Circle (1).jpg",
        megabytes: 0.53,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#795156",
        primary: "#e4c2bb",
        tertiary: "#a07680",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 552165,
        type: "max",
      },
      {
        original_file_name: "Flat Circle (2).jpg",
        megabytes: 0.46,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#4d7e7e",
        primary: "#d7c3bc",
        tertiary: "#a8bab9",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 487038,
        type: "max",
      },
      {
        original_file_name: "Flat Circle (3).jpg",
        megabytes: 0.44,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#9bb5b5",
        primary: "#f1bdb2",
        tertiary: "#c3bebc",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 456404,
        type: "max",
      },
      {
        original_file_name: "Flat Circle (4).jpg",
        megabytes: 0.46,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#91a9a9",
        primary: "#e0beb9",
        tertiary: "#6a8487",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 479290,
        type: "max",
      },
    ]
  },
  "Isometric L": {
    environment_title: "Isometric L",
    images: [
      {
        original_file_name: "Isometric L (1).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#5d3c67",
        primary: "#e0717a",
        tertiary: "#9d4f7a",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 32535,
        type: "min",
      },
      {
        original_file_name: "Isometric L (2).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#335f79",
        primary: "#8b9ba5",
        tertiary: "#963f51",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 36750,
        type: "min",
      },
      {
        original_file_name: "Isometric L (3).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#2d3444",
        primary: "#cf4e4f",
        tertiary: "#40b6b2",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 37670,
        type: "min",
      },
      {
        original_file_name: "Isometric L (4).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#2b2f42",
        primary: "#dd8a6b",
        tertiary: "#67b3ae",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 44182,
        type: "min",
      },
      {
        original_file_name: "Isometric L (1).jpg",
        megabytes: 1.18,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#e0707a",
        primary: "#5d3c67",
        tertiary: "#9d4f7a",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 1233536,
        type: "max",
      },
      {
        original_file_name: "Isometric L (2).jpg",
        megabytes: 0.93,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#346079",
        primary: "#8b9ba5",
        tertiary: "#983f52",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 972546,
        type: "max",
      },
      {
        original_file_name: "Isometric L (3).jpg",
        megabytes: 0.9,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#2d3444",
        primary: "#cf4e4f",
        tertiary: "#40b6b2",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 944959,
        type: "max",
      },
      {
        original_file_name: "Isometric L (4).jpg",
        megabytes: 0.97,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#2b2f42",
        primary: "#dd8a6a",
        tertiary: "#67b3af",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 1015712,
        type: "max",
      },
    ]
  },
  "Minimal Tri": {
    environment_title: "Minimal Tri",
    images: [
      {
        original_file_name: "Minimal Tri (1).jpg",
        megabytes: 0.01,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#f1f1f1",
        primary: "#3a3a3a",
        tertiary: "#0a0a0b",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 12362,
        type: "min",
      },
      {
        original_file_name: "Minimal Tri (2).jpg",
        megabytes: 0.01,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#e8e1d6",
        primary: "#2f3031",
        tertiary: "#448ba7",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 13414,
        type: "min",
      },
      {
        original_file_name: "Minimal Tri (3).jpg",
        megabytes: 0.01,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#2a2a2a",
        primary: "#8c8c8c",
        tertiary: "#e2e2e2",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 13492,
        type: "min",
      },
      {
        original_file_name: "Minimal Tri (4).jpg",
        megabytes: 0.01,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#2a4549",
        primary: "#9a9b9b",
        tertiary: "#568282",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 12724,
        type: "min",
      },
      {
        original_file_name: "Minimal Tri (1).jpg",
        megabytes: 0.42,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#efefef",
        primary: "#3a3a3a",
        tertiary: "#0a0a0b",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 445627,
        type: "max",
      },
      {
        original_file_name: "Minimal Tri (2).jpg",
        megabytes: 0.42,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#e7e0d5",
        primary: "#2f3031",
        tertiary: "#448ba7",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 436295,
        type: "max",
      },
      {
        original_file_name: "Minimal Tri (3).jpg",
        megabytes: 0.49,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#262626",
        primary: "#8a8a8a",
        tertiary: "#e1e1e1",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 515157,
        type: "max",
      },
      {
        original_file_name: "Minimal Tri (4).jpg",
        megabytes: 0.51,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#2b4549",
        primary: "#9a9b9b",
        tertiary: "#568282",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 536646,
        type: "max",
      },
    ]
  },
  "Mono Arc": {
    environment_title: "Mono Arc",
    images: [
      {
        original_file_name: "Mono Arc (1).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#272727",
        primary: "#d8d8d8",
        tertiary: "#858585",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 52572,
        type: "min",
      },
      {
        original_file_name: "Mono Arc (2).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#dfdfdf",
        primary: "#ababab",
        tertiary: "#181818",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 27822,
        type: "min",
      },
      {
        original_file_name: "Mono Arc (3).jpg",
        megabytes: 0.02,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#474747",
        primary: "#cfcfcf",
        tertiary: "#1e1e1e",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 24074,
        type: "min",
      },
      {
        original_file_name: "Mono Arc (4).jpg",
        megabytes: 0.02,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#272728",
        primary: "#b7b7b7",
        tertiary: "#e9e9e9",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 16431,
        type: "min",
      },
      {
        original_file_name: "Mono Arc (1).jpg",
        megabytes: 1.27,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#282828",
        primary: "#d8d8d9",
        tertiary: "#888888",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 1331296,
        type: "max",
      },
      {
        original_file_name: "Mono Arc (2).jpg",
        megabytes: 0.58,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#dfdfdf",
        primary: "#ababab",
        tertiary: "#191919",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 605393,
        type: "max",
      },
      {
        original_file_name: "Mono Arc (3).jpg",
        megabytes: 0.54,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#474747",
        primary: "#cdcdcd",
        tertiary: "#1e1e1e",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 564052,
        type: "max",
      },
      {
        original_file_name: "Mono Arc (4).jpg",
        megabytes: 0.42,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#272728",
        primary: "#b7b7b7",
        tertiary: "#e9e9e9",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 444458,
        type: "max",
      },
    ]
  },
  "Neon Grid": {
    environment_title: "Neon Grid",
    images: [
      {
        original_file_name: "Neon Grid (1).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#61959a",
        primary: "#08070c",
        tertiary: "#474f5f",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 50886,
        type: "min",
      },
      {
        original_file_name: "Neon Grid (2).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#6c6696",
        primary: "#0a0811",
        tertiary: "#505872",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 69590,
        type: "min",
      },
      {
        original_file_name: "Neon Grid (3).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#5d3c6b",
        primary: "#0d0812",
        tertiary: "#9a68a4",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 59937,
        type: "min",
      },
      {
        original_file_name: "Neon Grid (4).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#a04e89",
        primary: "#100d16",
        tertiary: "#612156",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 31736,
        type: "min",
      },
      {
        original_file_name: "Neon Grid (1).jpg",
        megabytes: 0.9,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#549499",
        primary: "#08070c",
        tertiary: "#414d5e",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 945168,
        type: "max",
      },
      {
        original_file_name: "Neon Grid (2).jpg",
        megabytes: 1.4,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#59446c",
        primary: "#0a0811",
        tertiary: "#9b65a0",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 1465947,
        type: "max",
      },
      {
        original_file_name: "Neon Grid (3).jpg",
        megabytes: 1.06,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#5c396b",
        primary: "#0d0913",
        tertiary: "#9e5da7",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 1111130,
        type: "max",
      },
      {
        original_file_name: "Neon Grid (4).jpg",
        megabytes: 0.81,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#9f4384",
        primary: "#100d16",
        tertiary: "#612056",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 849960,
        type: "max",
      },
    ]
  },
  "Offset Circle": {
    environment_title: "Offset Circle",
    images: [
      {
        original_file_name: "Offset Circle (1).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#afafb0",
        primary: "#19191b",
        tertiary: "#6b6b6c",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 32121,
        type: "min",
      },
      {
        original_file_name: "Offset Circle (2).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#9e9e9e",
        primary: "#1b1b1b",
        tertiary: "#707070",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 31108,
        type: "min",
      },
      {
        original_file_name: "Offset Circle (3).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c4c3c7",
        primary: "#1b1b1d",
        tertiary: "#3f3e43",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 26794,
        type: "min",
      },
      {
        original_file_name: "Offset Circle (4).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#e49959",
        primary: "#222020",
        tertiary: "#6f5642",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 31205,
        type: "min",
      },
      {
        original_file_name: "Offset Circle (1).jpg",
        megabytes: 0.68,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#b0b0b1",
        primary: "#19191b",
        tertiary: "#6b6b6c",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 715432,
        type: "max",
      },
      {
        original_file_name: "Offset Circle (2).jpg",
        megabytes: 0.63,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#969697",
        primary: "#1b1b1b",
        tertiary: "#686868",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 655845,
        type: "max",
      },
      {
        original_file_name: "Offset Circle (3).jpg",
        megabytes: 0.65,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c6c4c9",
        primary: "#1b1b1d",
        tertiary: "#3e3d41",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 683268,
        type: "max",
      },
      {
        original_file_name: "Offset Circle (4).jpg",
        megabytes: 0.59,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#e59857",
        primary: "#222120",
        tertiary: "#705744",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 615559,
        type: "max",
      },
    ]
  },
  "Slant Blocks": {
    environment_title: "Slant Blocks",
    images: [
      {
        original_file_name: "Slant Blocks (1).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#27323d",
        primary: "#c96f52",
        tertiary: "#53afa9",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 43210,
        type: "min",
      },
      {
        original_file_name: "Slant Blocks (2).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#395c5f",
        primary: "#d5a489",
        tertiary: "#9d8173",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 45269,
        type: "min",
      },
      {
        original_file_name: "Slant Blocks (3).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#583f40",
        primary: "#e09771",
        tertiary: "#9d5c4e",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 51642,
        type: "min",
      },
      {
        original_file_name: "Slant Blocks (4).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#323e46",
        primary: "#d59e7a",
        tertiary: "#8f6d58",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 55599,
        type: "min",
      },
      {
        original_file_name: "Slant Blocks (1).jpg",
        megabytes: 0.92,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#283843",
        primary: "#ca6e52",
        tertiary: "#53afa9",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 967422,
        type: "max",
      },
      {
        original_file_name: "Slant Blocks (2).jpg",
        megabytes: 1.02,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#395c5f",
        primary: "#d5a489",
        tertiary: "#9d8173",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 1068896,
        type: "max",
      },
      {
        original_file_name: "Slant Blocks (3).jpg",
        megabytes: 1.12,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#583f40",
        primary: "#e09671",
        tertiary: "#9c5b4e",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 1174157,
        type: "max",
      },
      {
        original_file_name: "Slant Blocks (4).jpg",
        megabytes: 1.1,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#323e46",
        primary: "#d59e79",
        tertiary: "#8f6d58",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 1148866,
        type: "max",
      },
    ]
  },
  "Stacked Tubes": {
    environment_title: "Stacked Tubes",
    images: [
      {
        original_file_name: "Stacked Tubes (1).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#302223",
        primary: "#d17555",
        tertiary: "#8d4941",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 49947,
        type: "min",
      },
      {
        original_file_name: "Stacked Tubes (2).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#8f99a6",
        primary: "#49525f",
        tertiary: "#c0cad6",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 35035,
        type: "min",
      },
      {
        original_file_name: "Stacked Tubes (3).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#241a20",
        primary: "#cf8067",
        tertiary: "#814845",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 45806,
        type: "min",
      },
      {
        original_file_name: "Stacked Tubes (4).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#311d17",
        primary: "#cc9f8b",
        tertiary: "#8d5d4a",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 72380,
        type: "min",
      },
      {
        original_file_name: "Stacked Tubes (1).jpg",
        megabytes: 1.23,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#302224",
        primary: "#d07554",
        tertiary: "#8d4940",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 1291889,
        type: "max",
      },
      {
        original_file_name: "Stacked Tubes (2).jpg",
        megabytes: 1.01,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#b8c2ce",
        primary: "#535c69",
        tertiary: "#171c29",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 1057909,
        type: "max",
      },
      {
        original_file_name: "Stacked Tubes (3).jpg",
        megabytes: 1.14,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#241b20",
        primary: "#cf8067",
        tertiary: "#814845",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 1195196,
        type: "max",
      },
      {
        original_file_name: "Stacked Tubes (4).jpg",
        megabytes: 1.64,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#321d17",
        primary: "#cc9e8a",
        tertiary: "#8d5d4a",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 1717320,
        type: "max",
      },
    ]
  },
  "Two Stripes": {
    environment_title: "Two Stripes",
    images: [
      {
        original_file_name: "Two Stripes (1).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#130e0d",
        primary: "#dbcabb",
        tertiary: "#be6b3f",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 35827,
        type: "min",
      },
      {
        original_file_name: "Two Stripes (2).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#a2928b",
        primary: "#4b4541",
        tertiary: "#dc9876",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 53145,
        type: "min",
      },
      {
        original_file_name: "Two Stripes (3).jpg",
        megabytes: 0.02,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#4c3e3e",
        primary: "#d1baa3",
        tertiary: "#4b464f",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 25886,
        type: "min",
      },
      {
        original_file_name: "Two Stripes (4).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#635348",
        primary: "#d6c6b7",
        tertiary: "#a49484",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 37396,
        type: "min",
      },
      {
        original_file_name: "Two Stripes (1).jpg",
        megabytes: 0.7,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#120e0c",
        primary: "#dbcabc",
        tertiary: "#bf6b3e",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 731631,
        type: "max",
      },
      {
        original_file_name: "Two Stripes (2).jpg",
        megabytes: 0.9,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#a28f86",
        primary: "#dda889",
        tertiary: "#4a4542",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 945877,
        type: "max",
      },
      {
        original_file_name: "Two Stripes (3).jpg",
        megabytes: 0.6,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#4b3f3f",
        primary: "#d1baa2",
        tertiary: "#49444e",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 628495,
        type: "max",
      },
      {
        original_file_name: "Two Stripes (4).jpg",
        megabytes: 0.72,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#d6c6b7",
        primary: "#645348",
        tertiary: "#a49384",
        branch: "Minimalist",
        folder: "Geometry",
        bytes: 752316,
        type: "max",
      },
    ]
  },
};
export default Minimalist_Geometry;
