import { EnvironmentEntry } from "../types";
const Minimalist_Realism: Record<string, EnvironmentEntry> = {
  "Chrome Ring": {
    environment_title: "Chrome Ring",
    images: [
      {
        original_file_name: "Chrome Ring (1).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#555555",
        primary: "#cac8c3",
        tertiary: "#9c9a97",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 30986,
        type: "min",
      },
      {
        original_file_name: "Chrome Ring (2).jpg",
        megabytes: 0.02,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c7c8cd",
        primary: "#8a8c91",
        tertiary: "#1e1f20",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 23343,
        type: "min",
      },
      {
        original_file_name: "Chrome Ring (3).jpg",
        megabytes: 0.02,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#222120",
        primary: "#a7a8aa",
        tertiary: "#676767",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 19818,
        type: "min",
      },
      {
        original_file_name: "Chrome Ring (4).jpg",
        megabytes: 0.02,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#2b2b2a",
        primary: "#b9b9b8",
        tertiary: "#747472",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 23439,
        type: "min",
      },
      {
        original_file_name: "Chrome Ring (1).jpg",
        megabytes: 0.91,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#555555",
        primary: "#cac7c3",
        tertiary: "#9c9a97",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 949508,
        type: "max",
      },
      {
        original_file_name: "Chrome Ring (2).jpg",
        megabytes: 0.66,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c6c8cc",
        primary: "#8a8d91",
        tertiary: "#1e1f21",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 694751,
        type: "max",
      },
      {
        original_file_name: "Chrome Ring (3).jpg",
        megabytes: 0.6,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#21201f",
        primary: "#a7a8aa",
        tertiary: "#666666",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 633113,
        type: "max",
      },
      {
        original_file_name: "Chrome Ring (4).jpg",
        megabytes: 0.71,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#2b2b2a",
        primary: "#b9b9b8",
        tertiary: "#747472",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 740724,
        type: "max",
      },
    ]
  },
  "Concrete Arch": {
    environment_title: "Concrete Arch",
    images: [
      {
        original_file_name: "Concrete Arch (1).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#504a41",
        primary: "#cbcac6",
        tertiary: "#979490",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 34259,
        type: "min",
      },
      {
        original_file_name: "Concrete Arch (2).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#d7d2cb",
        primary: "#484644",
        tertiary: "#bdaa96",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 28797,
        type: "min",
      },
      {
        original_file_name: "Concrete Arch (3).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#e5d8c9",
        primary: "#585756",
        tertiary: "#c4b1a0",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 26464,
        type: "min",
      },
      {
        original_file_name: "Concrete Arch (4).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#45413c",
        primary: "#c4c2bf",
        tertiary: "#b5a897",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 26395,
        type: "min",
      },
      {
        original_file_name: "Concrete Arch (1).jpg",
        megabytes: 1.33,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#cbc9c6",
        primary: "#504942",
        tertiary: "#979490",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 1394723,
        type: "max",
      },
      {
        original_file_name: "Concrete Arch (2).jpg",
        megabytes: 1.17,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#d7d2cb",
        primary: "#484645",
        tertiary: "#bdab96",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 1227580,
        type: "max",
      },
      {
        original_file_name: "Concrete Arch (3).jpg",
        megabytes: 1.18,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#e5d8ca",
        primary: "#595958",
        tertiary: "#cbb9a6",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 1237917,
        type: "max",
      },
      {
        original_file_name: "Concrete Arch (4).jpg",
        megabytes: 1.08,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#46413c",
        primary: "#c4c2bf",
        tertiary: "#b5a897",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 1128366,
        type: "max",
      },
    ]
  },
  "Glass Prisms": {
    environment_title: "Glass Prisms",
    images: [
      {
        original_file_name: "Glass Prisms (1).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#1b191b",
        primary: "#cab08f",
        tertiary: "#785345",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 73700,
        type: "min",
      },
      {
        original_file_name: "Glass Prisms (2).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#1b1a1f",
        primary: "#c3967d",
        tertiary: "#764e41",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 62639,
        type: "min",
      },
      {
        original_file_name: "Glass Prisms (3).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#bd967c",
        primary: "#191a1d",
        tertiary: "#76554b",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 68172,
        type: "min",
      },
      {
        original_file_name: "Glass Prisms (4).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#131114",
        primary: "#b16b5f",
        tertiary: "#77473b",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 52315,
        type: "min",
      },
      {
        original_file_name: "Glass Prisms (1).jpg",
        megabytes: 1.66,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#1b191b",
        primary: "#cab08f",
        tertiary: "#775344",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 1744742,
        type: "max",
      },
      {
        original_file_name: "Glass Prisms (2).jpg",
        megabytes: 1.72,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#1b1a20",
        primary: "#c3967b",
        tertiary: "#764d40",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 1802595,
        type: "max",
      },
      {
        original_file_name: "Glass Prisms (3).jpg",
        megabytes: 1.55,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#bd947a",
        primary: "#191a1d",
        tertiary: "#76544a",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 1626389,
        type: "max",
      },
      {
        original_file_name: "Glass Prisms (4).jpg",
        megabytes: 1.45,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#131214",
        primary: "#af675b",
        tertiary: "#77473a",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 1517731,
        type: "max",
      },
    ]
  },
  "Glass Shapes": {
    environment_title: "Glass Shapes",
    images: [
      {
        original_file_name: "Glass Shapes (1).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#514d48",
        primary: "#d8d0c0",
        tertiary: "#90877e",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 66471,
        type: "min",
      },
      {
        original_file_name: "Glass Shapes (2).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#dadbde",
        primary: "#52585d",
        tertiary: "#979da2",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 57259,
        type: "min",
      },
      {
        original_file_name: "Glass Shapes (3).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#2e2a28",
        primary: "#dacab3",
        tertiary: "#9ca6b1",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 55850,
        type: "min",
      },
      {
        original_file_name: "Glass Shapes (4).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c9c9c9",
        primary: "#202f37",
        tertiary: "#6c3a2b",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 54070,
        type: "min",
      },
      {
        original_file_name: "Glass Shapes (1).jpg",
        megabytes: 1.55,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#524d49",
        primary: "#d7cfbf",
        tertiary: "#90877e",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 1624400,
        type: "max",
      },
      {
        original_file_name: "Glass Shapes (2).jpg",
        megabytes: 1.44,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#dadcde",
        primary: "#545a5f",
        tertiary: "#999fa3",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 1514323,
        type: "max",
      },
      {
        original_file_name: "Glass Shapes (3).jpg",
        megabytes: 1.46,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#2e2a28",
        primary: "#dacab3",
        tertiary: "#9ca6b1",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 1528605,
        type: "max",
      },
      {
        original_file_name: "Glass Shapes (4).jpg",
        megabytes: 1.36,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c9c9ca",
        primary: "#203037",
        tertiary: "#6d392b",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 1424974,
        type: "max",
      },
    ]
  },
  "Marble Slab": {
    environment_title: "Marble Slab",
    images: [
      {
        original_file_name: "Marble Slab (1).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#26231f",
        primary: "#95928c",
        tertiary: "#d6d5d4",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 38995,
        type: "min",
      },
      {
        original_file_name: "Marble Slab (2).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#443c34",
        primary: "#aba8a2",
        tertiary: "#6b635b",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 51722,
        type: "min",
      },
      {
        original_file_name: "Marble Slab (3).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#0b0a09",
        primary: "#9c9c9b",
        tertiary: "#65625f",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 39170,
        type: "min",
      },
      {
        original_file_name: "Marble Slab (4).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#1b1816",
        primary: "#97948e",
        tertiary: "#d2d0cb",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 50394,
        type: "min",
      },
      {
        original_file_name: "Marble Slab (1).jpg",
        megabytes: 1.12,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#26231f",
        primary: "#95928c",
        tertiary: "#d5d5d4",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 1170970,
        type: "max",
      },
      {
        original_file_name: "Marble Slab (2).jpg",
        megabytes: 1.48,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#4b433b",
        primary: "#acaaa4",
        tertiary: "#6d675f",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 1556573,
        type: "max",
      },
      {
        original_file_name: "Marble Slab (3).jpg",
        megabytes: 1.1,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#0a0909",
        primary: "#9c9c9b",
        tertiary: "#65625f",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 1155344,
        type: "max",
      },
      {
        original_file_name: "Marble Slab (4).jpg",
        megabytes: 1.33,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#1b1817",
        primary: "#989590",
        tertiary: "#d6d4d1",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 1389539,
        type: "max",
      },
    ]
  },
  "Metal Cube": {
    environment_title: "Metal Cube",
    images: [
      {
        original_file_name: "Metal Cube (1).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#161311",
        primary: "#757473",
        tertiary: "#e4e1da",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 34144,
        type: "min",
      },
      {
        original_file_name: "Metal Cube (2).jpg",
        megabytes: 0.01,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#302f2d",
        primary: "#979797",
        tertiary: "#e1e1df",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 14943,
        type: "min",
      },
      {
        original_file_name: "Metal Cube (3).jpg",
        megabytes: 0.02,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#373737",
        primary: "#a0a1a1",
        tertiary: "#dddddd",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 18135,
        type: "min",
      },
      {
        original_file_name: "Metal Cube (4).jpg",
        megabytes: 0.02,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#d3d2cf",
        primary: "#605e5d",
        tertiary: "#9a9997",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 21881,
        type: "min",
      },
      {
        original_file_name: "Metal Cube (1).jpg",
        megabytes: 0.85,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#161311",
        primary: "#757473",
        tertiary: "#e4e0d9",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 892705,
        type: "max",
      },
      {
        original_file_name: "Metal Cube (2).jpg",
        megabytes: 0.62,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#302f2e",
        primary: "#979797",
        tertiary: "#e1e1df",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 654679,
        type: "max",
      },
      {
        original_file_name: "Metal Cube (3).jpg",
        megabytes: 0.66,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#373737",
        primary: "#a1a1a2",
        tertiary: "#dddddd",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 688042,
        type: "max",
      },
      {
        original_file_name: "Metal Cube (4).jpg",
        megabytes: 1.01,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#d3d2cf",
        primary: "#605e5d",
        tertiary: "#9c9c99",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 1061124,
        type: "max",
      },
    ]
  },
  "Paper Fold": {
    environment_title: "Paper Fold",
    images: [
      {
        original_file_name: "Paper Fold (1).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#cfcfcc",
        primary: "#2c2a26",
        tertiary: "#5d5b58",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 54765,
        type: "min",
      },
      {
        original_file_name: "Paper Fold (2).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#4d4239",
        primary: "#a6a39d",
        tertiary: "#e3e2de",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 40891,
        type: "min",
      },
      {
        original_file_name: "Paper Fold (3).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#dcdbd7",
        primary: "#807a74",
        tertiary: "#504740",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 34613,
        type: "min",
      },
      {
        original_file_name: "Paper Fold (4).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#42413f",
        primary: "#9a9a97",
        tertiary: "#dcdcda",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 40713,
        type: "min",
      },
      {
        original_file_name: "Paper Fold (1).jpg",
        megabytes: 1.25,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#d0cfcc",
        primary: "#2c2a26",
        tertiary: "#5d5b58",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 1314541,
        type: "max",
      },
      {
        original_file_name: "Paper Fold (2).jpg",
        megabytes: 0.96,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#4d423a",
        primary: "#a3a09a",
        tertiary: "#e3e2de",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 1003997,
        type: "max",
      },
      {
        original_file_name: "Paper Fold (3).jpg",
        megabytes: 0.93,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#807a74",
        primary: "#dddbd7",
        tertiary: "#504740",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 975776,
        type: "max",
      },
      {
        original_file_name: "Paper Fold (4).jpg",
        megabytes: 0.95,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#474645",
        primary: "#888885",
        tertiary: "#dcdcda",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 997381,
        type: "max",
      },
    ]
  },
  "Paper Layers": {
    environment_title: "Paper Layers",
    images: [
      {
        original_file_name: "Paper Layers (1).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#aba69f",
        primary: "#2d2926",
        tertiary: "#4f3320",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 52895,
        type: "min",
      },
      {
        original_file_name: "Paper Layers (2).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#7e7063",
        primary: "#e0dcd4",
        tertiary: "#d2c7b8",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 63481,
        type: "min",
      },
      {
        original_file_name: "Paper Layers (3).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#342721",
        primary: "#d0af90",
        tertiary: "#9eaaac",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 38398,
        type: "min",
      },
      {
        original_file_name: "Paper Layers (4).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#8f7e71",
        primary: "#28292e",
        tertiary: "#672c1d",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 38030,
        type: "min",
      },
      {
        original_file_name: "Paper Layers (1).jpg",
        megabytes: 1.22,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#aba69f",
        primary: "#2c2926",
        tertiary: "#4f3420",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 1278313,
        type: "max",
      },
      {
        original_file_name: "Paper Layers (2).jpg",
        megabytes: 1.71,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#7e7063",
        primary: "#dfdbd4",
        tertiary: "#d2c7b8",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 1795306,
        type: "max",
      },
      {
        original_file_name: "Paper Layers (3).jpg",
        megabytes: 0.96,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#352721",
        primary: "#d0af91",
        tertiary: "#9eaaac",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 1005189,
        type: "max",
      },
      {
        original_file_name: "Paper Layers (4).jpg",
        megabytes: 0.95,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#8f7e72",
        primary: "#28292f",
        tertiary: "#672b1c",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 991829,
        type: "max",
      },
    ]
  },
  "Stone Stack": {
    environment_title: "Stone Stack",
    images: [
      {
        original_file_name: "Stone Stack (1).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c8bcb2",
        primary: "#5b5c5b",
        tertiary: "#988d81",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 38173,
        type: "min",
      },
      {
        original_file_name: "Stone Stack (2).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#24211d",
        primary: "#9f9d99",
        tertiary: "#4c3c30",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 30152,
        type: "min",
      },
      {
        original_file_name: "Stone Stack (3).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#524840",
        primary: "#cab79c",
        tertiary: "#9b8b79",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 41467,
        type: "min",
      },
      {
        original_file_name: "Stone Stack (4).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#cfc5ba",
        primary: "#696563",
        tertiary: "#161210",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 41557,
        type: "min",
      },
      {
        original_file_name: "Stone Stack (1).jpg",
        megabytes: 1.55,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c8bcb2",
        primary: "#5b5c5b",
        tertiary: "#988d82",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 1630003,
        type: "max",
      },
      {
        original_file_name: "Stone Stack (2).jpg",
        megabytes: 1.2,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#25211d",
        primary: "#9f9d99",
        tertiary: "#4c3c30",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 1258483,
        type: "max",
      },
      {
        original_file_name: "Stone Stack (3).jpg",
        megabytes: 1.54,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#524841",
        primary: "#cab79c",
        tertiary: "#9b8b7a",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 1610572,
        type: "max",
      },
      {
        original_file_name: "Stone Stack (4).jpg",
        megabytes: 1.39,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#cfc5bb",
        primary: "#696563",
        tertiary: "#161210",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 1457482,
        type: "max",
      },
    ]
  },
  "Wooden Blocks": {
    environment_title: "Wooden Blocks",
    images: [
      {
        original_file_name: "Wooden Blocks (1).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#461e0c",
        primary: "#b88860",
        tertiary: "#754a2d",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 39817,
        type: "min",
      },
      {
        original_file_name: "Wooden Blocks (2).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#3b1808",
        primary: "#b6855d",
        tertiary: "#643516",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 44895,
        type: "min",
      },
      {
        original_file_name: "Wooden Blocks (3).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#2d1308",
        primary: "#a2704c",
        tertiary: "#d6ac85",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 46709,
        type: "min",
      },
      {
        original_file_name: "Wooden Blocks (4).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#b4835c",
        primary: "#381607",
        tertiary: "#5b2e14",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 50118,
        type: "min",
      },
      {
        original_file_name: "Wooden Blocks (1).jpg",
        megabytes: 1.52,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#381507",
        primary: "#b98860",
        tertiary: "#643417",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 1590951,
        type: "max",
      },
      {
        original_file_name: "Wooden Blocks (2).jpg",
        megabytes: 1.45,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#3b1908",
        primary: "#b4835c",
        tertiary: "#734525",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 1520279,
        type: "max",
      },
      {
        original_file_name: "Wooden Blocks (3).jpg",
        megabytes: 1.44,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#a2704c",
        primary: "#2d1308",
        tertiary: "#d6ac85",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 1511802,
        type: "max",
      },
      {
        original_file_name: "Wooden Blocks (4).jpg",
        megabytes: 1.88,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#b4835c",
        primary: "#391707",
        tertiary: "#5c2e14",
        branch: "Minimalist",
        folder: "Realism",
        bytes: 1975674,
        type: "max",
      },
    ]
  },
};
export default Minimalist_Realism;
