import { EnvironmentEntry } from "../types";
const Minimalist_Anime: Record<string, EnvironmentEntry> = {
  "Blush Grid": {
    environment_title: "Blush Grid",
    images: [
      {
        original_file_name: "Blush Grid (1).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#6b3635",
        primary: "#ebafb2",
        tertiary: "#a7706e",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 38623,
        type: "min",
      },
      {
        original_file_name: "Blush Grid (2).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#341f1f",
        primary: "#f8bec0",
        tertiary: "#86525f",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 41367,
        type: "min",
      },
      {
        original_file_name: "Blush Grid (3).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#dc9c9f",
        primary: "#241010",
        tertiary: "#886467",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 35084,
        type: "min",
      },
      {
        original_file_name: "Blush Grid (4).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#3f2422",
        primary: "#f0bbbd",
        tertiary: "#957171",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 41445,
        type: "min",
      },
      {
        original_file_name: "Blush Grid (1).jpg",
        megabytes: 1.14,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#6b3736",
        primary: "#ecafb2",
        tertiary: "#965d59",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 1199333,
        type: "max",
      },
      {
        original_file_name: "Blush Grid (2).jpg",
        megabytes: 0.97,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#341e1e",
        primary: "#f8bebf",
        tertiary: "#86525f",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 1017423,
        type: "max",
      },
      {
        original_file_name: "Blush Grid (3).jpg",
        megabytes: 0.84,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#dc9c9f",
        primary: "#251110",
        tertiary: "#896367",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 883838,
        type: "max",
      },
      {
        original_file_name: "Blush Grid (4).jpg",
        megabytes: 1.1,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#412624",
        primary: "#f0bbbd",
        tertiary: "#967271",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 1155529,
        type: "max",
      },
    ]
  },
  "Bubble Arch": {
    environment_title: "Bubble Arch",
    images: [
      {
        original_file_name: "Bubble Arch (1).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#ecc5d5",
        primary: "#8a8dc9",
        tertiary: "#382751",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 73274,
        type: "min",
      },
      {
        original_file_name: "Bubble Arch (2).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#4b69b1",
        primary: "#a285ba",
        tertiary: "#f8dde8",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 65165,
        type: "min",
      },
      {
        original_file_name: "Bubble Arch (3).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#35385e",
        primary: "#756a94",
        tertiary: "#eca7b0",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 87120,
        type: "min",
      },
      {
        original_file_name: "Bubble Arch (4).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#dea7c1",
        primary: "#573b64",
        tertiary: "#635485",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 78813,
        type: "min",
      },
      {
        original_file_name: "Bubble Arch (1).jpg",
        megabytes: 1.83,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#ecc5d5",
        primary: "#8a8dc9",
        tertiary: "#5b3960",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 1916316,
        type: "max",
      },
      {
        original_file_name: "Bubble Arch (2).jpg",
        megabytes: 1.66,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#4c69b1",
        primary: "#a285ba",
        tertiary: "#f8dde8",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 1740151,
        type: "max",
      },
      {
        original_file_name: "Bubble Arch (3).jpg",
        megabytes: 2.04,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#3f314e",
        primary: "#826b92",
        tertiary: "#41558d",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 2135493,
        type: "max",
      },
      {
        original_file_name: "Bubble Arch (4).jpg",
        megabytes: 1.91,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#dea7c0",
        primary: "#573b64",
        tertiary: "#635486",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 1997604,
        type: "max",
      },
    ]
  },
  "Candy Blocks": {
    environment_title: "Candy Blocks",
    images: [
      {
        original_file_name: "Candy Blocks (1).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#eac7b8",
        primary: "#4f4f6c",
        tertiary: "#90d9d6",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 72652,
        type: "min",
      },
      {
        original_file_name: "Candy Blocks (2).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#2e4e5f",
        primary: "#e2cfc7",
        tertiary: "#5c687b",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 66920,
        type: "min",
      },
      {
        original_file_name: "Candy Blocks (3).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#594e6c",
        primary: "#f1c1a6",
        tertiary: "#83daca",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 76591,
        type: "min",
      },
      {
        original_file_name: "Candy Blocks (4).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#69bbdf",
        primary: "#eab8a2",
        tertiary: "#574862",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 62175,
        type: "min",
      },
      {
        original_file_name: "Candy Blocks (1).jpg",
        megabytes: 1.72,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#eac6b7",
        primary: "#4f4f6d",
        tertiary: "#8fdad6",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 1798551,
        type: "max",
      },
      {
        original_file_name: "Candy Blocks (2).jpg",
        megabytes: 1.49,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#2e4f60",
        primary: "#e3d0c7",
        tertiary: "#5c687b",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 1565604,
        type: "max",
      },
      {
        original_file_name: "Candy Blocks (3).jpg",
        megabytes: 1.87,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#594f6c",
        primary: "#f1c1a6",
        tertiary: "#83dbcb",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 1965675,
        type: "max",
      },
      {
        original_file_name: "Candy Blocks (4).jpg",
        megabytes: 1.46,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#68bbdf",
        primary: "#eab8a1",
        tertiary: "#574861",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 1530418,
        type: "max",
      },
    ]
  },
  "Circle Bloom": {
    environment_title: "Circle Bloom",
    images: [
      {
        original_file_name: "Circle Bloom (1).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#14101b",
        primary: "#e3afb3",
        tertiary: "#723a3b",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 66667,
        type: "min",
      },
      {
        original_file_name: "Circle Bloom (2).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#241923",
        primary: "#eba899",
        tertiary: "#87d6e0",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 73940,
        type: "min",
      },
      {
        original_file_name: "Circle Bloom (3).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#241f2f",
        primary: "#e4acad",
        tertiary: "#8a585d",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 85908,
        type: "min",
      },
      {
        original_file_name: "Circle Bloom (4).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#201720",
        primary: "#dc938f",
        tertiary: "#73d9de",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 72905,
        type: "min",
      },
      {
        original_file_name: "Circle Bloom (1).jpg",
        megabytes: 1.4,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#14101b",
        primary: "#e4afb2",
        tertiary: "#71393a",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 1463298,
        type: "max",
      },
      {
        original_file_name: "Circle Bloom (2).jpg",
        megabytes: 1.48,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#241923",
        primary: "#eca898",
        tertiary: "#86d8e1",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 1548227,
        type: "max",
      },
      {
        original_file_name: "Circle Bloom (3).jpg",
        megabytes: 1.73,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#241f2f",
        primary: "#e4acac",
        tertiary: "#8a585d",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 1812045,
        type: "max",
      },
      {
        original_file_name: "Circle Bloom (4).jpg",
        megabytes: 1.53,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#201720",
        primary: "#dd938e",
        tertiary: "#73d9df",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 1604717,
        type: "max",
      },
    ]
  },
  "Crystal Tri": {
    environment_title: "Crystal Tri",
    images: [
      {
        original_file_name: "Crystal Tri (1).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#d7d3de",
        primary: "#353144",
        tertiary: "#79bae1",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 71190,
        type: "min",
      },
      {
        original_file_name: "Crystal Tri (2).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#1e1a2e",
        primary: "#dda9c4",
        tertiary: "#75afe2",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 67186,
        type: "min",
      },
      {
        original_file_name: "Crystal Tri (3).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#71b1d7",
        primary: "#dbb1ca",
        tertiary: "#5877c0",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 71282,
        type: "min",
      },
      {
        original_file_name: "Crystal Tri (4).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#1a1b30",
        primary: "#d4adc0",
        tertiary: "#517cbe",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 72137,
        type: "min",
      },
      {
        original_file_name: "Crystal Tri (1).jpg",
        megabytes: 1.6,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#d7d2de",
        primary: "#353144",
        tertiary: "#78b9e2",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 1674894,
        type: "max",
      },
      {
        original_file_name: "Crystal Tri (2).jpg",
        megabytes: 1.58,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#1e1a2e",
        primary: "#dda8c4",
        tertiary: "#75afe4",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 1654616,
        type: "max",
      },
      {
        original_file_name: "Crystal Tri (3).jpg",
        megabytes: 1.7,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#70b0d7",
        primary: "#dbb1c9",
        tertiary: "#201f39",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 1783803,
        type: "max",
      },
      {
        original_file_name: "Crystal Tri (4).jpg",
        megabytes: 1.64,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#201828",
        primary: "#d5adc0",
        tertiary: "#535c8d",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 1718922,
        type: "max",
      },
    ]
  },
  "Dream Stripe": {
    environment_title: "Dream Stripe",
    images: [
      {
        original_file_name: "Dream Stripe (1).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#273b64",
        primary: "#d3c0c7",
        tertiary: "#586e9b",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 66183,
        type: "min",
      },
      {
        original_file_name: "Dream Stripe (2).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#3e62a7",
        primary: "#b0bdda",
        tertiary: "#6b8ec3",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 55826,
        type: "min",
      },
      {
        original_file_name: "Dream Stripe (3).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#87a2d4",
        primary: "#e5bfd2",
        tertiary: "#a8b0db",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 54180,
        type: "min",
      },
      {
        original_file_name: "Dream Stripe (4).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#446791",
        primary: "#e2c0c5",
        tertiary: "#7089ba",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 69403,
        type: "min",
      },
      {
        original_file_name: "Dream Stripe (1).jpg",
        megabytes: 1.56,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#273b65",
        primary: "#d3c0c7",
        tertiary: "#586e9b",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 1637215,
        type: "max",
      },
      {
        original_file_name: "Dream Stripe (2).jpg",
        megabytes: 1.41,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#3e63a7",
        primary: "#b0bdda",
        tertiary: "#6b8ec3",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 1476098,
        type: "max",
      },
      {
        original_file_name: "Dream Stripe (3).jpg",
        megabytes: 1.37,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#83a1d6",
        primary: "#ebc0d1",
        tertiary: "#a0b0da",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 1441045,
        type: "max",
      },
      {
        original_file_name: "Dream Stripe (4).jpg",
        megabytes: 1.65,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#496a95",
        primary: "#d4b8c6",
        tertiary: "#788dbe",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 1732105,
        type: "max",
      },
    ]
  },
  "Glossy Heart": {
    environment_title: "Glossy Heart",
    images: [
      {
        original_file_name: "Glossy Heart (1).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#5967ab",
        primary: "#e493ad",
        tertiary: "#814943",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 65857,
        type: "min",
      },
      {
        original_file_name: "Glossy Heart (2).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#497aba",
        primary: "#ddb5cb",
        tertiary: "#903754",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 46974,
        type: "min",
      },
      {
        original_file_name: "Glossy Heart (3).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#f8b7e1",
        primary: "#c6879e",
        tertiary: "#fad7eb",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 50915,
        type: "min",
      },
      {
        original_file_name: "Glossy Heart (4).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#a693c3",
        primary: "#e4a7b9",
        tertiary: "#fadfde",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 40795,
        type: "min",
      },
      {
        original_file_name: "Glossy Heart (1).jpg",
        megabytes: 1.66,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#5967aa",
        primary: "#e493ad",
        tertiary: "#814a42",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 1742267,
        type: "max",
      },
      {
        original_file_name: "Glossy Heart (2).jpg",
        megabytes: 1.17,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#4574b4",
        primary: "#dbb4cb",
        tertiary: "#9c3d5b",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 1229483,
        type: "max",
      },
      {
        original_file_name: "Glossy Heart (3).jpg",
        megabytes: 1.34,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#f9b7e1",
        primary: "#c6879e",
        tertiary: "#fad7eb",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 1402226,
        type: "max",
      },
      {
        original_file_name: "Glossy Heart (4).jpg",
        megabytes: 1.07,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#8d8ac7",
        primary: "#e4a7ba",
        tertiary: "#a894c3",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 1117655,
        type: "max",
      },
    ]
  },
  "Kawaii Blocks": {
    environment_title: "Kawaii Blocks",
    images: [
      {
        original_file_name: "Kawaii Blocks (1).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#363e57",
        primary: "#e1abb7",
        tertiary: "#6ddbd3",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 49617,
        type: "min",
      },
      {
        original_file_name: "Kawaii Blocks (2).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#344263",
        primary: "#eba39e",
        tertiary: "#9d486e",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 49510,
        type: "min",
      },
      {
        original_file_name: "Kawaii Blocks (3).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#231c34",
        primary: "#ebab8e",
        tertiary: "#833655",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 44120,
        type: "min",
      },
      {
        original_file_name: "Kawaii Blocks (4).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#67647d",
        primary: "#28455e",
        tertiary: "#f5c8b2",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 49996,
        type: "min",
      },
      {
        original_file_name: "Kawaii Blocks (1).jpg",
        megabytes: 1.28,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#363e57",
        primary: "#e2abb7",
        tertiary: "#6ddbd3",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 1346324,
        type: "max",
      },
      {
        original_file_name: "Kawaii Blocks (2).jpg",
        megabytes: 1.28,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#344263",
        primary: "#eba29e",
        tertiary: "#9e486e",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 1337021,
        type: "max",
      },
      {
        original_file_name: "Kawaii Blocks (3).jpg",
        megabytes: 1.15,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#231c34",
        primary: "#ebaa8e",
        tertiary: "#833657",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 1203625,
        type: "max",
      },
      {
        original_file_name: "Kawaii Blocks (4).jpg",
        megabytes: 1.21,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#68647e",
        primary: "#28465f",
        tertiary: "#f5c8b2",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 1263886,
        type: "max",
      },
    ]
  },
  "Pastel Circle": {
    environment_title: "Pastel Circle",
    images: [
      {
        original_file_name: "Pastel Circle (1).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#2a3542",
        primary: "#9aadcd",
        tertiary: "#ede5f1",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 56593,
        type: "min",
      },
      {
        original_file_name: "Pastel Circle (2).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#242227",
        primary: "#e7d5c9",
        tertiary: "#7f5447",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 56675,
        type: "min",
      },
      {
        original_file_name: "Pastel Circle (3).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#1d1d31",
        primary: "#cf94c3",
        tertiary: "#605281",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 75014,
        type: "min",
      },
      {
        original_file_name: "Pastel Circle (4).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#394360",
        primary: "#e8c9d4",
        tertiary: "#97809b",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 74465,
        type: "min",
      },
      {
        original_file_name: "Pastel Circle (1).jpg",
        megabytes: 1.37,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#2a3542",
        primary: "#9aadcd",
        tertiary: "#ede5f1",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 1435350,
        type: "max",
      },
      {
        original_file_name: "Pastel Circle (2).jpg",
        megabytes: 1.41,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#242227",
        primary: "#e8d5c8",
        tertiary: "#7f5347",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 1481650,
        type: "max",
      },
      {
        original_file_name: "Pastel Circle (3).jpg",
        megabytes: 1.84,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#1e1d31",
        primary: "#cf93c3",
        tertiary: "#605282",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 1931433,
        type: "max",
      },
      {
        original_file_name: "Pastel Circle (4).jpg",
        megabytes: 1.68,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#2b3b57",
        primary: "#e8c8d3",
        tertiary: "#98839f",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 1761723,
        type: "max",
      },
    ]
  },
  "Polka Panels": {
    environment_title: "Polka Panels",
    images: [
      {
        original_file_name: "Polka Panels (1).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#1b151d",
        primary: "#e0b2a4",
        tertiary: "#7c5159",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 75483,
        type: "min",
      },
      {
        original_file_name: "Polka Panels (2).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#1a1517",
        primary: "#d6afa3",
        tertiary: "#7e514b",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 56854,
        type: "min",
      },
      {
        original_file_name: "Polka Panels (3).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#1a1a25",
        primary: "#dda693",
        tertiary: "#557cab",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 87814,
        type: "min",
      },
      {
        original_file_name: "Polka Panels (4).jpg",
        megabytes: 0.09,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#1b191d",
        primary: "#e7bcae",
        tertiary: "#855e56",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 90925,
        type: "min",
      },
      {
        original_file_name: "Polka Panels (1).jpg",
        megabytes: 1.7,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#1b151d",
        primary: "#e1b3a4",
        tertiary: "#7b5159",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 1784015,
        type: "max",
      },
      {
        original_file_name: "Polka Panels (2).jpg",
        megabytes: 1.34,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#1a1517",
        primary: "#d6afa3",
        tertiary: "#7e514b",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 1408855,
        type: "max",
      },
      {
        original_file_name: "Polka Panels (3).jpg",
        megabytes: 2.14,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#1a1a25",
        primary: "#dea592",
        tertiary: "#537cab",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 2248924,
        type: "max",
      },
      {
        original_file_name: "Polka Panels (4).jpg",
        megabytes: 2.08,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#1b191d",
        primary: "#e8bcad",
        tertiary: "#845e56",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 2178639,
        type: "max",
      },
    ]
  },
  "Sky Shapes": {
    environment_title: "Sky Shapes",
    images: [
      {
        original_file_name: "Sky Shapes (1).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#d5b6ca",
        primary: "#406cae",
        tertiary: "#8e86b7",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 75864,
        type: "min",
      },
      {
        original_file_name: "Sky Shapes (2).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#4d689e",
        primary: "#d4bac6",
        tertiary: "#8ac8ed",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 76859,
        type: "min",
      },
      {
        original_file_name: "Sky Shapes (3).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#2c619d",
        primary: "#daa9a6",
        tertiary: "#968aab",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 72999,
        type: "min",
      },
      {
        original_file_name: "Sky Shapes (4).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#e1bdc5",
        primary: "#3669a6",
        tertiary: "#9e87b0",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 81529,
        type: "min",
      },
      {
        original_file_name: "Sky Shapes (1).jpg",
        megabytes: 1.76,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#d5b5c9",
        primary: "#406cae",
        tertiary: "#8e86b6",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 1847487,
        type: "max",
      },
      {
        original_file_name: "Sky Shapes (2).jpg",
        megabytes: 1.82,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#d5bac6",
        primary: "#3d5f99",
        tertiary: "#8ac8ed",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 1905712,
        type: "max",
      },
      {
        original_file_name: "Sky Shapes (3).jpg",
        megabytes: 1.65,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#295d9a",
        primary: "#dba8a6",
        tertiary: "#968aac",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 1732298,
        type: "max",
      },
      {
        original_file_name: "Sky Shapes (4).jpg",
        megabytes: 1.82,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#e2bdc4",
        primary: "#3669a7",
        tertiary: "#9e87b0",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 1909022,
        type: "max",
      },
    ]
  },
  "Soft Lines": {
    environment_title: "Soft Lines",
    images: [
      {
        original_file_name: "Soft Lines (1).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#616d90",
        primary: "#e6bfbe",
        tertiary: "#85c2bc",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 39702,
        type: "min",
      },
      {
        original_file_name: "Soft Lines (2).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#4f9db1",
        primary: "#bdc1c7",
        tertiary: "#f0dbce",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 60215,
        type: "min",
      },
      {
        original_file_name: "Soft Lines (3).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#e5baae",
        primary: "#5e5e7d",
        tertiary: "#a5808f",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 88269,
        type: "min",
      },
      {
        original_file_name: "Soft Lines (4).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#6f7d97",
        primary: "#f2cdbf",
        tertiary: "#394f53",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 77891,
        type: "min",
      },
      {
        original_file_name: "Soft Lines (1).jpg",
        megabytes: 1.23,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#616d90",
        primary: "#e7bfbe",
        tertiary: "#84c2bd",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 1287001,
        type: "max",
      },
      {
        original_file_name: "Soft Lines (2).jpg",
        megabytes: 1.56,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#4f9eb1",
        primary: "#b9c4ca",
        tertiary: "#f1dbce",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 1633349,
        type: "max",
      },
      {
        original_file_name: "Soft Lines (3).jpg",
        megabytes: 2.15,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#5e5e7d",
        primary: "#e5baad",
        tertiary: "#a57f8f",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 2253515,
        type: "max",
      },
      {
        original_file_name: "Soft Lines (4).jpg",
        megabytes: 1.98,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#60748e",
        primary: "#ebc9be",
        tertiary: "#3a5054",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 2078402,
        type: "max",
      },
    ]
  },
  "Star Grid": {
    environment_title: "Star Grid",
    images: [
      {
        original_file_name: "Star Grid (1).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#3c2c4c",
        primary: "#cc93ae",
        tertiary: "#9f739c",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 61259,
        type: "min",
      },
      {
        original_file_name: "Star Grid (2).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#f6cad3",
        primary: "#b784b8",
        tertiary: "#e9b1c3",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 53183,
        type: "min",
      },
      {
        original_file_name: "Star Grid (3).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#373163",
        primary: "#dc909d",
        tertiary: "#925783",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 83424,
        type: "min",
      },
      {
        original_file_name: "Star Grid (4).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#b77cac",
        primary: "#282036",
        tertiary: "#e9b6d2",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 59437,
        type: "min",
      },
      {
        original_file_name: "Star Grid (1).jpg",
        megabytes: 1.65,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#45355d",
        primary: "#cc93ae",
        tertiary: "#9f739c",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 1732699,
        type: "max",
      },
      {
        original_file_name: "Star Grid (2).jpg",
        megabytes: 1.62,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#f7cad3",
        primary: "#b785b8",
        tertiary: "#e9b1c3",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 1695308,
        type: "max",
      },
      {
        original_file_name: "Star Grid (3).jpg",
        megabytes: 2.04,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#2a2d5f",
        primary: "#dd909d",
        tertiary: "#925884",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 2139549,
        type: "max",
      },
      {
        original_file_name: "Star Grid (4).jpg",
        megabytes: 1.69,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#2a213a",
        primary: "#e9b6d2",
        tertiary: "#6e5894",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 1770776,
        type: "max",
      },
    ]
  },
  "Striped Wave": {
    environment_title: "Striped Wave",
    images: [
      {
        original_file_name: "Striped Wave (1).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#3e5b6a",
        primary: "#da9b9c",
        tertiary: "#f9ded4",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 75343,
        type: "min",
      },
      {
        original_file_name: "Striped Wave (2).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#e2b7bc",
        primary: "#527889",
        tertiary: "#9d8596",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 87169,
        type: "min",
      },
      {
        original_file_name: "Striped Wave (3).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#d0bab9",
        primary: "#358394",
        tertiary: "#68969d",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 70554,
        type: "min",
      },
      {
        original_file_name: "Striped Wave (4).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#e8afc2",
        primary: "#5e82a0",
        tertiary: "#fae1e5",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 53097,
        type: "min",
      },
      {
        original_file_name: "Striped Wave (1).jpg",
        megabytes: 1.67,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#455d6c",
        primary: "#db9b9d",
        tertiary: "#f9ded4",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 1753302,
        type: "max",
      },
      {
        original_file_name: "Striped Wave (2).jpg",
        megabytes: 1.96,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#e2b6bc",
        primary: "#517688",
        tertiary: "#9d8596",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 2060061,
        type: "max",
      },
      {
        original_file_name: "Striped Wave (3).jpg",
        megabytes: 1.8,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#d0baba",
        primary: "#358494",
        tertiary: "#69969d",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 1890181,
        type: "max",
      },
      {
        original_file_name: "Striped Wave (4).jpg",
        megabytes: 1.62,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#e9afc2",
        primary: "#5e82a0",
        tertiary: "#fae1e5",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 1696565,
        type: "max",
      },
    ]
  },
  "Sugar Spiral": {
    environment_title: "Sugar Spiral",
    images: [
      {
        original_file_name: "Sugar Spiral (1).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#261b28",
        primary: "#e7998b",
        tertiary: "#88433e",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 62316,
        type: "min",
      },
      {
        original_file_name: "Sugar Spiral (2).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#2d2932",
        primary: "#e1b393",
        tertiary: "#895b53",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 74194,
        type: "min",
      },
      {
        original_file_name: "Sugar Spiral (3).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#262431",
        primary: "#d3a8bf",
        tertiary: "#5e5f85",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 76068,
        type: "min",
      },
      {
        original_file_name: "Sugar Spiral (4).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#372c34",
        primary: "#e7b0ad",
        tertiary: "#8d5c67",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 84692,
        type: "min",
      },
      {
        original_file_name: "Sugar Spiral (1).jpg",
        megabytes: 1.52,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#261b28",
        primary: "#e89789",
        tertiary: "#89433e",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 1590707,
        type: "max",
      },
      {
        original_file_name: "Sugar Spiral (2).jpg",
        megabytes: 1.85,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#2d2932",
        primary: "#e1b293",
        tertiary: "#895a52",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 1944043,
        type: "max",
      },
      {
        original_file_name: "Sugar Spiral (3).jpg",
        megabytes: 2.04,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#262431",
        primary: "#d4a8bf",
        tertiary: "#5d5e85",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 2138882,
        type: "max",
      },
      {
        original_file_name: "Sugar Spiral (4).jpg",
        megabytes: 2.05,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#372c34",
        primary: "#e8b0ad",
        tertiary: "#8d5b66",
        branch: "Minimalist",
        folder: "Anime",
        bytes: 2147620,
        type: "max",
      },
    ]
  },
};
export default Minimalist_Anime;
