import { EnvironmentEntry } from "../types";
const Surreal_Anime: Record<string, EnvironmentEntry> = {
  "Bubble Hills": {
    environment_title: "Bubble Hills",
    images: [
      {
        original_file_name: "Bubble Hills (1).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#e1b9bb",
        primary: "#4c6f9f",
        tertiary: "#958cb3",
        branch: "Surreal",
        folder: "Anime",
        bytes: 76230,
        type: "min",
      },
      {
        original_file_name: "Bubble Hills (2).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#2d4c77",
        primary: "#cbbae0",
        tertiary: "#6c97dd",
        branch: "Surreal",
        folder: "Anime",
        bytes: 62565,
        type: "min",
      },
      {
        original_file_name: "Bubble Hills (3).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#624569",
        primary: "#e8c5ad",
        tertiary: "#6ccaf0",
        branch: "Surreal",
        folder: "Anime",
        bytes: 88053,
        type: "min",
      },
      {
        original_file_name: "Bubble Hills (4).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#304a73",
        primary: "#daacbe",
        tertiary: "#9283a9",
        branch: "Surreal",
        folder: "Anime",
        bytes: 69690,
        type: "min",
      },
      {
        original_file_name: "Bubble Hills (1).jpg",
        megabytes: 1.91,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#e1b9bb",
        primary: "#4c6e9e",
        tertiary: "#958cb3",
        branch: "Surreal",
        folder: "Anime",
        bytes: 1999637,
        type: "max",
      },
      {
        original_file_name: "Bubble Hills (2).jpg",
        megabytes: 1.55,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#2d4c77",
        primary: "#cbbae0",
        tertiary: "#6c97dd",
        branch: "Surreal",
        folder: "Anime",
        bytes: 1626790,
        type: "max",
      },
      {
        original_file_name: "Bubble Hills (3).jpg",
        megabytes: 1.99,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#624569",
        primary: "#e8c4ac",
        tertiary: "#6ccbf1",
        branch: "Surreal",
        folder: "Anime",
        bytes: 2082319,
        type: "max",
      },
      {
        original_file_name: "Bubble Hills (4).jpg",
        megabytes: 1.64,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#304a73",
        primary: "#dbacbe",
        tertiary: "#9182a9",
        branch: "Surreal",
        folder: "Anime",
        bytes: 1720006,
        type: "max",
      },
    ]
  },
  "Bubble Ocean": {
    environment_title: "Bubble Ocean",
    images: [
      {
        original_file_name: "Bubble Ocean (1).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#226d83",
        primary: "#d8dbdc",
        tertiary: "#65a1d1",
        branch: "Surreal",
        folder: "Anime",
        bytes: 83214,
        type: "min",
      },
      {
        original_file_name: "Bubble Ocean (2).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#558db9",
        primary: "#dde3e5",
        tertiary: "#172130",
        branch: "Surreal",
        folder: "Anime",
        bytes: 78493,
        type: "min",
      },
      {
        original_file_name: "Bubble Ocean (3).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c8dff0",
        primary: "#286884",
        tertiary: "#57d5ed",
        branch: "Surreal",
        folder: "Anime",
        bytes: 75297,
        type: "min",
      },
      {
        original_file_name: "Bubble Ocean (4).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#d5e0e2",
        primary: "#3a749c",
        tertiary: "#6acdd8",
        branch: "Surreal",
        folder: "Anime",
        bytes: 75061,
        type: "min",
      },
      {
        original_file_name: "Bubble Ocean (1).jpg",
        megabytes: 1.87,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#226d83",
        primary: "#d8dbdc",
        tertiary: "#65a1d1",
        branch: "Surreal",
        folder: "Anime",
        bytes: 1960306,
        type: "max",
      },
      {
        original_file_name: "Bubble Ocean (2).jpg",
        megabytes: 1.74,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#558db9",
        primary: "#dee3e5",
        tertiary: "#172231",
        branch: "Surreal",
        folder: "Anime",
        bytes: 1829314,
        type: "max",
      },
      {
        original_file_name: "Bubble Ocean (3).jpg",
        megabytes: 1.84,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c8e0f1",
        primary: "#286884",
        tertiary: "#55d5ee",
        branch: "Surreal",
        folder: "Anime",
        bytes: 1925439,
        type: "max",
      },
      {
        original_file_name: "Bubble Ocean (4).jpg",
        megabytes: 1.76,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#d6e1e2",
        primary: "#3a749d",
        tertiary: "#6acdd9",
        branch: "Surreal",
        folder: "Anime",
        bytes: 1848358,
        type: "max",
      },
    ]
  },
  "Candy Rails": {
    environment_title: "Candy Rails",
    images: [
      {
        original_file_name: "Candy Rails (1).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#292535",
        primary: "#ebc7ca",
        tertiary: "#5f85c1",
        branch: "Surreal",
        folder: "Anime",
        bytes: 77647,
        type: "min",
      },
      {
        original_file_name: "Candy Rails (2).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#38558a",
        primary: "#c891a0",
        tertiary: "#f7dfd2",
        branch: "Surreal",
        folder: "Anime",
        bytes: 84963,
        type: "min",
      },
      {
        original_file_name: "Candy Rails (3).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#3b70ab",
        primary: "#c8a3bc",
        tertiary: "#6a3654",
        branch: "Surreal",
        folder: "Anime",
        bytes: 82636,
        type: "min",
      },
      {
        original_file_name: "Candy Rails (4).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#3e5b8c",
        primary: "#e4aebb",
        tertiary: "#9e7ca5",
        branch: "Surreal",
        folder: "Anime",
        bytes: 76726,
        type: "min",
      },
      {
        original_file_name: "Candy Rails (1).jpg",
        megabytes: 1.73,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#2a2635",
        primary: "#ecc7c9",
        tertiary: "#5f85c1",
        branch: "Surreal",
        folder: "Anime",
        bytes: 1814937,
        type: "max",
      },
      {
        original_file_name: "Candy Rails (2).jpg",
        megabytes: 1.78,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#38558a",
        primary: "#b97b93",
        tertiary: "#f8dfd2",
        branch: "Surreal",
        folder: "Anime",
        bytes: 1868084,
        type: "max",
      },
      {
        original_file_name: "Candy Rails (3).jpg",
        megabytes: 1.86,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#3b70ac",
        primary: "#c8a4bd",
        tertiary: "#6c3655",
        branch: "Surreal",
        folder: "Anime",
        bytes: 1954807,
        type: "max",
      },
      {
        original_file_name: "Candy Rails (4).jpg",
        megabytes: 1.82,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#4f6395",
        primary: "#e5aebb",
        tertiary: "#9e7ca5",
        branch: "Surreal",
        folder: "Anime",
        bytes: 1908063,
        type: "max",
      },
    ]
  },
  "Checker Clouds": {
    environment_title: "Checker Clouds",
    images: [
      {
        original_file_name: "Checker Clouds (1).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#e3ccbf",
        primary: "#3b648d",
        tertiary: "#18232a",
        branch: "Surreal",
        folder: "Anime",
        bytes: 86905,
        type: "min",
      },
      {
        original_file_name: "Checker Clouds (2).jpg",
        megabytes: 0.09,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#dac2bc",
        primary: "#385a89",
        tertiary: "#1b1d35",
        branch: "Surreal",
        folder: "Anime",
        bytes: 91892,
        type: "min",
      },
      {
        original_file_name: "Checker Clouds (3).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#deb4ab",
        primary: "#596d90",
        tertiary: "#1d1f29",
        branch: "Surreal",
        folder: "Anime",
        bytes: 75728,
        type: "min",
      },
      {
        original_file_name: "Checker Clouds (4).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#3b5577",
        primary: "#dfbfa3",
        tertiary: "#8f7a85",
        branch: "Surreal",
        folder: "Anime",
        bytes: 83743,
        type: "min",
      },
      {
        original_file_name: "Checker Clouds (1).jpg",
        megabytes: 1.92,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#e3ccbf",
        primary: "#3b658d",
        tertiary: "#19232a",
        branch: "Surreal",
        folder: "Anime",
        bytes: 2012201,
        type: "max",
      },
      {
        original_file_name: "Checker Clouds (2).jpg",
        megabytes: 2.23,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#dbc1bb",
        primary: "#385a89",
        tertiary: "#1a1d35",
        branch: "Surreal",
        folder: "Anime",
        bytes: 2341296,
        type: "max",
      },
      {
        original_file_name: "Checker Clouds (3).jpg",
        megabytes: 1.79,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#deb3ab",
        primary: "#596d91",
        tertiary: "#1d2029",
        branch: "Surreal",
        folder: "Anime",
        bytes: 1871868,
        type: "max",
      },
      {
        original_file_name: "Checker Clouds (4).jpg",
        megabytes: 2.01,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#375275",
        primary: "#e0bfa4",
        tertiary: "#8f7a86",
        branch: "Surreal",
        folder: "Anime",
        bytes: 2105921,
        type: "max",
      },
    ]
  },
  "Citrus Sun": {
    environment_title: "Citrus Sun",
    images: [
      {
        original_file_name: "Citrus Sun (1).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c16d24",
        primary: "#97738e",
        tertiary: "#f7dfb5",
        branch: "Surreal",
        folder: "Anime",
        bytes: 79459,
        type: "min",
      },
      {
        original_file_name: "Citrus Sun (2).jpg",
        megabytes: 0.09,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#e5806a",
        primary: "#483538",
        tertiary: "#d2c8ca",
        branch: "Surreal",
        folder: "Anime",
        bytes: 89506,
        type: "min",
      },
      {
        original_file_name: "Citrus Sun (3).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#ddc9cc",
        primary: "#37322c",
        tertiary: "#c86e2e",
        branch: "Surreal",
        folder: "Anime",
        bytes: 78894,
        type: "min",
      },
      {
        original_file_name: "Citrus Sun (4).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#e29786",
        primary: "#1f425d",
        tertiary: "#f4d8c7",
        branch: "Surreal",
        folder: "Anime",
        bytes: 86229,
        type: "min",
      },
      {
        original_file_name: "Citrus Sun (1).jpg",
        megabytes: 1.8,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c26d23",
        primary: "#97738e",
        tertiary: "#f8dfb5",
        branch: "Surreal",
        folder: "Anime",
        bytes: 1887206,
        type: "max",
      },
      {
        original_file_name: "Citrus Sun (2).jpg",
        megabytes: 1.99,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#e6806a",
        primary: "#483639",
        tertiary: "#d2c8ca",
        branch: "Surreal",
        folder: "Anime",
        bytes: 2091277,
        type: "max",
      },
      {
        original_file_name: "Citrus Sun (3).jpg",
        megabytes: 1.71,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#dec9cd",
        primary: "#37322d",
        tertiary: "#c96e2e",
        branch: "Surreal",
        folder: "Anime",
        bytes: 1789225,
        type: "max",
      },
      {
        original_file_name: "Citrus Sun (4).jpg",
        megabytes: 1.84,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#e38777",
        primary: "#1f435e",
        tertiary: "#697693",
        branch: "Surreal",
        folder: "Anime",
        bytes: 1933138,
        type: "max",
      },
    ]
  },
  "Floating Whale": {
    environment_title: "Floating Whale",
    images: [
      {
        original_file_name: "Floating Whale (1).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#facab0",
        primary: "#78537b",
        tertiary: "#362f4c",
        branch: "Surreal",
        folder: "Anime",
        bytes: 68008,
        type: "min",
      },
      {
        original_file_name: "Floating Whale (2).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#6c5476",
        primary: "#e1828d",
        tertiary: "#f9ccb8",
        branch: "Surreal",
        folder: "Anime",
        bytes: 64966,
        type: "min",
      },
      {
        original_file_name: "Floating Whale (3).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#9a5c78",
        primary: "#2f3050",
        tertiary: "#eb898d",
        branch: "Surreal",
        folder: "Anime",
        bytes: 65272,
        type: "min",
      },
      {
        original_file_name: "Floating Whale (4).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#785176",
        primary: "#343d6d",
        tertiary: "#e98a92",
        branch: "Surreal",
        folder: "Anime",
        bytes: 69234,
        type: "min",
      },
      {
        original_file_name: "Floating Whale (1).jpg",
        megabytes: 1.85,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#78537b",
        primary: "#35304d",
        tertiary: "#facab0",
        branch: "Surreal",
        folder: "Anime",
        bytes: 1942545,
        type: "max",
      },
      {
        original_file_name: "Floating Whale (2).jpg",
        megabytes: 1.85,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#6c5476",
        primary: "#e1818d",
        tertiary: "#faccb8",
        branch: "Surreal",
        folder: "Anime",
        bytes: 1938465,
        type: "max",
      },
      {
        original_file_name: "Floating Whale (3).jpg",
        megabytes: 1.89,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#9b5c79",
        primary: "#2f3151",
        tertiary: "#ec888c",
        branch: "Surreal",
        folder: "Anime",
        bytes: 1986377,
        type: "max",
      },
      {
        original_file_name: "Floating Whale (4).jpg",
        megabytes: 1.81,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#785177",
        primary: "#343d6d",
        tertiary: "#e98a92",
        branch: "Surreal",
        folder: "Anime",
        bytes: 1896364,
        type: "max",
      },
    ]
  },
  "Giant Teacup": {
    environment_title: "Giant Teacup",
    images: [
      {
        original_file_name: "Giant Teacup (1).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#e9caa5",
        primary: "#656b3a",
        tertiary: "#1b3732",
        branch: "Surreal",
        folder: "Anime",
        bytes: 79660,
        type: "min",
      },
      {
        original_file_name: "Giant Teacup (2).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#374130",
        primary: "#e3cbaf",
        tertiary: "#7b8bb0",
        branch: "Surreal",
        folder: "Anime",
        bytes: 72809,
        type: "min",
      },
      {
        original_file_name: "Giant Teacup (3).jpg",
        megabytes: 0.09,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#223620",
        primary: "#6b683e",
        tertiary: "#d6c4d1",
        branch: "Surreal",
        folder: "Anime",
        bytes: 94921,
        type: "min",
      },
      {
        original_file_name: "Giant Teacup (4).jpg",
        megabytes: 0.09,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#333f28",
        primary: "#eac795",
        tertiary: "#8980a4",
        branch: "Surreal",
        folder: "Anime",
        bytes: 90640,
        type: "min",
      },
      {
        original_file_name: "Giant Teacup (1).jpg",
        megabytes: 1.77,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#e9caa5",
        primary: "#656b3a",
        tertiary: "#1b3732",
        branch: "Surreal",
        folder: "Anime",
        bytes: 1856349,
        type: "max",
      },
      {
        original_file_name: "Giant Teacup (2).jpg",
        megabytes: 1.6,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#374130",
        primary: "#e4caaf",
        tertiary: "#7a8ab0",
        branch: "Surreal",
        folder: "Anime",
        bytes: 1679056,
        type: "max",
      },
      {
        original_file_name: "Giant Teacup (3).jpg",
        megabytes: 1.97,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#6b683d",
        primary: "#223721",
        tertiary: "#d6c4d1",
        branch: "Surreal",
        folder: "Anime",
        bytes: 2066969,
        type: "max",
      },
      {
        original_file_name: "Giant Teacup (4).jpg",
        megabytes: 1.89,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#344029",
        primary: "#eac794",
        tertiary: "#897fa5",
        branch: "Surreal",
        folder: "Anime",
        bytes: 1986288,
        type: "max",
      },
    ]
  },
  "Infinite Doors": {
    environment_title: "Infinite Doors",
    images: [
      {
        original_file_name: "Infinite Doors (1).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#f8e4d9",
        primary: "#99849f",
        tertiary: "#64637e",
        branch: "Surreal",
        folder: "Anime",
        bytes: 39909,
        type: "min",
      },
      {
        original_file_name: "Infinite Doors (2).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#626089",
        primary: "#c695a6",
        tertiary: "#f2d9dd",
        branch: "Surreal",
        folder: "Anime",
        bytes: 49907,
        type: "min",
      },
      {
        original_file_name: "Infinite Doors (3).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#54535d",
        primary: "#b0848a",
        tertiary: "#f3e0da",
        branch: "Surreal",
        folder: "Anime",
        bytes: 46416,
        type: "min",
      },
      {
        original_file_name: "Infinite Doors (4).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#f9cdca",
        primary: "#92758d",
        tertiary: "#eca1a7",
        branch: "Surreal",
        folder: "Anime",
        bytes: 45497,
        type: "min",
      },
      {
        original_file_name: "Infinite Doors (1).jpg",
        megabytes: 1.29,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#f8e4d8",
        primary: "#aa879f",
        tertiary: "#ecadad",
        branch: "Surreal",
        folder: "Anime",
        bytes: 1347624,
        type: "max",
      },
      {
        original_file_name: "Infinite Doors (2).jpg",
        megabytes: 1.58,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#f2d9dd",
        primary: "#ce99a9",
        tertiary: "#5b5b85",
        branch: "Surreal",
        folder: "Anime",
        bytes: 1655913,
        type: "max",
      },
      {
        original_file_name: "Infinite Doors (3).jpg",
        megabytes: 1.42,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#54535d",
        primary: "#b7868c",
        tertiary: "#f3dfda",
        branch: "Surreal",
        folder: "Anime",
        bytes: 1484697,
        type: "max",
      },
      {
        original_file_name: "Infinite Doors (4).jpg",
        megabytes: 1.47,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#e89fa6",
        primary: "#89738e",
        tertiary: "#f9ceca",
        branch: "Surreal",
        folder: "Anime",
        bytes: 1537364,
        type: "max",
      },
    ]
  },
  "Lollipop Trees": {
    environment_title: "Lollipop Trees",
    images: [
      {
        original_file_name: "Lollipop Trees (1).jpg",
        megabytes: 0.1,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#1c2b27",
        primary: "#c7d98f",
        tertiary: "#80aa7a",
        branch: "Surreal",
        folder: "Anime",
        bytes: 104886,
        type: "min",
      },
      {
        original_file_name: "Lollipop Trees (2).jpg",
        megabytes: 0.09,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#d0cf86",
        primary: "#262f2d",
        tertiary: "#7a7962",
        branch: "Surreal",
        folder: "Anime",
        bytes: 97922,
        type: "min",
      },
      {
        original_file_name: "Lollipop Trees (3).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#dbd96c",
        primary: "#253f30",
        tertiary: "#76d999",
        branch: "Surreal",
        folder: "Anime",
        bytes: 88739,
        type: "min",
      },
      {
        original_file_name: "Lollipop Trees (4).jpg",
        megabytes: 0.09,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#2d3b32",
        primary: "#b9a383",
        tertiary: "#887e63",
        branch: "Surreal",
        folder: "Anime",
        bytes: 98927,
        type: "min",
      },
      {
        original_file_name: "Lollipop Trees (1).jpg",
        megabytes: 2.29,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#1c2b27",
        primary: "#c7d98e",
        tertiary: "#80ab7a",
        branch: "Surreal",
        folder: "Anime",
        bytes: 2397379,
        type: "max",
      },
      {
        original_file_name: "Lollipop Trees (2).jpg",
        megabytes: 2.02,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#d1cf84",
        primary: "#26302e",
        tertiary: "#7a7961",
        branch: "Surreal",
        folder: "Anime",
        bytes: 2118210,
        type: "max",
      },
      {
        original_file_name: "Lollipop Trees (3).jpg",
        megabytes: 2.0,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#dcd96a",
        primary: "#253f31",
        tertiary: "#75d999",
        branch: "Surreal",
        folder: "Anime",
        bytes: 2102050,
        type: "max",
      },
      {
        original_file_name: "Lollipop Trees (4).jpg",
        megabytes: 2.15,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#2a3931",
        primary: "#baa284",
        tertiary: "#8d7f66",
        branch: "Surreal",
        folder: "Anime",
        bytes: 2258576,
        type: "max",
      },
    ]
  },
  "Magic Umbrellas": {
    environment_title: "Magic Umbrellas",
    images: [
      {
        original_file_name: "Magic Umbrellas (1).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#6197c5",
        primary: "#d4cad4",
        tertiary: "#3d344c",
        branch: "Surreal",
        folder: "Anime",
        bytes: 73338,
        type: "min",
      },
      {
        original_file_name: "Magic Umbrellas (2).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#e1b2b0",
        primary: "#60688d",
        tertiary: "#215b8d",
        branch: "Surreal",
        folder: "Anime",
        bytes: 74423,
        type: "min",
      },
      {
        original_file_name: "Magic Umbrellas (3).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#465b86",
        primary: "#e2b3af",
        tertiary: "#96829a",
        branch: "Surreal",
        folder: "Anime",
        bytes: 69603,
        type: "min",
      },
      {
        original_file_name: "Magic Umbrellas (4).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#5d779c",
        primary: "#e1c8c5",
        tertiary: "#2d2c35",
        branch: "Surreal",
        folder: "Anime",
        bytes: 76612,
        type: "min",
      },
      {
        original_file_name: "Magic Umbrellas (1).jpg",
        megabytes: 1.84,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#6297c5",
        primary: "#d5c9d3",
        tertiary: "#3e344c",
        branch: "Surreal",
        folder: "Anime",
        bytes: 1933344,
        type: "max",
      },
      {
        original_file_name: "Magic Umbrellas (2).jpg",
        megabytes: 1.85,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#e2b2af",
        primary: "#60688e",
        tertiary: "#215b8e",
        branch: "Surreal",
        folder: "Anime",
        bytes: 1935129,
        type: "max",
      },
      {
        original_file_name: "Magic Umbrellas (3).jpg",
        megabytes: 1.67,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#465c86",
        primary: "#e3b3ae",
        tertiary: "#96829a",
        branch: "Surreal",
        folder: "Anime",
        bytes: 1746536,
        type: "max",
      },
      {
        original_file_name: "Magic Umbrellas (4).jpg",
        megabytes: 1.77,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#5d779c",
        primary: "#e2c8c5",
        tertiary: "#2e2d35",
        branch: "Surreal",
        folder: "Anime",
        bytes: 1857836,
        type: "max",
      },
    ]
  },
  "Rainbow Bridge": {
    environment_title: "Rainbow Bridge",
    images: [
      {
        original_file_name: "Rainbow Bridge (1).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#dad9c5",
        primary: "#5179bd",
        tertiary: "#263741",
        branch: "Surreal",
        folder: "Anime",
        bytes: 69774,
        type: "min",
      },
      {
        original_file_name: "Rainbow Bridge (2).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#dbded3",
        primary: "#659dcf",
        tertiary: "#3a5644",
        branch: "Surreal",
        folder: "Anime",
        bytes: 83822,
        type: "min",
      },
      {
        original_file_name: "Rainbow Bridge (3).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#3766ac",
        primary: "#c6dbd8",
        tertiary: "#2f3c31",
        branch: "Surreal",
        folder: "Anime",
        bytes: 79225,
        type: "min",
      },
      {
        original_file_name: "Rainbow Bridge (4).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#dad6cb",
        primary: "#7e9fcd",
        tertiary: "#2c3f3f",
        branch: "Surreal",
        folder: "Anime",
        bytes: 71300,
        type: "min",
      },
      {
        original_file_name: "Rainbow Bridge (1).jpg",
        megabytes: 1.85,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#dbd9c6",
        primary: "#5179be",
        tertiary: "#273841",
        branch: "Surreal",
        folder: "Anime",
        bytes: 1944197,
        type: "max",
      },
      {
        original_file_name: "Rainbow Bridge (2).jpg",
        megabytes: 2.11,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#dbded3",
        primary: "#659dd0",
        tertiary: "#3b5744",
        branch: "Surreal",
        folder: "Anime",
        bytes: 2217030,
        type: "max",
      },
      {
        original_file_name: "Rainbow Bridge (3).jpg",
        megabytes: 1.96,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c8dde6",
        primary: "#3969ac",
        tertiary: "#344431",
        branch: "Surreal",
        folder: "Anime",
        bytes: 2051093,
        type: "max",
      },
      {
        original_file_name: "Rainbow Bridge (4).jpg",
        megabytes: 1.81,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#dad6cb",
        primary: "#7ea0cd",
        tertiary: "#2c3f3f",
        branch: "Surreal",
        folder: "Anime",
        bytes: 1896502,
        type: "max",
      },
    ]
  },
  "Sakura Cloud": {
    environment_title: "Sakura Cloud",
    images: [
      {
        original_file_name: "Sakura Cloud (1).jpg",
        megabytes: 0.09,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#f3e1ce",
        primary: "#a0778f",
        tertiary: "#305180",
        branch: "Surreal",
        folder: "Anime",
        bytes: 89428,
        type: "min",
      },
      {
        original_file_name: "Sakura Cloud (2).jpg",
        megabytes: 0.1,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#a27489",
        primary: "#2f4c70",
        tertiary: "#eedfde",
        branch: "Surreal",
        folder: "Anime",
        bytes: 104752,
        type: "min",
      },
      {
        original_file_name: "Sakura Cloud (3).jpg",
        megabytes: 0.1,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#9c6d88",
        primary: "#2b527e",
        tertiary: "#efd8d6",
        branch: "Surreal",
        folder: "Anime",
        bytes: 101188,
        type: "min",
      },
      {
        original_file_name: "Sakura Cloud (4).jpg",
        megabytes: 0.1,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#203c5e",
        primary: "#975c7a",
        tertiary: "#e3d0d1",
        branch: "Surreal",
        folder: "Anime",
        bytes: 101520,
        type: "min",
      },
      {
        original_file_name: "Sakura Cloud (1).jpg",
        megabytes: 2.13,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#305281",
        primary: "#a0778f",
        tertiary: "#f4e1ce",
        branch: "Surreal",
        folder: "Anime",
        bytes: 2231616,
        type: "max",
      },
      {
        original_file_name: "Sakura Cloud (2).jpg",
        megabytes: 2.4,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#a37489",
        primary: "#2f4d71",
        tertiary: "#efdfde",
        branch: "Surreal",
        folder: "Anime",
        bytes: 2519291,
        type: "max",
      },
      {
        original_file_name: "Sakura Cloud (3).jpg",
        megabytes: 2.29,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#9c6d88",
        primary: "#2b527f",
        tertiary: "#f0d8d6",
        branch: "Surreal",
        folder: "Anime",
        bytes: 2403746,
        type: "max",
      },
      {
        original_file_name: "Sakura Cloud (4).jpg",
        megabytes: 2.29,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#1f3c5f",
        primary: "#975c7a",
        tertiary: "#e4d0d1",
        branch: "Surreal",
        folder: "Anime",
        bytes: 2401137,
        type: "max",
      },
    ]
  },
  "Smiling Moon": {
    environment_title: "Smiling Moon",
    images: [
      {
        original_file_name: "Smiling Moon (1).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#243a62",
        primary: "#d5a093",
        tertiary: "#090d1c",
        branch: "Surreal",
        folder: "Anime",
        bytes: 76864,
        type: "min",
      },
      {
        original_file_name: "Smiling Moon (2).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#19233d",
        primary: "#e8d7c5",
        tertiary: "#505a83",
        branch: "Surreal",
        folder: "Anime",
        bytes: 65372,
        type: "min",
      },
      {
        original_file_name: "Smiling Moon (3).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#1e2235",
        primary: "#d2aaab",
        tertiary: "#5c5f88",
        branch: "Surreal",
        folder: "Anime",
        bytes: 75533,
        type: "min",
      },
      {
        original_file_name: "Smiling Moon (4).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#384f83",
        primary: "#d89caf",
        tertiary: "#10172a",
        branch: "Surreal",
        folder: "Anime",
        bytes: 83313,
        type: "min",
      },
      {
        original_file_name: "Smiling Moon (1).jpg",
        megabytes: 1.66,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#243a62",
        primary: "#d69f92",
        tertiary: "#090d1c",
        branch: "Surreal",
        folder: "Anime",
        bytes: 1744173,
        type: "max",
      },
      {
        original_file_name: "Smiling Moon (2).jpg",
        megabytes: 1.38,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#19233d",
        primary: "#e8d7c5",
        tertiary: "#505a83",
        branch: "Surreal",
        folder: "Anime",
        bytes: 1451518,
        type: "max",
      },
      {
        original_file_name: "Smiling Moon (3).jpg",
        megabytes: 1.79,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#1e2235",
        primary: "#d3aaa9",
        tertiary: "#5b5f88",
        branch: "Surreal",
        folder: "Anime",
        bytes: 1877960,
        type: "max",
      },
      {
        original_file_name: "Smiling Moon (4).jpg",
        megabytes: 1.7,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#384e83",
        primary: "#d89bae",
        tertiary: "#10172b",
        branch: "Surreal",
        folder: "Anime",
        bytes: 1777624,
        type: "max",
      },
    ]
  },
  "Starry Stairs": {
    environment_title: "Starry Stairs",
    images: [
      {
        original_file_name: "Starry Stairs (1).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#273252",
        primary: "#d99dbc",
        tertiary: "#5c79c6",
        branch: "Surreal",
        folder: "Anime",
        bytes: 76327,
        type: "min",
      },
      {
        original_file_name: "Starry Stairs (2).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#5e80b8",
        primary: "#e0acaf",
        tertiary: "#252338",
        branch: "Surreal",
        folder: "Anime",
        bytes: 73000,
        type: "min",
      },
      {
        original_file_name: "Starry Stairs (3).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#243248",
        primary: "#d4aaa8",
        tertiary: "#5388c4",
        branch: "Surreal",
        folder: "Anime",
        bytes: 70630,
        type: "min",
      },
      {
        original_file_name: "Starry Stairs (4).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#32568d",
        primary: "#c4a6d3",
        tertiary: "#17182b",
        branch: "Surreal",
        folder: "Anime",
        bytes: 69471,
        type: "min",
      },
      {
        original_file_name: "Starry Stairs (1).jpg",
        megabytes: 1.97,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#273455",
        primary: "#da9cbc",
        tertiary: "#5c79c6",
        branch: "Surreal",
        folder: "Anime",
        bytes: 2068206,
        type: "max",
      },
      {
        original_file_name: "Starry Stairs (2).jpg",
        megabytes: 1.79,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#5d7fb8",
        primary: "#e0acae",
        tertiary: "#252339",
        branch: "Surreal",
        folder: "Anime",
        bytes: 1874326,
        type: "max",
      },
      {
        original_file_name: "Starry Stairs (3).jpg",
        megabytes: 1.92,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#243248",
        primary: "#d5aaa7",
        tertiary: "#5388c4",
        branch: "Surreal",
        folder: "Anime",
        bytes: 2008972,
        type: "max",
      },
      {
        original_file_name: "Starry Stairs (4).jpg",
        megabytes: 1.77,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#32568d",
        primary: "#c4a5d3",
        tertiary: "#17192b",
        branch: "Surreal",
        folder: "Anime",
        bytes: 1857710,
        type: "max",
      },
    ]
  },
  "Upward Canal": {
    environment_title: "Upward Canal",
    images: [
      {
        original_file_name: "Upward Canal (1).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#1e2b39",
        primary: "#d4cecc",
        tertiary: "#7cb6d5",
        branch: "Surreal",
        folder: "Anime",
        bytes: 86973,
        type: "min",
      },
      {
        original_file_name: "Upward Canal (2).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#283a45",
        primary: "#d7d4c9",
        tertiary: "#75c5ce",
        branch: "Surreal",
        folder: "Anime",
        bytes: 77625,
        type: "min",
      },
      {
        original_file_name: "Upward Canal (3).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#303e4f",
        primary: "#d7c1ac",
        tertiary: "#63bcb2",
        branch: "Surreal",
        folder: "Anime",
        bytes: 74882,
        type: "min",
      },
      {
        original_file_name: "Upward Canal (4).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#2b3646",
        primary: "#d4d8cf",
        tertiary: "#498dc9",
        branch: "Surreal",
        folder: "Anime",
        bytes: 80674,
        type: "min",
      },
      {
        original_file_name: "Upward Canal (1).jpg",
        megabytes: 2.3,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#1e2b39",
        primary: "#d4cecb",
        tertiary: "#7bb6d7",
        branch: "Surreal",
        folder: "Anime",
        bytes: 2409071,
        type: "max",
      },
      {
        original_file_name: "Upward Canal (2).jpg",
        megabytes: 2.06,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#283a45",
        primary: "#d7d3c8",
        tertiary: "#74c6cf",
        branch: "Surreal",
        folder: "Anime",
        bytes: 2156070,
        type: "max",
      },
      {
        original_file_name: "Upward Canal (3).jpg",
        megabytes: 2.13,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#303e4f",
        primary: "#d8c0ac",
        tertiary: "#3e96d3",
        branch: "Surreal",
        folder: "Anime",
        bytes: 2237765,
        type: "max",
      },
      {
        original_file_name: "Upward Canal (4).jpg",
        megabytes: 2.13,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#5496cd",
        primary: "#d4d7d0",
        tertiary: "#2b3646",
        branch: "Surreal",
        folder: "Anime",
        bytes: 2238037,
        type: "max",
      },
    ]
  },
};
export default Surreal_Anime;
