import { EnvironmentEntry } from "../types";
const Surreal_Realism: Record<string, EnvironmentEntry> = {
  "Desert Ocean": {
    environment_title: "Desert Ocean",
    images: [
      {
        original_file_name: "Desert Ocean (1).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#49382d",
        primary: "#dcc9a9",
        tertiary: "#c8b496",
        branch: "Surreal",
        folder: "Realism",
        bytes: 31674,
        type: "min",
      },
      {
        original_file_name: "Desert Ocean (2).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#cec0ad",
        primary: "#7f6754",
        tertiary: "#2c2725",
        branch: "Surreal",
        folder: "Realism",
        bytes: 43010,
        type: "min",
      },
      {
        original_file_name: "Desert Ocean (3).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#9a806a",
        primary: "#56473e",
        tertiary: "#c3bab1",
        branch: "Surreal",
        folder: "Realism",
        bytes: 36140,
        type: "min",
      },
      {
        original_file_name: "Desert Ocean (1).jpg",
        megabytes: 1.02,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#dccaaa",
        primary: "#654d3b",
        tertiary: "#c9b596",
        branch: "Surreal",
        folder: "Realism",
        bytes: 1066307,
        type: "max",
      },
      {
        original_file_name: "Desert Ocean (2).jpg",
        megabytes: 1.42,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#cec0ad",
        primary: "#7f6754",
        tertiary: "#c2a17d",
        branch: "Surreal",
        folder: "Realism",
        bytes: 1486992,
        type: "max",
      },
      {
        original_file_name: "Desert Ocean (3).jpg",
        megabytes: 1.4,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#997b62",
        primary: "#524239",
        tertiary: "#9b9187",
        branch: "Surreal",
        folder: "Realism",
        bytes: 1469717,
        type: "max",
      },
    ]
  },
  "Floating Rocks": {
    environment_title: "Floating Rocks",
    images: [
      {
        original_file_name: "Floating Rocks (1).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c3b9aa",
        primary: "#342f24",
        tertiary: "#888272",
        branch: "Surreal",
        folder: "Realism",
        bytes: 44017,
        type: "min",
      },
      {
        original_file_name: "Floating Rocks (2).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c8b6a0",
        primary: "#4b483e",
        tertiary: "#948773",
        branch: "Surreal",
        folder: "Realism",
        bytes: 42741,
        type: "min",
      },
      {
        original_file_name: "Floating Rocks (3).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#36332a",
        primary: "#c8b8a6",
        tertiary: "#8c7c61",
        branch: "Surreal",
        folder: "Realism",
        bytes: 43080,
        type: "min",
      },
      {
        original_file_name: "Floating Rocks (4).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#2b2720",
        primary: "#d1c4b0",
        tertiary: "#8e816b",
        branch: "Surreal",
        folder: "Realism",
        bytes: 45548,
        type: "min",
      },
      {
        original_file_name: "Floating Rocks (1).jpg",
        megabytes: 1.89,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c3b9aa",
        primary: "#342f24",
        tertiary: "#888272",
        branch: "Surreal",
        folder: "Realism",
        bytes: 1978752,
        type: "max",
      },
      {
        original_file_name: "Floating Rocks (2).jpg",
        megabytes: 1.61,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c8b69f",
        primary: "#4b483e",
        tertiary: "#948773",
        branch: "Surreal",
        folder: "Realism",
        bytes: 1690749,
        type: "max",
      },
      {
        original_file_name: "Floating Rocks (3).jpg",
        megabytes: 1.82,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#36332a",
        primary: "#c8b8a6",
        tertiary: "#8c7b62",
        branch: "Surreal",
        folder: "Realism",
        bytes: 1905900,
        type: "max",
      },
      {
        original_file_name: "Floating Rocks (4).jpg",
        megabytes: 1.77,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#2b2720",
        primary: "#d1c4b0",
        tertiary: "#8e816b",
        branch: "Surreal",
        folder: "Realism",
        bytes: 1858027,
        type: "max",
      },
    ]
  },
  "Frozen Storm": {
    environment_title: "Frozen Storm",
    images: [
      {
        original_file_name: "Frozen Storm (1).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#28282e",
        primary: "#bda6a2",
        tertiary: "#7e6a69",
        branch: "Surreal",
        folder: "Realism",
        bytes: 39359,
        type: "min",
      },
      {
        original_file_name: "Frozen Storm (2).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#b9a9aa",
        primary: "#2a2a2f",
        tertiary: "#7d6f73",
        branch: "Surreal",
        folder: "Realism",
        bytes: 44454,
        type: "min",
      },
      {
        original_file_name: "Frozen Storm (3).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#bbaaa7",
        primary: "#232429",
        tertiary: "#746d6e",
        branch: "Surreal",
        folder: "Realism",
        bytes: 39228,
        type: "min",
      },
      {
        original_file_name: "Frozen Storm (4).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#282931",
        primary: "#bfb1b2",
        tertiary: "#867c83",
        branch: "Surreal",
        folder: "Realism",
        bytes: 42231,
        type: "min",
      },
      {
        original_file_name: "Frozen Storm (1).jpg",
        megabytes: 1.37,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#28282e",
        primary: "#bda5a1",
        tertiary: "#7e6a69",
        branch: "Surreal",
        folder: "Realism",
        bytes: 1440585,
        type: "max",
      },
      {
        original_file_name: "Frozen Storm (2).jpg",
        megabytes: 1.74,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#b9a9aa",
        primary: "#2a2a2f",
        tertiary: "#7d6f73",
        branch: "Surreal",
        folder: "Realism",
        bytes: 1825362,
        type: "max",
      },
      {
        original_file_name: "Frozen Storm (3).jpg",
        megabytes: 1.36,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#baaaa6",
        primary: "#232429",
        tertiary: "#746d6e",
        branch: "Surreal",
        folder: "Realism",
        bytes: 1423532,
        type: "max",
      },
      {
        original_file_name: "Frozen Storm (4).jpg",
        megabytes: 1.37,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#282a31",
        primary: "#bfb1b2",
        tertiary: "#867c83",
        branch: "Surreal",
        folder: "Realism",
        bytes: 1432398,
        type: "max",
      },
    ]
  },
  "Gravity Lake": {
    environment_title: "Gravity Lake",
    images: [
      {
        original_file_name: "Gravity Lake (1).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c8bfb5",
        primary: "#34393c",
        tertiary: "#7e7f7c",
        branch: "Surreal",
        folder: "Realism",
        bytes: 36828,
        type: "min",
      },
      {
        original_file_name: "Gravity Lake (2).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#b5b0a5",
        primary: "#2a2e2f",
        tertiary: "#83837b",
        branch: "Surreal",
        folder: "Realism",
        bytes: 37221,
        type: "min",
      },
      {
        original_file_name: "Gravity Lake (3).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#bdbcb5",
        primary: "#292e31",
        tertiary: "#808989",
        branch: "Surreal",
        folder: "Realism",
        bytes: 37684,
        type: "min",
      },
      {
        original_file_name: "Gravity Lake (4).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c3c2c1",
        primary: "#293031",
        tertiary: "#767a78",
        branch: "Surreal",
        folder: "Realism",
        bytes: 34371,
        type: "min",
      },
      {
        original_file_name: "Gravity Lake (1).jpg",
        megabytes: 1.18,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c8bfb5",
        primary: "#34393c",
        tertiary: "#7e7f7c",
        branch: "Surreal",
        folder: "Realism",
        bytes: 1233540,
        type: "max",
      },
      {
        original_file_name: "Gravity Lake (2).jpg",
        megabytes: 1.32,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#b5b0a5",
        primary: "#2a2e2f",
        tertiary: "#83837b",
        branch: "Surreal",
        folder: "Realism",
        bytes: 1388789,
        type: "max",
      },
      {
        original_file_name: "Gravity Lake (3).jpg",
        megabytes: 1.34,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#bdbcb5",
        primary: "#292e31",
        tertiary: "#808889",
        branch: "Surreal",
        folder: "Realism",
        bytes: 1406114,
        type: "max",
      },
      {
        original_file_name: "Gravity Lake (4).jpg",
        megabytes: 1.41,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c3c2c1",
        primary: "#293031",
        tertiary: "#767978",
        branch: "Surreal",
        folder: "Realism",
        bytes: 1479234,
        type: "max",
      },
    ]
  },
  "Melting Road": {
    environment_title: "Melting Road",
    images: [
      {
        original_file_name: "Melting Road (1).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#b3ab9c",
        primary: "#2b2a2c",
        tertiary: "#81796e",
        branch: "Surreal",
        folder: "Realism",
        bytes: 42752,
        type: "min",
      },
      {
        original_file_name: "Melting Road (2).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c2c8c6",
        primary: "#252729",
        tertiary: "#b28d70",
        branch: "Surreal",
        folder: "Realism",
        bytes: 41560,
        type: "min",
      },
      {
        original_file_name: "Melting Road (3).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#252425",
        primary: "#d0c3b8",
        tertiary: "#837d76",
        branch: "Surreal",
        folder: "Realism",
        bytes: 49517,
        type: "min",
      },
      {
        original_file_name: "Melting Road (4).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#a8acac",
        primary: "#2c2c2d",
        tertiary: "#797f82",
        branch: "Surreal",
        folder: "Realism",
        bytes: 40145,
        type: "min",
      },
      {
        original_file_name: "Melting Road (1).jpg",
        megabytes: 2.05,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#b3aa9c",
        primary: "#2b2a2c",
        tertiary: "#81796e",
        branch: "Surreal",
        folder: "Realism",
        bytes: 2153905,
        type: "max",
      },
      {
        original_file_name: "Melting Road (2).jpg",
        megabytes: 1.71,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#bbbdb7",
        primary: "#27292b",
        tertiary: "#79726e",
        branch: "Surreal",
        folder: "Realism",
        bytes: 1797134,
        type: "max",
      },
      {
        original_file_name: "Melting Road (3).jpg",
        megabytes: 2.12,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#252525",
        primary: "#d0c3b8",
        tertiary: "#837d76",
        branch: "Surreal",
        folder: "Realism",
        bytes: 2224866,
        type: "max",
      },
      {
        original_file_name: "Melting Road (4).jpg",
        megabytes: 1.64,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#a7acac",
        primary: "#2c2c2e",
        tertiary: "#7a8082",
        branch: "Surreal",
        folder: "Realism",
        bytes: 1719181,
        type: "max",
      },
    ]
  },
  "Path To": {
    environment_title: "Path To",
    images: [
      {
        original_file_name: "Path To (1).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#54483d",
        primary: "#d2bca0",
        tertiary: "#9c8971",
        branch: "Surreal",
        folder: "Realism",
        bytes: 51477,
        type: "min",
      },
      {
        original_file_name: "Path To (2).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#e1cbb3",
        primary: "#39312c",
        tertiary: "#b7997c",
        branch: "Surreal",
        folder: "Realism",
        bytes: 43734,
        type: "min",
      },
      {
        original_file_name: "Path To (3).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#cec2b0",
        primary: "#373231",
        tertiary: "#90877c",
        branch: "Surreal",
        folder: "Realism",
        bytes: 49882,
        type: "min",
      },
      {
        original_file_name: "Path To (4).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c7c3bb",
        primary: "#4c4b49",
        tertiary: "#948e86",
        branch: "Surreal",
        folder: "Realism",
        bytes: 47519,
        type: "min",
      },
      {
        original_file_name: "Path To (1).jpg",
        megabytes: 2.33,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c9b295",
        primary: "#50453b",
        tertiary: "#968169",
        branch: "Surreal",
        folder: "Realism",
        bytes: 2443137,
        type: "max",
      },
      {
        original_file_name: "Path To (2).jpg",
        megabytes: 1.72,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#e1cbb3",
        primary: "#39312c",
        tertiary: "#b7997c",
        branch: "Surreal",
        folder: "Realism",
        bytes: 1806280,
        type: "max",
      },
      {
        original_file_name: "Path To (3).jpg",
        megabytes: 1.68,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#d4c7b5",
        primary: "#373231",
        tertiary: "#b4a593",
        branch: "Surreal",
        folder: "Realism",
        bytes: 1757722,
        type: "max",
      },
      {
        original_file_name: "Path To (4).jpg",
        megabytes: 1.81,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#cac7c1",
        primary: "#504d4b",
        tertiary: "#96938c",
        branch: "Surreal",
        folder: "Realism",
        bytes: 1895105,
        type: "max",
      },
    ]
  },
  "Spiral Clouds": {
    environment_title: "Spiral Clouds",
    images: [
      {
        original_file_name: "Spiral Clouds (1).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#272829",
        primary: "#c8b195",
        tertiary: "#817363",
        branch: "Surreal",
        folder: "Realism",
        bytes: 31368,
        type: "min",
      },
      {
        original_file_name: "Spiral Clouds (2).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c3beb4",
        primary: "#2d2f31",
        tertiary: "#80827c",
        branch: "Surreal",
        folder: "Realism",
        bytes: 37632,
        type: "min",
      },
      {
        original_file_name: "Spiral Clouds (3).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#282829",
        primary: "#c9af93",
        tertiary: "#806f62",
        branch: "Surreal",
        folder: "Realism",
        bytes: 32305,
        type: "min",
      },
      {
        original_file_name: "Spiral Clouds (4).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c4a78b",
        primary: "#2a2929",
        tertiary: "#816855",
        branch: "Surreal",
        folder: "Realism",
        bytes: 39016,
        type: "min",
      },
      {
        original_file_name: "Spiral Clouds (1).jpg",
        megabytes: 0.83,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#272829",
        primary: "#c9b295",
        tertiary: "#817363",
        branch: "Surreal",
        folder: "Realism",
        bytes: 865806,
        type: "max",
      },
      {
        original_file_name: "Spiral Clouds (2).jpg",
        megabytes: 1.05,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c3bfb5",
        primary: "#2d2f31",
        tertiary: "#80827c",
        branch: "Surreal",
        folder: "Realism",
        bytes: 1103967,
        type: "max",
      },
      {
        original_file_name: "Spiral Clouds (3).jpg",
        megabytes: 0.87,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#28282a",
        primary: "#c9af93",
        tertiary: "#806f62",
        branch: "Surreal",
        folder: "Realism",
        bytes: 917214,
        type: "max",
      },
      {
        original_file_name: "Spiral Clouds (4).jpg",
        megabytes: 1.04,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c4a78b",
        primary: "#2a2a2a",
        tertiary: "#816855",
        branch: "Surreal",
        folder: "Realism",
        bytes: 1089333,
        type: "max",
      },
    ]
  },
  "Star Reflection": {
    environment_title: "Star Reflection",
    images: [
      {
        original_file_name: "Star Reflection (1).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#be9d86",
        primary: "#212327",
        tertiary: "#776a62",
        branch: "Surreal",
        folder: "Realism",
        bytes: 37968,
        type: "min",
      },
      {
        original_file_name: "Star Reflection (2).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#212329",
        primary: "#cf9a79",
        tertiary: "#775b56",
        branch: "Surreal",
        folder: "Realism",
        bytes: 40559,
        type: "min",
      },
      {
        original_file_name: "Star Reflection (3).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#232529",
        primary: "#bca178",
        tertiary: "#7a6754",
        branch: "Surreal",
        folder: "Realism",
        bytes: 34832,
        type: "min",
      },
      {
        original_file_name: "Star Reflection (4).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#252428",
        primary: "#c4977c",
        tertiary: "#755e56",
        branch: "Surreal",
        folder: "Realism",
        bytes: 35208,
        type: "min",
      },
      {
        original_file_name: "Star Reflection (1).jpg",
        megabytes: 1.21,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#be9c86",
        primary: "#212327",
        tertiary: "#776a62",
        branch: "Surreal",
        folder: "Realism",
        bytes: 1265543,
        type: "max",
      },
      {
        original_file_name: "Star Reflection (2).jpg",
        megabytes: 1.38,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#212329",
        primary: "#cf9a79",
        tertiary: "#775b57",
        branch: "Surreal",
        folder: "Realism",
        bytes: 1443973,
        type: "max",
      },
      {
        original_file_name: "Star Reflection (3).jpg",
        megabytes: 1.07,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#cab086",
        primary: "#26272a",
        tertiary: "#80705d",
        branch: "Surreal",
        folder: "Realism",
        bytes: 1127003,
        type: "max",
      },
      {
        original_file_name: "Star Reflection (4).jpg",
        megabytes: 1.05,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#252428",
        primary: "#c4967c",
        tertiary: "#755d56",
        branch: "Surreal",
        folder: "Realism",
        bytes: 1105838,
        type: "max",
      },
    ]
  },
  "Towering Hands": {
    environment_title: "Towering Hands",
    images: [
      {
        original_file_name: "Towering Hands (1).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#bcbcb9",
        primary: "#272823",
        tertiary: "#7d7e7a",
        branch: "Surreal",
        folder: "Realism",
        bytes: 43181,
        type: "min",
      },
      {
        original_file_name: "Towering Hands (2).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#949997",
        primary: "#2e2c23",
        tertiary: "#c4c5c1",
        branch: "Surreal",
        folder: "Realism",
        bytes: 37566,
        type: "min",
      },
      {
        original_file_name: "Towering Hands (3).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#272825",
        primary: "#b1b1aa",
        tertiary: "#757770",
        branch: "Surreal",
        folder: "Realism",
        bytes: 40696,
        type: "min",
      },
      {
        original_file_name: "Towering Hands (4).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#bdbcb1",
        primary: "#22231f",
        tertiary: "#77786d",
        branch: "Surreal",
        folder: "Realism",
        bytes: 43904,
        type: "min",
      },
      {
        original_file_name: "Towering Hands (1).jpg",
        megabytes: 1.89,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#b6b6b3",
        primary: "#272823",
        tertiary: "#7b7c78",
        branch: "Surreal",
        folder: "Realism",
        bytes: 1979399,
        type: "max",
      },
      {
        original_file_name: "Towering Hands (2).jpg",
        megabytes: 1.62,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#949894",
        primary: "#2f2f28",
        tertiary: "#c2c3c0",
        branch: "Surreal",
        folder: "Realism",
        bytes: 1701557,
        type: "max",
      },
      {
        original_file_name: "Towering Hands (3).jpg",
        megabytes: 1.77,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#282926",
        primary: "#b1b1a9",
        tertiary: "#777770",
        branch: "Surreal",
        folder: "Realism",
        bytes: 1850787,
        type: "max",
      },
      {
        original_file_name: "Towering Hands (4).jpg",
        megabytes: 1.89,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#bdbcb2",
        primary: "#22231f",
        tertiary: "#77786e",
        branch: "Surreal",
        folder: "Realism",
        bytes: 1978868,
        type: "max",
      },
    ]
  },
  "Upside Forest": {
    environment_title: "Upside Forest",
    images: [
      {
        original_file_name: "Upside Forest (1).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#bfcacc",
        primary: "#2e3232",
        tertiary: "#94a9b1",
        branch: "Surreal",
        folder: "Realism",
        bytes: 55691,
        type: "min",
      },
      {
        original_file_name: "Upside Forest (2).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#b8c1c9",
        primary: "#222424",
        tertiary: "#71787b",
        branch: "Surreal",
        folder: "Realism",
        bytes: 70862,
        type: "min",
      },
      {
        original_file_name: "Upside Forest (3).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c7c8c6",
        primary: "#212425",
        tertiary: "#737c7e",
        branch: "Surreal",
        folder: "Realism",
        bytes: 54158,
        type: "min",
      },
      {
        original_file_name: "Upside Forest (4).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c7ccce",
        primary: "#272a2d",
        tertiary: "#798083",
        branch: "Surreal",
        folder: "Realism",
        bytes: 62843,
        type: "min",
      },
      {
        original_file_name: "Upside Forest (1).jpg",
        megabytes: 2.75,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#bfcacc",
        primary: "#2e3232",
        tertiary: "#94a9b1",
        branch: "Surreal",
        folder: "Realism",
        bytes: 2885613,
        type: "max",
      },
      {
        original_file_name: "Upside Forest (2).jpg",
        megabytes: 3.72,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#b8c1c9",
        primary: "#222525",
        tertiary: "#71787b",
        branch: "Surreal",
        folder: "Realism",
        bytes: 3903361,
        type: "max",
      },
      {
        original_file_name: "Upside Forest (3).jpg",
        megabytes: 2.24,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c7c7c6",
        primary: "#212526",
        tertiary: "#737c7e",
        branch: "Surreal",
        folder: "Realism",
        bytes: 2353577,
        type: "max",
      },
      {
        original_file_name: "Upside Forest (4).jpg",
        megabytes: 2.8,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c6cacc",
        primary: "#282b2d",
        tertiary: "#798083",
        branch: "Surreal",
        folder: "Realism",
        bytes: 2931128,
        type: "max",
      },
    ]
  },
};
export default Surreal_Realism;
