import { EnvironmentEntry } from "../types";
const Surreal_Cinematic: Record<string, EnvironmentEntry> = {
  "Clock Tower": {
    environment_title: "Clock Tower",
    images: [
      {
        original_file_name: "Clock Tower (1).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#283743",
        primary: "#bb9486",
        tertiary: "#7f7074",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 33576,
        type: "min",
      },
      {
        original_file_name: "Clock Tower (2).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c19a87",
        primary: "#344151",
        tertiary: "#181a1c",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 46419,
        type: "min",
      },
      {
        original_file_name: "Clock Tower (3).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#bdaaa0",
        primary: "#2a3848",
        tertiary: "#697b8e",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 40177,
        type: "min",
      },
      {
        original_file_name: "Clock Tower (4).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c69572",
        primary: "#313a44",
        tertiary: "#816960",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 37406,
        type: "min",
      },
      {
        original_file_name: "Clock Tower (1).jpg",
        megabytes: 1.23,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#283743",
        primary: "#bb9486",
        tertiary: "#7f6f74",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 1290179,
        type: "max",
      },
      {
        original_file_name: "Clock Tower (2).jpg",
        megabytes: 1.5,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c19a87",
        primary: "#344151",
        tertiary: "#181a1c",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 1577467,
        type: "max",
      },
      {
        original_file_name: "Clock Tower (3).jpg",
        megabytes: 1.39,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#beaaa0",
        primary: "#2a3848",
        tertiary: "#697b8e",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 1458834,
        type: "max",
      },
      {
        original_file_name: "Clock Tower (4).jpg",
        megabytes: 1.27,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c59572",
        primary: "#313a44",
        tertiary: "#816960",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 1331085,
        type: "max",
      },
    ]
  },
  "Cosmic Road": {
    environment_title: "Cosmic Road",
    images: [
      {
        original_file_name: "Cosmic Road (1).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#202329",
        primary: "#b69e93",
        tertiary: "#706d6b",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 46256,
        type: "min",
      },
      {
        original_file_name: "Cosmic Road (2).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#181f27",
        primary: "#b28771",
        tertiary: "#704f47",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 40732,
        type: "min",
      },
      {
        original_file_name: "Cosmic Road (3).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#b1957f",
        primary: "#272930",
        tertiary: "#735f61",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 45991,
        type: "min",
      },
      {
        original_file_name: "Cosmic Road (4).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#a67d66",
        primary: "#181f28",
        tertiary: "#5d6671",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 50452,
        type: "min",
      },
      {
        original_file_name: "Cosmic Road (1).jpg",
        megabytes: 1.71,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#202429",
        primary: "#b69e92",
        tertiary: "#706d6c",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 1795114,
        type: "max",
      },
      {
        original_file_name: "Cosmic Road (2).jpg",
        megabytes: 1.39,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#181f27",
        primary: "#b1876f",
        tertiary: "#704f47",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 1455971,
        type: "max",
      },
      {
        original_file_name: "Cosmic Road (3).jpg",
        megabytes: 1.66,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#b1947d",
        primary: "#272930",
        tertiary: "#735f61",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 1742038,
        type: "max",
      },
      {
        original_file_name: "Cosmic Road (4).jpg",
        megabytes: 1.92,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#a57c65",
        primary: "#181f29",
        tertiary: "#5c6671",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 2009696,
        type: "max",
      },
    ]
  },
  "Desert Spheres": {
    environment_title: "Desert Spheres",
    images: [
      {
        original_file_name: "Desert Spheres (1).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#26272d",
        primary: "#aa7240",
        tertiary: "#615042",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 73527,
        type: "min",
      },
      {
        original_file_name: "Desert Spheres (2).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#5f4636",
        primary: "#d0b191",
        tertiary: "#1e1411",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 67960,
        type: "min",
      },
      {
        original_file_name: "Desert Spheres (3).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#d5bc9c",
        primary: "#603f2b",
        tertiary: "#212024",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 72363,
        type: "min",
      },
      {
        original_file_name: "Desert Spheres (4).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#d5a877",
        primary: "#5c3f30",
        tertiary: "#272324",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 64798,
        type: "min",
      },
      {
        original_file_name: "Desert Spheres (1).jpg",
        megabytes: 2.67,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#26272d",
        primary: "#ab7240",
        tertiary: "#615144",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 2797042,
        type: "max",
      },
      {
        original_file_name: "Desert Spheres (2).jpg",
        megabytes: 1.68,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#5f4636",
        primary: "#d0b191",
        tertiary: "#1e1411",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 1762400,
        type: "max",
      },
      {
        original_file_name: "Desert Spheres (3).jpg",
        megabytes: 2.42,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#d5bc9c",
        primary: "#603f2b",
        tertiary: "#212025",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 2540600,
        type: "max",
      },
      {
        original_file_name: "Desert Spheres (4).jpg",
        megabytes: 2.37,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#e4bf8d",
        primary: "#583b2d",
        tertiary: "#c89564",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 2480487,
        type: "max",
      },
    ]
  },
  "Frozen Wave": {
    environment_title: "Frozen Wave",
    images: [
      {
        original_file_name: "Frozen Wave (1).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c4cbcf",
        primary: "#133845",
        tertiary: "#9ba7b1",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 59819,
        type: "min",
      },
      {
        original_file_name: "Frozen Wave (2).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#b9bebf",
        primary: "#1a3341",
        tertiary: "#7d929e",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 58264,
        type: "min",
      },
      {
        original_file_name: "Frozen Wave (3).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#335666",
        primary: "#b8b8b5",
        tertiary: "#8697a1",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 64630,
        type: "min",
      },
      {
        original_file_name: "Frozen Wave (4).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c6bdb2",
        primary: "#1a4250",
        tertiary: "#6c8a97",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 62139,
        type: "min",
      },
      {
        original_file_name: "Frozen Wave (1).jpg",
        megabytes: 2.14,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#113541",
        primary: "#bcc4c9",
        tertiary: "#66899b",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 2240096,
        type: "max",
      },
      {
        original_file_name: "Frozen Wave (2).jpg",
        megabytes: 1.9,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#b9bebf",
        primary: "#1c3745",
        tertiary: "#7d929e",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 1992905,
        type: "max",
      },
      {
        original_file_name: "Frozen Wave (3).jpg",
        megabytes: 2.3,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#315565",
        primary: "#b9b8b5",
        tertiary: "#8298a3",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 2409179,
        type: "max",
      },
      {
        original_file_name: "Frozen Wave (4).jpg",
        megabytes: 2.18,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c6beb2",
        primary: "#194250",
        tertiary: "#6c8b97",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 2285455,
        type: "max",
      },
    ]
  },
  "Glass Desert": {
    environment_title: "Glass Desert",
    images: [
      {
        original_file_name: "Glass Desert (1).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#9fbabf",
        primary: "#313f43",
        tertiary: "#64848a",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 54725,
        type: "min",
      },
      {
        original_file_name: "Glass Desert (2).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c1bcae",
        primary: "#353a3c",
        tertiary: "#8c887c",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 51060,
        type: "min",
      },
      {
        original_file_name: "Glass Desert (3).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#6c8589",
        primary: "#3b4649",
        tertiary: "#b4b5ad",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 44878,
        type: "min",
      },
      {
        original_file_name: "Glass Desert (4).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#333b3f",
        primary: "#b8b6b4",
        tertiary: "#837e7a",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 53233,
        type: "min",
      },
      {
        original_file_name: "Glass Desert (1).jpg",
        megabytes: 1.93,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#a0babf",
        primary: "#303f43",
        tertiary: "#64848b",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 2027866,
        type: "max",
      },
      {
        original_file_name: "Glass Desert (2).jpg",
        megabytes: 1.63,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c1bbad",
        primary: "#353a3c",
        tertiary: "#8b887c",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 1708066,
        type: "max",
      },
      {
        original_file_name: "Glass Desert (3).jpg",
        megabytes: 1.68,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#6c8589",
        primary: "#3b4649",
        tertiary: "#b4b4ad",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 1759524,
        type: "max",
      },
      {
        original_file_name: "Glass Desert (4).jpg",
        megabytes: 1.77,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#333b3f",
        primary: "#b8b6b4",
        tertiary: "#837e79",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 1852876,
        type: "max",
      },
    ]
  },
  "Gravity Falls": {
    environment_title: "Gravity Falls",
    images: [
      {
        original_file_name: "Gravity Falls (1).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#222622",
        primary: "#c4b5a9",
        tertiary: "#757272",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 65443,
        type: "min",
      },
      {
        original_file_name: "Gravity Falls (2).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#b9c1c8",
        primary: "#242620",
        tertiary: "#6c797a",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 67897,
        type: "min",
      },
      {
        original_file_name: "Gravity Falls (3).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c6d0d5",
        primary: "#282b28",
        tertiary: "#94aab1",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 69567,
        type: "min",
      },
      {
        original_file_name: "Gravity Falls (4).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#bcb8af",
        primary: "#22231f",
        tertiary: "#76715f",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 72761,
        type: "min",
      },
      {
        original_file_name: "Gravity Falls (1).jpg",
        megabytes: 2.32,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#222623",
        primary: "#c4b5a9",
        tertiary: "#757272",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 2429938,
        type: "max",
      },
      {
        original_file_name: "Gravity Falls (2).jpg",
        megabytes: 2.4,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#b8c1c7",
        primary: "#242621",
        tertiary: "#6c797a",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 2521714,
        type: "max",
      },
      {
        original_file_name: "Gravity Falls (3).jpg",
        megabytes: 2.42,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c6d0d5",
        primary: "#282b28",
        tertiary: "#94aab1",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 2537690,
        type: "max",
      },
      {
        original_file_name: "Gravity Falls (4).jpg",
        megabytes: 2.64,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#bbb7ae",
        primary: "#222320",
        tertiary: "#75715f",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 2764675,
        type: "max",
      },
    ]
  },
  "Inverted City": {
    environment_title: "Inverted City",
    images: [
      {
        original_file_name: "Inverted City (1).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#cbbdaf",
        primary: "#2d3337",
        tertiary: "#8c837b",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 65560,
        type: "min",
      },
      {
        original_file_name: "Inverted City (2).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#caab94",
        primary: "#2f3a42",
        tertiary: "#8e7b73",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 56134,
        type: "min",
      },
      {
        original_file_name: "Inverted City (3).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c9cac7",
        primary: "#374249",
        tertiary: "#848b8f",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 57296,
        type: "min",
      },
      {
        original_file_name: "Inverted City (4).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#cdbaa7",
        primary: "#273035",
        tertiary: "#897f75",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 74102,
        type: "min",
      },
      {
        original_file_name: "Inverted City (1).jpg",
        megabytes: 2.2,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#cbbdaf",
        primary: "#2d3337",
        tertiary: "#8c847b",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 2306816,
        type: "max",
      },
      {
        original_file_name: "Inverted City (2).jpg",
        megabytes: 1.84,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#caac94",
        primary: "#2f3b42",
        tertiary: "#8e7b73",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 1926397,
        type: "max",
      },
      {
        original_file_name: "Inverted City (3).jpg",
        megabytes: 1.89,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c9cac7",
        primary: "#2d363e",
        tertiary: "#898f93",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 1978431,
        type: "max",
      },
      {
        original_file_name: "Inverted City (4).jpg",
        megabytes: 2.7,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#cdbaa6",
        primary: "#2a3337",
        tertiary: "#8d8278",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 2827790,
        type: "max",
      },
    ]
  },
  "Rainbow Storm": {
    environment_title: "Rainbow Storm",
    images: [
      {
        original_file_name: "Rainbow Storm (1).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#2f3339",
        primary: "#c39c83",
        tertiary: "#8d6c68",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 37447,
        type: "min",
      },
      {
        original_file_name: "Rainbow Storm (2).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c3865b",
        primary: "#3e3942",
        tertiary: "#845641",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 37896,
        type: "min",
      },
      {
        original_file_name: "Rainbow Storm (3).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#2f333a",
        primary: "#cea781",
        tertiary: "#8e6e5b",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 42370,
        type: "min",
      },
      {
        original_file_name: "Rainbow Storm (4).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c6a26c",
        primary: "#303940",
        tertiary: "#7f6a51",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 39025,
        type: "min",
      },
      {
        original_file_name: "Rainbow Storm (1).jpg",
        megabytes: 1.26,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#2f3339",
        primary: "#c39d83",
        tertiary: "#8d6c68",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 1324609,
        type: "max",
      },
      {
        original_file_name: "Rainbow Storm (2).jpg",
        megabytes: 1.09,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c3865b",
        primary: "#3e3a42",
        tertiary: "#845641",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 1140327,
        type: "max",
      },
      {
        original_file_name: "Rainbow Storm (3).jpg",
        megabytes: 1.14,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#2f333a",
        primary: "#cea780",
        tertiary: "#8e6e5b",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 1196746,
        type: "max",
      },
      {
        original_file_name: "Rainbow Storm (4).jpg",
        megabytes: 1.14,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c6a26c",
        primary: "#303941",
        tertiary: "#7f6a51",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 1194677,
        type: "max",
      },
    ]
  },
  "Sky Stairway": {
    environment_title: "Sky Stairway",
    images: [
      {
        original_file_name: "Sky Stairway (1).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#2a3038",
        primary: "#c3c0bb",
        tertiary: "#76868d",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 50092,
        type: "min",
      },
      {
        original_file_name: "Sky Stairway (2).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#cec7bf",
        primary: "#343f49",
        tertiary: "#999590",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 61436,
        type: "min",
      },
      {
        original_file_name: "Sky Stairway (3).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#d2c1b0",
        primary: "#3a4650",
        tertiary: "#928b87",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 50685,
        type: "min",
      },
      {
        original_file_name: "Sky Stairway (4).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#cac7c0",
        primary: "#2c363e",
        tertiary: "#87857e",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 56490,
        type: "min",
      },
      {
        original_file_name: "Sky Stairway (1).jpg",
        megabytes: 1.77,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#28343d",
        primary: "#c3c0bb",
        tertiary: "#828789",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 1854422,
        type: "max",
      },
      {
        original_file_name: "Sky Stairway (2).jpg",
        megabytes: 1.79,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#cec7c0",
        primary: "#343f49",
        tertiary: "#999590",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 1874179,
        type: "max",
      },
      {
        original_file_name: "Sky Stairway (3).jpg",
        megabytes: 1.54,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#d2c1b0",
        primary: "#3a4650",
        tertiary: "#928b87",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 1613524,
        type: "max",
      },
      {
        original_file_name: "Sky Stairway (4).jpg",
        megabytes: 1.82,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#2c363e",
        primary: "#cac7c0",
        tertiary: "#87857e",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 1912089,
        type: "max",
      },
    ]
  },
  "Sunken Moon": {
    environment_title: "Sunken Moon",
    images: [
      {
        original_file_name: "Sunken Moon (1).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#14232c",
        primary: "#aeaaa0",
        tertiary: "#75716a",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 42213,
        type: "min",
      },
      {
        original_file_name: "Sunken Moon (2).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#18252d",
        primary: "#bca487",
        tertiary: "#667473",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 34698,
        type: "min",
      },
      {
        original_file_name: "Sunken Moon (3).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#ad9a8d",
        primary: "#1d2832",
        tertiary: "#695152",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 32327,
        type: "min",
      },
      {
        original_file_name: "Sunken Moon (4).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#162a34",
        primary: "#b9a089",
        tertiary: "#696c66",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 37112,
        type: "min",
      },
      {
        original_file_name: "Sunken Moon (1).jpg",
        megabytes: 1.33,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#14242c",
        primary: "#aeaaa0",
        tertiary: "#75716b",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 1396517,
        type: "max",
      },
      {
        original_file_name: "Sunken Moon (2).jpg",
        megabytes: 1.18,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#18252e",
        primary: "#bca487",
        tertiary: "#667473",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 1241290,
        type: "max",
      },
      {
        original_file_name: "Sunken Moon (3).jpg",
        megabytes: 1.05,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#ad9a8d",
        primary: "#1d2832",
        tertiary: "#6e716e",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 1104166,
        type: "max",
      },
      {
        original_file_name: "Sunken Moon (4).jpg",
        megabytes: 1.42,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#162a35",
        primary: "#b9a088",
        tertiary: "#696c66",
        branch: "Surreal",
        folder: "Cinematic",
        bytes: 1485683,
        type: "max",
      },
    ]
  },
};
export default Surreal_Cinematic;
