import { EnvironmentEntry } from "../types";
const Surreal_Geometry: Record<string, EnvironmentEntry> = {
  "Checker Sky": {
    environment_title: "Checker Sky",
    images: [
      {
        original_file_name: "Checker Sky (1).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#4c7996",
        primary: "#a5b8c9",
        tertiary: "#dfe1e5",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 35025,
        type: "min",
      },
      {
        original_file_name: "Checker Sky (2).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#496a91",
        primary: "#cad2dc",
        tertiary: "#698bac",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 41969,
        type: "min",
      },
      {
        original_file_name: "Checker Sky (3).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#3b6187",
        primary: "#a3b8cd",
        tertiary: "#dfe1e5",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 30410,
        type: "min",
      },
      {
        original_file_name: "Checker Sky (4).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#7e9bb7",
        primary: "#4a698d",
        tertiary: "#e2e5eb",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 33515,
        type: "min",
      },
      {
        original_file_name: "Checker Sky (1).jpg",
        megabytes: 0.86,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#a8bacb",
        primary: "#5084a5",
        tertiary: "#464b56",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 902570,
        type: "max",
      },
      {
        original_file_name: "Checker Sky (2).jpg",
        megabytes: 0.93,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#496a91",
        primary: "#cad2dc",
        tertiary: "#698bac",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 976474,
        type: "max",
      },
      {
        original_file_name: "Checker Sky (3).jpg",
        megabytes: 0.8,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#3b6188",
        primary: "#a3b8cd",
        tertiary: "#dee0e5",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 838805,
        type: "max",
      },
      {
        original_file_name: "Checker Sky (4).jpg",
        megabytes: 0.82,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#7e9bb7",
        primary: "#4a698d",
        tertiary: "#e3e5eb",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 864672,
        type: "max",
      },
    ]
  },
  "Cube Ocean": {
    environment_title: "Cube Ocean",
    images: [
      {
        original_file_name: "Cube Ocean (1).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#a4c5d4",
        primary: "#356278",
        tertiary: "#cddce4",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 46691,
        type: "min",
      },
      {
        original_file_name: "Cube Ocean (2).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#bed3dc",
        primary: "#294457",
        tertiary: "#92b3c2",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 45733,
        type: "min",
      },
      {
        original_file_name: "Cube Ocean (3).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c3d3dc",
        primary: "#446e88",
        tertiary: "#8daaba",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 43195,
        type: "min",
      },
      {
        original_file_name: "Cube Ocean (4).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#507488",
        primary: "#d7dfe5",
        tertiary: "#9cafbc",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 52835,
        type: "min",
      },
      {
        original_file_name: "Cube Ocean (1).jpg",
        megabytes: 1.08,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#a4c5d4",
        primary: "#356278",
        tertiary: "#cddbe4",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 1137483,
        type: "max",
      },
      {
        original_file_name: "Cube Ocean (2).jpg",
        megabytes: 1.1,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#bed3dc",
        primary: "#2a4659",
        tertiary: "#92b3c2",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 1154694,
        type: "max",
      },
      {
        original_file_name: "Cube Ocean (3).jpg",
        megabytes: 1.01,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c3d3dc",
        primary: "#446f89",
        tertiary: "#8daaba",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 1056237,
        type: "max",
      },
      {
        original_file_name: "Cube Ocean (4).jpg",
        megabytes: 1.28,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#9cafbc",
        primary: "#557a8e",
        tertiary: "#d7dfe5",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 1340581,
        type: "max",
      },
    ]
  },
  "Floating Grid": {
    environment_title: "Floating Grid",
    images: [
      {
        original_file_name: "Floating Grid (1).jpg",
        megabytes: 0.02,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c9b0be",
        primary: "#a6a0b0",
        tertiary: "#e3c5d1",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 24608,
        type: "min",
      },
      {
        original_file_name: "Floating Grid (2).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#7e8d9b",
        primary: "#a496a1",
        tertiary: "#d9bbc2",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 37786,
        type: "min",
      },
      {
        original_file_name: "Floating Grid (3).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#e2cad0",
        primary: "#8ba0aa",
        tertiary: "#b0dee4",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 27351,
        type: "min",
      },
      {
        original_file_name: "Floating Grid (4).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#e6bab9",
        primary: "#929ba1",
        tertiary: "#a9dadc",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 29885,
        type: "min",
      },
      {
        original_file_name: "Floating Grid (1).jpg",
        megabytes: 0.8,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c9b0be",
        primary: "#9e9dad",
        tertiary: "#e3c5d1",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 843961,
        type: "max",
      },
      {
        original_file_name: "Floating Grid (2).jpg",
        megabytes: 1.19,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#7e8e9b",
        primary: "#a496a1",
        tertiary: "#d8bac2",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 1245664,
        type: "max",
      },
      {
        original_file_name: "Floating Grid (3).jpg",
        megabytes: 0.89,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#e2c9cf",
        primary: "#8da4ad",
        tertiary: "#addde2",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 930685,
        type: "max",
      },
      {
        original_file_name: "Floating Grid (4).jpg",
        megabytes: 0.99,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#e6b9b9",
        primary: "#929ba2",
        tertiary: "#c3a3a6",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 1041337,
        type: "max",
      },
    ]
  },
  "Optical Stairs": {
    environment_title: "Optical Stairs",
    images: [
      {
        original_file_name: "Optical Stairs (1).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#262625",
        primary: "#a7a7a7",
        tertiary: "#e5e5e5",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 29880,
        type: "min",
      },
      {
        original_file_name: "Optical Stairs (2).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#b6b6b6",
        primary: "#1b1b1b",
        tertiary: "#626262",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 34078,
        type: "min",
      },
      {
        original_file_name: "Optical Stairs (3).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c5c5c5",
        primary: "#1d1d1d",
        tertiary: "#5f5f5f",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 40148,
        type: "min",
      },
      {
        original_file_name: "Optical Stairs (4).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#7b7b7a",
        primary: "#232323",
        tertiary: "#dedede",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 34697,
        type: "min",
      },
      {
        original_file_name: "Optical Stairs (1).jpg",
        megabytes: 0.76,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#262626",
        primary: "#a7a7a7",
        tertiary: "#e5e5e5",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 795449,
        type: "max",
      },
      {
        original_file_name: "Optical Stairs (2).jpg",
        megabytes: 0.9,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#1a1a1a",
        primary: "#bfbfbf",
        tertiary: "#656565",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 948067,
        type: "max",
      },
      {
        original_file_name: "Optical Stairs (3).jpg",
        megabytes: 0.91,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c5c5c5",
        primary: "#1d1d1d",
        tertiary: "#5f5f5f",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 954023,
        type: "max",
      },
      {
        original_file_name: "Optical Stairs (4).jpg",
        megabytes: 0.8,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#7d7d7d",
        primary: "#232323",
        tertiary: "#dedede",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 839674,
        type: "max",
      },
    ]
  },
  "Pixel Sunset": {
    environment_title: "Pixel Sunset",
    images: [
      {
        original_file_name: "Pixel Sunset (1).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#74404c",
        primary: "#e68965",
        tertiary: "#2d2836",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 38253,
        type: "min",
      },
      {
        original_file_name: "Pixel Sunset (2).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#e66d5f",
        primary: "#485285",
        tertiary: "#a65f7c",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 40159,
        type: "min",
      },
      {
        original_file_name: "Pixel Sunset (3).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#2a2838",
        primary: "#d56d52",
        tertiary: "#663241",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 44762,
        type: "min",
      },
      {
        original_file_name: "Pixel Sunset (4).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#f9ca90",
        primary: "#813e54",
        tertiary: "#e37460",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 37709,
        type: "min",
      },
      {
        original_file_name: "Pixel Sunset (1).jpg",
        megabytes: 1.34,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#312a38",
        primary: "#7b434d",
        tertiary: "#e5785c",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 1408535,
        type: "max",
      },
      {
        original_file_name: "Pixel Sunset (2).jpg",
        megabytes: 1.49,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#485285",
        primary: "#e47064",
        tertiary: "#a75b76",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 1563507,
        type: "max",
      },
      {
        original_file_name: "Pixel Sunset (3).jpg",
        megabytes: 1.54,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#2a2839",
        primary: "#d56c52",
        tertiary: "#663241",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 1615575,
        type: "max",
      },
      {
        original_file_name: "Pixel Sunset (4).jpg",
        megabytes: 1.46,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#3a314b",
        primary: "#a14655",
        tertiary: "#f9cb8f",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 1532768,
        type: "max",
      },
    ]
  },
  "Polygon Cloud": {
    environment_title: "Polygon Cloud",
    images: [
      {
        original_file_name: "Polygon Cloud (1).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#e0d0d6",
        primary: "#718d9e",
        tertiary: "#476a82",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 28913,
        type: "min",
      },
      {
        original_file_name: "Polygon Cloud (2).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#667f8f",
        primary: "#e0cbcd",
        tertiary: "#a894a0",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 30033,
        type: "min",
      },
      {
        original_file_name: "Polygon Cloud (3).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#4f7282",
        primary: "#d1d4d7",
        tertiary: "#d1a8aa",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 28200,
        type: "min",
      },
      {
        original_file_name: "Polygon Cloud (4).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#527084",
        primary: "#9d989d",
        tertiary: "#e9e1dd",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 30709,
        type: "min",
      },
      {
        original_file_name: "Polygon Cloud (1).jpg",
        megabytes: 0.82,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#e0d0d6",
        primary: "#718d9e",
        tertiary: "#476a82",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 855514,
        type: "max",
      },
      {
        original_file_name: "Polygon Cloud (2).jpg",
        megabytes: 0.85,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#667f8f",
        primary: "#e1cccd",
        tertiary: "#a994a0",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 894273,
        type: "max",
      },
      {
        original_file_name: "Polygon Cloud (3).jpg",
        megabytes: 0.82,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#527382",
        primary: "#dfc6c7",
        tertiary: "#b3969c",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 856008,
        type: "max",
      },
      {
        original_file_name: "Polygon Cloud (4).jpg",
        megabytes: 0.81,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#527184",
        primary: "#9d989d",
        tertiary: "#e9e0dd",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 850221,
        type: "max",
      },
    ]
  },
  "Sliced Land": {
    environment_title: "Sliced Land",
    images: [
      {
        original_file_name: "Sliced Land (1).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#614f40",
        primary: "#e2a981",
        tertiary: "#ecd9c0",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 52624,
        type: "min",
      },
      {
        original_file_name: "Sliced Land (2).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#cea169",
        primary: "#3a4f41",
        tertiary: "#783630",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 59521,
        type: "min",
      },
      {
        original_file_name: "Sliced Land (3).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#2b7e7b",
        primary: "#98a14e",
        tertiary: "#7c4a3c",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 38966,
        type: "min",
      },
      {
        original_file_name: "Sliced Land (4).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#616446",
        primary: "#d5b967",
        tertiary: "#22383b",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 57404,
        type: "min",
      },
      {
        original_file_name: "Sliced Land (1).jpg",
        megabytes: 1.3,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#625041",
        primary: "#e2a981",
        tertiary: "#ecd9c0",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 1362334,
        type: "max",
      },
      {
        original_file_name: "Sliced Land (2).jpg",
        megabytes: 1.98,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#cea169",
        primary: "#3a4f41",
        tertiary: "#793630",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 2072962,
        type: "max",
      },
      {
        original_file_name: "Sliced Land (3).jpg",
        megabytes: 1.43,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#2b7e7c",
        primary: "#98a14e",
        tertiary: "#7d4a3d",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 1502056,
        type: "max",
      },
      {
        original_file_name: "Sliced Land (4).jpg",
        megabytes: 1.72,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#d6bb6c",
        primary: "#677053",
        tertiary: "#22393c",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 1805835,
        type: "max",
      },
    ]
  },
  "Split Spiral": {
    environment_title: "Split Spiral",
    images: [
      {
        original_file_name: "Split Spiral (1).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#3a323c",
        primary: "#d39875",
        tertiary: "#9e5d52",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 52431,
        type: "min",
      },
      {
        original_file_name: "Split Spiral (2).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#29393d",
        primary: "#6e423b",
        tertiary: "#cbc89d",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 48727,
        type: "min",
      },
      {
        original_file_name: "Split Spiral (3).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#603036",
        primary: "#e38a83",
        tertiary: "#82bcc5",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 53070,
        type: "min",
      },
      {
        original_file_name: "Split Spiral (4).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#352a32",
        primary: "#d98b5d",
        tertiary: "#6cb3c7",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 47796,
        type: "min",
      },
      {
        original_file_name: "Split Spiral (1).jpg",
        megabytes: 1.23,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#3a323c",
        primary: "#d39875",
        tertiary: "#9e5d53",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 1292731,
        type: "max",
      },
      {
        original_file_name: "Split Spiral (2).jpg",
        megabytes: 1.2,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#29393d",
        primary: "#6f423c",
        tertiary: "#cbc89d",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 1262859,
        type: "max",
      },
      {
        original_file_name: "Split Spiral (3).jpg",
        megabytes: 1.26,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#603036",
        primary: "#e38a83",
        tertiary: "#81bcc5",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 1320456,
        type: "max",
      },
      {
        original_file_name: "Split Spiral (4).jpg",
        megabytes: 1.17,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#352a33",
        primary: "#d98b5d",
        tertiary: "#6bb3c8",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 1229780,
        type: "max",
      },
    ]
  },
  "Squares Drip": {
    environment_title: "Squares Drip",
    images: [
      {
        original_file_name: "Squares Drip (1).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#251c29",
        primary: "#cb5c44",
        tertiary: "#84383a",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 43967,
        type: "min",
      },
      {
        original_file_name: "Squares Drip (2).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#5aa9b2",
        primary: "#d46d5d",
        tertiary: "#2a2231",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 42903,
        type: "min",
      },
      {
        original_file_name: "Squares Drip (3).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#241f27",
        primary: "#d0644f",
        tertiary: "#49a9c8",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 45993,
        type: "min",
      },
      {
        original_file_name: "Squares Drip (4).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#d97156",
        primary: "#363540",
        tertiary: "#82404a",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 35026,
        type: "min",
      },
      {
        original_file_name: "Squares Drip (1).jpg",
        megabytes: 1.21,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#251c29",
        primary: "#cb5c44",
        tertiary: "#84383a",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 1270237,
        type: "max",
      },
      {
        original_file_name: "Squares Drip (2).jpg",
        megabytes: 1.27,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#5aa9b2",
        primary: "#d56d5d",
        tertiary: "#2a2332",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 1330526,
        type: "max",
      },
      {
        original_file_name: "Squares Drip (3).jpg",
        megabytes: 1.15,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#241f28",
        primary: "#d0634e",
        tertiary: "#49a9c9",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 1207513,
        type: "max",
      },
      {
        original_file_name: "Squares Drip (4).jpg",
        megabytes: 0.94,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#d97154",
        primary: "#363540",
        tertiary: "#83404b",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 980653,
        type: "max",
      },
    ]
  },
  "Wire Warp": {
    environment_title: "Wire Warp",
    images: [
      {
        original_file_name: "Wire Warp (1).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#b7939c",
        primary: "#1e1e27",
        tertiary: "#755762",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 65102,
        type: "min",
      },
      {
        original_file_name: "Wire Warp (2).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#ca84a3",
        primary: "#281a28",
        tertiary: "#824866",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 66365,
        type: "min",
      },
      {
        original_file_name: "Wire Warp (3).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#1c1a28",
        primary: "#bc758e",
        tertiary: "#784660",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 52078,
        type: "min",
      },
      {
        original_file_name: "Wire Warp (4).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#ad7aa3",
        primary: "#1e1521",
        tertiary: "#6c4f73",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 58746,
        type: "min",
      },
      {
        original_file_name: "Wire Warp (1).jpg",
        megabytes: 1.67,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#b7919a",
        primary: "#1e1e28",
        tertiary: "#755661",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 1750789,
        type: "max",
      },
      {
        original_file_name: "Wire Warp (2).jpg",
        megabytes: 2.27,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#ca83a2",
        primary: "#281b28",
        tertiary: "#824866",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 2384456,
        type: "max",
      },
      {
        original_file_name: "Wire Warp (3).jpg",
        megabytes: 1.91,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#1c1a28",
        primary: "#bc758e",
        tertiary: "#784660",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 2001034,
        type: "max",
      },
      {
        original_file_name: "Wire Warp (4).jpg",
        megabytes: 2.24,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#ae79a3",
        primary: "#1e1521",
        tertiary: "#6c4f73",
        branch: "Surreal",
        folder: "Geometry",
        bytes: 2352176,
        type: "max",
      },
    ]
  },
};
export default Surreal_Geometry;
