import { EnvironmentEntry } from "../types";
const Urban_Anime: Record<string, EnvironmentEntry> = {
  "Canal Row": {
    environment_title: "Canal Row",
    images: [
      {
        original_file_name: "Canal Row (1).jpg",
        megabytes: 0.09,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#2c333d",
        primary: "#dac69d",
        tertiary: "#61be97",
        branch: "Urban",
        folder: "Anime",
        bytes: 89595,
        type: "min",
      },
      {
        original_file_name: "Canal Row (2).jpg",
        megabytes: 0.1,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#303a45",
        primary: "#d9b787",
        tertiary: "#87715f",
        branch: "Urban",
        folder: "Anime",
        bytes: 102512,
        type: "min",
      },
      {
        original_file_name: "Canal Row (3).jpg",
        megabytes: 0.09,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#2e3e4e",
        primary: "#d8be93",
        tertiary: "#62b28d",
        branch: "Urban",
        folder: "Anime",
        bytes: 92843,
        type: "min",
      },
      {
        original_file_name: "Canal Row (4).jpg",
        megabytes: 0.09,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#2c3944",
        primary: "#dcbb8a",
        tertiary: "#5c8a76",
        branch: "Urban",
        folder: "Anime",
        bytes: 96162,
        type: "min",
      },
      {
        original_file_name: "Canal Row (1).jpg",
        megabytes: 2.59,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#2c333e",
        primary: "#dbc69c",
        tertiary: "#60be97",
        branch: "Urban",
        folder: "Anime",
        bytes: 2719121,
        type: "max",
      },
      {
        original_file_name: "Canal Row (2).jpg",
        megabytes: 2.89,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#313a46",
        primary: "#dab687",
        tertiary: "#87705f",
        branch: "Urban",
        folder: "Anime",
        bytes: 3034451,
        type: "max",
      },
      {
        original_file_name: "Canal Row (3).jpg",
        megabytes: 2.52,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#2e3e4e",
        primary: "#d9bd92",
        tertiary: "#61b38b",
        branch: "Urban",
        folder: "Anime",
        bytes: 2646404,
        type: "max",
      },
      {
        original_file_name: "Canal Row (4).jpg",
        megabytes: 2.76,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#2c3944",
        primary: "#dcba89",
        tertiary: "#5b8a77",
        branch: "Urban",
        folder: "Anime",
        bytes: 2890181,
        type: "max",
      },
    ]
  },
  "Cozy Alley": {
    environment_title: "Cozy Alley",
    images: [
      {
        original_file_name: "Cozy Alley (1).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#211c27",
        primary: "#cd9485",
        tertiary: "#764a4a",
        branch: "Urban",
        folder: "Anime",
        bytes: 77470,
        type: "min",
      },
      {
        original_file_name: "Cozy Alley (2).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#221c26",
        primary: "#c9917c",
        tertiary: "#764b48",
        branch: "Urban",
        folder: "Anime",
        bytes: 74550,
        type: "min",
      },
      {
        original_file_name: "Cozy Alley (3).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c8958d",
        primary: "#1f202c",
        tertiary: "#764e51",
        branch: "Urban",
        folder: "Anime",
        bytes: 78486,
        type: "min",
      },
      {
        original_file_name: "Cozy Alley (4).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c89b92",
        primary: "#201f29",
        tertiary: "#765353",
        branch: "Urban",
        folder: "Anime",
        bytes: 77000,
        type: "min",
      },
      {
        original_file_name: "Cozy Alley (1).jpg",
        megabytes: 2.31,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#211c27",
        primary: "#ce9384",
        tertiary: "#764a4b",
        branch: "Urban",
        folder: "Anime",
        bytes: 2420627,
        type: "max",
      },
      {
        original_file_name: "Cozy Alley (2).jpg",
        megabytes: 2.29,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#221d26",
        primary: "#c9907b",
        tertiary: "#764b47",
        branch: "Urban",
        folder: "Anime",
        bytes: 2401658,
        type: "max",
      },
      {
        original_file_name: "Cozy Alley (3).jpg",
        megabytes: 2.46,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c8948c",
        primary: "#1f202c",
        tertiary: "#764d50",
        branch: "Urban",
        folder: "Anime",
        bytes: 2575536,
        type: "max",
      },
      {
        original_file_name: "Cozy Alley (4).jpg",
        megabytes: 2.25,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c89a90",
        primary: "#201f29",
        tertiary: "#765353",
        branch: "Urban",
        folder: "Anime",
        bytes: 2360792,
        type: "max",
      },
    ]
  },
  "Fruit Stalls": {
    environment_title: "Fruit Stalls",
    images: [
      {
        original_file_name: "Fruit Stalls (1).jpg",
        megabytes: 0.09,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#322d32",
        primary: "#d69d66",
        tertiary: "#8e5f45",
        branch: "Urban",
        folder: "Anime",
        bytes: 92187,
        type: "min",
      },
      {
        original_file_name: "Fruit Stalls (2).jpg",
        megabytes: 0.09,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#312f32",
        primary: "#d8b284",
        tertiary: "#89624a",
        branch: "Urban",
        folder: "Anime",
        bytes: 94787,
        type: "min",
      },
      {
        original_file_name: "Fruit Stalls (3).jpg",
        megabytes: 0.09,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#313131",
        primary: "#d7af87",
        tertiary: "#896449",
        branch: "Urban",
        folder: "Anime",
        bytes: 97715,
        type: "min",
      },
      {
        original_file_name: "Fruit Stalls (4).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#2b292f",
        primary: "#d08e5a",
        tertiary: "#81543a",
        branch: "Urban",
        folder: "Anime",
        bytes: 87901,
        type: "min",
      },
      {
        original_file_name: "Fruit Stalls (1).jpg",
        megabytes: 2.5,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#322d33",
        primary: "#d79d65",
        tertiary: "#8e5f45",
        branch: "Urban",
        folder: "Anime",
        bytes: 2620864,
        type: "max",
      },
      {
        original_file_name: "Fruit Stalls (2).jpg",
        megabytes: 2.58,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#313032",
        primary: "#d9b183",
        tertiary: "#8a6249",
        branch: "Urban",
        folder: "Anime",
        bytes: 2709979,
        type: "max",
      },
      {
        original_file_name: "Fruit Stalls (3).jpg",
        megabytes: 2.54,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#313131",
        primary: "#d8af85",
        tertiary: "#896449",
        branch: "Urban",
        folder: "Anime",
        bytes: 2664945,
        type: "max",
      },
      {
        original_file_name: "Fruit Stalls (4).jpg",
        megabytes: 2.55,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#2e2b31",
        primary: "#d18e58",
        tertiary: "#815339",
        branch: "Urban",
        folder: "Anime",
        bytes: 2675287,
        type: "max",
      },
    ]
  },
  "Highrise Cafe": {
    environment_title: "Highrise Cafe",
    images: [
      {
        original_file_name: "Highrise Cafe (1).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#2a232d",
        primary: "#d59b86",
        tertiary: "#6fa6c7",
        branch: "Urban",
        folder: "Anime",
        bytes: 83254,
        type: "min",
      },
      {
        original_file_name: "Highrise Cafe (2).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#28252f",
        primary: "#d29b90",
        tertiary: "#5e6280",
        branch: "Urban",
        folder: "Anime",
        bytes: 72443,
        type: "min",
      },
      {
        original_file_name: "Highrise Cafe (3).jpg",
        megabytes: 0.09,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#292731",
        primary: "#d09388",
        tertiary: "#815c5e",
        branch: "Urban",
        folder: "Anime",
        bytes: 89714,
        type: "min",
      },
      {
        original_file_name: "Highrise Cafe (4).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#2c2730",
        primary: "#d59880",
        tertiary: "#795453",
        branch: "Urban",
        folder: "Anime",
        bytes: 84638,
        type: "min",
      },
      {
        original_file_name: "Highrise Cafe (1).jpg",
        megabytes: 2.25,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#2a232d",
        primary: "#d69b85",
        tertiary: "#6fa6c7",
        branch: "Urban",
        folder: "Anime",
        bytes: 2354371,
        type: "max",
      },
      {
        original_file_name: "Highrise Cafe (2).jpg",
        megabytes: 2.11,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#302f3e",
        primary: "#d79d90",
        tertiary: "#7f5a5e",
        branch: "Urban",
        folder: "Anime",
        bytes: 2213077,
        type: "max",
      },
      {
        original_file_name: "Highrise Cafe (3).jpg",
        megabytes: 2.4,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#2d2f3c",
        primary: "#d19287",
        tertiary: "#815b5e",
        branch: "Urban",
        folder: "Anime",
        bytes: 2520121,
        type: "max",
      },
      {
        original_file_name: "Highrise Cafe (4).jpg",
        megabytes: 2.25,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#2c2730",
        primary: "#d6977f",
        tertiary: "#795453",
        branch: "Urban",
        folder: "Anime",
        bytes: 2361126,
        type: "max",
      },
    ]
  },
  "Lantern Lane": {
    environment_title: "Lantern Lane",
    images: [
      {
        original_file_name: "Lantern Lane (1).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#231d24",
        primary: "#d69a66",
        tertiary: "#764232",
        branch: "Urban",
        folder: "Anime",
        bytes: 79009,
        type: "min",
      },
      {
        original_file_name: "Lantern Lane (2).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#261c1f",
        primary: "#d48e59",
        tertiary: "#814631",
        branch: "Urban",
        folder: "Anime",
        bytes: 85835,
        type: "min",
      },
      {
        original_file_name: "Lantern Lane (3).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#221c22",
        primary: "#d8965e",
        tertiary: "#784937",
        branch: "Urban",
        folder: "Anime",
        bytes: 80415,
        type: "min",
      },
      {
        original_file_name: "Lantern Lane (4).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#231e24",
        primary: "#d6905d",
        tertiary: "#774232",
        branch: "Urban",
        folder: "Anime",
        bytes: 82974,
        type: "min",
      },
      {
        original_file_name: "Lantern Lane (1).jpg",
        megabytes: 2.27,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#231d24",
        primary: "#d89a65",
        tertiary: "#764231",
        branch: "Urban",
        folder: "Anime",
        bytes: 2379861,
        type: "max",
      },
      {
        original_file_name: "Lantern Lane (2).jpg",
        megabytes: 2.22,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#261c1f",
        primary: "#d58d57",
        tertiary: "#814530",
        branch: "Urban",
        folder: "Anime",
        bytes: 2329457,
        type: "max",
      },
      {
        original_file_name: "Lantern Lane (3).jpg",
        megabytes: 2.19,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#221c22",
        primary: "#d9955d",
        tertiary: "#784836",
        branch: "Urban",
        folder: "Anime",
        bytes: 2297893,
        type: "max",
      },
      {
        original_file_name: "Lantern Lane (4).jpg",
        megabytes: 2.26,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#231e25",
        primary: "#d78f5c",
        tertiary: "#774232",
        branch: "Urban",
        folder: "Anime",
        bytes: 2367179,
        type: "max",
      },
    ]
  },
  "Midday Plaza": {
    environment_title: "Midday Plaza",
    images: [
      {
        original_file_name: "Midday Plaza (1).jpg",
        megabytes: 0.1,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#2a303e",
        primary: "#ac9583",
        tertiary: "#4f3b3d",
        branch: "Urban",
        folder: "Anime",
        bytes: 101562,
        type: "min",
      },
      {
        original_file_name: "Midday Plaza (2).jpg",
        megabytes: 0.09,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#2c303b",
        primary: "#a9957f",
        tertiary: "#4c3d3d",
        branch: "Urban",
        folder: "Anime",
        bytes: 98513,
        type: "min",
      },
      {
        original_file_name: "Midday Plaza (3).jpg",
        megabytes: 0.1,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#30363e",
        primary: "#dac4a2",
        tertiary: "#8b7965",
        branch: "Urban",
        folder: "Anime",
        bytes: 103127,
        type: "min",
      },
      {
        original_file_name: "Midday Plaza (4).jpg",
        megabytes: 0.1,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#333c49",
        primary: "#e1c6a8",
        tertiary: "#8e7f69",
        branch: "Urban",
        folder: "Anime",
        bytes: 102378,
        type: "min",
      },
      {
        original_file_name: "Midday Plaza (1).jpg",
        megabytes: 2.49,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#2a303f",
        primary: "#ac9582",
        tertiary: "#4f3b3d",
        branch: "Urban",
        folder: "Anime",
        bytes: 2608944,
        type: "max",
      },
      {
        original_file_name: "Midday Plaza (2).jpg",
        megabytes: 2.47,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#aa957e",
        primary: "#2c313b",
        tertiary: "#4c3d3d",
        branch: "Urban",
        folder: "Anime",
        bytes: 2585929,
        type: "max",
      },
      {
        original_file_name: "Midday Plaza (3).jpg",
        megabytes: 2.5,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#30363e",
        primary: "#dbc4a2",
        tertiary: "#8b7963",
        branch: "Urban",
        folder: "Anime",
        bytes: 2618088,
        type: "max",
      },
      {
        original_file_name: "Midday Plaza (4).jpg",
        megabytes: 2.52,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#333c49",
        primary: "#e2c6a7",
        tertiary: "#8d7d68",
        branch: "Urban",
        folder: "Anime",
        bytes: 2641001,
        type: "max",
      },
    ]
  },
  "Neon Street": {
    environment_title: "Neon Street",
    images: [
      {
        original_file_name: "Neon Street (1).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#181f2f",
        primary: "#cfa399",
        tertiary: "#65ceda",
        branch: "Urban",
        folder: "Anime",
        bytes: 79531,
        type: "min",
      },
      {
        original_file_name: "Neon Street (2).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#1e202e",
        primary: "#d5999a",
        tertiary: "#5bc7ca",
        branch: "Urban",
        folder: "Anime",
        bytes: 86853,
        type: "min",
      },
      {
        original_file_name: "Neon Street (3).jpg",
        megabytes: 0.09,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#1c222e",
        primary: "#d19888",
        tertiary: "#785150",
        branch: "Urban",
        folder: "Anime",
        bytes: 92376,
        type: "min",
      },
      {
        original_file_name: "Neon Street (4).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#1d2231",
        primary: "#c99b9a",
        tertiary: "#68c8d4",
        branch: "Urban",
        folder: "Anime",
        bytes: 87756,
        type: "min",
      },
      {
        original_file_name: "Neon Street (1).jpg",
        megabytes: 2.28,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#181f2f",
        primary: "#d2a398",
        tertiary: "#63d0dd",
        branch: "Urban",
        folder: "Anime",
        bytes: 2387663,
        type: "max",
      },
      {
        original_file_name: "Neon Street (2).jpg",
        megabytes: 2.48,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#1d202f",
        primary: "#d7999a",
        tertiary: "#59c7c9",
        branch: "Urban",
        folder: "Anime",
        bytes: 2595428,
        type: "max",
      },
      {
        original_file_name: "Neon Street (3).jpg",
        megabytes: 2.54,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#1c222f",
        primary: "#d29887",
        tertiary: "#78504f",
        branch: "Urban",
        folder: "Anime",
        bytes: 2661780,
        type: "max",
      },
      {
        original_file_name: "Neon Street (4).jpg",
        megabytes: 2.48,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#1d2231",
        primary: "#ca9998",
        tertiary: "#67c8d5",
        branch: "Urban",
        folder: "Anime",
        bytes: 2602633,
        type: "max",
      },
    ]
  },
  "Night Arcade": {
    environment_title: "Night Arcade",
    images: [
      {
        original_file_name: "Night Arcade (1).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#1e1931",
        primary: "#ce8bca",
        tertiary: "#4b4684",
        branch: "Urban",
        folder: "Anime",
        bytes: 71340,
        type: "min",
      },
      {
        original_file_name: "Night Arcade (2).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#1c1329",
        primary: "#cd75a1",
        tertiary: "#723552",
        branch: "Urban",
        folder: "Anime",
        bytes: 77286,
        type: "min",
      },
      {
        original_file_name: "Night Arcade (3).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#1e1629",
        primary: "#d06b83",
        tertiary: "#792d42",
        branch: "Urban",
        folder: "Anime",
        bytes: 68992,
        type: "min",
      },
      {
        original_file_name: "Night Arcade (4).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#25192a",
        primary: "#ca5e6c",
        tertiary: "#772a38",
        branch: "Urban",
        folder: "Anime",
        bytes: 67103,
        type: "min",
      },
      {
        original_file_name: "Night Arcade (1).jpg",
        megabytes: 2.29,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#1e1931",
        primary: "#cf78c4",
        tertiary: "#4b4684",
        branch: "Urban",
        folder: "Anime",
        bytes: 2401846,
        type: "max",
      },
      {
        original_file_name: "Night Arcade (2).jpg",
        megabytes: 2.35,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#1d1429",
        primary: "#cf73a0",
        tertiary: "#4c6bb5",
        branch: "Urban",
        folder: "Anime",
        bytes: 2464875,
        type: "max",
      },
      {
        original_file_name: "Night Arcade (3).jpg",
        megabytes: 2.1,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#1e1629",
        primary: "#d26a82",
        tertiary: "#792d41",
        branch: "Urban",
        folder: "Anime",
        bytes: 2206307,
        type: "max",
      },
      {
        original_file_name: "Night Arcade (4).jpg",
        megabytes: 2.14,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#251a2a",
        primary: "#cd5d6b",
        tertiary: "#772938",
        branch: "Urban",
        folder: "Anime",
        bytes: 2246430,
        type: "max",
      },
    ]
  },
  "Rainy Corner": {
    environment_title: "Rainy Corner",
    images: [
      {
        original_file_name: "Rainy Corner (1).jpg",
        megabytes: 0.09,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c9a489",
        primary: "#25242f",
        tertiary: "#755752",
        branch: "Urban",
        folder: "Anime",
        bytes: 89751,
        type: "min",
      },
      {
        original_file_name: "Rainy Corner (2).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#282430",
        primary: "#d19572",
        tertiary: "#784e49",
        branch: "Urban",
        folder: "Anime",
        bytes: 89015,
        type: "min",
      },
      {
        original_file_name: "Rainy Corner (3).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#d2ab90",
        primary: "#27242f",
        tertiary: "#775552",
        branch: "Urban",
        folder: "Anime",
        bytes: 88373,
        type: "min",
      },
      {
        original_file_name: "Rainy Corner (4).jpg",
        megabytes: 0.09,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#d09d7d",
        primary: "#25222b",
        tertiary: "#765149",
        branch: "Urban",
        folder: "Anime",
        bytes: 89434,
        type: "min",
      },
      {
        original_file_name: "Rainy Corner (1).jpg",
        megabytes: 2.36,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#caa487",
        primary: "#25242f",
        tertiary: "#765752",
        branch: "Urban",
        folder: "Anime",
        bytes: 2472562,
        type: "max",
      },
      {
        original_file_name: "Rainy Corner (2).jpg",
        megabytes: 2.49,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#282430",
        primary: "#d29571",
        tertiary: "#784e49",
        branch: "Urban",
        folder: "Anime",
        bytes: 2606987,
        type: "max",
      },
      {
        original_file_name: "Rainy Corner (3).jpg",
        megabytes: 2.41,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#d2aa8e",
        primary: "#27242f",
        tertiary: "#775451",
        branch: "Urban",
        folder: "Anime",
        bytes: 2526640,
        type: "max",
      },
      {
        original_file_name: "Rainy Corner (4).jpg",
        megabytes: 2.59,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#d09c7b",
        primary: "#25222c",
        tertiary: "#765149",
        branch: "Urban",
        folder: "Anime",
        bytes: 2715783,
        type: "max",
      },
    ]
  },
  "Shibuya Glow": {
    environment_title: "Shibuya Glow",
    images: [
      {
        original_file_name: "Shibuya Glow (1).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#20222d",
        primary: "#d0afa5",
        tertiary: "#775b58",
        branch: "Urban",
        folder: "Anime",
        bytes: 87812,
        type: "min",
      },
      {
        original_file_name: "Shibuya Glow (2).jpg",
        megabytes: 0.1,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#25262f",
        primary: "#dabeac",
        tertiary: "#80635b",
        branch: "Urban",
        folder: "Anime",
        bytes: 100396,
        type: "min",
      },
      {
        original_file_name: "Shibuya Glow (3).jpg",
        megabytes: 0.09,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#1e222b",
        primary: "#ceb9bd",
        tertiary: "#70bcc6",
        branch: "Urban",
        folder: "Anime",
        bytes: 92806,
        type: "min",
      },
      {
        original_file_name: "Shibuya Glow (4).jpg",
        megabytes: 0.09,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#25292f",
        primary: "#cbbfb8",
        tertiary: "#756a69",
        branch: "Urban",
        folder: "Anime",
        bytes: 89802,
        type: "min",
      },
      {
        original_file_name: "Shibuya Glow (1).jpg",
        megabytes: 2.66,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#20232d",
        primary: "#d1afa5",
        tertiary: "#775b58",
        branch: "Urban",
        folder: "Anime",
        bytes: 2785164,
        type: "max",
      },
      {
        original_file_name: "Shibuya Glow (2).jpg",
        megabytes: 2.85,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#25272f",
        primary: "#dbbdaa",
        tertiary: "#80625a",
        branch: "Urban",
        folder: "Anime",
        bytes: 2991202,
        type: "max",
      },
      {
        original_file_name: "Shibuya Glow (3).jpg",
        megabytes: 2.72,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#1e222c",
        primary: "#cebabd",
        tertiary: "#77575c",
        branch: "Urban",
        folder: "Anime",
        bytes: 2851357,
        type: "max",
      },
      {
        original_file_name: "Shibuya Glow (4).jpg",
        megabytes: 2.72,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#25292f",
        primary: "#cdbfb8",
        tertiary: "#756968",
        branch: "Urban",
        folder: "Anime",
        bytes: 2854378,
        type: "max",
      },
    ]
  },
  "Sky Bridge": {
    environment_title: "Sky Bridge",
    images: [
      {
        original_file_name: "Sky Bridge (1).jpg",
        megabytes: 0.09,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#2c3d52",
        primary: "#d3d4dc",
        tertiary: "#88bcdd",
        branch: "Urban",
        folder: "Anime",
        bytes: 99432,
        type: "min",
      },
      {
        original_file_name: "Sky Bridge (2).jpg",
        megabytes: 0.09,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#31394a",
        primary: "#d2cbd0",
        tertiary: "#5c91c4",
        branch: "Urban",
        folder: "Anime",
        bytes: 91667,
        type: "min",
      },
      {
        original_file_name: "Sky Bridge (3).jpg",
        megabytes: 0.09,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#2b3649",
        primary: "#c9d3df",
        tertiary: "#5289c7",
        branch: "Urban",
        folder: "Anime",
        bytes: 91536,
        type: "min",
      },
      {
        original_file_name: "Sky Bridge (4).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#24364e",
        primary: "#c3cddc",
        tertiary: "#87b0d2",
        branch: "Urban",
        folder: "Anime",
        bytes: 85074,
        type: "min",
      },
      {
        original_file_name: "Sky Bridge (1).jpg",
        megabytes: 2.63,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#2e3f55",
        primary: "#d3d4dc",
        tertiary: "#87bcde",
        branch: "Urban",
        folder: "Anime",
        bytes: 2757187,
        type: "max",
      },
      {
        original_file_name: "Sky Bridge (2).jpg",
        megabytes: 2.34,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#313a4a",
        primary: "#d2cacf",
        tertiary: "#5c91c4",
        branch: "Urban",
        folder: "Anime",
        bytes: 2450001,
        type: "max",
      },
      {
        original_file_name: "Sky Bridge (3).jpg",
        megabytes: 2.41,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#2b3749",
        primary: "#c9d3df",
        tertiary: "#5289c7",
        branch: "Urban",
        folder: "Anime",
        bytes: 2525827,
        type: "max",
      },
      {
        original_file_name: "Sky Bridge (4).jpg",
        megabytes: 2.13,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#24364e",
        primary: "#c4cddc",
        tertiary: "#87b0d2",
        branch: "Urban",
        folder: "Anime",
        bytes: 2238082,
        type: "max",
      },
    ]
  },
  "Sunrise Town": {
    environment_title: "Sunrise Town",
    images: [
      {
        original_file_name: "Sunrise Town (1).jpg",
        megabytes: 0.09,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#2f2f3d",
        primary: "#d59169",
        tertiary: "#815143",
        branch: "Urban",
        folder: "Anime",
        bytes: 95831,
        type: "min",
      },
      {
        original_file_name: "Sunrise Town (2).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#333143",
        primary: "#d5966f",
        tertiary: "#80524d",
        branch: "Urban",
        folder: "Anime",
        bytes: 87045,
        type: "min",
      },
      {
        original_file_name: "Sunrise Town (3).jpg",
        megabytes: 0.09,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#463c40",
        primary: "#e1a873",
        tertiary: "#956d57",
        branch: "Urban",
        folder: "Anime",
        bytes: 92398,
        type: "min",
      },
      {
        original_file_name: "Sunrise Town (4).jpg",
        megabytes: 0.09,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#312d3a",
        primary: "#d9a276",
        tertiary: "#8f5f50",
        branch: "Urban",
        folder: "Anime",
        bytes: 93409,
        type: "min",
      },
      {
        original_file_name: "Sunrise Town (1).jpg",
        megabytes: 2.6,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#2f2f3e",
        primary: "#d69168",
        tertiary: "#815042",
        branch: "Urban",
        folder: "Anime",
        bytes: 2723667,
        type: "max",
      },
      {
        original_file_name: "Sunrise Town (2).jpg",
        megabytes: 2.56,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#333143",
        primary: "#d6956e",
        tertiary: "#80524d",
        branch: "Urban",
        folder: "Anime",
        bytes: 2685104,
        type: "max",
      },
      {
        original_file_name: "Sunrise Town (3).jpg",
        megabytes: 2.46,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#463c40",
        primary: "#e2a772",
        tertiary: "#956c57",
        branch: "Urban",
        folder: "Anime",
        bytes: 2581640,
        type: "max",
      },
      {
        original_file_name: "Sunrise Town (4).jpg",
        megabytes: 2.66,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#312d3a",
        primary: "#d9a174",
        tertiary: "#8f5f50",
        branch: "Urban",
        folder: "Anime",
        bytes: 2793145,
        type: "max",
      },
    ]
  },
  "Sunset View": {
    environment_title: "Sunset View",
    images: [
      {
        original_file_name: "Sunset View (1).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#34222c",
        primary: "#dc8661",
        tertiary: "#8d4c47",
        branch: "Urban",
        folder: "Anime",
        bytes: 80559,
        type: "min",
      },
      {
        original_file_name: "Sunset View (2).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#291c25",
        primary: "#df866e",
        tertiary: "#84709b",
        branch: "Urban",
        folder: "Anime",
        bytes: 81410,
        type: "min",
      },
      {
        original_file_name: "Sunset View (3).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#e4927c",
        primary: "#36252a",
        tertiary: "#9b6368",
        branch: "Urban",
        folder: "Anime",
        bytes: 73422,
        type: "min",
      },
      {
        original_file_name: "Sunset View (4).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#4f3038",
        primary: "#dc6d5b",
        tertiary: "#954b4f",
        branch: "Urban",
        folder: "Anime",
        bytes: 79419,
        type: "min",
      },
      {
        original_file_name: "Sunset View (1).jpg",
        megabytes: 2.02,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#34232c",
        primary: "#dd8661",
        tertiary: "#8d4c46",
        branch: "Urban",
        folder: "Anime",
        bytes: 2117222,
        type: "max",
      },
      {
        original_file_name: "Sunset View (2).jpg",
        megabytes: 1.91,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#291c25",
        primary: "#df866f",
        tertiary: "#84709b",
        branch: "Urban",
        folder: "Anime",
        bytes: 2001965,
        type: "max",
      },
      {
        original_file_name: "Sunset View (3).jpg",
        megabytes: 1.72,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#e5927b",
        primary: "#36252a",
        tertiary: "#9b6369",
        branch: "Urban",
        folder: "Anime",
        bytes: 1807406,
        type: "max",
      },
      {
        original_file_name: "Sunset View (4).jpg",
        megabytes: 1.99,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#e16f5c",
        primary: "#52313a",
        tertiary: "#9d4d51",
        branch: "Urban",
        folder: "Anime",
        bytes: 2086807,
        type: "max",
      },
    ]
  },
  "Urban Blossoms": {
    environment_title: "Urban Blossoms",
    images: [
      {
        original_file_name: "Urban Blossoms (1).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#221e2c",
        primary: "#d48c9e",
        tertiary: "#784859",
        branch: "Urban",
        folder: "Anime",
        bytes: 88878,
        type: "min",
      },
      {
        original_file_name: "Urban Blossoms (2).jpg",
        megabytes: 0.09,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#292131",
        primary: "#d48b98",
        tertiary: "#894f63",
        branch: "Urban",
        folder: "Anime",
        bytes: 99128,
        type: "min",
      },
      {
        original_file_name: "Urban Blossoms (3).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#262231",
        primary: "#cf7584",
        tertiary: "#7f4654",
        branch: "Urban",
        folder: "Anime",
        bytes: 86768,
        type: "min",
      },
      {
        original_file_name: "Urban Blossoms (4).jpg",
        megabytes: 0.09,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#2a222f",
        primary: "#d59296",
        tertiary: "#85525b",
        branch: "Urban",
        folder: "Anime",
        bytes: 91659,
        type: "min",
      },
      {
        original_file_name: "Urban Blossoms (1).jpg",
        megabytes: 2.36,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#221e2c",
        primary: "#d58b9e",
        tertiary: "#784759",
        branch: "Urban",
        folder: "Anime",
        bytes: 2475401,
        type: "max",
      },
      {
        original_file_name: "Urban Blossoms (2).jpg",
        megabytes: 2.55,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#292132",
        primary: "#d58b97",
        tertiary: "#894f63",
        branch: "Urban",
        folder: "Anime",
        bytes: 2677243,
        type: "max",
      },
      {
        original_file_name: "Urban Blossoms (3).jpg",
        megabytes: 2.35,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#262231",
        primary: "#d07483",
        tertiary: "#7f4654",
        branch: "Urban",
        folder: "Anime",
        bytes: 2464499,
        type: "max",
      },
      {
        original_file_name: "Urban Blossoms (4).jpg",
        megabytes: 2.36,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#2a222f",
        primary: "#d69296",
        tertiary: "#85525b",
        branch: "Urban",
        folder: "Anime",
        bytes: 2471237,
        type: "max",
      },
    ]
  },
};
export default Urban_Anime;
