import { EnvironmentEntry } from "../types";
const Urban_Realism: Record<string, EnvironmentEntry> = {
  "Abandoned Block": {
    environment_title: "Abandoned Block",
    images: [
      {
        original_file_name: "Abandoned Block (1).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#28251e",
        primary: "#cad0d4",
        tertiary: "#7a766d",
        branch: "Urban",
        folder: "Realism",
        bytes: 48786,
        type: "min",
      },
      {
        original_file_name: "Abandoned Block (2).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#7a6e68",
        primary: "#423e36",
        tertiary: "#d4d7d9",
        branch: "Urban",
        folder: "Realism",
        bytes: 52437,
        type: "min",
      },
      {
        original_file_name: "Abandoned Block (3).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#847f78",
        primary: "#27251e",
        tertiary: "#abaaa6",
        branch: "Urban",
        folder: "Realism",
        bytes: 47365,
        type: "min",
      },
      {
        original_file_name: "Abandoned Block (4).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#dcdde0",
        primary: "#262620",
        tertiary: "#78746c",
        branch: "Urban",
        folder: "Realism",
        bytes: 55202,
        type: "min",
      },
      {
        original_file_name: "Abandoned Block (1).jpg",
        megabytes: 1.9,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#28251e",
        primary: "#cad0d5",
        tertiary: "#7a766d",
        branch: "Urban",
        folder: "Realism",
        bytes: 1991224,
        type: "max",
      },
      {
        original_file_name: "Abandoned Block (2).jpg",
        megabytes: 2.29,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#7a6d67",
        primary: "#423e36",
        tertiary: "#d3d6d8",
        branch: "Urban",
        folder: "Realism",
        bytes: 2397631,
        type: "max",
      },
      {
        original_file_name: "Abandoned Block (3).jpg",
        megabytes: 1.69,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#abaaa6",
        primary: "#292720",
        tertiary: "#87837c",
        branch: "Urban",
        folder: "Realism",
        bytes: 1776458,
        type: "max",
      },
      {
        original_file_name: "Abandoned Block (4).jpg",
        megabytes: 2.13,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#dbdcdf",
        primary: "#272620",
        tertiary: "#77736c",
        branch: "Urban",
        folder: "Realism",
        bytes: 2231580,
        type: "max",
      },
    ]
  },
  "Glass Tower": {
    environment_title: "Glass Tower",
    images: [
      {
        original_file_name: "Glass Tower (1).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#433638",
        primary: "#dd935f",
        tertiary: "#9b6a56",
        branch: "Urban",
        folder: "Realism",
        bytes: 49262,
        type: "min",
      },
      {
        original_file_name: "Glass Tower (2).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#d8a588",
        primary: "#5b362c",
        tertiary: "#978787",
        branch: "Urban",
        folder: "Realism",
        bytes: 48559,
        type: "min",
      },
      {
        original_file_name: "Glass Tower (3).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#524a4d",
        primary: "#debc9e",
        tertiary: "#c9987a",
        branch: "Urban",
        folder: "Realism",
        bytes: 41373,
        type: "min",
      },
      {
        original_file_name: "Glass Tower (4).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#362620",
        primary: "#da9467",
        tertiary: "#9e7767",
        branch: "Urban",
        folder: "Realism",
        bytes: 56388,
        type: "min",
      },
      {
        original_file_name: "Glass Tower (1).jpg",
        megabytes: 1.52,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#453a3d",
        primary: "#d27e48",
        tertiary: "#e7b88d",
        branch: "Urban",
        folder: "Realism",
        bytes: 1592938,
        type: "max",
      },
      {
        original_file_name: "Glass Tower (2).jpg",
        megabytes: 1.65,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#d8a587",
        primary: "#5c362d",
        tertiary: "#958585",
        branch: "Urban",
        folder: "Realism",
        bytes: 1733305,
        type: "max",
      },
      {
        original_file_name: "Glass Tower (3).jpg",
        megabytes: 1.33,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#524a4d",
        primary: "#debc9e",
        tertiary: "#c9987a",
        branch: "Urban",
        folder: "Realism",
        bytes: 1393183,
        type: "max",
      },
      {
        original_file_name: "Glass Tower (4).jpg",
        megabytes: 1.75,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#d48455",
        primary: "#362621",
        tertiary: "#c9b9ab",
        branch: "Urban",
        folder: "Realism",
        bytes: 1831092,
        type: "max",
      },
    ]
  },
  "Gothic Street": {
    environment_title: "Gothic Street",
    images: [
      {
        original_file_name: "Gothic Street (1).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#b8b2ae",
        primary: "#252122",
        tertiary: "#726a68",
        branch: "Urban",
        folder: "Realism",
        bytes: 53799,
        type: "min",
      },
      {
        original_file_name: "Gothic Street (2).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c2afa9",
        primary: "#272222",
        tertiary: "#74655f",
        branch: "Urban",
        folder: "Realism",
        bytes: 57128,
        type: "min",
      },
      {
        original_file_name: "Gothic Street (3).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#252325",
        primary: "#ba9d86",
        tertiary: "#766c63",
        branch: "Urban",
        folder: "Realism",
        bytes: 46675,
        type: "min",
      },
      {
        original_file_name: "Gothic Street (4).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c1b3a9",
        primary: "#232022",
        tertiary: "#77706e",
        branch: "Urban",
        folder: "Realism",
        bytes: 52677,
        type: "min",
      },
      {
        original_file_name: "Gothic Street (1).jpg",
        megabytes: 2.16,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#b8b2ae",
        primary: "#252122",
        tertiary: "#786f6c",
        branch: "Urban",
        folder: "Realism",
        bytes: 2262114,
        type: "max",
      },
      {
        original_file_name: "Gothic Street (2).jpg",
        megabytes: 2.07,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c2afa9",
        primary: "#272322",
        tertiary: "#73655f",
        branch: "Urban",
        folder: "Realism",
        bytes: 2168112,
        type: "max",
      },
      {
        original_file_name: "Gothic Street (3).jpg",
        megabytes: 1.61,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#262325",
        primary: "#bb9d86",
        tertiary: "#776c63",
        branch: "Urban",
        folder: "Realism",
        bytes: 1691567,
        type: "max",
      },
      {
        original_file_name: "Gothic Street (4).jpg",
        megabytes: 1.94,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c1b2a9",
        primary: "#232022",
        tertiary: "#766f6e",
        branch: "Urban",
        folder: "Realism",
        bytes: 2029410,
        type: "max",
      },
    ]
  },
  "Narrow Alley": {
    environment_title: "Narrow Alley",
    images: [
      {
        original_file_name: "Narrow Alley (1).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#463529",
        primary: "#cbc3bb",
        tertiary: "#7e6756",
        branch: "Urban",
        folder: "Realism",
        bytes: 56159,
        type: "min",
      },
      {
        original_file_name: "Narrow Alley (2).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#2e231a",
        primary: "#d0bba1",
        tertiary: "#806954",
        branch: "Urban",
        folder: "Realism",
        bytes: 51634,
        type: "min",
      },
      {
        original_file_name: "Narrow Alley (3).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c5b4a1",
        primary: "#403126",
        tertiary: "#836950",
        branch: "Urban",
        folder: "Realism",
        bytes: 55508,
        type: "min",
      },
      {
        original_file_name: "Narrow Alley (4).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#cbaf97",
        primary: "#4b3a2e",
        tertiary: "#8b7769",
        branch: "Urban",
        folder: "Realism",
        bytes: 62932,
        type: "min",
      },
      {
        original_file_name: "Narrow Alley (1).jpg",
        megabytes: 2.19,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#463529",
        primary: "#cbc3ba",
        tertiary: "#7e6756",
        branch: "Urban",
        folder: "Realism",
        bytes: 2299565,
        type: "max",
      },
      {
        original_file_name: "Narrow Alley (2).jpg",
        megabytes: 2.03,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#2e231a",
        primary: "#cfbba0",
        tertiary: "#806954",
        branch: "Urban",
        folder: "Realism",
        bytes: 2127523,
        type: "max",
      },
      {
        original_file_name: "Narrow Alley (3).jpg",
        megabytes: 2.07,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c5b4a1",
        primary: "#403126",
        tertiary: "#836850",
        branch: "Urban",
        folder: "Realism",
        bytes: 2170432,
        type: "max",
      },
      {
        original_file_name: "Narrow Alley (4).jpg",
        megabytes: 2.29,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#caae95",
        primary: "#4b3b2e",
        tertiary: "#8a7769",
        branch: "Urban",
        folder: "Realism",
        bytes: 2403369,
        type: "max",
      },
    ]
  },
  "Neon Reflection": {
    environment_title: "Neon Reflection",
    images: [
      {
        original_file_name: "Neon Reflection (1).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#161217",
        primary: "#ce9c64",
        tertiary: "#6e4c49",
        branch: "Urban",
        folder: "Realism",
        bytes: 59544,
        type: "min",
      },
      {
        original_file_name: "Neon Reflection (2).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#161318",
        primary: "#bc6d68",
        tertiary: "#63a7bd",
        branch: "Urban",
        folder: "Realism",
        bytes: 56984,
        type: "min",
      },
      {
        original_file_name: "Neon Reflection (3).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#18151b",
        primary: "#c6654e",
        tertiary: "#5f9ab1",
        branch: "Urban",
        folder: "Realism",
        bytes: 51708,
        type: "min",
      },
      {
        original_file_name: "Neon Reflection (4).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#16151a",
        primary: "#c28c82",
        tertiary: "#6f4644",
        branch: "Urban",
        folder: "Realism",
        bytes: 56068,
        type: "min",
      },
      {
        original_file_name: "Neon Reflection (1).jpg",
        megabytes: 1.81,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#161217",
        primary: "#cf9b63",
        tertiary: "#6e4c49",
        branch: "Urban",
        folder: "Realism",
        bytes: 1892794,
        type: "max",
      },
      {
        original_file_name: "Neon Reflection (2).jpg",
        megabytes: 1.92,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#161318",
        primary: "#bd6d68",
        tertiary: "#64a7bd",
        branch: "Urban",
        folder: "Realism",
        bytes: 2008515,
        type: "max",
      },
      {
        original_file_name: "Neon Reflection (3).jpg",
        megabytes: 1.48,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#18151b",
        primary: "#c7654e",
        tertiary: "#5e9ab1",
        branch: "Urban",
        folder: "Realism",
        bytes: 1547326,
        type: "max",
      },
      {
        original_file_name: "Neon Reflection (4).jpg",
        megabytes: 1.71,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#16151b",
        primary: "#c38c82",
        tertiary: "#6f4644",
        branch: "Urban",
        folder: "Realism",
        bytes: 1789359,
        type: "max",
      },
    ]
  },
  "Rooftop Dawn": {
    environment_title: "Rooftop Dawn",
    images: [
      {
        original_file_name: "Rooftop Dawn (1).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#261816",
        primary: "#d5b194",
        tertiary: "#896b60",
        branch: "Urban",
        folder: "Realism",
        bytes: 47260,
        type: "min",
      },
      {
        original_file_name: "Rooftop Dawn (2).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#291f1e",
        primary: "#cea78c",
        tertiary: "#847069",
        branch: "Urban",
        folder: "Realism",
        bytes: 41125,
        type: "min",
      },
      {
        original_file_name: "Rooftop Dawn (3).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#242023",
        primary: "#cbab95",
        tertiary: "#78625e",
        branch: "Urban",
        folder: "Realism",
        bytes: 44113,
        type: "min",
      },
      {
        original_file_name: "Rooftop Dawn (4).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#2a2b30",
        primary: "#cdac8d",
        tertiary: "#806c64",
        branch: "Urban",
        folder: "Realism",
        bytes: 39726,
        type: "min",
      },
      {
        original_file_name: "Rooftop Dawn (1).jpg",
        megabytes: 1.42,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#261916",
        primary: "#d5b194",
        tertiary: "#876f67",
        branch: "Urban",
        folder: "Realism",
        bytes: 1483756,
        type: "max",
      },
      {
        original_file_name: "Rooftop Dawn (2).jpg",
        megabytes: 1.38,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#cea78c",
        primary: "#291f1e",
        tertiary: "#847069",
        branch: "Urban",
        folder: "Realism",
        bytes: 1445468,
        type: "max",
      },
      {
        original_file_name: "Rooftop Dawn (3).jpg",
        megabytes: 1.48,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#242023",
        primary: "#cbab95",
        tertiary: "#77615d",
        branch: "Urban",
        folder: "Realism",
        bytes: 1553088,
        type: "max",
      },
      {
        original_file_name: "Rooftop Dawn (4).jpg",
        megabytes: 1.29,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#2a2b30",
        primary: "#cdac8d",
        tertiary: "#806d64",
        branch: "Urban",
        folder: "Realism",
        bytes: 1352069,
        type: "max",
      },
    ]
  },
  "Skyline Storm": {
    environment_title: "Skyline Storm",
    images: [
      {
        original_file_name: "Skyline Storm (1).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#a9a39c",
        primary: "#1e1e21",
        tertiary: "#6d7171",
        branch: "Urban",
        folder: "Realism",
        bytes: 34871,
        type: "min",
      },
      {
        original_file_name: "Skyline Storm (2).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#1e1e21",
        primary: "#a2887b",
        tertiary: "#71615a",
        branch: "Urban",
        folder: "Realism",
        bytes: 39262,
        type: "min",
      },
      {
        original_file_name: "Skyline Storm (3).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#626d74",
        primary: "#1e1f22",
        tertiary: "#a3aeb3",
        branch: "Urban",
        folder: "Realism",
        bytes: 39370,
        type: "min",
      },
      {
        original_file_name: "Skyline Storm (4).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#b1825b",
        primary: "#1c1d22",
        tertiary: "#6e6965",
        branch: "Urban",
        folder: "Realism",
        bytes: 35697,
        type: "min",
      },
      {
        original_file_name: "Skyline Storm (1).jpg",
        megabytes: 1.19,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#a8a39c",
        primary: "#1e1e21",
        tertiary: "#6d7171",
        branch: "Urban",
        folder: "Realism",
        bytes: 1251677,
        type: "max",
      },
      {
        original_file_name: "Skyline Storm (2).jpg",
        megabytes: 1.19,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#1e1e21",
        primary: "#a2887b",
        tertiary: "#71615a",
        branch: "Urban",
        folder: "Realism",
        bytes: 1246676,
        type: "max",
      },
      {
        original_file_name: "Skyline Storm (3).jpg",
        megabytes: 1.4,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#626d74",
        primary: "#1e1f22",
        tertiary: "#a3aeb3",
        branch: "Urban",
        folder: "Realism",
        bytes: 1465980,
        type: "max",
      },
      {
        original_file_name: "Skyline Storm (4).jpg",
        megabytes: 1.1,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#b18259",
        primary: "#1c1d22",
        tertiary: "#6e6965",
        branch: "Urban",
        folder: "Realism",
        bytes: 1157899,
        type: "max",
      },
    ]
  },
  "Sunlit Avenue": {
    environment_title: "Sunlit Avenue",
    images: [
      {
        original_file_name: "Sunlit Avenue (1).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#d9d1c7",
        primary: "#483121",
        tertiary: "#b8875c",
        branch: "Urban",
        folder: "Realism",
        bytes: 58798,
        type: "min",
      },
      {
        original_file_name: "Sunlit Avenue (2).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#d7bfa7",
        primary: "#533c2b",
        tertiary: "#a7acb3",
        branch: "Urban",
        folder: "Realism",
        bytes: 58159,
        type: "min",
      },
      {
        original_file_name: "Sunlit Avenue (3).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#3b2c23",
        primary: "#d4c7b8",
        tertiary: "#969ba3",
        branch: "Urban",
        folder: "Realism",
        bytes: 57208,
        type: "min",
      },
      {
        original_file_name: "Sunlit Avenue (4).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#35241a",
        primary: "#d6c2ac",
        tertiary: "#906c4c",
        branch: "Urban",
        folder: "Realism",
        bytes: 60482,
        type: "min",
      },
      {
        original_file_name: "Sunlit Avenue (1).jpg",
        megabytes: 2.11,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#d9d0c8",
        primary: "#483122",
        tertiary: "#b8875c",
        branch: "Urban",
        folder: "Realism",
        bytes: 2208218,
        type: "max",
      },
      {
        original_file_name: "Sunlit Avenue (2).jpg",
        megabytes: 2.16,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#d7bfa7",
        primary: "#533c2b",
        tertiary: "#a7acb4",
        branch: "Urban",
        folder: "Realism",
        bytes: 2261160,
        type: "max",
      },
      {
        original_file_name: "Sunlit Avenue (3).jpg",
        megabytes: 1.95,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#3c2c23",
        primary: "#d4c7b8",
        tertiary: "#959ca2",
        branch: "Urban",
        folder: "Realism",
        bytes: 2048272,
        type: "max",
      },
      {
        original_file_name: "Sunlit Avenue (4).jpg",
        megabytes: 2.14,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#35241a",
        primary: "#d5c2ac",
        tertiary: "#906c4c",
        branch: "Urban",
        folder: "Realism",
        bytes: 2240067,
        type: "max",
      },
    ]
  },
};
export default Urban_Realism;
