import { EnvironmentEntry } from "../types";
const Urban_Geometry: Record<string, EnvironmentEntry> = {
  "Checker Avenue": {
    environment_title: "Checker Avenue",
    images: [
      {
        original_file_name: "Checker Avenue (1).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#dbdbda",
        primary: "#363636",
        tertiary: "#888887",
        branch: "Urban",
        folder: "Geometry",
        bytes: 66472,
        type: "min",
      },
      {
        original_file_name: "Checker Avenue (2).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#d3d3d2",
        primary: "#454545",
        tertiary: "#909090",
        branch: "Urban",
        folder: "Geometry",
        bytes: 68507,
        type: "min",
      },
      {
        original_file_name: "Checker Avenue (3).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#d7d7d6",
        primary: "#454545",
        tertiary: "#8f8f8f",
        branch: "Urban",
        folder: "Geometry",
        bytes: 59748,
        type: "min",
      },
      {
        original_file_name: "Checker Avenue (4).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#d5d5d5",
        primary: "#3d3d3d",
        tertiary: "#858584",
        branch: "Urban",
        folder: "Geometry",
        bytes: 51503,
        type: "min",
      },
      {
        original_file_name: "Checker Avenue (1).jpg",
        megabytes: 1.63,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#dadada",
        primary: "#363636",
        tertiary: "#888887",
        branch: "Urban",
        folder: "Geometry",
        bytes: 1705723,
        type: "max",
      },
      {
        original_file_name: "Checker Avenue (2).jpg",
        megabytes: 1.91,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#d2d2d2",
        primary: "#454545",
        tertiary: "#909090",
        branch: "Urban",
        folder: "Geometry",
        bytes: 2001124,
        type: "max",
      },
      {
        original_file_name: "Checker Avenue (3).jpg",
        megabytes: 2.05,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#d6d6d6",
        primary: "#454545",
        tertiary: "#8b8b8b",
        branch: "Urban",
        folder: "Geometry",
        bytes: 2145170,
        type: "max",
      },
      {
        original_file_name: "Checker Avenue (4).jpg",
        megabytes: 1.41,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#d5d5d5",
        primary: "#353535",
        tertiary: "#8b8b8b",
        branch: "Urban",
        folder: "Geometry",
        bytes: 1480324,
        type: "max",
      },
    ]
  },
  "Circles Town": {
    environment_title: "Circles Town",
    images: [
      {
        original_file_name: "Circles Town (1).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#9d7066",
        primary: "#e1dac4",
        tertiary: "#3f5c66",
        branch: "Urban",
        folder: "Geometry",
        bytes: 62943,
        type: "min",
      },
      {
        original_file_name: "Circles Town (2).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#3a5466",
        primary: "#e5d0ad",
        tertiary: "#725d62",
        branch: "Urban",
        folder: "Geometry",
        bytes: 70867,
        type: "min",
      },
      {
        original_file_name: "Circles Town (3).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#425a69",
        primary: "#a07a6e",
        tertiary: "#e69c77",
        branch: "Urban",
        folder: "Geometry",
        bytes: 68703,
        type: "min",
      },
      {
        original_file_name: "Circles Town (4).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#675d61",
        primary: "#2c4753",
        tertiary: "#e9906b",
        branch: "Urban",
        folder: "Geometry",
        bytes: 64613,
        type: "min",
      },
      {
        original_file_name: "Circles Town (1).jpg",
        megabytes: 1.77,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#7e6a68",
        primary: "#3f5c66",
        tertiary: "#e99c77",
        branch: "Urban",
        folder: "Geometry",
        bytes: 1853284,
        type: "max",
      },
      {
        original_file_name: "Circles Town (2).jpg",
        megabytes: 1.97,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#3a5466",
        primary: "#e5d0ad",
        tertiary: "#725d62",
        branch: "Urban",
        folder: "Geometry",
        bytes: 2062594,
        type: "max",
      },
      {
        original_file_name: "Circles Town (3).jpg",
        megabytes: 1.93,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#a07a6e",
        primary: "#465c6a",
        tertiary: "#e69b77",
        branch: "Urban",
        folder: "Geometry",
        bytes: 2028275,
        type: "max",
      },
      {
        original_file_name: "Circles Town (4).jpg",
        megabytes: 1.46,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#675e61",
        primary: "#2c4753",
        tertiary: "#e9906a",
        branch: "Urban",
        folder: "Geometry",
        bytes: 1530579,
        type: "max",
      },
    ]
  },
  "Cubist Blocks": {
    environment_title: "Cubist Blocks",
    images: [
      {
        original_file_name: "Cubist Blocks (1).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#393439",
        primary: "#dfb483",
        tertiary: "#98785d",
        branch: "Urban",
        folder: "Geometry",
        bytes: 44088,
        type: "min",
      },
      {
        original_file_name: "Cubist Blocks (2).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#edd2b0",
        primary: "#484a4a",
        tertiary: "#d48553",
        branch: "Urban",
        folder: "Geometry",
        bytes: 45673,
        type: "min",
      },
      {
        original_file_name: "Cubist Blocks (3).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#3b464e",
        primary: "#d9a372",
        tertiary: "#eadabe",
        branch: "Urban",
        folder: "Geometry",
        bytes: 42426,
        type: "min",
      },
      {
        original_file_name: "Cubist Blocks (4).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#29333c",
        primary: "#dcaf8a",
        tertiary: "#9fb1a6",
        branch: "Urban",
        folder: "Geometry",
        bytes: 45796,
        type: "min",
      },
      {
        original_file_name: "Cubist Blocks (1).jpg",
        megabytes: 1.1,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#393439",
        primary: "#dfb483",
        tertiary: "#99795c",
        branch: "Urban",
        folder: "Geometry",
        bytes: 1148654,
        type: "max",
      },
      {
        original_file_name: "Cubist Blocks (2).jpg",
        megabytes: 1.14,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#ecd1af",
        primary: "#3d4649",
        tertiary: "#d48452",
        branch: "Urban",
        folder: "Geometry",
        bytes: 1198095,
        type: "max",
      },
      {
        original_file_name: "Cubist Blocks (3).jpg",
        megabytes: 1.02,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#3b464e",
        primary: "#d8a271",
        tertiary: "#eadabd",
        branch: "Urban",
        folder: "Geometry",
        bytes: 1066320,
        type: "max",
      },
      {
        original_file_name: "Cubist Blocks (4).jpg",
        megabytes: 1.03,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#29333c",
        primary: "#dcae89",
        tertiary: "#9fb1a6",
        branch: "Urban",
        folder: "Geometry",
        bytes: 1077075,
        type: "max",
      },
    ]
  },
  "Future Blocks": {
    environment_title: "Future Blocks",
    images: [
      {
        original_file_name: "Future Blocks (1).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#262a41",
        primary: "#c58eb6",
        tertiary: "#795c87",
        branch: "Urban",
        folder: "Geometry",
        bytes: 49920,
        type: "min",
      },
      {
        original_file_name: "Future Blocks (2).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#2a3854",
        primary: "#d598a8",
        tertiary: "#83c0d3",
        branch: "Urban",
        folder: "Geometry",
        bytes: 60828,
        type: "min",
      },
      {
        original_file_name: "Future Blocks (3).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#78bdd8",
        primary: "#c18bbd",
        tertiary: "#283053",
        branch: "Urban",
        folder: "Geometry",
        bytes: 52861,
        type: "min",
      },
      {
        original_file_name: "Future Blocks (4).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#d4a9bf",
        primary: "#2d3854",
        tertiary: "#67b1d1",
        branch: "Urban",
        folder: "Geometry",
        bytes: 51362,
        type: "min",
      },
      {
        original_file_name: "Future Blocks (1).jpg",
        megabytes: 1.47,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#252a41",
        primary: "#c58eb7",
        tertiary: "#6a6890",
        branch: "Urban",
        folder: "Geometry",
        bytes: 1543302,
        type: "max",
      },
      {
        original_file_name: "Future Blocks (2).jpg",
        megabytes: 1.62,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#d697a8",
        primary: "#333d5a",
        tertiary: "#83bfd3",
        branch: "Urban",
        folder: "Geometry",
        bytes: 1696061,
        type: "max",
      },
      {
        original_file_name: "Future Blocks (3).jpg",
        megabytes: 1.6,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#78bdd8",
        primary: "#c28abc",
        tertiary: "#283054",
        branch: "Urban",
        folder: "Geometry",
        bytes: 1673796,
        type: "max",
      },
      {
        original_file_name: "Future Blocks (4).jpg",
        megabytes: 1.52,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#2c3652",
        primary: "#d3a8bd",
        tertiary: "#66b0d1",
        branch: "Urban",
        folder: "Geometry",
        bytes: 1592155,
        type: "max",
      },
    ]
  },
  "Gradual Towers": {
    environment_title: "Gradual Towers",
    images: [
      {
        original_file_name: "Gradual Towers (1).jpg",
        megabytes: 0.02,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#242837",
        primary: "#d4825f",
        tertiary: "#774a4e",
        branch: "Urban",
        folder: "Geometry",
        bytes: 24122,
        type: "min",
      },
      {
        original_file_name: "Gradual Towers (2).jpg",
        megabytes: 0.02,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#212732",
        primary: "#ca947f",
        tertiary: "#69535d",
        branch: "Urban",
        folder: "Geometry",
        bytes: 21420,
        type: "min",
      },
      {
        original_file_name: "Gradual Towers (3).jpg",
        megabytes: 0.02,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#1e1c2d",
        primary: "#ca6b6c",
        tertiary: "#70425b",
        branch: "Urban",
        folder: "Geometry",
        bytes: 21604,
        type: "min",
      },
      {
        original_file_name: "Gradual Towers (4).jpg",
        megabytes: 0.02,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#ae6870",
        primary: "#251f2c",
        tertiary: "#774a5c",
        branch: "Urban",
        folder: "Geometry",
        bytes: 24323,
        type: "min",
      },
      {
        original_file_name: "Gradual Towers (1).jpg",
        megabytes: 0.62,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#252837",
        primary: "#d3815e",
        tertiary: "#774c52",
        branch: "Urban",
        folder: "Geometry",
        bytes: 651990,
        type: "max",
      },
      {
        original_file_name: "Gradual Towers (2).jpg",
        megabytes: 0.55,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#212733",
        primary: "#ca937e",
        tertiary: "#68525d",
        branch: "Urban",
        folder: "Geometry",
        bytes: 578257,
        type: "max",
      },
      {
        original_file_name: "Gradual Towers (3).jpg",
        megabytes: 0.7,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c8686b",
        primary: "#1e1c2d",
        tertiary: "#f4997e",
        branch: "Urban",
        folder: "Geometry",
        bytes: 738640,
        type: "max",
      },
      {
        original_file_name: "Gradual Towers (4).jpg",
        megabytes: 0.78,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#ae676f",
        primary: "#251f2c",
        tertiary: "#784a5d",
        branch: "Urban",
        folder: "Geometry",
        bytes: 814890,
        type: "max",
      },
    ]
  },
  "Iso City": {
    environment_title: "Iso City",
    images: [
      {
        original_file_name: "Iso City (1).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#353d4b",
        primary: "#cc9470",
        tertiary: "#74b1bc",
        branch: "Urban",
        folder: "Geometry",
        bytes: 89053,
        type: "min",
      },
      {
        original_file_name: "Iso City (2).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#35384c",
        primary: "#dea385",
        tertiary: "#66b5a5",
        branch: "Urban",
        folder: "Geometry",
        bytes: 77849,
        type: "min",
      },
      {
        original_file_name: "Iso City (3).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#353849",
        primary: "#d39983",
        tertiary: "#75adaa",
        branch: "Urban",
        folder: "Geometry",
        bytes: 77688,
        type: "min",
      },
      {
        original_file_name: "Iso City (4).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#d6a88c",
        primary: "#46454c",
        tertiary: "#968277",
        branch: "Urban",
        folder: "Geometry",
        bytes: 82909,
        type: "min",
      },
      {
        original_file_name: "Iso City (1).jpg",
        megabytes: 2.38,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#353d4b",
        primary: "#cd946f",
        tertiary: "#73b1bc",
        branch: "Urban",
        folder: "Geometry",
        bytes: 2491175,
        type: "max",
      },
      {
        original_file_name: "Iso City (2).jpg",
        megabytes: 1.93,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#35384c",
        primary: "#dea284",
        tertiary: "#66b5a4",
        branch: "Urban",
        folder: "Geometry",
        bytes: 2027530,
        type: "max",
      },
      {
        original_file_name: "Iso City (3).jpg",
        megabytes: 1.89,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#343849",
        primary: "#d18e76",
        tertiary: "#8e6f6a",
        branch: "Urban",
        folder: "Geometry",
        bytes: 1980797,
        type: "max",
      },
      {
        original_file_name: "Iso City (4).jpg",
        megabytes: 2.22,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#3a404b",
        primary: "#d7aa8f",
        tertiary: "#957e74",
        branch: "Urban",
        folder: "Geometry",
        bytes: 2332078,
        type: "max",
      },
    ]
  },
  "Minimal Skyline": {
    environment_title: "Minimal Skyline",
    images: [
      {
        original_file_name: "Minimal Skyline (1).jpg",
        megabytes: 0.02,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#e4b1ad",
        primary: "#4c5674",
        tertiary: "#a57793",
        branch: "Urban",
        folder: "Geometry",
        bytes: 19782,
        type: "min",
      },
      {
        original_file_name: "Minimal Skyline (2).jpg",
        megabytes: 0.02,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#516883",
        primary: "#d4959d",
        tertiary: "#7c8e9e",
        branch: "Urban",
        folder: "Geometry",
        bytes: 22585,
        type: "min",
      },
      {
        original_file_name: "Minimal Skyline (3).jpg",
        megabytes: 0.02,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#433f51",
        primary: "#d9abad",
        tertiary: "#4c6973",
        branch: "Urban",
        folder: "Geometry",
        bytes: 22823,
        type: "min",
      },
      {
        original_file_name: "Minimal Skyline (4).jpg",
        megabytes: 0.02,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#536784",
        primary: "#deb4ad",
        tertiary: "#899eab",
        branch: "Urban",
        folder: "Geometry",
        bytes: 25395,
        type: "min",
      },
      {
        original_file_name: "Minimal Skyline (1).jpg",
        megabytes: 0.62,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#4c5774",
        primary: "#e5b1ad",
        tertiary: "#92859d",
        branch: "Urban",
        folder: "Geometry",
        bytes: 646497,
        type: "max",
      },
      {
        original_file_name: "Minimal Skyline (2).jpg",
        megabytes: 0.69,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#516a84",
        primary: "#d79ba0",
        tertiary: "#7c8e9d",
        branch: "Urban",
        folder: "Geometry",
        bytes: 728091,
        type: "max",
      },
      {
        original_file_name: "Minimal Skyline (3).jpg",
        megabytes: 0.67,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#d9abae",
        primary: "#415261",
        tertiary: "#789198",
        branch: "Urban",
        folder: "Geometry",
        bytes: 707393,
        type: "max",
      },
      {
        original_file_name: "Minimal Skyline (4).jpg",
        megabytes: 0.69,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#536885",
        primary: "#deb4ad",
        tertiary: "#899eab",
        branch: "Urban",
        folder: "Geometry",
        bytes: 724396,
        type: "max",
      },
    ]
  },
  "Neon Grids": {
    environment_title: "Neon Grids",
    images: [
      {
        original_file_name: "Neon Grids (1).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#120e18",
        primary: "#cb6bb5",
        tertiary: "#653565",
        branch: "Urban",
        folder: "Geometry",
        bytes: 47430,
        type: "min",
      },
      {
        original_file_name: "Neon Grids (2).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#48385e",
        primary: "#0d0b13",
        tertiary: "#29213b",
        branch: "Urban",
        folder: "Geometry",
        bytes: 41918,
        type: "min",
      },
      {
        original_file_name: "Neon Grids (3).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#a476aa",
        primary: "#0e0e19",
        tertiary: "#46436c",
        branch: "Urban",
        folder: "Geometry",
        bytes: 52578,
        type: "min",
      },
      {
        original_file_name: "Neon Grids (4).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#100e16",
        primary: "#ab5d8c",
        tertiary: "#514a6b",
        branch: "Urban",
        folder: "Geometry",
        bytes: 50678,
        type: "min",
      },
      {
        original_file_name: "Neon Grids (1).jpg",
        megabytes: 1.43,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#120e18",
        primary: "#cb6ab5",
        tertiary: "#643565",
        branch: "Urban",
        folder: "Geometry",
        bytes: 1494733,
        type: "max",
      },
      {
        original_file_name: "Neon Grids (2).jpg",
        megabytes: 1.28,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#28203b",
        primary: "#0d0b13",
        tertiary: "#573260",
        branch: "Urban",
        folder: "Geometry",
        bytes: 1345149,
        type: "max",
      },
      {
        original_file_name: "Neon Grids (3).jpg",
        megabytes: 1.74,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#a577ab",
        primary: "#0e0e19",
        tertiary: "#45426c",
        branch: "Urban",
        folder: "Geometry",
        bytes: 1820592,
        type: "max",
      },
      {
        original_file_name: "Neon Grids (4).jpg",
        megabytes: 1.66,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#100e16",
        primary: "#ac5b8b",
        tertiary: "#50496b",
        branch: "Urban",
        folder: "Geometry",
        bytes: 1738144,
        type: "max",
      },
    ]
  },
  "Trapezoid Street": {
    environment_title: "Trapezoid Street",
    images: [
      {
        original_file_name: "Trapezoid Street (1).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#302d3a",
        primary: "#dec4aa",
        tertiary: "#8eb4b3",
        branch: "Urban",
        folder: "Geometry",
        bytes: 38225,
        type: "min",
      },
      {
        original_file_name: "Trapezoid Street (2).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#d3c4a2",
        primary: "#d68460",
        tertiary: "#35323e",
        branch: "Urban",
        folder: "Geometry",
        bytes: 46233,
        type: "min",
      },
      {
        original_file_name: "Trapezoid Street (3).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#2a3a46",
        primary: "#c9b5b2",
        tertiary: "#527b83",
        branch: "Urban",
        folder: "Geometry",
        bytes: 38282,
        type: "min",
      },
      {
        original_file_name: "Trapezoid Street (4).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#2c3642",
        primary: "#d3c5bb",
        tertiary: "#8d545b",
        branch: "Urban",
        folder: "Geometry",
        bytes: 40959,
        type: "min",
      },
      {
        original_file_name: "Trapezoid Street (1).jpg",
        megabytes: 1.01,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#372a37",
        primary: "#d4d2be",
        tertiary: "#ca7962",
        branch: "Urban",
        folder: "Geometry",
        bytes: 1059436,
        type: "max",
      },
      {
        original_file_name: "Trapezoid Street (2).jpg",
        megabytes: 1.18,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#373641",
        primary: "#d1c4a3",
        tertiary: "#d48460",
        branch: "Urban",
        folder: "Geometry",
        bytes: 1238625,
        type: "max",
      },
      {
        original_file_name: "Trapezoid Street (3).jpg",
        megabytes: 0.99,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#2a3b47",
        primary: "#c9b6b4",
        tertiary: "#527b84",
        branch: "Urban",
        folder: "Geometry",
        bytes: 1039786,
        type: "max",
      },
      {
        original_file_name: "Trapezoid Street (4).jpg",
        megabytes: 1.11,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#2c3642",
        primary: "#d3c5bb",
        tertiary: "#8c545a",
        branch: "Urban",
        folder: "Geometry",
        bytes: 1161475,
        type: "max",
      },
    ]
  },
  "Voxel Town": {
    environment_title: "Voxel Town",
    images: [
      {
        original_file_name: "Voxel Town (1).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#e3b59d",
        primary: "#564960",
        tertiary: "#84c6c7",
        branch: "Urban",
        folder: "Geometry",
        bytes: 76561,
        type: "min",
      },
      {
        original_file_name: "Voxel Town (2).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#4f4d6a",
        primary: "#dba99c",
        tertiary: "#92c2bd",
        branch: "Urban",
        folder: "Geometry",
        bytes: 77171,
        type: "min",
      },
      {
        original_file_name: "Voxel Town (3).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#4f4657",
        primary: "#e1ae91",
        tertiary: "#7dc5c3",
        branch: "Urban",
        folder: "Geometry",
        bytes: 80099,
        type: "min",
      },
      {
        original_file_name: "Voxel Town (4).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#e19b88",
        primary: "#66596c",
        tertiary: "#c6cdc8",
        branch: "Urban",
        folder: "Geometry",
        bytes: 77441,
        type: "min",
      },
      {
        original_file_name: "Voxel Town (1).jpg",
        megabytes: 1.91,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#e3b59c",
        primary: "#564961",
        tertiary: "#84c6c8",
        branch: "Urban",
        folder: "Geometry",
        bytes: 1997808,
        type: "max",
      },
      {
        original_file_name: "Voxel Town (2).jpg",
        megabytes: 2.23,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#4f4d6a",
        primary: "#dba99b",
        tertiary: "#92c3bd",
        branch: "Urban",
        folder: "Geometry",
        bytes: 2340925,
        type: "max",
      },
      {
        original_file_name: "Voxel Town (3).jpg",
        megabytes: 2.23,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#e4af91",
        primary: "#51485b",
        tertiary: "#7fc4c3",
        branch: "Urban",
        folder: "Geometry",
        bytes: 2336075,
        type: "max",
      },
      {
        original_file_name: "Voxel Town (4).jpg",
        megabytes: 2.2,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#e19a87",
        primary: "#65596d",
        tertiary: "#c7ccc8",
        branch: "Urban",
        folder: "Geometry",
        bytes: 2305153,
        type: "max",
      },
    ]
  },
};
export default Urban_Geometry;
