import { EnvironmentEntry } from "../types";
const Urban_Cinematic: Record<string, EnvironmentEntry> = {
  "Desert Town": {
    environment_title: "Desert Town",
    images: [
      {
        original_file_name: "Desert Town (1).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#caac90",
        primary: "#617175",
        tertiary: "#232321",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 46429,
        type: "min",
      },
      {
        original_file_name: "Desert Town (2).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#2d231d",
        primary: "#bdbdb4",
        tertiary: "#543a2b",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 51950,
        type: "min",
      },
      {
        original_file_name: "Desert Town (3).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#ac9b85",
        primary: "#332820",
        tertiary: "#cdcfcd",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 54161,
        type: "min",
      },
      {
        original_file_name: "Desert Town (4).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#2d1f17",
        primary: "#a79b89",
        tertiary: "#513725",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 61929,
        type: "min",
      },
      {
        original_file_name: "Desert Town (1).jpg",
        megabytes: 1.89,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#caac90",
        primary: "#617175",
        tertiary: "#232321",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 1985908,
        type: "max",
      },
      {
        original_file_name: "Desert Town (2).jpg",
        megabytes: 2.05,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#543a2b",
        primary: "#bdbdb4",
        tertiary: "#2c231e",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 2145959,
        type: "max",
      },
      {
        original_file_name: "Desert Town (3).jpg",
        megabytes: 2.19,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#ac9b85",
        primary: "#332920",
        tertiary: "#cecfcd",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 2295912,
        type: "max",
      },
      {
        original_file_name: "Desert Town (4).jpg",
        megabytes: 2.28,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#2d1f17",
        primary: "#a69b89",
        tertiary: "#523725",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 2390968,
        type: "max",
      },
    ]
  },
  "Dusk Streets": {
    environment_title: "Dusk Streets",
    images: [
      {
        original_file_name: "Dusk Streets (1).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#2e211b",
        primary: "#be7b47",
        tertiary: "#83502d",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 70433,
        type: "min",
      },
      {
        original_file_name: "Dusk Streets (2).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c17741",
        primary: "#2d201b",
        tertiary: "#8c5b40",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 61709,
        type: "min",
      },
      {
        original_file_name: "Dusk Streets (3).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#251c1c",
        primary: "#c27042",
        tertiary: "#8c5643",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 53501,
        type: "min",
      },
      {
        original_file_name: "Dusk Streets (4).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#281c17",
        primary: "#b9a288",
        tertiary: "#775239",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 60584,
        type: "min",
      },
      {
        original_file_name: "Dusk Streets (1).jpg",
        megabytes: 2.29,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#2f211c",
        primary: "#be7a45",
        tertiary: "#83502c",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 2398092,
        type: "max",
      },
      {
        original_file_name: "Dusk Streets (2).jpg",
        megabytes: 2.13,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c17741",
        primary: "#2d201c",
        tertiary: "#8c5b40",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 2233635,
        type: "max",
      },
      {
        original_file_name: "Dusk Streets (3).jpg",
        megabytes: 1.81,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#251d1c",
        primary: "#c37042",
        tertiary: "#8c5643",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 1900184,
        type: "max",
      },
      {
        original_file_name: "Dusk Streets (4).jpg",
        megabytes: 2.05,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#281c17",
        primary: "#b8a187",
        tertiary: "#775239",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 2150651,
        type: "max",
      },
    ]
  },
  "Foggy Skyline": {
    environment_title: "Foggy Skyline",
    images: [
      {
        original_file_name: "Foggy Skyline (1).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#ae9b95",
        primary: "#373d43",
        tertiary: "#8d8a8a",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 42144,
        type: "min",
      },
      {
        original_file_name: "Foggy Skyline (2).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#35373a",
        primary: "#c1ab90",
        tertiary: "#9a8b7d",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 43306,
        type: "min",
      },
      {
        original_file_name: "Foggy Skyline (3).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c8b5a0",
        primary: "#9b9389",
        tertiary: "#212429",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 32039,
        type: "min",
      },
      {
        original_file_name: "Foggy Skyline (4).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#2d2d30",
        primary: "#c2ae9e",
        tertiary: "#8b8785",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 48532,
        type: "min",
      },
      {
        original_file_name: "Foggy Skyline (1).jpg",
        megabytes: 1.4,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#ad9b95",
        primary: "#373d43",
        tertiary: "#8e8a8a",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 1466225,
        type: "max",
      },
      {
        original_file_name: "Foggy Skyline (2).jpg",
        megabytes: 1.39,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#998b7d",
        primary: "#36373a",
        tertiary: "#c0aa8f",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 1462372,
        type: "max",
      },
      {
        original_file_name: "Foggy Skyline (3).jpg",
        megabytes: 1.19,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c9b6a0",
        primary: "#9b9389",
        tertiary: "#212429",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 1244938,
        type: "max",
      },
      {
        original_file_name: "Foggy Skyline (4).jpg",
        megabytes: 1.44,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#2d2d30",
        primary: "#c2ae9e",
        tertiary: "#8a8785",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 1507551,
        type: "max",
      },
    ]
  },
  "Future Transit": {
    environment_title: "Future Transit",
    images: [
      {
        original_file_name: "Future Transit (1).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#1c2125",
        primary: "#c29c8b",
        tertiary: "#766d69",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 71537,
        type: "min",
      },
      {
        original_file_name: "Future Transit (2).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#161d24",
        primary: "#b58f90",
        tertiary: "#6d6374",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 75800,
        type: "min",
      },
      {
        original_file_name: "Future Transit (3).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#b7b2ba",
        primary: "#151a20",
        tertiary: "#6b6b77",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 75086,
        type: "min",
      },
      {
        original_file_name: "Future Transit (4).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#181a21",
        primary: "#b6938d",
        tertiary: "#5d6472",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 79545,
        type: "min",
      },
      {
        original_file_name: "Future Transit (1).jpg",
        megabytes: 2.18,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#1c2226",
        primary: "#c29b89",
        tertiary: "#756d69",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 2287697,
        type: "max",
      },
      {
        original_file_name: "Future Transit (2).jpg",
        megabytes: 2.36,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#161d25",
        primary: "#b58d8e",
        tertiary: "#6d6474",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 2470056,
        type: "max",
      },
      {
        original_file_name: "Future Transit (3).jpg",
        megabytes: 1.89,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#b7b1b9",
        primary: "#151a21",
        tertiary: "#6b6a77",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 1979990,
        type: "max",
      },
      {
        original_file_name: "Future Transit (4).jpg",
        megabytes: 2.27,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#181a21",
        primary: "#b6928d",
        tertiary: "#5d6573",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 2376146,
        type: "max",
      },
    ]
  },
  "Misty Outskirts": {
    environment_title: "Misty Outskirts",
    images: [
      {
        original_file_name: "Misty Outskirts (1).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#7f8991",
        primary: "#1e2529",
        tertiary: "#b8aea0",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 63475,
        type: "min",
      },
      {
        original_file_name: "Misty Outskirts (2).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#677b88",
        primary: "#24292d",
        tertiary: "#bfa07b",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 40971,
        type: "min",
      },
      {
        original_file_name: "Misty Outskirts (3).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#be8c60",
        primary: "#282a2c",
        tertiary: "#79736c",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 43545,
        type: "min",
      },
      {
        original_file_name: "Misty Outskirts (4).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c5a26f",
        primary: "#475055",
        tertiary: "#131418",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 51219,
        type: "min",
      },
      {
        original_file_name: "Misty Outskirts (1).jpg",
        megabytes: 2.47,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#7f8991",
        primary: "#1e2529",
        tertiary: "#b9aea1",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 2589352,
        type: "max",
      },
      {
        original_file_name: "Misty Outskirts (2).jpg",
        megabytes: 1.55,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#677b88",
        primary: "#24292d",
        tertiary: "#c0a07c",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 1626325,
        type: "max",
      },
      {
        original_file_name: "Misty Outskirts (3).jpg",
        megabytes: 1.6,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#be8c60",
        primary: "#282a2c",
        tertiary: "#79736b",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 1673852,
        type: "max",
      },
      {
        original_file_name: "Misty Outskirts (4).jpg",
        megabytes: 2.01,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c5a270",
        primary: "#475055",
        tertiary: "#131418",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 2111063,
        type: "max",
      },
    ]
  },
  "Neon Alley": {
    environment_title: "Neon Alley",
    images: [
      {
        original_file_name: "Neon Alley (1).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#170f1e",
        primary: "#b776a5",
        tertiary: "#21456a",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 51561,
        type: "min",
      },
      {
        original_file_name: "Neon Alley (2).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#10101a",
        primary: "#b24b91",
        tertiary: "#37416c",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 56823,
        type: "min",
      },
      {
        original_file_name: "Neon Alley (3).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#2a4d75",
        primary: "#161321",
        tertiary: "#b287a8",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 62628,
        type: "min",
      },
      {
        original_file_name: "Neon Alley (4).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#1a1523",
        primary: "#bb3e7a",
        tertiary: "#354e74",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 64865,
        type: "min",
      },
      {
        original_file_name: "Neon Alley (1).jpg",
        megabytes: 2.11,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#b676a4",
        primary: "#17101f",
        tertiary: "#21446a",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 2211504,
        type: "max",
      },
      {
        original_file_name: "Neon Alley (2).jpg",
        megabytes: 1.99,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#10101a",
        primary: "#b34c92",
        tertiary: "#36416c",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 2090013,
        type: "max",
      },
      {
        original_file_name: "Neon Alley (3).jpg",
        megabytes: 2.2,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#294d75",
        primary: "#161421",
        tertiary: "#b286a7",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 2307645,
        type: "max",
      },
      {
        original_file_name: "Neon Alley (4).jpg",
        megabytes: 2.25,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#1a1523",
        primary: "#bb3e7a",
        tertiary: "#334e74",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 2355075,
        type: "max",
      },
    ]
  },
  "Night Bridge": {
    environment_title: "Night Bridge",
    images: [
      {
        original_file_name: "Night Bridge (1).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#0f0e14",
        primary: "#be8d54",
        tertiary: "#694021",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 49536,
        type: "min",
      },
      {
        original_file_name: "Night Bridge (2).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#151011",
        primary: "#bd8830",
        tertiary: "#70491b",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 57910,
        type: "min",
      },
      {
        original_file_name: "Night Bridge (3).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#181619",
        primary: "#bb7923",
        tertiary: "#663c17",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 57849,
        type: "min",
      },
      {
        original_file_name: "Night Bridge (4).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#121013",
        primary: "#bd7522",
        tertiary: "#6c411b",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 60266,
        type: "min",
      },
      {
        original_file_name: "Night Bridge (1).jpg",
        megabytes: 1.45,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#0f0f14",
        primary: "#be8d52",
        tertiary: "#694021",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 1516376,
        type: "max",
      },
      {
        original_file_name: "Night Bridge (2).jpg",
        megabytes: 1.63,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#151011",
        primary: "#be882d",
        tertiary: "#704819",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 1705798,
        type: "max",
      },
      {
        original_file_name: "Night Bridge (3).jpg",
        megabytes: 1.71,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#18161a",
        primary: "#c17c21",
        tertiary: "#693f18",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 1788274,
        type: "max",
      },
      {
        original_file_name: "Night Bridge (4).jpg",
        megabytes: 1.87,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#121014",
        primary: "#bd7420",
        tertiary: "#6c4019",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 1956257,
        type: "max",
      },
    ]
  },
  "Rainy Neon": {
    environment_title: "Rainy Neon",
    images: [
      {
        original_file_name: "Rainy Neon (1).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#b06f70",
        primary: "#15181d",
        tertiary: "#4e6f73",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 62874,
        type: "min",
      },
      {
        original_file_name: "Rainy Neon (2).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#bca6ac",
        primary: "#1a1b22",
        tertiary: "#6b4751",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 67011,
        type: "min",
      },
      {
        original_file_name: "Rainy Neon (3).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#14141b",
        primary: "#b4677e",
        tertiary: "#6e3b4f",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 63414,
        type: "min",
      },
      {
        original_file_name: "Rainy Neon (4).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#16151e",
        primary: "#ae94a1",
        tertiary: "#6aaeb9",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 63325,
        type: "min",
      },
      {
        original_file_name: "Rainy Neon (1).jpg",
        megabytes: 1.84,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#b06e6f",
        primary: "#15181d",
        tertiary: "#6ea5a8",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 1928249,
        type: "max",
      },
      {
        original_file_name: "Rainy Neon (2).jpg",
        megabytes: 2.02,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#bda6ac",
        primary: "#1b1c22",
        tertiary: "#6b4650",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 2118526,
        type: "max",
      },
      {
        original_file_name: "Rainy Neon (3).jpg",
        megabytes: 2.31,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#14141b",
        primary: "#b4657d",
        tertiary: "#6e3b4e",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 2426996,
        type: "max",
      },
      {
        original_file_name: "Rainy Neon (4).jpg",
        megabytes: 1.88,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#17151e",
        primary: "#b093a0",
        tertiary: "#6aafba",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 1968568,
        type: "max",
      },
    ]
  },
  "Shadow Corner": {
    environment_title: "Shadow Corner",
    images: [
      {
        original_file_name: "Shadow Corner (1).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#cf9c72",
        primary: "#180f0b",
        tertiary: "#6e462d",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 44255,
        type: "min",
      },
      {
        original_file_name: "Shadow Corner (2).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#131111",
        primary: "#c49f7d",
        tertiary: "#624836",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 41618,
        type: "min",
      },
      {
        original_file_name: "Shadow Corner (3).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#cc9c73",
        primary: "#131010",
        tertiary: "#68442f",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 35320,
        type: "min",
      },
      {
        original_file_name: "Shadow Corner (4).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#100e0f",
        primary: "#ad6c3c",
        tertiary: "#64371e",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 36916,
        type: "min",
      },
      {
        original_file_name: "Shadow Corner (1).jpg",
        megabytes: 1.64,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#180f0b",
        primary: "#cf9c71",
        tertiary: "#6e472d",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 1717078,
        type: "max",
      },
      {
        original_file_name: "Shadow Corner (2).jpg",
        megabytes: 1.6,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#131010",
        primary: "#c29e7e",
        tertiary: "#614635",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 1679598,
        type: "max",
      },
      {
        original_file_name: "Shadow Corner (3).jpg",
        megabytes: 1.22,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#cc9c72",
        primary: "#131010",
        tertiary: "#67422c",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 1279489,
        type: "max",
      },
      {
        original_file_name: "Shadow Corner (4).jpg",
        megabytes: 1.36,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#110e0e",
        primary: "#ad6c3b",
        tertiary: "#64361d",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 1421076,
        type: "max",
      },
    ]
  },
  "Thunder City": {
    environment_title: "Thunder City",
    images: [
      {
        original_file_name: "Thunder City (1).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c2a49e",
        primary: "#27292f",
        tertiary: "#776066",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 43897,
        type: "min",
      },
      {
        original_file_name: "Thunder City (2).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#1f2327",
        primary: "#b89f9d",
        tertiary: "#726672",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 52256,
        type: "min",
      },
      {
        original_file_name: "Thunder City (3).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#222329",
        primary: "#bb9d93",
        tertiary: "#7a625e",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 53765,
        type: "min",
      },
      {
        original_file_name: "Thunder City (4).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#222429",
        primary: "#b9a6a0",
        tertiary: "#786a70",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 55879,
        type: "min",
      },
      {
        original_file_name: "Thunder City (1).jpg",
        megabytes: 1.22,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c2a49e",
        primary: "#27292f",
        tertiary: "#776066",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 1283117,
        type: "max",
      },
      {
        original_file_name: "Thunder City (2).jpg",
        megabytes: 1.48,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#1f2327",
        primary: "#b99f9d",
        tertiary: "#726672",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 1556236,
        type: "max",
      },
      {
        original_file_name: "Thunder City (3).jpg",
        megabytes: 1.46,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#222329",
        primary: "#bb9d92",
        tertiary: "#7a625e",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 1526258,
        type: "max",
      },
      {
        original_file_name: "Thunder City (4).jpg",
        megabytes: 1.63,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#b9a59f",
        primary: "#27272b",
        tertiary: "#776970",
        branch: "Urban",
        folder: "Cinematic",
        bytes: 1710036,
        type: "max",
      },
    ]
  },
};
export default Urban_Cinematic;
