import { EnvironmentEntry } from "../types";
const Wonders_Anime: Record<string, EnvironmentEntry> = {
  "Aurora Lake": {
    environment_title: "Aurora Lake",
    images: [
      {
        original_file_name: "Aurora Lake (1).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#233450",
        primary: "#d9a2a9",
        tertiary: "#50d0a8",
        branch: "Wonders",
        folder: "Anime",
        bytes: 62621,
        type: "min",
      },
      {
        original_file_name: "Aurora Lake (2).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#243559",
        primary: "#cca9be",
        tertiary: "#40c9b3",
        branch: "Wonders",
        folder: "Anime",
        bytes: 52355,
        type: "min",
      },
      {
        original_file_name: "Aurora Lake (3).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#cbb3b1",
        primary: "#1f2e4d",
        tertiary: "#48ca8a",
        branch: "Wonders",
        folder: "Anime",
        bytes: 48335,
        type: "min",
      },
      {
        original_file_name: "Aurora Lake (4).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c491aa",
        primary: "#22344f",
        tertiary: "#40dbae",
        branch: "Wonders",
        folder: "Anime",
        bytes: 51880,
        type: "min",
      },
      {
        original_file_name: "Aurora Lake (1).jpg",
        megabytes: 1.65,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#233450",
        primary: "#daa1a9",
        tertiary: "#50d0a9",
        branch: "Wonders",
        folder: "Anime",
        bytes: 1725701,
        type: "max",
      },
      {
        original_file_name: "Aurora Lake (2).jpg",
        megabytes: 1.56,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#243559",
        primary: "#cca9be",
        tertiary: "#40c9b4",
        branch: "Wonders",
        folder: "Anime",
        bytes: 1639017,
        type: "max",
      },
      {
        original_file_name: "Aurora Lake (3).jpg",
        megabytes: 1.47,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#cbb3b1",
        primary: "#1f2e4d",
        tertiary: "#49ca8a",
        branch: "Wonders",
        folder: "Anime",
        bytes: 1536261,
        type: "max",
      },
      {
        original_file_name: "Aurora Lake (4).jpg",
        megabytes: 1.55,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c592ab",
        primary: "#233550",
        tertiary: "#40dbae",
        branch: "Wonders",
        folder: "Anime",
        bytes: 1625397,
        type: "max",
      },
    ]
  },
  "Blossom Ridge": {
    environment_title: "Blossom Ridge",
    images: [
      {
        original_file_name: "Blossom Ridge (1).jpg",
        megabytes: 0.09,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#2a3740",
        primary: "#cc8f99",
        tertiary: "#585f7f",
        branch: "Wonders",
        folder: "Anime",
        bytes: 98641,
        type: "min",
      },
      {
        original_file_name: "Blossom Ridge (2).jpg",
        megabytes: 0.11,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#e6a7a1",
        primary: "#574c69",
        tertiary: "#a6718a",
        branch: "Wonders",
        folder: "Anime",
        bytes: 110815,
        type: "min",
      },
      {
        original_file_name: "Blossom Ridge (3).jpg",
        megabytes: 0.09,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#d69da5",
        primary: "#2c3343",
        tertiary: "#586a96",
        branch: "Wonders",
        folder: "Anime",
        bytes: 93436,
        type: "min",
      },
      {
        original_file_name: "Blossom Ridge (4).jpg",
        megabytes: 0.11,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#313448",
        primary: "#81607e",
        tertiary: "#e9d4d1",
        branch: "Wonders",
        folder: "Anime",
        bytes: 112616,
        type: "min",
      },
      {
        original_file_name: "Blossom Ridge (1).jpg",
        megabytes: 2.32,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#2a3841",
        primary: "#cd8f99",
        tertiary: "#585f80",
        branch: "Wonders",
        folder: "Anime",
        bytes: 2435197,
        type: "max",
      },
      {
        original_file_name: "Blossom Ridge (2).jpg",
        megabytes: 2.55,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#e7a7a0",
        primary: "#574c6a",
        tertiary: "#a6708a",
        branch: "Wonders",
        folder: "Anime",
        bytes: 2671241,
        type: "max",
      },
      {
        original_file_name: "Blossom Ridge (3).jpg",
        megabytes: 2.2,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#d79da5",
        primary: "#2c3343",
        tertiary: "#586a96",
        branch: "Wonders",
        folder: "Anime",
        bytes: 2303846,
        type: "max",
      },
      {
        original_file_name: "Blossom Ridge (4).jpg",
        megabytes: 2.56,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#313449",
        primary: "#81617f",
        tertiary: "#e9d4d2",
        branch: "Wonders",
        folder: "Anime",
        bytes: 2688698,
        type: "max",
      },
    ]
  },
  "Bubble Lagoon": {
    environment_title: "Bubble Lagoon",
    images: [
      {
        original_file_name: "Bubble Lagoon (1).jpg",
        megabytes: 0.1,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#21747d",
        primary: "#d1e7d9",
        tertiary: "#6bddd3",
        branch: "Wonders",
        folder: "Anime",
        bytes: 102462,
        type: "min",
      },
      {
        original_file_name: "Bubble Lagoon (2).jpg",
        megabytes: 0.09,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#182f2f",
        primary: "#376e77",
        tertiary: "#cee5ea",
        branch: "Wonders",
        folder: "Anime",
        bytes: 96300,
        type: "min",
      },
      {
        original_file_name: "Bubble Lagoon (3).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#90d3d1",
        primary: "#1a849d",
        tertiary: "#dbe7e0",
        branch: "Wonders",
        folder: "Anime",
        bytes: 77084,
        type: "min",
      },
      {
        original_file_name: "Bubble Lagoon (4).jpg",
        megabytes: 0.09,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#1c7b86",
        primary: "#cde4d8",
        tertiary: "#73dece",
        branch: "Wonders",
        folder: "Anime",
        bytes: 89776,
        type: "min",
      },
      {
        original_file_name: "Bubble Lagoon (1).jpg",
        megabytes: 2.27,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#21747d",
        primary: "#d1e7d8",
        tertiary: "#6addd3",
        branch: "Wonders",
        folder: "Anime",
        bytes: 2377988,
        type: "max",
      },
      {
        original_file_name: "Bubble Lagoon (2).jpg",
        megabytes: 2.12,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#18302f",
        primary: "#376e77",
        tertiary: "#7de1dc",
        branch: "Wonders",
        folder: "Anime",
        bytes: 2227952,
        type: "max",
      },
      {
        original_file_name: "Bubble Lagoon (3).jpg",
        megabytes: 1.73,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#1c8aa1",
        primary: "#dbe7e1",
        tertiary: "#94d5d3",
        branch: "Wonders",
        folder: "Anime",
        bytes: 1818931,
        type: "max",
      },
      {
        original_file_name: "Bubble Lagoon (4).jpg",
        megabytes: 1.99,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#1c7b86",
        primary: "#cee4d8",
        tertiary: "#73dece",
        branch: "Wonders",
        folder: "Anime",
        bytes: 2086972,
        type: "max",
      },
    ]
  },
  "Cloud Shard": {
    environment_title: "Cloud Shard",
    images: [
      {
        original_file_name: "Cloud Shard (1).jpg",
        megabytes: 0.09,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#3a5689",
        primary: "#e9b39b",
        tertiary: "#30242b",
        branch: "Wonders",
        folder: "Anime",
        bytes: 93096,
        type: "min",
      },
      {
        original_file_name: "Cloud Shard (2).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#40547e",
        primary: "#e3ab90",
        tertiary: "#94728a",
        branch: "Wonders",
        folder: "Anime",
        bytes: 86647,
        type: "min",
      },
      {
        original_file_name: "Cloud Shard (3).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#3f4a6f",
        primary: "#e5ac92",
        tertiary: "#956678",
        branch: "Wonders",
        folder: "Anime",
        bytes: 87065,
        type: "min",
      },
      {
        original_file_name: "Cloud Shard (4).jpg",
        megabytes: 0.09,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#3b537d",
        primary: "#e8a687",
        tertiary: "#a46d7a",
        branch: "Wonders",
        folder: "Anime",
        bytes: 89658,
        type: "min",
      },
      {
        original_file_name: "Cloud Shard (1).jpg",
        megabytes: 2.05,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#395689",
        primary: "#eab29a",
        tertiary: "#31242c",
        branch: "Wonders",
        folder: "Anime",
        bytes: 2149591,
        type: "max",
      },
      {
        original_file_name: "Cloud Shard (2).jpg",
        megabytes: 1.98,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#40547f",
        primary: "#e4ab90",
        tertiary: "#94728a",
        branch: "Wonders",
        folder: "Anime",
        bytes: 2074946,
        type: "max",
      },
      {
        original_file_name: "Cloud Shard (3).jpg",
        megabytes: 1.96,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#3f4b70",
        primary: "#e6ab92",
        tertiary: "#956678",
        branch: "Wonders",
        folder: "Anime",
        bytes: 2050076,
        type: "max",
      },
      {
        original_file_name: "Cloud Shard (4).jpg",
        megabytes: 2.0,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#3b537e",
        primary: "#e9a687",
        tertiary: "#a46d7a",
        branch: "Wonders",
        folder: "Anime",
        bytes: 2101162,
        type: "max",
      },
    ]
  },
  "Crystal Cavern": {
    environment_title: "Crystal Cavern",
    images: [
      {
        original_file_name: "Crystal Cavern (1).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#0b1227",
        primary: "#b1e9f6",
        tertiary: "#25517f",
        branch: "Wonders",
        folder: "Anime",
        bytes: 86084,
        type: "min",
      },
      {
        original_file_name: "Crystal Cavern (2).jpg",
        megabytes: 0.09,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#14162f",
        primary: "#d2a9c1",
        tertiary: "#54bce7",
        branch: "Wonders",
        folder: "Anime",
        bytes: 92153,
        type: "min",
      },
      {
        original_file_name: "Crystal Cavern (3).jpg",
        megabytes: 0.09,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#1d1d31",
        primary: "#d4b3ba",
        tertiary: "#67bce5",
        branch: "Wonders",
        folder: "Anime",
        bytes: 95711,
        type: "min",
      },
      {
        original_file_name: "Crystal Cavern (4).jpg",
        megabytes: 0.09,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#11172d",
        primary: "#c8c2c7",
        tertiary: "#5bbbe0",
        branch: "Wonders",
        folder: "Anime",
        bytes: 93323,
        type: "min",
      },
      {
        original_file_name: "Crystal Cavern (1).jpg",
        megabytes: 1.99,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#0b1227",
        primary: "#b2eaf7",
        tertiary: "#24517f",
        branch: "Wonders",
        folder: "Anime",
        bytes: 2084094,
        type: "max",
      },
      {
        original_file_name: "Crystal Cavern (2).jpg",
        megabytes: 2.19,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#14162f",
        primary: "#d0a5be",
        tertiary: "#51bcea",
        branch: "Wonders",
        folder: "Anime",
        bytes: 2294466,
        type: "max",
      },
      {
        original_file_name: "Crystal Cavern (3).jpg",
        megabytes: 2.21,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#1d1d31",
        primary: "#d5b3ba",
        tertiary: "#68bde8",
        branch: "Wonders",
        folder: "Anime",
        bytes: 2319952,
        type: "max",
      },
      {
        original_file_name: "Crystal Cavern (4).jpg",
        megabytes: 2.17,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#11172d",
        primary: "#c9c2c7",
        tertiary: "#5abce3",
        branch: "Wonders",
        folder: "Anime",
        bytes: 2276118,
        type: "max",
      },
    ]
  },
  "Crystal Sands": {
    environment_title: "Crystal Sands",
    images: [
      {
        original_file_name: "Crystal Sands (1).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#4d67a4",
        primary: "#efccad",
        tertiary: "#8e7b9b",
        branch: "Wonders",
        folder: "Anime",
        bytes: 76810,
        type: "min",
      },
      {
        original_file_name: "Crystal Sands (2).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#f2e3cd",
        primary: "#7c749a",
        tertiary: "#e5ae95",
        branch: "Wonders",
        folder: "Anime",
        bytes: 64474,
        type: "min",
      },
      {
        original_file_name: "Crystal Sands (3).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#e9d2c0",
        primary: "#485d92",
        tertiary: "#806e89",
        branch: "Wonders",
        folder: "Anime",
        bytes: 83935,
        type: "min",
      },
      {
        original_file_name: "Crystal Sands (4).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#e7b99f",
        primary: "#775464",
        tertiary: "#457bb1",
        branch: "Wonders",
        folder: "Anime",
        bytes: 66737,
        type: "min",
      },
      {
        original_file_name: "Crystal Sands (1).jpg",
        megabytes: 1.98,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#4d67a6",
        primary: "#efccad",
        tertiary: "#8e7b9b",
        branch: "Wonders",
        folder: "Anime",
        bytes: 2079035,
        type: "max",
      },
      {
        original_file_name: "Crystal Sands (2).jpg",
        megabytes: 1.74,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#f2e3cd",
        primary: "#79739a",
        tertiary: "#e5ae95",
        branch: "Wonders",
        folder: "Anime",
        bytes: 1828689,
        type: "max",
      },
      {
        original_file_name: "Crystal Sands (3).jpg",
        megabytes: 2.08,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#e9d2c0",
        primary: "#485e93",
        tertiary: "#806d89",
        branch: "Wonders",
        folder: "Anime",
        bytes: 2176626,
        type: "max",
      },
      {
        original_file_name: "Crystal Sands (4).jpg",
        megabytes: 1.78,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#e7b99f",
        primary: "#765464",
        tertiary: "#467cb2",
        branch: "Wonders",
        folder: "Anime",
        bytes: 1871399,
        type: "max",
      },
    ]
  },
  "Floating Isle": {
    environment_title: "Floating Isle",
    images: [
      {
        original_file_name: "Floating Isle (1).jpg",
        megabytes: 0.09,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#354e4d",
        primary: "#d0dbc3",
        tertiary: "#82c6d9",
        branch: "Wonders",
        folder: "Anime",
        bytes: 93183,
        type: "min",
      },
      {
        original_file_name: "Floating Isle (2).jpg",
        megabytes: 0.09,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#356486",
        primary: "#dbe4d9",
        tertiary: "#97b5c2",
        branch: "Wonders",
        folder: "Anime",
        bytes: 97276,
        type: "min",
      },
      {
        original_file_name: "Floating Isle (3).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#2f4a3d",
        primary: "#dbddd5",
        tertiary: "#4796cd",
        branch: "Wonders",
        folder: "Anime",
        bytes: 88012,
        type: "min",
      },
      {
        original_file_name: "Floating Isle (4).jpg",
        megabytes: 0.09,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#569ce0",
        primary: "#dad9c5",
        tertiary: "#526474",
        branch: "Wonders",
        folder: "Anime",
        bytes: 94372,
        type: "min",
      },
      {
        original_file_name: "Floating Isle (1).jpg",
        megabytes: 2.14,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#354e4e",
        primary: "#d1dbc2",
        tertiary: "#81c6d9",
        branch: "Wonders",
        folder: "Anime",
        bytes: 2244323,
        type: "max",
      },
      {
        original_file_name: "Floating Isle (2).jpg",
        megabytes: 2.14,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#32658a",
        primary: "#dce5e2",
        tertiary: "#a0c2cf",
        branch: "Wonders",
        folder: "Anime",
        bytes: 2246142,
        type: "max",
      },
      {
        original_file_name: "Floating Isle (3).jpg",
        megabytes: 2.02,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#2f4b3e",
        primary: "#dcddd6",
        tertiary: "#4696cd",
        branch: "Wonders",
        folder: "Anime",
        bytes: 2118979,
        type: "max",
      },
      {
        original_file_name: "Floating Isle (4).jpg",
        megabytes: 2.12,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#569ce1",
        primary: "#dbd9c5",
        tertiary: "#526474",
        branch: "Wonders",
        folder: "Anime",
        bytes: 2221930,
        type: "max",
      },
    ]
  },
  "Magma Falls": {
    environment_title: "Magma Falls",
    images: [
      {
        original_file_name: "Magma Falls (1).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#2b1922",
        primary: "#df572c",
        tertiary: "#8a2e29",
        branch: "Wonders",
        folder: "Anime",
        bytes: 67192,
        type: "min",
      },
      {
        original_file_name: "Magma Falls (2).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#2d1920",
        primary: "#da5a2d",
        tertiary: "#873026",
        branch: "Wonders",
        folder: "Anime",
        bytes: 71035,
        type: "min",
      },
      {
        original_file_name: "Magma Falls (3).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#2c1a20",
        primary: "#da532d",
        tertiary: "#892e29",
        branch: "Wonders",
        folder: "Anime",
        bytes: 76123,
        type: "min",
      },
      {
        original_file_name: "Magma Falls (4).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#36252f",
        primary: "#da4920",
        tertiary: "#8d3028",
        branch: "Wonders",
        folder: "Anime",
        bytes: 71409,
        type: "min",
      },
      {
        original_file_name: "Magma Falls (1).jpg",
        megabytes: 1.74,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#2b1a24",
        primary: "#e0562b",
        tertiary: "#8a2e2a",
        branch: "Wonders",
        folder: "Anime",
        bytes: 1828803,
        type: "max",
      },
      {
        original_file_name: "Magma Falls (2).jpg",
        megabytes: 1.78,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#2d1920",
        primary: "#db5a2c",
        tertiary: "#873026",
        branch: "Wonders",
        folder: "Anime",
        bytes: 1863431,
        type: "max",
      },
      {
        original_file_name: "Magma Falls (3).jpg",
        megabytes: 1.82,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#2c1a20",
        primary: "#da522c",
        tertiary: "#892e28",
        branch: "Wonders",
        folder: "Anime",
        bytes: 1905257,
        type: "max",
      },
      {
        original_file_name: "Magma Falls (4).jpg",
        megabytes: 1.81,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#362530",
        primary: "#db481f",
        tertiary: "#8d3028",
        branch: "Wonders",
        folder: "Anime",
        bytes: 1899573,
        type: "max",
      },
    ]
  },
  "Moonlit Tide": {
    environment_title: "Moonlit Tide",
    images: [
      {
        original_file_name: "Moonlit Tide (1).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#2a3662",
        primary: "#e2c8e5",
        tertiary: "#8c849b",
        branch: "Wonders",
        folder: "Anime",
        bytes: 65710,
        type: "min",
      },
      {
        original_file_name: "Moonlit Tide (2).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#333c67",
        primary: "#d8abb1",
        tertiary: "#867491",
        branch: "Wonders",
        folder: "Anime",
        bytes: 68956,
        type: "min",
      },
      {
        original_file_name: "Moonlit Tide (3).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#dbd3e4",
        primary: "#353f68",
        tertiary: "#9d8496",
        branch: "Wonders",
        folder: "Anime",
        bytes: 65394,
        type: "min",
      },
      {
        original_file_name: "Moonlit Tide (1).jpg",
        megabytes: 1.93,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#2a3662",
        primary: "#e2c8e5",
        tertiary: "#8c839b",
        branch: "Wonders",
        folder: "Anime",
        bytes: 2023034,
        type: "max",
      },
      {
        original_file_name: "Moonlit Tide (2).jpg",
        megabytes: 1.91,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#2f3862",
        primary: "#d8abb1",
        tertiary: "#867491",
        branch: "Wonders",
        folder: "Anime",
        bytes: 2005902,
        type: "max",
      },
      {
        original_file_name: "Moonlit Tide (3).jpg",
        megabytes: 1.77,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#dbd2e3",
        primary: "#353f68",
        tertiary: "#9c8495",
        branch: "Wonders",
        folder: "Anime",
        bytes: 1852529,
        type: "max",
      },
    ]
  },
  "Pastel Desert": {
    environment_title: "Pastel Desert",
    images: [
      {
        original_file_name: "Pastel Desert (1).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#926c79",
        primary: "#fbc594",
        tertiary: "#f4ab7b",
        branch: "Wonders",
        folder: "Anime",
        bytes: 44517,
        type: "min",
      },
      {
        original_file_name: "Pastel Desert (2).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#ebd2c6",
        primary: "#65444b",
        tertiary: "#d6926a",
        branch: "Wonders",
        folder: "Anime",
        bytes: 35157,
        type: "min",
      },
      {
        original_file_name: "Pastel Desert (3).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#76575a",
        primary: "#efc29c",
        tertiary: "#8e6666",
        branch: "Wonders",
        folder: "Anime",
        bytes: 47678,
        type: "min",
      },
      {
        original_file_name: "Pastel Desert (4).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#f8cfa9",
        primary: "#735350",
        tertiary: "#e09f71",
        branch: "Wonders",
        folder: "Anime",
        bytes: 38320,
        type: "min",
      },
      {
        original_file_name: "Pastel Desert (1).jpg",
        megabytes: 1.3,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#926c79",
        primary: "#fbc594",
        tertiary: "#f5ab7b",
        branch: "Wonders",
        folder: "Anime",
        bytes: 1362148,
        type: "max",
      },
      {
        original_file_name: "Pastel Desert (2).jpg",
        megabytes: 1.26,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#da976e",
        primary: "#65444b",
        tertiary: "#ebd1c6",
        branch: "Wonders",
        folder: "Anime",
        bytes: 1317448,
        type: "max",
      },
      {
        original_file_name: "Pastel Desert (3).jpg",
        megabytes: 1.42,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#f0c49c",
        primary: "#745256",
        tertiary: "#7d5d5e",
        branch: "Wonders",
        folder: "Anime",
        bytes: 1490815,
        type: "max",
      },
      {
        original_file_name: "Pastel Desert (4).jpg",
        megabytes: 1.32,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#f9cfa9",
        primary: "#735350",
        tertiary: "#e0a073",
        branch: "Wonders",
        folder: "Anime",
        bytes: 1382747,
        type: "max",
      },
    ]
  },
  "Sakura Valley": {
    environment_title: "Sakura Valley",
    images: [
      {
        original_file_name: "Sakura Valley (1).jpg",
        megabytes: 0.12,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#344140",
        primary: "#ddbec8",
        tertiary: "#5f738e",
        branch: "Wonders",
        folder: "Anime",
        bytes: 120727,
        type: "min",
      },
      {
        original_file_name: "Sakura Valley (2).jpg",
        megabytes: 0.12,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#ae8488",
        primary: "#395249",
        tertiary: "#e0d5de",
        branch: "Wonders",
        folder: "Anime",
        bytes: 124498,
        type: "min",
      },
      {
        original_file_name: "Sakura Valley (3).jpg",
        megabytes: 0.12,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#314940",
        primary: "#877081",
        tertiary: "#e5e0d1",
        branch: "Wonders",
        folder: "Anime",
        bytes: 124262,
        type: "min",
      },
      {
        original_file_name: "Sakura Valley (4).jpg",
        megabytes: 0.12,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#335453",
        primary: "#decbcc",
        tertiary: "#638a95",
        branch: "Wonders",
        folder: "Anime",
        bytes: 120648,
        type: "min",
      },
      {
        original_file_name: "Sakura Valley (1).jpg",
        megabytes: 2.68,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#344240",
        primary: "#e1bfc9",
        tertiary: "#5f738f",
        branch: "Wonders",
        folder: "Anime",
        bytes: 2812256,
        type: "max",
      },
      {
        original_file_name: "Sakura Valley (2).jpg",
        megabytes: 2.76,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#ae8487",
        primary: "#39534a",
        tertiary: "#dfd5de",
        branch: "Wonders",
        folder: "Anime",
        bytes: 2895140,
        type: "max",
      },
      {
        original_file_name: "Sakura Valley (3).jpg",
        megabytes: 2.77,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#314a40",
        primary: "#807a7f",
        tertiary: "#e5e0d1",
        branch: "Wonders",
        folder: "Anime",
        bytes: 2905575,
        type: "max",
      },
      {
        original_file_name: "Sakura Valley (4).jpg",
        megabytes: 2.71,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#335553",
        primary: "#dfcbcd",
        tertiary: "#638a96",
        branch: "Wonders",
        folder: "Anime",
        bytes: 2846170,
        type: "max",
      },
    ]
  },
  "Sky Springs": {
    environment_title: "Sky Springs",
    images: [
      {
        original_file_name: "Sky Springs (1).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#38586a",
        primary: "#d9d4c8",
        tertiary: "#84cadb",
        branch: "Wonders",
        folder: "Anime",
        bytes: 83860,
        type: "min",
      },
      {
        original_file_name: "Sky Springs (2).jpg",
        megabytes: 0.09,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#d6d9cc",
        primary: "#3a4e53",
        tertiary: "#9bd5d1",
        branch: "Wonders",
        folder: "Anime",
        bytes: 93362,
        type: "min",
      },
      {
        original_file_name: "Sky Springs (3).jpg",
        megabytes: 0.09,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#27373b",
        primary: "#dcdec1",
        tertiary: "#a0c7ba",
        branch: "Wonders",
        folder: "Anime",
        bytes: 94428,
        type: "min",
      },
      {
        original_file_name: "Sky Springs (4).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#2c3a54",
        primary: "#d39f98",
        tertiary: "#79d1dc",
        branch: "Wonders",
        folder: "Anime",
        bytes: 77924,
        type: "min",
      },
      {
        original_file_name: "Sky Springs (1).jpg",
        megabytes: 1.97,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#38586b",
        primary: "#d9d3c7",
        tertiary: "#84cadc",
        branch: "Wonders",
        folder: "Anime",
        bytes: 2062657,
        type: "max",
      },
      {
        original_file_name: "Sky Springs (2).jpg",
        megabytes: 2.19,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#d6d9cb",
        primary: "#3a4e53",
        tertiary: "#9bd5d2",
        branch: "Wonders",
        folder: "Anime",
        bytes: 2295863,
        type: "max",
      },
      {
        original_file_name: "Sky Springs (3).jpg",
        megabytes: 2.19,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#27373b",
        primary: "#dcddbf",
        tertiary: "#a0c8bb",
        branch: "Wonders",
        folder: "Anime",
        bytes: 2292886,
        type: "max",
      },
      {
        original_file_name: "Sky Springs (4).jpg",
        megabytes: 1.88,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#2c3a54",
        primary: "#d49f97",
        tertiary: "#79d2dc",
        branch: "Wonders",
        folder: "Anime",
        bytes: 1975265,
        type: "max",
      },
    ]
  },
  "Spirit Falls": {
    environment_title: "Spirit Falls",
    images: [
      {
        original_file_name: "Spirit Falls (1).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#cfebec",
        primary: "#2d3f49",
        tertiary: "#72c0d5",
        branch: "Wonders",
        folder: "Anime",
        bytes: 64705,
        type: "min",
      },
      {
        original_file_name: "Spirit Falls (2).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#71bfbc",
        primary: "#192b34",
        tertiary: "#b5ecc9",
        branch: "Wonders",
        folder: "Anime",
        bytes: 71423,
        type: "min",
      },
      {
        original_file_name: "Spirit Falls (3).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#71c3d7",
        primary: "#24313d",
        tertiary: "#b7dfe2",
        branch: "Wonders",
        folder: "Anime",
        bytes: 69414,
        type: "min",
      },
      {
        original_file_name: "Spirit Falls (4).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#76c8e4",
        primary: "#213746",
        tertiary: "#5393b7",
        branch: "Wonders",
        folder: "Anime",
        bytes: 70795,
        type: "min",
      },
      {
        original_file_name: "Spirit Falls (1).jpg",
        megabytes: 1.89,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#cfebed",
        primary: "#2d3f49",
        tertiary: "#72c0d6",
        branch: "Wonders",
        folder: "Anime",
        bytes: 1983349,
        type: "max",
      },
      {
        original_file_name: "Spirit Falls (2).jpg",
        megabytes: 1.93,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#71bfbd",
        primary: "#192b35",
        tertiary: "#b6edc9",
        branch: "Wonders",
        folder: "Anime",
        bytes: 2026103,
        type: "max",
      },
      {
        original_file_name: "Spirit Falls (3).jpg",
        megabytes: 1.88,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#71c3d7",
        primary: "#24313d",
        tertiary: "#b7dfe2",
        branch: "Wonders",
        folder: "Anime",
        bytes: 1969560,
        type: "max",
      },
      {
        original_file_name: "Spirit Falls (4).jpg",
        megabytes: 1.94,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#75c8e4",
        primary: "#213746",
        tertiary: "#5292b6",
        branch: "Wonders",
        folder: "Anime",
        bytes: 2037507,
        type: "max",
      },
    ]
  },
  "Spirit Grove": {
    environment_title: "Spirit Grove",
    images: [
      {
        original_file_name: "Spirit Grove (1).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#262e3d",
        primary: "#d76967",
        tertiary: "#46c094",
        branch: "Wonders",
        folder: "Anime",
        bytes: 85735,
        type: "min",
      },
      {
        original_file_name: "Spirit Grove (2).jpg",
        megabytes: 0.09,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#262e35",
        primary: "#d6c4a2",
        tertiary: "#77b79f",
        branch: "Wonders",
        folder: "Anime",
        bytes: 93235,
        type: "min",
      },
      {
        original_file_name: "Spirit Grove (3).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#d0769d",
        primary: "#243545",
        tertiary: "#456c8a",
        branch: "Wonders",
        folder: "Anime",
        bytes: 87943,
        type: "min",
      },
      {
        original_file_name: "Spirit Grove (4).jpg",
        megabytes: 0.09,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#d5a189",
        primary: "#223146",
        tertiary: "#38658c",
        branch: "Wonders",
        folder: "Anime",
        bytes: 90672,
        type: "min",
      },
      {
        original_file_name: "Spirit Grove (1).jpg",
        megabytes: 2.01,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#262e3d",
        primary: "#d86866",
        tertiary: "#45c294",
        branch: "Wonders",
        folder: "Anime",
        bytes: 2103578,
        type: "max",
      },
      {
        original_file_name: "Spirit Grove (2).jpg",
        megabytes: 2.08,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#262e35",
        primary: "#d7c4a2",
        tertiary: "#77b79e",
        branch: "Wonders",
        folder: "Anime",
        bytes: 2177103,
        type: "max",
      },
      {
        original_file_name: "Spirit Grove (3).jpg",
        megabytes: 2.05,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#d1769d",
        primary: "#243545",
        tertiary: "#446c8a",
        branch: "Wonders",
        folder: "Anime",
        bytes: 2148879,
        type: "max",
      },
      {
        original_file_name: "Spirit Grove (4).jpg",
        megabytes: 2.1,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#d6a189",
        primary: "#223146",
        tertiary: "#37658c",
        branch: "Wonders",
        folder: "Anime",
        bytes: 2197505,
        type: "max",
      },
    ]
  },
};
export default Wonders_Anime;
