import { EnvironmentEntry } from "../types";
const Wonders_Realism: Record<string, EnvironmentEntry> = {
  "Bioluminescent Bay": {
    environment_title: "Bioluminescent Bay",
    images: [
      {
        original_file_name: "Bioluminescent Bay (1).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#191e25",
        primary: "#c3a9a6",
        tertiary: "#63758a",
        branch: "Wonders",
        folder: "Realism",
        bytes: 42312,
        type: "min",
      },
      {
        original_file_name: "Bioluminescent Bay (2).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#60b4c7",
        primary: "#151f29",
        tertiary: "#3a6983",
        branch: "Wonders",
        folder: "Realism",
        bytes: 48407,
        type: "min",
      },
      {
        original_file_name: "Bioluminescent Bay (3).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c29071",
        primary: "#223341",
        tertiary: "#396680",
        branch: "Wonders",
        folder: "Realism",
        bytes: 33581,
        type: "min",
      },
      {
        original_file_name: "Bioluminescent Bay (4).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c1c0c1",
        primary: "#2f333c",
        tertiary: "#46617c",
        branch: "Wonders",
        folder: "Realism",
        bytes: 38584,
        type: "min",
      },
      {
        original_file_name: "Bioluminescent Bay (1).jpg",
        megabytes: 1.53,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#191e25",
        primary: "#c4a8a6",
        tertiary: "#63758a",
        branch: "Wonders",
        folder: "Realism",
        bytes: 1608391,
        type: "max",
      },
      {
        original_file_name: "Bioluminescent Bay (2).jpg",
        megabytes: 1.73,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#3a6983",
        primary: "#161f29",
        tertiary: "#5ab0c6",
        branch: "Wonders",
        folder: "Realism",
        bytes: 1814747,
        type: "max",
      },
      {
        original_file_name: "Bioluminescent Bay (3).jpg",
        megabytes: 1.18,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c39070",
        primary: "#233341",
        tertiary: "#3a6680",
        branch: "Wonders",
        folder: "Realism",
        bytes: 1238918,
        type: "max",
      },
      {
        original_file_name: "Bioluminescent Bay (4).jpg",
        megabytes: 1.45,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c1c0c0",
        primary: "#2f333c",
        tertiary: "#46617c",
        branch: "Wonders",
        folder: "Realism",
        bytes: 1520319,
        type: "max",
      },
    ]
  },
  "Glacial Cave": {
    environment_title: "Glacial Cave",
    images: [
      {
        original_file_name: "Glacial Cave (1).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#84abb4",
        primary: "#1a2e35",
        tertiary: "#baccd1",
        branch: "Wonders",
        folder: "Realism",
        bytes: 54257,
        type: "min",
      },
      {
        original_file_name: "Glacial Cave (2).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#b8cbd5",
        primary: "#1a353e",
        tertiary: "#487c86",
        branch: "Wonders",
        folder: "Realism",
        bytes: 56510,
        type: "min",
      },
      {
        original_file_name: "Glacial Cave (3).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#172a32",
        primary: "#b7c7cb",
        tertiary: "#588189",
        branch: "Wonders",
        folder: "Realism",
        bytes: 55741,
        type: "min",
      },
      {
        original_file_name: "Glacial Cave (4).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c1ced2",
        primary: "#172e35",
        tertiary: "#618288",
        branch: "Wonders",
        folder: "Realism",
        bytes: 50979,
        type: "min",
      },
      {
        original_file_name: "Glacial Cave (1).jpg",
        megabytes: 1.76,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#b9cbd0",
        primary: "#1a2d35",
        tertiary: "#83abb4",
        branch: "Wonders",
        folder: "Realism",
        bytes: 1846071,
        type: "max",
      },
      {
        original_file_name: "Glacial Cave (2).jpg",
        megabytes: 1.71,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#b7cad4",
        primary: "#1a353e",
        tertiary: "#497c86",
        branch: "Wonders",
        folder: "Realism",
        bytes: 1797847,
        type: "max",
      },
      {
        original_file_name: "Glacial Cave (3).jpg",
        megabytes: 1.79,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#172a32",
        primary: "#b8c7cb",
        tertiary: "#57818a",
        branch: "Wonders",
        folder: "Realism",
        bytes: 1880092,
        type: "max",
      },
      {
        original_file_name: "Glacial Cave (4).jpg",
        megabytes: 1.63,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c0ced2",
        primary: "#172e35",
        tertiary: "#618288",
        branch: "Wonders",
        folder: "Realism",
        bytes: 1707129,
        type: "max",
      },
    ]
  },
  "Limestone Falls": {
    environment_title: "Limestone Falls",
    images: [
      {
        original_file_name: "Limestone Falls (1).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c4c4bc",
        primary: "#2e322c",
        tertiary: "#808781",
        branch: "Wonders",
        folder: "Realism",
        bytes: 57694,
        type: "min",
      },
      {
        original_file_name: "Limestone Falls (2).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c7c4b7",
        primary: "#242c25",
        tertiary: "#7e806c",
        branch: "Wonders",
        folder: "Realism",
        bytes: 67953,
        type: "min",
      },
      {
        original_file_name: "Limestone Falls (3).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c9cecb",
        primary: "#2e332c",
        tertiary: "#95aeb0",
        branch: "Wonders",
        folder: "Realism",
        bytes: 63729,
        type: "min",
      },
      {
        original_file_name: "Limestone Falls (4).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c4c4bd",
        primary: "#282c29",
        tertiary: "#7d8179",
        branch: "Wonders",
        folder: "Realism",
        bytes: 57837,
        type: "min",
      },
      {
        original_file_name: "Limestone Falls (1).jpg",
        megabytes: 2.34,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c4c4bc",
        primary: "#2e322c",
        tertiary: "#808781",
        branch: "Wonders",
        folder: "Realism",
        bytes: 2452444,
        type: "max",
      },
      {
        original_file_name: "Limestone Falls (2).jpg",
        megabytes: 3.18,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c7c3b7",
        primary: "#242c25",
        tertiary: "#7e806b",
        branch: "Wonders",
        folder: "Realism",
        bytes: 3330362,
        type: "max",
      },
      {
        original_file_name: "Limestone Falls (3).jpg",
        megabytes: 2.93,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#cacecb",
        primary: "#2e332c",
        tertiary: "#95aeb1",
        branch: "Wonders",
        folder: "Realism",
        bytes: 3070029,
        type: "max",
      },
      {
        original_file_name: "Limestone Falls (4).jpg",
        megabytes: 2.23,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c4c4bd",
        primary: "#282c29",
        tertiary: "#7d8178",
        branch: "Wonders",
        folder: "Realism",
        bytes: 2337112,
        type: "max",
      },
    ]
  },
  "Majestic Gorge": {
    environment_title: "Majestic Gorge",
    images: [
      {
        original_file_name: "Majestic Gorge (1).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c1b69f",
        primary: "#262626",
        tertiary: "#81796a",
        branch: "Wonders",
        folder: "Realism",
        bytes: 56244,
        type: "min",
      },
      {
        original_file_name: "Majestic Gorge (2).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#252626",
        primary: "#d4cbbb",
        tertiary: "#80776c",
        branch: "Wonders",
        folder: "Realism",
        bytes: 48220,
        type: "min",
      },
      {
        original_file_name: "Majestic Gorge (3).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#b49973",
        primary: "#2a2a29",
        tertiary: "#7e6c51",
        branch: "Wonders",
        folder: "Realism",
        bytes: 52373,
        type: "min",
      },
      {
        original_file_name: "Majestic Gorge (4).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c2b19d",
        primary: "#262423",
        tertiary: "#816e5a",
        branch: "Wonders",
        folder: "Realism",
        bytes: 46237,
        type: "min",
      },
      {
        original_file_name: "Majestic Gorge (1).jpg",
        megabytes: 2.06,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#262626",
        primary: "#c1b69f",
        tertiary: "#82796a",
        branch: "Wonders",
        folder: "Realism",
        bytes: 2158441,
        type: "max",
      },
      {
        original_file_name: "Majestic Gorge (2).jpg",
        megabytes: 1.72,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#252626",
        primary: "#d4cbbb",
        tertiary: "#80776c",
        branch: "Wonders",
        folder: "Realism",
        bytes: 1800497,
        type: "max",
      },
      {
        original_file_name: "Majestic Gorge (3).jpg",
        megabytes: 2.03,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#b49973",
        primary: "#2a2a2a",
        tertiary: "#7d6c52",
        branch: "Wonders",
        folder: "Realism",
        bytes: 2125922,
        type: "max",
      },
      {
        original_file_name: "Majestic Gorge (4).jpg",
        megabytes: 1.8,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c2b29d",
        primary: "#262523",
        tertiary: "#806d5a",
        branch: "Wonders",
        folder: "Realism",
        bytes: 1884588,
        type: "max",
      },
    ]
  },
  "Marble Canyon": {
    environment_title: "Marble Canyon",
    images: [
      {
        original_file_name: "Marble Canyon (1).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#302421",
        primary: "#c8b2a1",
        tertiary: "#83604b",
        branch: "Wonders",
        folder: "Realism",
        bytes: 52903,
        type: "min",
      },
      {
        original_file_name: "Marble Canyon (2).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c3c2bb",
        primary: "#553c30",
        tertiary: "#9a7963",
        branch: "Wonders",
        folder: "Realism",
        bytes: 58906,
        type: "min",
      },
      {
        original_file_name: "Marble Canyon (3).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c7c4c1",
        primary: "#533120",
        tertiary: "#7195ae",
        branch: "Wonders",
        folder: "Realism",
        bytes: 65285,
        type: "min",
      },
      {
        original_file_name: "Marble Canyon (4).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#84aec8",
        primary: "#5f3d2d",
        tertiary: "#d2af92",
        branch: "Wonders",
        folder: "Realism",
        bytes: 66138,
        type: "min",
      },
      {
        original_file_name: "Marble Canyon (1).jpg",
        megabytes: 1.89,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#302521",
        primary: "#c8b2a2",
        tertiary: "#83604b",
        branch: "Wonders",
        folder: "Realism",
        bytes: 1981768,
        type: "max",
      },
      {
        original_file_name: "Marble Canyon (2).jpg",
        megabytes: 2.24,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c3c2bb",
        primary: "#553c30",
        tertiary: "#9a7963",
        branch: "Wonders",
        folder: "Realism",
        bytes: 2353923,
        type: "max",
      },
      {
        original_file_name: "Marble Canyon (3).jpg",
        megabytes: 2.33,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c7c4c2",
        primary: "#543121",
        tertiary: "#7295ad",
        branch: "Wonders",
        folder: "Realism",
        bytes: 2447754,
        type: "max",
      },
      {
        original_file_name: "Marble Canyon (4).jpg",
        megabytes: 2.45,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#abb8bc",
        primary: "#5d3b2c",
        tertiary: "#78a2be",
        branch: "Wonders",
        folder: "Realism",
        bytes: 2572646,
        type: "max",
      },
    ]
  },
  "Mountain Lake": {
    environment_title: "Mountain Lake",
    images: [
      {
        original_file_name: "Mountain Lake (1).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#b4b9bc",
        primary: "#313431",
        tertiary: "#bf9277",
        branch: "Wonders",
        folder: "Realism",
        bytes: 52363,
        type: "min",
      },
      {
        original_file_name: "Mountain Lake (2).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c4ab94",
        primary: "#333a3c",
        tertiary: "#8d7d6c",
        branch: "Wonders",
        folder: "Realism",
        bytes: 49905,
        type: "min",
      },
      {
        original_file_name: "Mountain Lake (3).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#d5c4bc",
        primary: "#40484b",
        tertiary: "#b09787",
        branch: "Wonders",
        folder: "Realism",
        bytes: 46659,
        type: "min",
      },
      {
        original_file_name: "Mountain Lake (4).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c5b3a2",
        primary: "#303637",
        tertiary: "#857366",
        branch: "Wonders",
        folder: "Realism",
        bytes: 56355,
        type: "min",
      },
      {
        original_file_name: "Mountain Lake (1).jpg",
        megabytes: 2.05,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#b4b9bc",
        primary: "#313431",
        tertiary: "#bf9277",
        branch: "Wonders",
        folder: "Realism",
        bytes: 2149546,
        type: "max",
      },
      {
        original_file_name: "Mountain Lake (2).jpg",
        megabytes: 2.2,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c4ab94",
        primary: "#333a3c",
        tertiary: "#8d7d6c",
        branch: "Wonders",
        folder: "Realism",
        bytes: 2311191,
        type: "max",
      },
      {
        original_file_name: "Mountain Lake (3).jpg",
        megabytes: 1.85,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#cfbbb1",
        primary: "#353d41",
        tertiary: "#8d847e",
        branch: "Wonders",
        folder: "Realism",
        bytes: 1940627,
        type: "max",
      },
      {
        original_file_name: "Mountain Lake (4).jpg",
        megabytes: 2.15,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c5b3a2",
        primary: "#303637",
        tertiary: "#857366",
        branch: "Wonders",
        folder: "Realism",
        bytes: 2253857,
        type: "max",
      },
    ]
  },
  "Red Rock": {
    environment_title: "Red Rock",
    images: [
      {
        original_file_name: "Red Rock (1).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#6194ac",
        primary: "#cda490",
        tertiary: "#5b2e22",
        branch: "Wonders",
        folder: "Realism",
        bytes: 60525,
        type: "min",
      },
      {
        original_file_name: "Red Rock (2).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#adbbbf",
        primary: "#6690ac",
        tertiary: "#5d2e20",
        branch: "Wonders",
        folder: "Realism",
        bytes: 56226,
        type: "min",
      },
      {
        original_file_name: "Red Rock (3).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c1815c",
        primary: "#3c2b2c",
        tertiary: "#cbcbc6",
        branch: "Wonders",
        folder: "Realism",
        bytes: 57963,
        type: "min",
      },
      {
        original_file_name: "Red Rock (4).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#7da4b6",
        primary: "#502b20",
        tertiary: "#c18667",
        branch: "Wonders",
        folder: "Realism",
        bytes: 62269,
        type: "min",
      },
      {
        original_file_name: "Red Rock (1).jpg",
        megabytes: 2.38,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#6094ac",
        primary: "#cda48f",
        tertiary: "#5b2e22",
        branch: "Wonders",
        folder: "Realism",
        bytes: 2491774,
        type: "max",
      },
      {
        original_file_name: "Red Rock (2).jpg",
        megabytes: 2.07,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#5a2c20",
        primary: "#cfa282",
        tertiary: "#628daa",
        branch: "Wonders",
        folder: "Realism",
        bytes: 2173651,
        type: "max",
      },
      {
        original_file_name: "Red Rock (3).jpg",
        megabytes: 2.12,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c1815c",
        primary: "#3c2b2c",
        tertiary: "#cccbc5",
        branch: "Wonders",
        folder: "Realism",
        bytes: 2219638,
        type: "max",
      },
      {
        original_file_name: "Red Rock (4).jpg",
        megabytes: 2.55,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c48a6a",
        primary: "#4e291e",
        tertiary: "#588ea7",
        branch: "Wonders",
        folder: "Realism",
        bytes: 2678144,
        type: "max",
      },
    ]
  },
  "Thermal Pools": {
    environment_title: "Thermal Pools",
    images: [
      {
        original_file_name: "Thermal Pools (1).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#523833",
        primary: "#d49c7e",
        tertiary: "#67898a",
        branch: "Wonders",
        folder: "Realism",
        bytes: 59813,
        type: "min",
      },
      {
        original_file_name: "Thermal Pools (2).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#b3afad",
        primary: "#2e3d44",
        tertiary: "#6b3023",
        branch: "Wonders",
        folder: "Realism",
        bytes: 52890,
        type: "min",
      },
      {
        original_file_name: "Thermal Pools (3).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#d2a68f",
        primary: "#323737",
        tertiary: "#9c897d",
        branch: "Wonders",
        folder: "Realism",
        bytes: 53537,
        type: "min",
      },
      {
        original_file_name: "Thermal Pools (4).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#332d31",
        primary: "#989794",
        tertiary: "#643026",
        branch: "Wonders",
        folder: "Realism",
        bytes: 55218,
        type: "min",
      },
      {
        original_file_name: "Thermal Pools (1).jpg",
        megabytes: 2.37,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#523833",
        primary: "#d59c7f",
        tertiary: "#67898a",
        branch: "Wonders",
        folder: "Realism",
        bytes: 2481230,
        type: "max",
      },
      {
        original_file_name: "Thermal Pools (2).jpg",
        megabytes: 1.93,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#b3afad",
        primary: "#2e3d44",
        tertiary: "#6c3023",
        branch: "Wonders",
        folder: "Realism",
        bytes: 2020766,
        type: "max",
      },
      {
        original_file_name: "Thermal Pools (3).jpg",
        megabytes: 2.13,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#d2a68f",
        primary: "#323737",
        tertiary: "#9c897d",
        branch: "Wonders",
        folder: "Realism",
        bytes: 2230535,
        type: "max",
      },
      {
        original_file_name: "Thermal Pools (4).jpg",
        megabytes: 1.8,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c0c3c3",
        primary: "#718188",
        tertiary: "#9cadb6",
        branch: "Wonders",
        folder: "Realism",
        bytes: 1889690,
        type: "max",
      },
    ]
  },
};
export default Wonders_Realism;
