import { EnvironmentEntry } from "../types";
const Wonders_Geometry: Record<string, EnvironmentEntry> = {
  "Crystalline Shore": {
    environment_title: "Crystalline Shore",
    images: [
      {
        original_file_name: "Crystalline Shore (1).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#a0afb7",
        primary: "#3e667b",
        tertiary: "#6c6378",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 46517,
        type: "min",
      },
      {
        original_file_name: "Crystalline Shore (2).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#497684",
        primary: "#acb5be",
        tertiary: "#e9d8d2",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 37012,
        type: "min",
      },
      {
        original_file_name: "Crystalline Shore (3).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#70a4b2",
        primary: "#d9c7ce",
        tertiary: "#ababb5",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 38938,
        type: "min",
      },
      {
        original_file_name: "Crystalline Shore (4).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#d2e6ec",
        primary: "#aaa9b8",
        tertiary: "#745c7e",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 41358,
        type: "min",
      },
      {
        original_file_name: "Crystalline Shore (1).jpg",
        megabytes: 1.33,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#a0afb7",
        primary: "#3e667b",
        tertiary: "#6d6378",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 1394417,
        type: "max",
      },
      {
        original_file_name: "Crystalline Shore (2).jpg",
        megabytes: 1.26,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#497684",
        primary: "#b0b7c0",
        tertiary: "#e9d8d2",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 1326026,
        type: "max",
      },
      {
        original_file_name: "Crystalline Shore (3).jpg",
        megabytes: 1.25,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#d9c7ce",
        primary: "#73a4b2",
        tertiary: "#3d5c72",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 1306113,
        type: "max",
      },
      {
        original_file_name: "Crystalline Shore (4).jpg",
        megabytes: 1.27,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#745c7e",
        primary: "#93a6b6",
        tertiary: "#e7d9da",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 1330033,
        type: "max",
      },
    ]
  },
  "Cubist Crater": {
    environment_title: "Cubist Crater",
    images: [
      {
        original_file_name: "Cubist Crater (1).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#322d35",
        primary: "#ce8f77",
        tertiary: "#93675f",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 36641,
        type: "min",
      },
      {
        original_file_name: "Cubist Crater (2).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#2e2d3a",
        primary: "#c68674",
        tertiary: "#855b5a",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 30224,
        type: "min",
      },
      {
        original_file_name: "Cubist Crater (3).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#cf9d93",
        primary: "#312c35",
        tertiary: "#8d5754",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 30739,
        type: "min",
      },
      {
        original_file_name: "Cubist Crater (4).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#d4cec3",
        primary: "#433e44",
        tertiary: "#d87253",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 31370,
        type: "min",
      },
      {
        original_file_name: "Cubist Crater (1).jpg",
        megabytes: 1.72,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#322d35",
        primary: "#ce8f77",
        tertiary: "#93675f",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 1800844,
        type: "max",
      },
      {
        original_file_name: "Cubist Crater (2).jpg",
        megabytes: 1.31,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#2e2d3a",
        primary: "#c68674",
        tertiary: "#855b5a",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 1377975,
        type: "max",
      },
      {
        original_file_name: "Cubist Crater (3).jpg",
        megabytes: 1.21,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#cf9c92",
        primary: "#312c35",
        tertiary: "#8c5855",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 1263568,
        type: "max",
      },
      {
        original_file_name: "Cubist Crater (4).jpg",
        megabytes: 1.16,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#403940",
        primary: "#dba089",
        tertiary: "#8c5247",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 1217033,
        type: "max",
      },
    ]
  },
  "Faceted Mesa": {
    environment_title: "Faceted Mesa",
    images: [
      {
        original_file_name: "Faceted Mesa (1).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#5a2a25",
        primary: "#d68358",
        tertiary: "#f8b986",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 33550,
        type: "min",
      },
      {
        original_file_name: "Faceted Mesa (2).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#cdaeaf",
        primary: "#e1946b",
        tertiary: "#6e372f",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 31028,
        type: "min",
      },
      {
        original_file_name: "Faceted Mesa (3).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#673027",
        primary: "#d89872",
        tertiary: "#8a4f41",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 34199,
        type: "min",
      },
      {
        original_file_name: "Faceted Mesa (4).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#461f23",
        primary: "#b7795c",
        tertiary: "#fac192",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 28895,
        type: "min",
      },
      {
        original_file_name: "Faceted Mesa (1).jpg",
        megabytes: 1.1,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#5a2b25",
        primary: "#d68358",
        tertiary: "#f9b986",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 1150938,
        type: "max",
      },
      {
        original_file_name: "Faceted Mesa (2).jpg",
        megabytes: 1.08,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#e18f63",
        primary: "#6e372f",
        tertiary: "#ceaeb0",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 1136769,
        type: "max",
      },
      {
        original_file_name: "Faceted Mesa (3).jpg",
        megabytes: 1.11,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#673027",
        primary: "#d89873",
        tertiary: "#8a4f40",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 1159463,
        type: "max",
      },
      {
        original_file_name: "Faceted Mesa (4).jpg",
        megabytes: 0.91,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#461f23",
        primary: "#b7795c",
        tertiary: "#632928",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 959005,
        type: "max",
      },
    ]
  },
  "Flat Reef": {
    environment_title: "Flat Reef",
    images: [
      {
        original_file_name: "Flat Reef (1).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#ebb9b2",
        primary: "#72a2a8",
        tertiary: "#93553b",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 49647,
        type: "min",
      },
      {
        original_file_name: "Flat Reef (2).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#e0a89c",
        primary: "#8fb5b4",
        tertiary: "#76453a",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 52825,
        type: "min",
      },
      {
        original_file_name: "Flat Reef (3).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#799da1",
        primary: "#2e636d",
        tertiary: "#deb3ad",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 50597,
        type: "min",
      },
      {
        original_file_name: "Flat Reef (4).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#80b5b4",
        primary: "#d6acaa",
        tertiary: "#55505d",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 45540,
        type: "min",
      },
      {
        original_file_name: "Flat Reef (1).jpg",
        megabytes: 1.32,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#ebbab2",
        primary: "#71a2a8",
        tertiary: "#94563b",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 1379234,
        type: "max",
      },
      {
        original_file_name: "Flat Reef (2).jpg",
        megabytes: 1.37,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#e0a89c",
        primary: "#8fb5b4",
        tertiary: "#77453a",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 1441242,
        type: "max",
      },
      {
        original_file_name: "Flat Reef (3).jpg",
        megabytes: 1.27,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#799da1",
        primary: "#2e636d",
        tertiary: "#deb4ae",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 1329079,
        type: "max",
      },
      {
        original_file_name: "Flat Reef (4).jpg",
        megabytes: 1.19,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#d6acaa",
        primary: "#8cb9b9",
        tertiary: "#55505d",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 1245471,
        type: "max",
      },
    ]
  },
  "Iso Canyon": {
    environment_title: "Iso Canyon",
    images: [
      {
        original_file_name: "Iso Canyon (1).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#683a35",
        primary: "#eaba98",
        tertiary: "#d29571",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 48298,
        type: "min",
      },
      {
        original_file_name: "Iso Canyon (2).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#ce9173",
        primary: "#764b43",
        tertiary: "#35383f",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 40416,
        type: "min",
      },
      {
        original_file_name: "Iso Canyon (3).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#6a3933",
        primary: "#edb28e",
        tertiary: "#d79270",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 51096,
        type: "min",
      },
      {
        original_file_name: "Iso Canyon (4).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#d49476",
        primary: "#523737",
        tertiary: "#e9ba9c",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 45520,
        type: "min",
      },
      {
        original_file_name: "Iso Canyon (1).jpg",
        megabytes: 1.42,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#683b35",
        primary: "#ebba98",
        tertiary: "#d29471",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 1489418,
        type: "max",
      },
      {
        original_file_name: "Iso Canyon (2).jpg",
        megabytes: 1.35,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#ce9173",
        primary: "#754a43",
        tertiary: "#303941",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 1416840,
        type: "max",
      },
      {
        original_file_name: "Iso Canyon (3).jpg",
        megabytes: 1.55,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#edb28e",
        primary: "#714139",
        tertiary: "#d79270",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 1624639,
        type: "max",
      },
      {
        original_file_name: "Iso Canyon (4).jpg",
        megabytes: 1.35,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#d49476",
        primary: "#523738",
        tertiary: "#e8ba9c",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 1418540,
        type: "max",
      },
    ]
  },
  "Layered Cliffs": {
    environment_title: "Layered Cliffs",
    images: [
      {
        original_file_name: "Layered Cliffs (1).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#ddb5a4",
        primary: "#603936",
        tertiary: "#d39274",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 46457,
        type: "min",
      },
      {
        original_file_name: "Layered Cliffs (2).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#503b3f",
        primary: "#d38561",
        tertiary: "#aaa5a9",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 36494,
        type: "min",
      },
      {
        original_file_name: "Layered Cliffs (3).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#e3cdc0",
        primary: "#613734",
        tertiary: "#ce8d6a",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 38346,
        type: "min",
      },
      {
        original_file_name: "Layered Cliffs (4).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#553e41",
        primary: "#d2957a",
        tertiary: "#849dad",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 43290,
        type: "min",
      },
      {
        original_file_name: "Layered Cliffs (1).jpg",
        megabytes: 1.52,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#dcb5a3",
        primary: "#603936",
        tertiary: "#d39273",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 1590681,
        type: "max",
      },
      {
        original_file_name: "Layered Cliffs (2).jpg",
        megabytes: 1.4,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#503b3f",
        primary: "#d38560",
        tertiary: "#aaa5aa",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 1470773,
        type: "max",
      },
      {
        original_file_name: "Layered Cliffs (3).jpg",
        megabytes: 1.38,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#613531",
        primary: "#e3ccc0",
        tertiary: "#cd8d6a",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 1444882,
        type: "max",
      },
      {
        original_file_name: "Layered Cliffs (4).jpg",
        megabytes: 1.48,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#d2977c",
        primary: "#553e41",
        tertiary: "#202631",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 1555990,
        type: "max",
      },
    ]
  },
  "Lowpoly Falls": {
    environment_title: "Lowpoly Falls",
    images: [
      {
        original_file_name: "Lowpoly Falls (1).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#d1cec7",
        primary: "#2f363d",
        tertiary: "#90b4c8",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 55187,
        type: "min",
      },
      {
        original_file_name: "Lowpoly Falls (2).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#d7c0b7",
        primary: "#5c434e",
        tertiary: "#92baca",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 51652,
        type: "min",
      },
      {
        original_file_name: "Lowpoly Falls (3).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#332f3a",
        primary: "#d9bca5",
        tertiary: "#7aadc3",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 51567,
        type: "min",
      },
      {
        original_file_name: "Lowpoly Falls (4).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#343540",
        primary: "#d9bdb0",
        tertiary: "#93b6ca",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 48300,
        type: "min",
      },
      {
        original_file_name: "Lowpoly Falls (1).jpg",
        megabytes: 1.39,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#d1cdc7",
        primary: "#2f363d",
        tertiary: "#90b4c8",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 1454156,
        type: "max",
      },
      {
        original_file_name: "Lowpoly Falls (2).jpg",
        megabytes: 1.33,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#d6bfb6",
        primary: "#5c434e",
        tertiary: "#91baca",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 1390999,
        type: "max",
      },
      {
        original_file_name: "Lowpoly Falls (3).jpg",
        megabytes: 1.26,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#33303a",
        primary: "#dabba5",
        tertiary: "#7aaec4",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 1316644,
        type: "max",
      },
      {
        original_file_name: "Lowpoly Falls (4).jpg",
        megabytes: 1.25,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#353540",
        primary: "#d9bcb0",
        tertiary: "#93b6ca",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 1311410,
        type: "max",
      },
    ]
  },
  "Neon Cavern": {
    environment_title: "Neon Cavern",
    images: [
      {
        original_file_name: "Neon Cavern (1).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#ad42b5",
        primary: "#13101d",
        tertiary: "#4b3a6f",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 48668,
        type: "min",
      },
      {
        original_file_name: "Neon Cavern (2).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#bd8ddf",
        primary: "#0d101d",
        tertiary: "#3b4072",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 48377,
        type: "min",
      },
      {
        original_file_name: "Neon Cavern (3).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#120f1b",
        primary: "#b94693",
        tertiary: "#48396b",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 39076,
        type: "min",
      },
      {
        original_file_name: "Neon Cavern (4).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#bb4b9d",
        primary: "#121320",
        tertiary: "#3a466b",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 44903,
        type: "min",
      },
      {
        original_file_name: "Neon Cavern (1).jpg",
        megabytes: 1.3,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#ad40b6",
        primary: "#14101d",
        tertiary: "#493a6e",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 1367885,
        type: "max",
      },
      {
        original_file_name: "Neon Cavern (2).jpg",
        megabytes: 1.34,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#363b6a",
        primary: "#0d101d",
        tertiary: "#c089df",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 1409690,
        type: "max",
      },
      {
        original_file_name: "Neon Cavern (3).jpg",
        megabytes: 1.26,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#b94391",
        primary: "#15101c",
        tertiary: "#4a386c",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 1319072,
        type: "max",
      },
      {
        original_file_name: "Neon Cavern (4).jpg",
        megabytes: 1.26,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#bb499d",
        primary: "#121320",
        tertiary: "#39466b",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 1323581,
        type: "max",
      },
    ]
  },
  "Polygon Geyser": {
    environment_title: "Polygon Geyser",
    images: [
      {
        original_file_name: "Polygon Geyser (1).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#d9dcdf",
        primary: "#7699ac",
        tertiary: "#213a58",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 41787,
        type: "min",
      },
      {
        original_file_name: "Polygon Geyser (2).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#2f5673",
        primary: "#9fa9b3",
        tertiary: "#5c7f95",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 35145,
        type: "min",
      },
      {
        original_file_name: "Polygon Geyser (3).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#b8bec7",
        primary: "#385d77",
        tertiary: "#708c9f",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 33983,
        type: "min",
      },
      {
        original_file_name: "Polygon Geyser (4).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#bec4cc",
        primary: "#3e596d",
        tertiary: "#758d9d",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 34405,
        type: "min",
      },
      {
        original_file_name: "Polygon Geyser (1).jpg",
        megabytes: 1.08,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#d9dbdf",
        primary: "#7699ac",
        tertiary: "#223958",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 1130498,
        type: "max",
      },
      {
        original_file_name: "Polygon Geyser (2).jpg",
        megabytes: 0.94,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#2f5774",
        primary: "#a0a9b3",
        tertiary: "#5c7f96",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 982840,
        type: "max",
      },
      {
        original_file_name: "Polygon Geyser (3).jpg",
        megabytes: 0.82,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#b8bec7",
        primary: "#385d77",
        tertiary: "#708da0",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 862029,
        type: "max",
      },
      {
        original_file_name: "Polygon Geyser (4).jpg",
        megabytes: 0.82,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c0c6cd",
        primary: "#3e596d",
        tertiary: "#768f9f",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 860864,
        type: "max",
      },
    ]
  },
  "Tri Cascade": {
    environment_title: "Tri Cascade",
    images: [
      {
        original_file_name: "Tri Cascade (1).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#3e4554",
        primary: "#cd8e72",
        tertiary: "#92bac0",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 52022,
        type: "min",
      },
      {
        original_file_name: "Tri Cascade (2).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#2f3748",
        primary: "#d07370",
        tertiary: "#76b7c0",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 48136,
        type: "min",
      },
      {
        original_file_name: "Tri Cascade (3).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#deb7b2",
        primary: "#4d3542",
        tertiary: "#945351",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 51720,
        type: "min",
      },
      {
        original_file_name: "Tri Cascade (4).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#262636",
        primary: "#d36668",
        tertiary: "#893d56",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 42570,
        type: "min",
      },
      {
        original_file_name: "Tri Cascade (1).jpg",
        megabytes: 1.38,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#3e4554",
        primary: "#cd8e71",
        tertiary: "#91bac0",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 1450657,
        type: "max",
      },
      {
        original_file_name: "Tri Cascade (2).jpg",
        megabytes: 1.39,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#2f3748",
        primary: "#d17370",
        tertiary: "#74b6c0",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 1458507,
        type: "max",
      },
      {
        original_file_name: "Tri Cascade (3).jpg",
        megabytes: 1.36,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#deb8b2",
        primary: "#4e3542",
        tertiary: "#945251",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 1421815,
        type: "max",
      },
      {
        original_file_name: "Tri Cascade (4).jpg",
        megabytes: 1.27,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#262636",
        primary: "#d36668",
        tertiary: "#893d56",
        branch: "Wonders",
        folder: "Geometry",
        bytes: 1332218,
        type: "max",
      },
    ]
  },
};
export default Wonders_Geometry;
