import { EnvironmentEntry } from "../types";
const Wonders_Cinematic: Record<string, EnvironmentEntry> = {
  "Aurora Night": {
    environment_title: "Aurora Night",
    images: [
      {
        original_file_name: "Aurora Night (1).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#607f79",
        primary: "#18252e",
        tertiary: "#9fbd87",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 41813,
        type: "min",
      },
      {
        original_file_name: "Aurora Night (2).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#b1a4a9",
        primary: "#24303e",
        tertiary: "#7dad8a",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 39497,
        type: "min",
      },
      {
        original_file_name: "Aurora Night (3).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#587b54",
        primary: "#1d2630",
        tertiary: "#4d6981",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 38347,
        type: "min",
      },
      {
        original_file_name: "Aurora Night (1).jpg",
        megabytes: 1.28,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#607f78",
        primary: "#18252e",
        tertiary: "#9fbd89",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 1346253,
        type: "max",
      },
      {
        original_file_name: "Aurora Night (2).jpg",
        megabytes: 1.31,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#b1a4a9",
        primary: "#24303e",
        tertiary: "#7ead8b",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 1371726,
        type: "max",
      },
      {
        original_file_name: "Aurora Night (3).jpg",
        megabytes: 1.31,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#597961",
        primary: "#1d2630",
        tertiary: "#79a65c",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 1371268,
        type: "max",
      },
    ]
  },
  "Crimson Canyon": {
    environment_title: "Crimson Canyon",
    images: [
      {
        original_file_name: "Crimson Canyon (1).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#be6e38",
        primary: "#311f1e",
        tertiary: "#824d29",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 71294,
        type: "min",
      },
      {
        original_file_name: "Crimson Canyon (2).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#2e2427",
        primary: "#c8693a",
        tertiary: "#803f28",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 66704,
        type: "min",
      },
      {
        original_file_name: "Crimson Canyon (3).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#372121",
        primary: "#d08455",
        tertiary: "#905332",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 73389,
        type: "min",
      },
      {
        original_file_name: "Crimson Canyon (4).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#452928",
        primary: "#d68d5d",
        tertiary: "#935a45",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 69824,
        type: "min",
      },
      {
        original_file_name: "Crimson Canyon (1).jpg",
        megabytes: 2.63,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#be6e37",
        primary: "#311f1e",
        tertiary: "#824d29",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 2760827,
        type: "max",
      },
      {
        original_file_name: "Crimson Canyon (2).jpg",
        megabytes: 2.25,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#2e2427",
        primary: "#c86838",
        tertiary: "#803f28",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 2358949,
        type: "max",
      },
      {
        original_file_name: "Crimson Canyon (3).jpg",
        megabytes: 2.33,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#372121",
        primary: "#d08354",
        tertiary: "#905332",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 2445484,
        type: "max",
      },
      {
        original_file_name: "Crimson Canyon (4).jpg",
        megabytes: 2.5,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#452928",
        primary: "#d68d5c",
        tertiary: "#935a44",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 2618343,
        type: "max",
      },
    ]
  },
  "Emerald Cave": {
    environment_title: "Emerald Cave",
    images: [
      {
        original_file_name: "Emerald Cave (1).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#30b59f",
        primary: "#092221",
        tertiary: "#1c786a",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 55675,
        type: "min",
      },
      {
        original_file_name: "Emerald Cave (2).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#3faf9d",
        primary: "#092120",
        tertiary: "#1f786a",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 62025,
        type: "min",
      },
      {
        original_file_name: "Emerald Cave (3).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#4db29c",
        primary: "#082320",
        tertiary: "#16786a",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 56138,
        type: "min",
      },
      {
        original_file_name: "Emerald Cave (4).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#42b5a5",
        primary: "#092623",
        tertiary: "#1c756a",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 65318,
        type: "min",
      },
      {
        original_file_name: "Emerald Cave (1).jpg",
        megabytes: 1.53,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#2fb59f",
        primary: "#092321",
        tertiary: "#1c786a",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 1606562,
        type: "max",
      },
      {
        original_file_name: "Emerald Cave (2).jpg",
        megabytes: 1.8,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#4cb5a5",
        primary: "#092221",
        tertiary: "#1f786a",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 1885051,
        type: "max",
      },
      {
        original_file_name: "Emerald Cave (3).jpg",
        megabytes: 1.61,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#4bb19c",
        primary: "#082320",
        tertiary: "#15786a",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 1692702,
        type: "max",
      },
      {
        original_file_name: "Emerald Cave (4).jpg",
        megabytes: 1.72,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#41b5a5",
        primary: "#092624",
        tertiary: "#1b7569",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 1808208,
        type: "max",
      },
    ]
  },
  "Giant Sequoia": {
    environment_title: "Giant Sequoia",
    images: [
      {
        original_file_name: "Giant Sequoia (1).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c5b098",
        primary: "#3e2e22",
        tertiary: "#84755e",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 76590,
        type: "min",
      },
      {
        original_file_name: "Giant Sequoia (2).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#cbb9a0",
        primary: "#423629",
        tertiary: "#84735f",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 76371,
        type: "min",
      },
      {
        original_file_name: "Giant Sequoia (3).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#403125",
        primary: "#d0bea5",
        tertiary: "#8b765b",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 77439,
        type: "min",
      },
      {
        original_file_name: "Giant Sequoia (4).jpg",
        megabytes: 0.08,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#30271c",
        primary: "#bda888",
        tertiary: "#847557",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 79450,
        type: "min",
      },
      {
        original_file_name: "Giant Sequoia (1).jpg",
        megabytes: 2.83,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c5b097",
        primary: "#3e2f23",
        tertiary: "#84755e",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 2966349,
        type: "max",
      },
      {
        original_file_name: "Giant Sequoia (2).jpg",
        megabytes: 2.68,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#cbb9a0",
        primary: "#423629",
        tertiary: "#857460",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 2813334,
        type: "max",
      },
      {
        original_file_name: "Giant Sequoia (3).jpg",
        megabytes: 3.0,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#cfbda3",
        primary: "#46382a",
        tertiary: "#8b765b",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 3141562,
        type: "max",
      },
      {
        original_file_name: "Giant Sequoia (4).jpg",
        megabytes: 2.9,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#30271c",
        primary: "#bea888",
        tertiary: "#847557",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 3037116,
        type: "max",
      },
    ]
  },
  "Golden Rapids": {
    environment_title: "Golden Rapids",
    images: [
      {
        original_file_name: "Golden Rapids (1).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#2f2721",
        primary: "#d7b58c",
        tertiary: "#856345",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 65550,
        type: "min",
      },
      {
        original_file_name: "Golden Rapids (2).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#483427",
        primary: "#d5b180",
        tertiary: "#8c6948",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 69301,
        type: "min",
      },
      {
        original_file_name: "Golden Rapids (3).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#2e2824",
        primary: "#ddae7d",
        tertiary: "#87674f",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 66756,
        type: "min",
      },
      {
        original_file_name: "Golden Rapids (4).jpg",
        megabytes: 0.07,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#2b2726",
        primary: "#d6ae7c",
        tertiary: "#846a53",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 69652,
        type: "min",
      },
      {
        original_file_name: "Golden Rapids (1).jpg",
        megabytes: 1.69,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#2f2822",
        primary: "#d8b58c",
        tertiary: "#856345",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 1770628,
        type: "max",
      },
      {
        original_file_name: "Golden Rapids (2).jpg",
        megabytes: 1.64,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#483427",
        primary: "#d5b17f",
        tertiary: "#8c6948",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 1718986,
        type: "max",
      },
      {
        original_file_name: "Golden Rapids (3).jpg",
        megabytes: 1.63,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#2e2825",
        primary: "#ddae7c",
        tertiary: "#87674f",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 1707883,
        type: "max",
      },
      {
        original_file_name: "Golden Rapids (4).jpg",
        megabytes: 1.66,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#2c2726",
        primary: "#d6ad7b",
        tertiary: "#846a53",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 1742592,
        type: "max",
      },
    ]
  },
  "Hidden Oasis": {
    environment_title: "Hidden Oasis",
    images: [
      {
        original_file_name: "Hidden Oasis (1).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#e4c9aa",
        primary: "#5d4a34",
        tertiary: "#c59e78",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 60577,
        type: "min",
      },
      {
        original_file_name: "Hidden Oasis (2).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#95a6b2",
        primary: "#53412d",
        tertiary: "#cfc3b3",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 62037,
        type: "min",
      },
      {
        original_file_name: "Hidden Oasis (3).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#674e31",
        primary: "#dfc9ae",
        tertiary: "#312410",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 63726,
        type: "min",
      },
      {
        original_file_name: "Hidden Oasis (4).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#ca9769",
        primary: "#5b4937",
        tertiary: "#decbb7",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 60917,
        type: "min",
      },
      {
        original_file_name: "Hidden Oasis (1).jpg",
        megabytes: 1.74,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#e4c9aa",
        primary: "#5d4b34",
        tertiary: "#c59d77",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 1826497,
        type: "max",
      },
      {
        original_file_name: "Hidden Oasis (2).jpg",
        megabytes: 2.18,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#d5af86",
        primary: "#55422d",
        tertiary: "#a3b0b6",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 2289642,
        type: "max",
      },
      {
        original_file_name: "Hidden Oasis (3).jpg",
        megabytes: 2.19,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#674e31",
        primary: "#dfc9ae",
        tertiary: "#31240f",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 2300935,
        type: "max",
      },
      {
        original_file_name: "Hidden Oasis (4).jpg",
        megabytes: 2.0,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c99768",
        primary: "#5b4938",
        tertiary: "#e0cbb7",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 2098658,
        type: "max",
      },
    ]
  },
  "Icy Grotto": {
    environment_title: "Icy Grotto",
    images: [
      {
        original_file_name: "Icy Grotto (1).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#b9c4cc",
        primary: "#264f5e",
        tertiary: "#7297a5",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 59452,
        type: "min",
      },
      {
        original_file_name: "Icy Grotto (2).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#1e4654",
        primary: "#bfccd6",
        tertiary: "#628a9b",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 59230,
        type: "min",
      },
      {
        original_file_name: "Icy Grotto (3).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#1e4452",
        primary: "#afc4d1",
        tertiary: "#518da0",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 60881,
        type: "min",
      },
      {
        original_file_name: "Icy Grotto (4).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#bbcad5",
        primary: "#1d4656",
        tertiary: "#5e8c9e",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 57606,
        type: "min",
      },
      {
        original_file_name: "Icy Grotto (1).jpg",
        megabytes: 1.96,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#b9c4cc",
        primary: "#264f5e",
        tertiary: "#7297a5",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 2059297,
        type: "max",
      },
      {
        original_file_name: "Icy Grotto (2).jpg",
        megabytes: 1.77,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#1e4654",
        primary: "#bfccd6",
        tertiary: "#628a9b",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 1856828,
        type: "max",
      },
      {
        original_file_name: "Icy Grotto (3).jpg",
        megabytes: 1.83,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#1e4452",
        primary: "#afc4d1",
        tertiary: "#508da0",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 1922992,
        type: "max",
      },
      {
        original_file_name: "Icy Grotto (4).jpg",
        megabytes: 1.81,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#bbcad5",
        primary: "#1e4657",
        tertiary: "#5e8c9e",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 1900185,
        type: "max",
      },
    ]
  },
  "Mighty Falls": {
    environment_title: "Mighty Falls",
    images: [
      {
        original_file_name: "Mighty Falls (1).jpg",
        megabytes: 0.06,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#29251d",
        primary: "#c0a981",
        tertiary: "#827254",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 64389,
        type: "min",
      },
      {
        original_file_name: "Mighty Falls (2).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#b6b0a8",
        primary: "#2f2a1e",
        tertiary: "#c09f73",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 55796,
        type: "min",
      },
      {
        original_file_name: "Mighty Falls (3).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#252421",
        primary: "#c2af8c",
        tertiary: "#807762",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 55520,
        type: "min",
      },
      {
        original_file_name: "Mighty Falls (4).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#29231c",
        primary: "#cbb394",
        tertiary: "#806e5b",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 57388,
        type: "min",
      },
      {
        original_file_name: "Mighty Falls (1).jpg",
        megabytes: 2.15,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#2c271f",
        primary: "#c0a881",
        tertiary: "#827254",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 2249284,
        type: "max",
      },
      {
        original_file_name: "Mighty Falls (2).jpg",
        megabytes: 2.11,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#cdb08a",
        primary: "#302a1e",
        tertiary: "#8d7754",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 2207563,
        type: "max",
      },
      {
        original_file_name: "Mighty Falls (3).jpg",
        megabytes: 1.96,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#252421",
        primary: "#c3af8c",
        tertiary: "#807763",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 2051801,
        type: "max",
      },
      {
        original_file_name: "Mighty Falls (4).jpg",
        megabytes: 1.77,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#29231c",
        primary: "#ccb293",
        tertiary: "#806d5b",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 1859414,
        type: "max",
      },
    ]
  },
  "Skybound Peaks": {
    environment_title: "Skybound Peaks",
    images: [
      {
        original_file_name: "Skybound Peaks (1).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#bdb5ab",
        primary: "#2f363a",
        tertiary: "#90908c",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 47488,
        type: "min",
      },
      {
        original_file_name: "Skybound Peaks (2).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c7c0b6",
        primary: "#3f4d56",
        tertiary: "#8f8b85",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 44781,
        type: "min",
      },
      {
        original_file_name: "Skybound Peaks (3).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#253239",
        primary: "#c1aa91",
        tertiary: "#7a7770",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 42362,
        type: "min",
      },
      {
        original_file_name: "Skybound Peaks (4).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#2f383e",
        primary: "#bbb5ad",
        tertiary: "#828380",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 49768,
        type: "min",
      },
      {
        original_file_name: "Skybound Peaks (1).jpg",
        megabytes: 1.4,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#beb6ac",
        primary: "#30363a",
        tertiary: "#90908c",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 1468646,
        type: "max",
      },
      {
        original_file_name: "Skybound Peaks (2).jpg",
        megabytes: 1.46,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c7c0b6",
        primary: "#3f4d56",
        tertiary: "#8f8c85",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 1526388,
        type: "max",
      },
      {
        original_file_name: "Skybound Peaks (3).jpg",
        megabytes: 1.33,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#243139",
        primary: "#c1ab91",
        tertiary: "#827e75",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 1392681,
        type: "max",
      },
      {
        original_file_name: "Skybound Peaks (4).jpg",
        megabytes: 1.54,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#30383e",
        primary: "#bbb5ad",
        tertiary: "#828380",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 1611440,
        type: "max",
      },
    ]
  },
  "Volcanic Glow": {
    environment_title: "Volcanic Glow",
    images: [
      {
        original_file_name: "Volcanic Glow (1).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c04d1d",
        primary: "#1c1a1f",
        tertiary: "#6d2e24",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 46695,
        type: "min",
      },
      {
        original_file_name: "Volcanic Glow (2).jpg",
        megabytes: 0.03,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#c45b2f",
        primary: "#1b1d23",
        tertiary: "#6b4845",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 35551,
        type: "min",
      },
      {
        original_file_name: "Volcanic Glow (3).jpg",
        megabytes: 0.04,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#18171b",
        primary: "#c86d44",
        tertiary: "#6d3b35",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 40887,
        type: "min",
      },
      {
        original_file_name: "Volcanic Glow (4).jpg",
        megabytes: 0.05,
        format: "JPEG",
        height: 640,
        width: 360,
        mode: "RGB",
        secondary: "#ca5720",
        primary: "#221c21",
        tertiary: "#76311f",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 47958,
        type: "min",
      },
      {
        original_file_name: "Volcanic Glow (1).jpg",
        megabytes: 1.25,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c14d1c",
        primary: "#1b1a20",
        tertiary: "#6d2d24",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 1305710,
        type: "max",
      },
      {
        original_file_name: "Volcanic Glow (2).jpg",
        megabytes: 1.12,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#c65b2d",
        primary: "#1c1f25",
        tertiary: "#6b4946",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 1172537,
        type: "max",
      },
      {
        original_file_name: "Volcanic Glow (3).jpg",
        megabytes: 1.31,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#18181d",
        primary: "#c86d43",
        tertiary: "#6d3b35",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 1369928,
        type: "max",
      },
      {
        original_file_name: "Volcanic Glow (4).jpg",
        megabytes: 1.44,
        format: "JPEG",
        height: 5472,
        width: 3072,
        mode: "RGB",
        secondary: "#ca571f",
        primary: "#231d21",
        tertiary: "#77311f",
        branch: "Wonders",
        folder: "Cinematic",
        bytes: 1512537,
        type: "max",
      },
    ]
  },
};
export default Wonders_Cinematic;
